export const shopLotsCheese = [
    {
        type: "retail",
        url: "./images/shop/food/dairy/cheese/mlekivita_brie_classic_125.jpg",
        alt: "mlekivita_brie_classic_125",
        marker: "FDEE060",
        brand: "Mlekovita",
        search: "млековита млековіта бри брі сыр с плесенью плесень пліснява мягкие сыры м'який мягкий сир м'які сири классичний класичний классік класік классический класический классик класик",
        nameUKR: "Cир з пліснявою",
        nameEN: "Brie Classic",
        companyName: "SM Mlekovita",
        countryName: "Польща",
        weightName: "Вага",
        weight: "125 гр.",
        priceGRN: 50,
        quantityOnStorage: "11",
        description01: "&#171Mlekovita - Brie Classic&#187 - це вишуканий сир з пліснявою, що дарує неповторний смак. Цей сир має ніжну текстуру та гладку корку, яка робить його ідеальним для сервірування на столі. Він гарантує найвищу якість та смак.",
        description02: "Це ідеальний вибір для справжніх цінителів сиру. Його ніжний смак і неперевершена м'якість роблять його ідеальним додатком до смачних закусок, сендвічів або сирних тарілок. Цей сир може бути частиною вашого щоденного задоволення або особливого святкування.",
        description03: "Завдяки своїй унікальній якості та аромату, &#171Mlekovita - Brie Classic&#187 може перетворити будь-яку звичайну страву у шедевр.",
        description04: "<strong>Сир м'який, з пліснявою.</strong>",
        description05: "Приготуйте вишукані страви або просто насолоджуйтеся ніжністю &#171Mlekovita - Brie Classic&#187 на хлібі!"
    },
    {
        type: "retail",
        url: "./images/shop/food/dairy/cheese/mlekivita_camembert_classic_120.jpg",
        alt: "mlekivita_camembert_classic_120",
        marker: "FDEE070",
        brand: "Mlekovita",
        search: "млековита млековіта камемберт сыр с плесенью плесень пліснява мягкие сыры м'який мягкий сир м'які сири классичний класичний классік класік классический класический классик класик",
        nameUKR: "Cир з пліснявою",
        nameEN: "Camembert",
        companyName: "SM Mlekovita",
        countryName: "Польща",
        weightName: "Вага",
        weight: "120 гр.",
        priceGRN: 50,
        quantityOnStorage: "11",
        description01: "&#171Mlekovita - Camembert&#187 - це справжній сирний діамант з ніжною коркою та неперевершеним смаком. Цей сир володіє неповторнОю ніжною текстурою, що тане в роті. Виготовлений із відібраних інгредієнтів, він гарантує найвищу якість та смак.",
        description02: "Це ідеальний вибір для гурманів та цінителів справжнього смаку. Ніжний смак робить його ідеальним для смачних закусок, сендвічів або сирних тарілок. Цей сир може стати справжньою окрасою будь-якого заходу.",
        description03: "Завдяки &#171Mlekovita - Camembert&#187, Ви можете подарувати собі та гостям неперевершений смак справжнього французького сиру.",
        description04: "<strong>Сир м'який, з пліснявою.</strong>",
        description05: "Подаруйте собі миті справжнього задоволення та насолоди разом з&#171Mlekovita - Camembert&#187!"
    },
    {
        type: "wholesale",
        url: "./images/shop/food/dairy/cheese/parmareggio_parmigiano_reggiano_30_mesi_250.jpg",
        alt: "parmareggio_parmigiano_reggiano_30_mesi_250",
        marker: "FDEE082",
        brand: "Parmareggio",
        search: "твердый сыр твердые сыры твердий сир тверді сири 30 месяцев",
        nameUKR: "Пармезан",
        nameEN: "Parmigiano Reggiano 30 Mesi",
        companyName: "Parmareggio S.p.a.",
        countryName: "Італія",
        weightName: "Вага",
        weight: "250 гр.",
        priceGRN: 148,
        priceGRNOpt: 134,
        description01: "&#171Parmareggio - Parmigiano Reggiano 30 Mesi&#187 - це вишуканий італійський сир, який здивує навіть найвибагливіших гурманів. Відзначається терпким, багатим смаком та крихкими кришталевими гранулами, що роблять його неперевершеним.",
        description02: "Цей сир витримується протягом 30 місяців, дозволяючи йому розвинути неймовірні аромати та неперевершений смак. Справжній шедевр італійського мистецтва.",
        description03: "Використовуйте &#171Parmareggio - Parmigiano Reggiano 30 Mesi&#187 для приготування паст, салатів та сирних тарілок. Поступайте як справжній гурман та розкрийте всі нюанси смаку італійської кухні.",
        description04: "<strong>Сир твердий. Пармезан. 30 місяців витримки.</strong>",
        description05: "Не втрачайте можливості спробувати &#171Parmareggio - Parmigiano Reggiano 30 Mesi&#187 - доторкніться до смакової вишуканості Італії вже сьогодні!"
    },
]