export const shopLotsChips = [
    {
        type: "wholesale",
        url: "./images/shop/food/snacks/chips/pringles_original_40.jpg",
        alt: "pringles_original_40",
        marker: "FDCH050",
        brand: "Pringles",
        search: "принглс прінглс чипсы оригинал оригінал сіль соль с солью з сілью",
        nameUKR: "Чіпси",
        nameEN: "Original",
        companyName: "Kellogg's",
        countryName: "Угорщина",
        weightName: "Вага",
        weight: "40 гр.",
        priceGRN: 39,
        priceGRNOpt: 34,
        description01: "&#171Pringles - Original&#187 - це справжня класика серед чіпсів, яка завжди залишається улюбленою. Їх унікальна трубчаста форма робить їх неповторними, а смак бездоганний. Кожен чіпс має ідеальний баланс солі та картоплі, створюючи неповторний смак, який завжди впізнаєш.",
        description02: "&#171Pringles - Original&#187 - це ідеальний снек для будь-якого випадку. Ці чіпси підходять для вечірки з друзями, перегляду фільму або навіть просто для швидкої закуски під час перерви на обід.",
        description03: "Вони завжди свіжі та смачні, завдяки спеціальній упаковці.",
        description04: "<strong>Смак: солений.</strong>",
        description05: "Спробуйте &#171Pringles - Original&#187 прямо зараз і відчуйте смак класики!"
    },
    {
        type: "wholesale",
        url: "./images/shop/food/snacks/chips/pringles_original_165.jpg",
        alt: "pringles_original_165",
        marker: "FDCH051",
        brand: "Pringles",
        search: "принглс прінглс чипсы оригинал оригінал сіль соль с солью з сілью",
        nameUKR: "Чіпси",
        nameEN: "Original",
        companyName: "Kellogg's",
        countryName: "Угорщина",
        weightName: "Вага",
        weight: "165 гр.",
        priceGRN: 88,
        priceGRNOpt: 81,
        description01: "&#171Pringles - Original&#187 - це справжня класика серед чіпсів, яка завжди залишається улюбленою. Їх унікальна трубчаста форма робить їх неповторними, а смак бездоганний. Кожен чіпс має ідеальний баланс солі та картоплі, створюючи неповторний смак, який завжди впізнаєш.",
        description02: "&#171Pringles - Original&#187 - це ідеальний снек для будь-якого випадку. Ці чіпси підходять для вечірки з друзями, перегляду фільму або навіть просто для швидкої закуски під час перерви на обід.",
        description03: "Вони завжди свіжі та смачні, завдяки спеціальній упаковці.",
        description04: "<strong>Смак: солений.</strong>",
        description05: "Спробуйте &#171Pringles - Original&#187 прямо зараз і відчуйте смак класики!"
    },
]