export const shopLotsWaffles = [
    {
        type: "retail",
        url: "./images/shop/food/sweets/waffles/opavia_tatranky_cokoladove_47.jpg",
        alt: "opavia_tatranky_cokoladove_47",
        marker: "FDWF110",
        brand: "Opavia",
        search: "опавия опавія татранки татранкі шоколад шоколадные вафли",
        nameUKR: "Шоколадні вафлі",
        nameEN: "Tatranky Čokoládové",
        companyName: "Mondelez s.r.o.",
        countryName: "Чехія",
        weightName: "Вага",
        weight: "47 гр.",
        priceGRN: 18,
        quantityOnStorage: "11",
        description01: "&#171Opavia - Tatranky Čokoládové&#187 - це справжній шедевр для любителів солодкого. Ці шоколадні вафлі вразять вас ніжним та густим шоколадом, що робить їх незабутніми.",
        description02: "Завдяки вишуканому поєднанню вафель та шоколаду, вони стали популярними серед всіх вікових груп. Ця солодка насолода ідеально підходить для перекусу вдома чи у дорозі.",
        description03: "Відчуйте справжню солодкість &#171Opavia - Tatranky Čokoládové&#187 і пориньте у світ насолоди. Вони заслуговують на вашу увагу!",
        description04: "<strong>Вафлі шоколадні. Без шкідливих барвників.</strong>",
        description05: "Не вагайтесь та спробуйте &#171Opavia - Tatranky Čokoládové&#187. Дозвольте собі солодку радість!"
    },
    {
        type: "retail",
        url: "./images/shop/food/sweets/waffles/opavia_tatranky_cokoladove_47_8.jpg",
        alt: "opavia_tatranky_cokoladove_47_8",
        marker: "FDWF112",
        brand: "Opavia",
        search: "опавия опавія татранки татранкі шоколад шоколадные вафли",
        nameUKR: "Шоколадні вафлі",
        nameEN: "Tatranky Čokoládové",
        companyName: "Mondelez s.r.o.",
        countryName: "Чехія",
        weightName: "Вага",
        weight: "376 гр.",
        priceGRN: 142,
        quantityOnStorage: "5",
        description01: "&#171Opavia - Tatranky Čokoládové&#187 - це справжній шедевр для любителів солодкого. Ці шоколадні вафлі вразять вас ніжним та густим шоколадом, що робить їх незабутніми.",
        description02: "Завдяки вишуканому поєднанню вафель та шоколаду, вони стали популярними серед всіх вікових груп. Ця солодка насолода ідеально підходить для перекусу вдома чи у дорозі.",
        description03: "Відчуйте справжню солодкість &#171Opavia - Tatranky Čokoládové&#187 і пориньте у світ насолоди. Вони заслуговують на вашу увагу!",
        description04: "<strong>Вафлі шоколадні. Без шкідливих барвників. 8 шт. у пачці.</strong>",
        description05: "Не вагайтесь та спробуйте &#171Opavia - Tatranky Čokoládové&#187. Дозвольте собі солодку радість!"
    },
    {
        type: "retail",
        url: "./images/shop/food/sweets/waffles/opavia_tatranky_mlecne_47.jpg",
        alt: "opavia_tatranky_mlecne_47",
        marker: "FDWF120",
        brand: "Opavia",
        search: "опавия опавія татранки татранкі шоколад шоколадные молочные вафли",
        nameUKR: "Молочно-шоколадні вафлі",
        nameEN: "Tatranky Mléčné",
        companyName: "Mondelez s.r.o.",
        countryName: "Чехія",
        weightName: "Вага",
        weight: "47 гр.",
        priceGRN: 18,
        quantityOnStorage: "13",
        description01: "&#171Opavia - Tatranky Mléčné&#187 - це неперевершене поєднання ніжного молочного крему та смачного шоколаду. Ці вафлі - справжнє задоволення для вашого смаку. Ідеально підходять для перекусу вдома чи у дорозі.",
        description02: "Завдяки вишуканому смаку і поживній цінності, вони стали улюбленими ласощами для всієї родини. Їхній хрусткий шар вафель обгорнутий ніжним молочним кремом, а все це покрите справжнім шоколадом.",
        description03: "&#171Opavia - Tatranky Mléčné&#187 - це ідеальний вибір для гурманів та тих, хто цінує справжню якість і смачний десерт.",
        description04: "<strong>Вафлі молочно-шоколадні. Без шкідливих барвників.</strong>",
        description05: "Спробуйте &#171Opavia - Tatranky Mléčné&#187 і зануртесь у безмежний світ смаку та задоволення!"
    },
    {
        type: "retail",
        url: "./images/shop/food/sweets/waffles/opavia_tatranky_orisky_47.jpg",
        alt: "opavia_tatranky_orisky_47",
        marker: "FDWF130",
        brand: "Opavia",
        search: "опавия опавія татранки татранкі шоколад шоколадные c лесными орехами орешками вафли горіх горіхи горіхами",
        nameUKR: "Шоколадні вафлі з лісовими горішками",
        nameEN: "Tatranky S Lískovými Oříšky",
        companyName: "Mondelez s.r.o.",
        countryName: "Чехія",
        weightName: "Вага",
        weight: "47 гр.",
        priceGRN: 18,
        quantityOnStorage: "13",
        description01: "&#171Opavia - Tatranky S Lískovými Oříšky&#187 - це ідеальний вибір для гурманів та прихильників лісових горішків. Ці вафлі поєднують у собі ніжний смак тонких вафель, які доповнюються хрусткими, ароматними горішками.",
        description02: "Ці вафлі виготовлені з найкращих інгредієнтів з урахуванням найвищих стандартів якості. Кожен шматочок - це справжній шедевр, який піднесе настрій та подарує Вам енергію на цілий день.",
        description03: "Завдяки компактній упаковці, &#171Opavia - Tatranky S Lískovými Oříšky&#187 ідеально підходять для подорожей, перекусів на роботі або для солодкого задоволення у будь-який момент.",
        description04: "<strong>Вафлі шоколадні, з лісовими горіхами. Без шкідливих барвників.</strong>",
        description05: "Замовте &#171Opavia - Tatranky S Lískovými Oříšky&#187 сьогодні та розкажіть своїй родині історію неперевершеного задоволення!"
    },
]