export const shopLotsPates = [
    {
        type: "wholesale",
        url: "./images/shop/food/canned_food/pates/fresh_pecenovka_190.jpg",
        alt: "fresh_pecenovka_190",
        marker: "FDPT010",
        brand: "Fresh",
        search: "печінка печень печеночный печёночный с з печінки печенки печёнки",
        nameUKR: "Печінковий паштет",
        nameEN: "Pečeňovka",
        companyName: "HAMÉ SLOVAKIA, spol.",
        countryName: "Словаччина",
        weightName: "Вага",
        weight: "190 гр.",
        priceGRN: 29,
        priceGRNOpt: 24,
        description01: "&#171Fresh - Pečeňovka&#187 - це смачна і корисна закуска, яка ідеально підходить для будь-якого випадку. Він виготовлений з високоякісних інгредієнтів, включаючи свинячу печінку, шпик, цибулю та спеції.",
        description02: "Паштет має ніжну, кремову текстуру і приємний смак з легкими нотками прянощів. Він не містить штучних барвників, консервантів та ароматизаторів.",
        description03: "Печінковий паштет &#171Fresh - Pečeňovka&#187 - це відмінний вибір для тих, хто хоче насолодитися смачним і корисним продуктом. Він ідеально підходить для бутербродів, канапе, овочевих салатів та інших страв.",
        description04: "<strong>Печінковий паштет, свинина. Жестяна банка.</strong>",
        description05: "Спробуйте печінковий паштет &#171Fresh - Pečeňovka&#187 та переконайтеся у його чудовому смаку!"
    },
    {
        type: "wholesale",
        url: "./images/shop/food/canned_food/pates/freshona_pasta_ardei_120.jpg",
        alt: "freshona_pasta_ardei_120",
        marker: "FDPT020",
        brand: "Freshona",
        search: "паприка перець веган веганство",
        nameUKR: "Пісний паштет з паприкою",
        nameEN: "Pastă Vegetală Tartinabilă Cu Ardei",
        companyName: "Lidl",
        countryName: "Румунія",
        weightName: "Вага",
        weight: "120 гр.",
        priceGRN: 23,
        priceGRNOpt: 19,
        description01: "&#171Freshona - Pastă Vegetală Tartinabilă Cu Ardei&#187 - це смачна і корисна закуска, яка ідеально підходить для тих, хто дотримується вегетаріанства або веганства. Він виготовлений з високоякісних інгредієнтів, включаючи квасолю, сочевицю, моркву, цибулю та перець.",
        description02: "Він ідеально підходить для вживання на хлібі, як діп для снеків або просто в якості начинки для сендвічів.",
        description03: "Складаючись лише з натуральних інгредієнтів, &#171Freshona - Pastă Vegetală Tartinabilă Cu Ardei&#187 не містить консервантів та шкідливих добавок, що робить його вибором для тих, хто піклується про своє здоров'я. Він багатий вітамінами та антиоксидантами, сприяючи зміцненню імунної системи та покращенню загального самопочуття.",
        description04: "<strong>Пісний паштет з паприкою. Жестяна банка.</strong>",
        description05: "&#171Freshona - Pastă Vegetală Tartinabilă Cu Ardei&#187 - справжня родзинка в світі вегетаріанської кухні готова вразити вас своєю смаковою насолодою та користью для організму!"
    },
    {
        type: "wholesale",
        url: "./images/shop/food/canned_food/pates/freshona_pasta_ciuperci_120.jpg",
        alt: "freshona_pasta_ciuperci_120",
        marker: "FDPT022",
        brand: "Freshona",
        search: "веган веганство печериці шампиньоны с шампиньонами",
        nameUKR: "Пісний паштет з печерицями",
        nameEN: "Pastă Vegetală Tartinabilă Cu Ciuperci",
        companyName: "Lidl",
        countryName: "Румунія",
        weightName: "Вага",
        weight: "120 гр.",
        priceGRN: 23,
        priceGRNOpt: 19,
        description01: "&#171Freshona - Pastă Vegetală Tartinabilă Cu Ciuperci&#187 - це справжній шедевр вегетаріанської кухні. Виготовлений з найкращих печериць, цей паштет дарує неперевершений аромат та насичений смак, який стає справжньою насолодою.",
        description02: "Він ідеально підходить на грільований хліб, печиво або в якості начинки для сендвічів.",
        description03: "Зі складом, що не містить штучних барвників та консервантів, &#171Freshona - Pastă Vegetală Tartinabilă Cu Ciuperci&#187 стає вибором для тих, хто цінує натуральність і смак. Він багатий білком та вітамінами, сприяючи вашому здоров'ю та зміцнюючи імунну систему.",
        description04: "<strong>Пісний паштет з печерицями. Жестяна банка.</strong>",
        description05: "Відкрийте для себе безмежні можливості для творчості в кулінарії та додайте смаку своїм стравам з &#171Freshona - Pastă Vegetală Tartinabilă Cu Ciuperci&#187!"
    },
    {
        type: "wholesale",
        url: "./images/shop/food/canned_food/pates/freshona_pasta_măsline_120.jpg",
        alt: "freshona_pasta_măsline_120",
        marker: "FDPT022",
        brand: "Freshona",
        search: "веган веганство в маслини маслины",
        nameUKR: "Пісний паштет з маслинами",
        nameEN: "Pastă Vegetală Tartinabilă Cu Măsline",
        companyName: "Lidl",
        countryName: "Румунія",
        weightName: "Вага",
        weight: "120 гр.",
        priceGRN: 23,
        priceGRNOpt: 19,
        description01: "&#171Freshona - Pastă Vegetală Tartinabilă Cu Măsline&#187 - це справжній кулінарний шедевр, який вкраде ваше серце своєю вишуканістю. Виготовлений зі свіжих маслин, цей паштет вражає яскравим смаком і неповторним ароматом. Він ідеально підходить на хліб чи в якості начинки для канапок.",
        description02: "Складаючись лише з природних інгредієнтів, не містить шкідливих домішок і штучних добавок. Він є чудовим вибором для вегетаріанців та тих, хто прагне зберегти своє здоров'я.",
        description03: "Багатий вітамінами та корисними речовинами, &#171Freshona - Pastă Vegetală Tartinabilă Cu Măsline&#187 сприяє підтриманню вашого імунітету та загального здоров'я.",
        description04: "<strong>Пісний паштет з маслинами. Жестяна банка.</strong>",
        description05: "Не втратьте можливість розкрити нові кулінарні горизонти з &#171Freshona - Pastă Vegetală Tartinabilă Cu Măsline&#187. Замовте його вже сьогодні та насолоджуйтеся неперевершеним смаком та ароматом!"
    },
]