export const shopLotsSauces = [
    {
        type: "retail",
        url: "./images/shop/food/taste_modifier/sauces/asia_gold_thai_hot_chili_700.jpg",
        alt: "asia_gold_thai_hot_chili_700",
        marker: "FDSU010",
        brand: "Asia Gold",
        search: "азия азія голд перець гострі острый острые соуси соусы",
        nameUKR: "Гострий соус",
        nameEN: "Thai Hot Chili Sauce",
        companyName: "Asia Gold Ltd.",
        countryName: "Німеччина",
        volumeName: "Об'єм",
        volume: "700 мл.",
        priceGRN: 88,
        quantityOnStorage: "5",
        description01: "&#171Asia Gold - Thai Hot Chili Sauce&#187 - це справжній скарб для прихильників гострих смаків. Цей соус - поєднання традиційного тайського смаку та неймовірної гостроти, яка запалює с першої спроби.",
        description02: "Завдяки унікальній рецептурі, цей соус створений для того, щоб робити ваші страви неперевершеними. Використовуйте його для маринування м'яса, смаження, або як соус для суші. Що б ви не обрали, він неодмінно зробить ваші страви незабутніми.",
        description03: "Зараз настав час приготувати справжню гостреньку феєрію на вашому столі. І у цьому Вам допоможе &#171Asia Gold - Thai Hot Chili Sauce&#187.",
        description04: "<strong>Соус гострий. Не містить шкідливих барвників.</strong>",
        description05: "Замовте &#171Asia Gold - Thai Hot Chili Sauce&#187 вже сьогодні та дозвольте собі насолодитися смаком Таїланду, не виходячи з дому!"
    },
    {
        type: "retail",
        url: "./images/shop/food/taste_modifier/sauces/asia_gold_thai_sweet_chili_700.jpg",
        alt: "asia_gold_thai_sweet_chili_700",
        marker: "FDSU012",
        brand: "Asia Gold",
        search: "азия азія голд перець сладкий соус соуси соусы",
        nameUKR: "Солодкий соус",
        nameEN: "Thai Hot Sweet Sauce",
        companyName: "Asia Gold Ltd.",
        countryName: "Німеччина",
        volumeName: "Об'єм",
        volume: "700 мл.",
        priceGRN: 88,
        quantityOnStorage: "5",
        description01: "&#171Asia Gold - Thai Hot Sweet Sauce&#187 - це справжній скарб для прихильників азійських смаків. Цей соус поєднує e собі солодкість та натхненний традиціями тайського кулінарного мистецтва.",
        description02: "Він відзначається глибоким ароматом і солодким смаком, що робить його ідеальним доповненням до широкого спектру страв. Завдяки унікальному поєднанню солодкості і спецій, цей соус підходить для маринування м'яса, салатів, а також як супровід для суші та ролів.",
        description03: "&#171Asia Gold - Thai Hot Sweet Sauce&#187 додасть екзотичного колориту вашій кухні та створить незабутній смаковий вибух.",
        description04: "<strong>Соус солодкий. Не містить шкідливих барвників.</strong>",
        description05: "Створіть найсмачніші страви, які вразять своїм смаком всіх, хто сяде за ваш стіл. Замовляйте прямо зараз &#171Asia Gold - Thai Hot Sweet Sauce&#187 та розпочніть кулінарну подорож у Таїланд!"
    },
    {
        type: "retail",
        url: "./images/shop/food/taste_modifier/sauces/eros_pista.jpg",
        alt: "eros_pista",
        marker: "FDSU070",
        brand: "Univer",
        search: "універ универ ерош ерюш пішта перець гострі острый острые соуси соусы",
        nameUKR: "Гострий соус",
        nameEN: "Erős Pista",
        companyName: "Univer Product Zrt.",
        countryName: "Угорщина",
        weightName: "Вага",
        weight: "200 гр.",
        priceGRN: 59,
        quantityOnStorage: "7",
        description01: "&#171Univer - Erős Pista&#187 - це угорський гострий соус, який надасть вашим стравам неперевершений гострий смак та аромат. Виготовлений зі свіжих та якісних інгредієнтів, цей соус вражає багатогранністю смаків.",
        description02: "З ним кожна страва стає справжнім шедевром. Додайте його до піци, супу або м'ясних страв, щоб отримати неперевершений смаковий досвід. Цей гострий соус надасть вашим стравам угорську гостроту і зробить їх незабутніми.",
        description03: "&#171Univer - Erős Pista&#187; - це незрівняний гострий соус, який завоював серця шанувальників гостроти по всьому світу.",
        description04: "<strong>Соус гострий. Не містить шкідливих барвників.</strong>",
        description05: "Створіть найсмачніші страви та насолоджуйтесь найкращими смаковими враженнями разом із &#171Univer - Erős Pista&#187;."
    },
]