export const shopLotsSprats = [
    {
        type: "retail",
        url: "./images/shop/food/canned_food/sprats/evrafish_winter_sprats_170.jpg",
        alt: "evrafish_winter_sprats_170",
        marker: "FDST020",
        brand: "EvraFish",
        search: "эврафіш еврафиш шпроты в масле масло олія масло рыба риба",
        nameUKR: "Шпроти в олії",
        nameEN: "Winter Sprats",
        companyName: "EvraFish Sp.",
        countryName: "Польша",
        weightName: "Вага",
        weight: "170 гр.",
        priceGRN: 49,
        quantityOnStorage: "23",
        description01: "&#171EvraFish - Winter Sprats&#187 - це справжній дарунок природи, який переносить нас у світ арктичних вод. Кожен шпрот незвичайно ніжний та смачний завдяки холодним водам, в яких вони зростають.",
        description02: "Смак &#171EvraFish - Winter Sprats&#187 - це поєднання ніжності та м'якості м'яса з багатим ароматом моря. Ці шпроти - ідеальний вибір для тих, хто цінує якість та натуральний смак риби.",
        description03: "Бренд &#171EvraFish&#187 завжди гарантує свіжість та смакову насолоду у кожному ковзку завдяки своєму досвіду та відповідальному відношенню до виробництва.",
        description04: "<strong>Шпроти в олії. Без консервантів.</strong>",
        description05: "Не вагайтеся та замовляйте &#171EvraFish - Winter Sprats&#187 прямо зараз, щоб зануритися у світ арктичних вод!"
    },
    {
        type: "wholesale",
        url: "./images/shop/food/canned_food/sprats/king_oscar_szproty_tomato_160.jpg",
        alt: "king_oscar_szproty_tomato_160",
        marker: "FDST030",
        brand: "King Oscar",
        search: "король оскар шпроты томатный соус рыба риба",
        nameUKR: "Шпроти у томатному соусі",
        nameEN: "Szproty W Sosie Pomidorowym",
        companyName: "Thai Union Poland Sp.",
        countryName: "Польша",
        weightName: "Вага",
        weight: "160 гр.",
        priceGRN: 42,
        priceGRNOpt: 37,
        description01: "&#171King Oscar - Szprot&#187 - це вишуканий дар норвезьких морів, заповнений багатством смаку та користі. Ці шпроти у томатному соусі - справжній діамант серед морських дарунків. Кожен шматочок риби відзначається неймовірною ніжністю та поживністю.",
        description02: "Соус, у &#171King Oscar - Szprot&#187 виготовлений з найсвіжіших томатів та ретельно підібраних спецій. Він додає страві неповторний аромат та глибокий смак, який гармонійно поєднується з ніжністю риби. Це ідеальний вибір для гурманів та тих, хто цінує справжню якість.",
        description03: "Пригощайте себе та своїх гостей цією розкішшю природного походження. &#171King Oscar - Szprot&#187 - це не просто страва, це смакова подорож у світ норвезької традиції.",
        description04: "<strong>Шпроти у томатному соусі. Без консервантів.</strong>",
        description05: "Замовляйте &#171King Oscar - Szprot&#187 та відчуйте всю силу морського дару у кожному шматочку."
    },
    // {
    //     type: "wholesale",
    //     url: "./images/shop/food/canned_food/sprats/m&k_szprot_podwedzany_w_oleju_160.jpg",
    //     alt: "m&k_szprot_podwedzany_w_oleju_160",
    //     marker: "FDST040",
    //     brand: "M & K",
    //     search: "шпроты в масле масло олія масло рыба риба",
    //     nameUKR: "Шпроти в олії",
    //     nameEN: "Szprot Podwedzany W Oleju",
    //     companyName: "Kasprzyk SP. K.",
    //     countryName: "Польша",
    //     weightName: "Вага",
    //     weight: "160 гр.",
    //     priceGRN: 43,
    //     priceGRNOpt: 38,
    //     description01: "&#171M & K - Szprot Podwedzany W Oleju&#187 - це справжній шедевр у світі морських делікатесів. Кожен шматочок цих ніжних шпротів, замаринованих у відбірній олії, - це витвір мистецтва. Вони виробляються з використанням найкращих рибних уловів та традиційних рецептів.",
    //     description02: "Олія, в якій зберігаються ці шпроти, надає їм неповторний смак та аромат. Ви отримуєте надзвичайно соковиті та ніжні шпроти, які легко тануть у роті. Це ідеальна закуска для гурманів та тих, хто цінує вишуканість в кожній деталі.",
    //     description03: "Спробуйте &#171M & K - Szprot Podwedzany W Oleju&#187 та переконайтеся в якості цього продукту самі. Завдяки найвищому стандарту виробництва і натуральним інгредієнтам, вони стануть вашим улюбленим вибором серед морських смаколиків.",
    //     description04: "<strong>Шпроти в олії. Без консервантів.</strong>",
    //     description05: "А тепер, дозвольте і собі розкрити секрет цього неймовірного смаку та замовте &#171M & K - Szprot Podwedzany W Oleju&#187 вже сьогодні!"
    // },
    {
        type: "wholesale",
        url: "./images/shop/food/canned_food/sprats/m&k_szprot_podwedzany_w_sosie_pomidorowym_160.jpg",
        alt: "m&k_szprot_podwedzany_w_sosie_pomidorowym_160",
        marker: "FDST042",
        brand: "M & K",
        search: "шпроты томатный соус рыба риба",
        nameUKR: "Шпроти у томатному соусі",
        nameEN: "Szprot Podwedzany W Sosie Pomidorowym",
        companyName: "Kasprzyk SP. K.",
        countryName: "Польша",
        weightName: "Вага",
        weight: "160 гр.",
        priceGRN: 43,
        priceGRNOpt: 38,
        description01: "&#171M & K - Szprot Podwedzany W Sosie Pomidorowym&#187 - це найвищий стандарт якості у морських делікатесах. Ця страва переповнена смаком та корисністю. Кожен шматочок ніжної риби насичений таємничим ароматом вогню та помідорів.",
        description02: "Томатний соус, що супроводжує ці шпроти, виробляється із відібраних помідорів та суміші спецій, створюючи неперевершений букет смаків. Ця комбінація робить страву ідеальною для закуски або головною страваю. Кожен шматочок - це кулінарна поїзія на вашій тарільці.",
        description03: "Спробуйте &#171M & K - Szprot Podwedzany W Sosie Pomidorowym&#187 та відчуйте всю глибину смаку моря, обігріту ніжністю помідорів.",
        description04: "<strong>Шпроти у томатному соусі. Без консервантів.</strong>",
        description05: "Не відкладайте задоволення на завтра! Замовте &#171M & K - Szprot Podwedzany W Sosie Pomidorowym&#187 вже сьогодні і подаруйте собі смакове св'ято, яке назавжди запам'ятається."
    },
    {
        type: "wholesale",
        url: "./images/shop/food/canned_food/sprats/m&k_szproty_wedzone_w_oleju_250.jpg",
        alt: "m&k_szproty_wedzone_w_oleju_250",
        marker: "FDST046",
        brand: "M & K",
        search: "шпроты в масле масло олія масло рыба риба",
        nameUKR: "Шпроти в олії",
        nameEN: "Szproty Wedzone W Oleju",
        companyName: "Kasprzyk SP. K.",
        countryName: "Польша",
        weightName: "Вага",
        weight: "250 гр.",
        priceGRN: 88,
        priceGRNOpt: 81,
        description01: "&#171M & K - Szproty Wedzone W Oleju&#187 - це справжній шедевр серед морських смаколиків. Кожен шпрот у цій неймовірно смачній олії - це витвір мистецтва та смакова розкіш. Вони виготовлені з найсвіжіших рибних уловів і володіють неперевершеним смаком та ароматом.",
        description02: "Олія, в якій знаходяться ці шпроти, надає їм неймовірну м'якість та ніжність. Кожен шматочок риби пропитаний багатогранним смаком диму та олії, що робить їх неперевершеними. Це ідеальний вибір для вишуканих гурманів і тих, хто цінує справжню якість.",
        description03: "Спробуйте &#171M & K - Szproty Wedzone W Oleju&#187 та відчуйте смакову розкіш, яка вас приголомшить. Дозвольте собі насолоджуватися найкращими смаками моря у кожному шматочку.",
        description04: "<strong>Шпроти в олії. Без консервантів.</strong>",
        description05: "Замовте &#171M & K - Szproty Wedzone W Oleju&#187 та переконайтеся в їх неперевершеній смаковій якості!"
    },
    {
        type: "wholesale",
        url: "./images/shop/food/canned_food/sprats/posejdon_szprot_300.jpg",
        alt: "posejdon_szprot_300",
        marker: "FDST060",
        brand: "Posejdon",
        search: "посейдон шпроты томатный соус рыба риба",
        nameUKR: "Шпроти у томатному соусі",
        nameEN: "Szprot XXL",
        companyName: "Przetwórstwo Rybne Sp.",
        countryName: "Польша",
        weightName: "Вага",
        weight: "300 гр.",
        priceGRN: 67,
        priceGRNOpt: 61,
        description01: "&#171Posejdon - Szprot&#187 - це справжній океанський смак у кожному шматочку риби. Ця страва поєднує у собі свіжість морського бризу та ніжність шпротів. Відірвавши кришечку, Ви відразу відчуєте запах рибок, занурених у томатний соус.",
        description02: "Спеціально підібрана рецептура соусу надає шпротам неперевершений смак. Томати, спеції та інші натуральні інгредієнти додають найкращі якості цих риб, роблячи кожен ковзаючий шматочок неперевершеним у своєму роді. Цей продукт стане ідеальним додатком до салатів, канапок або гарячих страв.",
        description03: "Спробуйте шпроти &#171Posejdon - Szprot&#187 і Ви отримаєте чисту морську насолоду, яку можна смакувати у будь-який час.",
        description04: "<strong>Шпроти у томатному соусі. Без консервантів.</strong>",
        description05: "Не відкладайте задоволення на завтра - насолоджуйтесь неперевершеним смаком &#171Posejdon - Szprot&#187 вже сьогодні!"
    },
]