export const shopLotsSale = [
    {
        type: "retail",
        url: "./images/shop/sale/ace_sgrassatore_cucina_1550.jpg",
        alt: "ace_sgrassatore_cucina_1550",
        url1: "./images/shop/sale/ace_sgrassatore_cucina_1550-01.jpg",
        alt1: "ace_sgrassatore_cucina_1550-01",
        url2: "./images/shop/sale/ace_sgrassatore_cucina_1550-02.jpg",
        alt2: "ace_sgrassatore_cucina_1550-02",
        marker: "SALE005",
        brand: "Ace",
        search: "ейс аце эйс засоби проти жиру обезжириватель средство средства против жира кухня для кухни средство для чистки",
        nameUKR: "Знежирювач для кухні з ароматами лимону та бергамоту, без відбілювача",
        nameEN: "Sgrassatore Cucuna Limone E Bergamotto Senza Candeggina",
        companyName: "Fater S.P.A.",
        countryName: "Італія",
        volumeName: "Об'єм",
        volume: "1550 мл.",
        priceGRN: 162,
        quantityOnStorage: 4,
        description01: "&#171Ace - Sgrassatore Cucuna Limone E Bergamotto Senza Candeggina&#187 - Ваша таємниця бездоганної чистоти на кухні! Його унікальний склад, збагачений ароматами лимону та бергамоту, створює атмосферу свіжості та чистоти.",
        description02: "Він здатний побороти навіть найскладніші жирні плями та утворення, дбає про збереження довготривалої чистоти, даруючи вам свободу на Вашій кухні.",
        description03: "Дія &#171Ace - Sgrassatore Cucuna Limone E Bergamotto Senza Candeggina&#187 вражає, а результат залишається назавжди! Підходить для будь-якого типу кухонних поверхонь та посуди.",
        description04: "<strong>Комплект! Знежирювач для кухні. Аромат: лимон, бергамот. Без відбілювача.</strong>",
        description05: "Відкрийте новий рівень чистоти у Вашому домі та дізнайтеся, як легко та ефективно здійснити догляд за Вашою кухнею разом з &#171Ace - Sgrassatore Cucuna Limone E Bergamotto Senza Candeggina&#187."
    },
    // {
    //     type: "retail",
    //     url: "./images/shop/sale/ace_candeggina_piu_fresco_profumo_1600.jpg",
    //     alt: "ace_candeggina_piu_fresco_profumo_1600",
    //     url1: "./images/shop/sale/ace_candeggina_piu_fresco_profumo_1600-01.jpg",
    //     alt1: "ace_candeggina_piu_fresco_profumo_1600-01",
    //     url2: "./images/shop/household_chemicals/universal_tools/ace_candeggina_piu_fresco_profumo_1600-02.jpg",
    //     alt2: "ace_candeggina_piu_fresco_profumo_1600-02",
    //     marker: "SALE010",
    //     brand: "Ace",
    //     search: "ейс аце эйс плюс засоби видалення пляма пятновыводитель пятновыдодители кольорові речі цветные вещи для цветных вещей делікатні речі с активным кислородом активный кислород дезинфекция дезинфекція дезінфектор дезінфекція відбілювачі отбеливатель отбеливатели piu засоби проти жиру обезжириватель средство средства против жира аромат свежести",
    //     nameUKR: "Плямовивідник для білих речей, дезінфектор, від плісняви з відбілювачем, знежирювач з ароматом свіжості",
    //     nameEN: "Candeggina Più Fresco Profumo + Mousse",
    //     companyName: "Fater S.P.A.",
    //     countryName: "Італія",
    //     volumeName: "Об'єм",
    //     volume: "1600 мл.",
    //     priceGRN: 169,
    //     quantityOnStorage: 1,
    //     description01: "&#171Ace - Candeggina Più Fresco Profumo + Mousse&#187 - Ваш незамінний помічник у догляді за будинком! Цей революційний засіб - справжній чарівник у Вашій руці. Він є плямовивідником для білих речей, дезинфектором та знежирювачем, одночасно надаючи універсальний захист від плям, бруду та плісняви.",
    //     description02: "Чистота та свіжість поєднуються з неймовірним ароматом, який залишається на поверхнях та у тканинах. Відпочиньте від домашніх завдань та довіртеся магії &#171Ace - Candeggina Più Fresco Profumo + Mousse&#187.",
    //     description03: "Замовте вже сьогодні і відкрийте безмежні можливості для бездоганності Вашого дому.",
    //     description04: "<strong>Комплект! Засіб для виведення плям для білих речей, дезінфектор, знежирювач, засіб для чищення універсальний з відбілювачем, засіб від плісняви. Аромат свіжості.</strong>",
    //     description05: "Оберіть &#171Ace - Candeggina Più Fresco Profumo + Mousse&#187 для знищення бруду і насолоджуйтеся чистотою та ароматом у своєму домі!"
    // },
    // {
    //     type: "retail",
    //     url: "./images/shop/sale/ace_pavimenti_lavanda_2l.jpg",
    //     alt: "ace_pavimenti_lavanda_2l",
    //     url1: "./images/shop/sale/ace_pavimenti_lavanda_2l-01.jpg",
    //     alt1: "ace_pavimenti_lavanda_2l-01",
    //     url2: "./images/shop/sale/ace_pavimenti_lavanda_2l-02.jpg",
    //     alt2: "ace_pavimenti_lavanda_2l-02",
    //     marker: "SALE020",
    //     brand: "Ace",
    //     search: "ейс аце эйс средство для чистки чищення чистка забоси стредства для мытья пола полов підлога с ароматом лаванды лавандой эфирное масло ефирные масла эфирным маслом",
    //     nameUKR: "Засіб для миття підлоги (лаванда та ефірні олії), без відбілювача",
    //     nameEN: "Ace Pavimenti Lavanda E Oli Essenziale Senza Candeggina",
    //     companyName: "Fater S.P.A.",
    //     countryName: "Італія",
    //     volumeName: "Об'єм",
    //     volume: "2 л.",
    //     priceGRN: 173,
    //     quantityOnStorage: 3,
    //     description01: "Забезпечте вашому дому неперевершену чистоту та аромат з засобом для миття підлоги &#171Ace - Pavimenti Lavanda E Oli Essenziale Senza Candeggina&#187.",
    //     description02: "Ефективно очищає підлоги без використання відбілювача, роблячи їх безпечними для всієї родини. Формула з ефірними оліями та лавандой додає приємний аромат, створюючи затишну атмосферу.",
    //     description03: "Уявіть собі підлоги, які не тільки блищать чистотою, але й наповнюють дім приємними ароматами. З &#171Ace - Pavimenti Lavanda E Oli Essenziale Senza Candeggina&#187 Ваш дім стане справжнім оазисом свіжості та затишку.",
    //     description04: "<strong>Комплект! Засіб для миття підлоги. Аромат: лаванда, ефірні олії. Не містить відбілювач. 2 шт.</strong>",
    //     description05: "Придбайте засіб &#171Ace - Pavimenti Lavanda E Oli Essenziale Senza Candeggina&#187 вже сьогодні і насолоджуйтеся ідеально чистими підлогами та приємним ароматом у домі!"
    // },
    // {
    //     type: "retail",
    //     url: "./images/shop/sale/ace_pavimenti_talco_2l.jpg",
    //     alt: "ace_pavimenti_talco_2l",
    //     url1: "./images/shop/sale/ace_pavimenti_talco_2l-01.jpg",
    //     alt1: "ace_pavimenti_talco_2l-01",
    //     url2: "./images/shop/household_chemicals/means_for_cleaning/for_floor/ace_pavimenti_talco_1l-02.jpg",
    //     alt2: "ace_pavimenti_talco_1l-02",
    //     marker: "SALE022",
    //     brand: "Ace",
    //     search: "ейс аце эйс средство для чистки чищення чистка забоси стредства для мытья пола полов підлога с з тальком білим мускусом белый мускус белым мускусом",
    //     nameUKR: "Засіб для миття підлоги (тальк та білий мускус), без відбілювача",
    //     nameEN: "Ace Pavimenti Talco E Muschio Bianco Senza Candeggina",
    //     companyName: "Fater S.P.A.",
    //     countryName: "Італія",
    //     volumeName: "Об'єм",
    //     volume: "2 л.",
    //     priceGRN: 173,
    //     quantityOnStorage: 3,
    //     description01: "Відчуйте свіжість та чистоту у Вашому домі з засобом для миття підлоги &#171Ace - Pavimenti Talco E Muschio Bianco Senza Candeggina&#187 з ароматом тальку та білого мускусу.",
    //     description02: "Не містить відбілювача, тому його можна використовувати на будь-яких типах підлогових покриттів. Він ретельно очищає та залишає тривалий приємний аромат.",
    //     description03: "Уявіть собі підлоги, які не тільки сяють чистотою, але й наповнюють дім ніжним ароматом тальку та білого мускусу. З  &#171Ace - Pavimenti Talco E Muschio Bianco Senza Candeggina&#187 Ваш будинок буде завжди чистим і привабливим.",
    //     description04: "<strong>Засіб для миття підлоги. Аромат: тальк, білий мускус. Не містить відбілювач.</strong>",
    //     description05: "Придбайте засіб для миття підлоги &#171Ace - Pavimenti Talco E Muschio Bianco Senza Candeggina&#187 з ароматом тальку та білого мускусу сьогодні і перетворіть свій дім на місце свіжості та комфорту!"
    // },
    {
        type: "retail",
        url: "./images/shop/sale/right_guard_bubhen_girl_15_off.jpg",
        alt: "right_guard_bubhen_girl_15_off",
        url1: "./images/shop/sale/right_guard_bubhen_girl_15_off-01.jpg",
        alt1: "right_guard_bubhen_girl_15_off-01",
        url2: "./images/shop/gigiena/bath_gels/right_guard_sport_300-01.jpg",
        alt2: "right_guard_sport_300-01",
        url3: "./images/shop/gigiena/bath_gels/right_guard_sensual_300-01.jpg",
        alt3: "right_guard_sensual_300-01",
        url4: "./images/shop/gigiena/hair_care/baby_shampoos/bubchen_prinzessin_rosalea_230-01.jpg",
        alt4: "bubchen_prinzessin_rosalea_230-01",
        marker: "SALE050",
        brand: "Bübchen & Right Guard",
        search: "райт гуард гель гелі гели для душа шварцкопф хенкель чоловічий чоловічі чоловічій джонсон бубхен bubchen бюбхен для дітей детей дитей дитячі шампуні",
        nameUKR: "Сімейний набір",
        nameEN: "Sport Recharge, Sensual & Oil, Prinzessin Rosalea",
        companyName: "Schwarzkopf & Henkel, Johnson & Johnson",
        countryName: "Німеччина & Англія",
        volumeName: "Об'єм",
        volume: "830 мл.",
        priceGRN: 229,
        quantityOnStorage: 7,
        description01: "&#171Sport Recharge, Sensual & Oil, Prinzessin Rosalea&#187 - це ексклюзивна акційна пропозиція для всієї родини від компанії &#171Cras&#187.",
        description02: "&#171Sport Recharge&#187 - це секрет успіху активних чоловіків. Його потужна формула дарує свіжість та захист протягом усього дня. Цей потужний і відновлюючий комплексний засіб для душу, ідеально підходить для очищення тіла, обличчя та волосся.<br> &#171Sensual & Oil&#187 - це елегантний захист, що розкриває вашу справжню жіночу силу. Його спеціально розроблена формула збагачена натуральними оліями, що живлять і пом'якшують вашу шкіру.",
        description03: "&#171Prinzessin Rosalea&#187 - це казкова мить, яка зачаровує вашу маленьку принцесу. Цей унікальний продукт надає ніжного догляду шкірі, роблячи її м'якою і гладенькою.",
        description04: "<strong>Набір для чоловіків (гель для душу, шампунь), жінок (гель для душу) та маленьких принцесс (гель для душу, шампунь). (300 + 300 + 230) мл.</strong>",
        description05: "Не втрачайте нагоди заощадити з сімейним набором &#171Sport Recharge, Sensual & Oil, Prinzessin Rosalea&#187 та подарувати своїй родині якість, на яку вона заслуговує!"
    },
    {
        type: "retail",
        url: "./images/shop/sale/right_guard_bubhen_boy_15_off.jpg",
        alt: "right_guard_bubhen_boy_15_off",
        url1: "./images/shop/sale/right_guard_bubhen_boy_15_off-01.jpg",
        alt1: "right_guard_bubhen_boy_15_off-01",
        url2: "./images/shop/gigiena/bath_gels/right_guard_sport_300-01.jpg",
        alt2: "right_guard_sport_300-01",
        url3: "./images/shop/gigiena/bath_gels/right_guard_sensual_300-01.jpg",
        alt3: "right_guard_sensual_300-01",
        url4: "./images/shop/gigiena/hair_care/baby_shampoos/bubchen_dschungelbande_230-01.jpg",
        alt4: "bubchen_dschungelbande_230-01",
        url5: "./images/shop/gigiena/hair_care/baby_shampoos/bubchen_superdusche_230-01.jpg",
        alt5: "bubchen_superdusche_230-01",
        url6: "./images/shop/gigiena/hair_care/baby_shampoos/bubchen_sportsfreund_230-01.jpg",
        alt6: "bubchen_sportsfreund_230-01",
        marker: "SALE052",
        brand: "Bübchen & Right Guard",
        search: "райт гуард гель гелі гели для душа шварцкопф хенкель чоловічий чоловічі чоловічій джонсон бубхен bubchen бюбхен для дітей детей дитей дитячі шампуні",
        nameUKR: "Сімейний набір",
        nameEN: "Sport Recharge, Sensual & Oil та Bübchen для хлопчиків на вибір",
        companyName: "Schwarzkopf & Henkel, Johnson & Johnson",
        countryName: "Німеччина & Англія",
        volumeName: "Об'єм",
        volume: "830 мл.",
        priceGRN: 233,
        quantityOnStorage: 7,
        description01: "&#171Sport Recharge, Sensual & Oil та Bübchen&#187 - це ексклюзивна акційна пропозиція для всієї родини від компанії &#171Cras&#187.",
        description02: "&#171Sport Recharge&#187 - це секрет успіху активних чоловіків. Його потужна формула дарує свіжість та захист протягом усього дня. Цей потужний і відновлюючий комплексний засіб для душу, ідеально підходить для очищення тіла, обличчя та волосся.<br> &#171Sensual & Oil&#187 - це елегантний захист, що розкриває вашу справжню жіночу силу. Його спеціально розроблена формула збагачена натуральними оліями, що живлять і пом'якшують вашу шкіру.",
        description03: "Також пропонуємо Вам на вибір шамнунь-гель для хлопчиків від бренду &#171Bübchen&#187.",
        description04: "<strong>Набір для чоловіків (гель для душу, шампунь), жінок (гель для душу) та хлопчиків (гель для душу, шампунь). (300 + 300 + 230) мл.</strong>",
        description05: "Не втрачайте нагоди заощадити з сімейним набором &#171Sport Recharge, Sensual & Oil та Bübchen&#187 та подарувати своїй родині якість, на яку вона заслуговує!"
    },
    {
        type: "retail",
        url: "./images/shop/sale/right_guard_bubhen_sens_15_off.jpg",
        alt: "right_guard_bubhen_sens_15_off",
        url1: "./images/shop/sale/right_guard_bubhen_sens_15_off-01.jpg",
        alt1: "right_guard_bubhen_sens_15_off-01",
        url2: "./images/shop/gigiena/bath_gels/right_guard_sport_300-01.jpg",
        alt2: "right_guard_sport_300-01",
        url3: "./images/shop/gigiena/bath_gels/right_guard_sensual_300-01.jpg",
        alt3: "right_guard_sensual_300-01",
        url4: "./images/shop/gigiena/hair_care/baby_shampoos/bubchen_sanfte_lieblinge_230-01.jpg",
        alt4: "bubchen_sanfte_lieblinge_230-01",
        marker: "SALE054",
        brand: "Bübchen & Right Guard",
        search: "райт гуард гель гелі гели для душа шварцкопф хенкель чоловічий чоловічі чоловічій джонсон бубхен bubchen бюбхен для дітей детей дитей дитячі шампуні",
        nameUKR: "Сімейний набір",
        nameEN: "Sport Recharge, Sensual & Oil, Sanfte Lieblinge",
        companyName: "Schwarzkopf & Henkel, Johnson & Johnson",
        countryName: "Німеччина & Англія",
        volumeName: "Об'єм",
        volume: "830 мл.",
        priceGRN: 233,
        quantityOnStorage: 7,
        description01: "&#171Sport Recharge, Sensual & Oil, Sanfte Lieblinge&#187 - це ексклюзивна акційна пропозиція для всієї родини від компанії &#171Cras&#187.",
        description02: "&#171Sport Recharge&#187 - це секрет успіху активних чоловіків. Його потужна формула дарує свіжість та захист протягом усього дня. Цей потужний і відновлюючий комплексний засіб для душу, ідеально підходить для очищення тіла, обличчя та волосся.<br> &#171Sensual & Oil&#187 - це елегантний захист, що розкриває вашу справжню жіночу силу. Його спеціально розроблена формула збагачена натуральними оліями, що живлять і пом'якшують вашу шкіру.",
        description03: "&#171Sanfte Lieblinge&#187 - це ніжні обійми для малюків у кожній краплині. Цей унікальний продукт забезпечує м'який і дбайливий догляд за ніжною шкірою вашої дитини.",
        description04: "<strong>Набір для чоловіків (гель для душу, шампунь), жінок (гель для душу) та малючків з чутливою шкірою (гель для душу, шампунь). (300 + 300 + 230) мл.</strong>",
        description05: "Не втрачайте нагоди заощадити з сімейним набором &#171Sport Recharge, Sensual & Oil, Sanfte Lieblinge&#187 та подарувати своїй родині якість, на яку вона заслуговує!"
    },
    // {
    //     type: "retail",
    //     url: "./images/shop/sale/candy_planet_minions_75.jpg",
    //     alt: "candy_planet_minions_75",
    //     url1: "./images/shop/sale/candy_planet_minions_75-01.jpg",
    //     alt1: "candy_planet_minions_75-01",
    //     url2: "./images/shop/sale/candy_planet_minions_75-02.jpg",
    //     alt2: "candy_planet_minions_75-02",
    //     marker: "SALE100",
    //     brand: "Candy Planet",
    //     search: "кенді кенди пленет планет адвенткалендар молочный шоколад цукерка шоколадні цукерки конфета конфеты",
    //     nameUKR: "Адвент календар з сюрпризом",
    //     nameEN: "Minions",
    //     companyName: "Uno Foods Dubicki",
    //     countryName: "Польща",
    //     weightName: "Вага",
    //     weight: "75 гр.",
    //     priceGRN: 179,
    //     quantityOnStorage: 11,
    //     description01: "&#171Candy Planet - Minions&#187. ",
    //     description02: "Кожен день розкриває новий секрет солодкого задоволення у вигляді розкішного молочного шоколаду. Інтригуючі форми та вишукана якість створюють світ, де кожен шматочок – це миттєвий вихід у світ Різдвяної ярмарки.",
    //     description03: "Відчуйте бажання відзначати кожен день зі смаком витонченості та тепла. Бажання розпаковувати подарунки солодощів &#171Lindt - Weihnachtsmarkt&#187, які роблять свята ще більш неповторними.",
    //     description04: "<strong>Печиво, брелки. 24 шт.</strong>",
    //     description05: "Створіть свої унікальні моменти святкової насолоди – замовте адвент календар &#171Lindt - Weihnachtsmarkt&#187 прямо зараз та зануртеся у світ солодкого очікування!"
    // },
    // {
    //     type: "retail",
    //     url: "./images/shop/sale/chanteclair_wg_s_2575.jpg",
    //     alt: "chanteclair_wg_s_2575",
    //     url1: "./images/shop/sale/chanteclair_wg_s_2575-01.jpg",
    //     alt1: "chanteclair_wg_s_2575-01",
    //     url2: "./images/shop/household_chemicals/laundry_detergents/washing_gels/chanteclair_bicarbonato_35-01.jpg",
    //     alt2: "chanteclair_bicarbonato_35-01",
    //     url3: "./images/shop/household_chemicals/laundry_detergents/washing_gels/chanteclair_color_35-01.jpg",
    //     alt3: "chanteclair_color_35-01",
    //     url4: "./images/shop/household_chemicals/laundry_detergents/washing_gels/chanteclair_marsiglia_35-01.jpg",
    //     alt4: "chanteclair_marsiglia_35-01",
    //     url5: "./images/shop/household_chemicals/laundry_detergents/washing_gels/chanteclair_muschio_blanco_35-01.jpg",
    //     alt5: "chanteclair_muschio_blanco_35-01",
    //     url6: "./images/shop/household_chemicals/laundry_detergents/washing_gels/chanteclair_pulito_profondo_35-01.jpg",
    //     alt6: "chanteclair_pulito_profondo_35-01",
    //     url7: "./images/shop/household_chemicals/laundry_detergents/softeners/chanteclair_iconcentrati_fiori_50-01.jpg",
    //     alt7: "chanteclair_iconcentrati_fiori_50-01",
    //     url8: "./images/shop/household_chemicals/laundry_detergents/softeners/chanteclair_iconcentrati_bianco_50-01.jpg",
    //     alt8: "chanteclair_iconcentrati_bianco_50-01",
    //     url9: "./images/shop/household_chemicals/laundry_detergents/softeners/chanteclair_iconcentrati_peonia_magnolia_50-01.jpg",
    //     alt9: "chanteclair_iconcentrati_peonia_magnolia_50-01",
    //     url10: "./images/shop/household_chemicals/laundry_detergents/softeners/chanteclair_iconcentrati_marini_50-01.jpg",
    //     alt10: "chanteclair_iconcentrati_marini_50-01",
    //     marker: "SALE130",
    //     brand: "Chanteclair",
    //     search: "шантеклер гели гелі для прання стирки ополаскиватель помякшувач кондиционер смягчитель ополіскувач",
    //     nameUKR: "Гель та кондиціонер для прання &#171Chanteclair&#187",
    //     nameEN: "Lavatrice & I Concentrati Ammorbidente Sublime",
    //     companyName: "Real Chimica Srl",
    //     countryName: "Італія",
    //     volumeName: "Об'єм",
    //     volume: "2.575 л.",
    //     priceGRN: 408,
    //     quantityOnStorage: 8,
    //     description01: "Скористайтеся нашою акційною пропозицією та оберіть один з гелів для прання та один з кондиціонерів для прання від &#171Chanteclair&#187.",
    //     description02: "Гелі &#171Chanteclair&#187 забезпечують ефективне видалення плям, зберігаючи яскравість кольорів та м'якість тканин.",
    //     description03: "Кондиціонери та пом'якшувачі &#171Chanteclair&#187 дарують Вашим речам ніжний аромат і неймовірну м'якість, роблячи прання приємним ритуалом.",
    //     description04: "<strong>Набір: гель для прання, діє навіть у холодній воді, розрахований на 35 прань (1575 мл.); кондиціонер, пом'якшувач, концентрат, розрахований на 50 прань (1000 мл.).</strong>",
    //     description05: "Не пропустіть шанс поєднати якість і догляд з &#171Chanteclair&#187 та забезпечте бездоганну чистоту Вашому одягу!"
    // },
    {
        type: "retail",
        url: "./images/shop/sale/cynosure_3_1.jpg",
        alt: "cynosure_3_1",
        url1: "./images/shop/sale/cynosure_3_1-01.jpg",
        alt1: "cynosure_3_1-01",
        marker: "SALE195",
        brand: "Cynosure",
        search: "серветка макіяж макияж для снятия зняття гіалуронова кислота",
        nameUKR: "Міцелярні серветки для зняття макіяжу з гіалуроновою кислотою<br>&#171 1 + 1 = 3 &#187",
        nameEN: "Micellar Cleansing Wipes",
        companyName: "Lachmund GmbH",
        countryName: "Німеччина",
        quantityName: "Кількість",
        quantity: "75 шт.",
        priceGRN: 150,
        quantityOnStorage: 7,
        description01: "&#171Cynosure - Micellar Cleansing Wipes&#187 - це секрет бездоганної і яскравої шкіри. Ці зволожуючі і збагачені гіалуроновою кислотою серветки забезпечують ефективне очищення, одночасно зволожуючи і заспокоюючи вашу шкіру.",
        description02: "Інтенсивний догляд гіалуронової кислоти глибоко проникає у шкіру, допомагаючи зберігати природний баланс вологи і підтримувати молодість шкіри. Завдяки цьому, ваша шкіра виглядає свіжою, пружною і сяючою красою.",
        description03: "Тонкий аромат &#171Cynosure - Micellar Cleansing Wipes&#187 створює атмосферу релаксації та комфорту. Практичні та зручні у використанні, ці серветки ідеально підходять для використання у дорозі.",
        description04: "<strong>Підходять для будь-якого типу шкіри. Акційна пропозиція 1 + 1 = 3.</strong>",
        description05: "Поспішайте придбати дві упаковки &#171Cynosure - Micellar Cleansing Wipes&#187 та отримайте третю у подарунок!"
    },
    // {
    //     type: "retail",
    //     url: "./images/shop/sale/denkmit_wc_reiniger_schaum_tabletten_3.jpg",
    //     alt: "denkmit_wc_reiniger_schaum_tabletten_3",
    //     url1: "./images/shop/sale/denkmit_wc_reiniger_schaum_tabletten_3-01.jpg",
    //     alt1: "denkmit_wc_reiniger_schaum_tabletten_3-01",
    //     url2: "./images/shop/household_chemicals/means_for_cleaning/for_wc/denkmit_wc_reineiger_1l-01.jpg",
    //     alt2: "denkmit_wc_reineiger_1l-01",
    //     url3: "./images/shop/household_chemicals/means_for_cleaning/for_wc/denkmit_wc-wasserkasten-tabletten_4-01.jpg",
    //     alt3: "denkmit_wc-wasserkasten-tabletten_4-01",
    //     url4: "./images/shop/household_chemicals/means_for_cleaning/for_wc/denkmit_wc-reinigungsschaum_500-01.jpg",
    //     alt4: "denkmit_wc-reinigungsschaum_500-01",
    //     marker: "SALE210",
    //     brand: "Denkmit",
    //     search: "денкмит денкміт средство для чистки чищення чистка засіб стредства туалет пена таблетки для туалета унитаз для унитаза унітаз для унітаза унітазу",
    //     nameUKR: "Засоби &#171Denkmit&#187 для чищення туалету: піна (лимон), рідина (свіжість океану), таблетки для бачку",
    //     nameEN: "WC-Reiniger, Tabletten, Reinigungsschaum",
    //     companyName: "dm-drogerie markt GmbH + Co.",
    //     countryName: "Німеччина",
    //     volumeName: "Об'єм",
    //     volume: "1.5 л.",
    //     priceGRN: 288,
    //     quantityOnStorage: 5,
    //     description01: "Відкрийте для себе революційні засоби &#171Denkmit&#187 для чищення туалету, які забезпечують бездоганну чистоту та свіжість!",
    //     description02: "Піна з ароматом лимона, засіб для чищення (свіжость океану) та таблетки для бачку - ідеальне поєднання для догляду за Вашим туалетом.",
    //     description03: "Засоби  &#171Denkmit&#187 ефективно видаляють бруд та наліт, залишаючи приємний аромат і забезпечуючи тривалу свіжість.",
    //     description04: "<strong>Набір: засіб для чищення унітазу (свіжість океану) (1 л.), не використовувати на мармурі; піна (лимон) для чистки туалету (500 мл.), не підходить для мармуру, алюмінію, дерева; таблетки для унітазного бачку, видаляють накип та забруднення (4 штуки х 50 гр.).</strong>",
    //     description05: "Не втрачайте можливості отримати ці високоякісні засоби &#171Denkmit&#187 для чищення вже сьогодні за приємною ціною!"
    // },
    // {
    //     type: "retail",
    //     url: "./images/shop/sale/denkmit_color_US_frosch_WP_SOFT.jpg",
    //     alt: "denkmit_color_US_frosch_WP_SOFT",
    //     url1: "./images/shop/household_chemicals/laundry_detergents/washing_powder/denkmit_colorwaschmittel_ultra_sensitive_1.35-01.jpg",
    //     alt1: "denkmit_colorwaschmittel_ultra_sensitive_1.35-01",
    //     url2: "./images/shop/household_chemicals/laundry_detergents/washing_powder/denkmit_colorwaschmittel_ultra_sensitive_1.35-02.jpg",
    //     alt2: "denkmit_colorwaschmittel_ultra_sensitive_1.35-02",
    //     url3: "./images/shop/household_chemicals/laundry_detergents/washing_powder/denkmit_colorwaschmittel_ultra_sensitive_1.35-03.jpg",
    //     alt3: "denkmit_colorwaschmittel_ultra_sensitive_1.35-03",
    //     url4: "./images/shop/household_chemicals/laundry_detergents/washing_powder/denkmit_colorwaschmittel_ultra_sensitive_1.35-04.jpg",
    //     alt4: "denkmit_colorwaschmittel_ultra_sensitive_1.35-04",
    //     url5: "./images/shop/household_chemicals/laundry_detergents/softeners/frosch_zero_750-01.jpg",
    //     alt5: "frosch_zero_750-01",
    //     url6: "./images/shop/household_chemicals/laundry_detergents/softeners/frosch_zero_750-02.jpg",
    //     alt6: "frosch_zero_750-02",
    //     marker: "SALE215",
    //     brand: "Denkmit & Frosch",
    //     search: "денкміт денкмит стиральный пральний порошок пральні порошки кольорові речі цветные вещи для цветных вещей чутливі тканини чувствительные ткани для чувствительных тканей фрош зеро ополаскиватель помякшувач пом'якшувач кондиціонер кондиционер для нежной чуствительной чувствительной кожи нежная чувствительная кожа ніжна чутлива шкіра",
    //     nameUKR: "Екологічно чистий набір: порошок для кольорових речей та ополіскувач (для чутливих тканин та шкіри)",
    //     nameEN: "Colorwaschmittel Ultra Sensitive & Zero%",
    //     companyName: "dm-drogerie markt GmbH + Co. & Werner & Mertz GmbH",
    //     countryName: "Німеччина",
    //     quantityName: "Кількість",
    //     quantity: "2 шт.",
    //     priceGRN: 324,
    //     quantityOnStorage: 4,
    //     description01: "Скористайтеся екологічно чистим набором &#171Denkmit & Frosch - Colorwaschmittel Ultra Sensitive & Zero%&#187.",
    //     description02: "Порошок для кольорових речей &#171Denkmit - Colorwaschmittel Ultra Sensitive&#187 дбайливо видаляє забруднення, зберігаючи яскравість та насиченість кольорів.",
    //     description03: "Ополіскувач &#171Frosch - Zero%&#187 для чутливих тканин та шкіри забезпечує м'якість та свіжість Вашого одягу, не викликаючи подразнень.",
    //     description04: "<strong>Набір, екологічно чистий: порошок для кольорових речей (для чутливих тканин; без запаху, без барників, без консервуючих домішок; розрахований на 20 прань); ополіскувач (кондиціонер) (без фосфатів, барвників та консервантів, розрахований на 31 прання).</strong>",
    //     description05: "Зробіть вибір на користь екологічно чистого догляду за одягом - замовляйте набір &#171Denkmit & Frosch - Colorwaschmittel Ultra Sensitive & Zero%&#187 вже сьогодні!"
    // // },
    // {
    //     type: "retail",
    //     url: "./images/shop/sale/denkmit_voll_US_frosch_WP_SOFT.jpg",
    //     alt: "denkmit_voll_US_frosch_WP_SOFT",
    //     url1: "./images/shop/household_chemicals/laundry_detergents/washing_powder/denkmit_vollwaschmittel_ultra_sensitive_1.35-01.jpg",
    //     alt1: "denkmit_vollwaschmittel_ultra_sensitive_1.35-01",
    //     url2: "./images/shop/household_chemicals/laundry_detergents/washing_powder/denkmit_vollwaschmittel_ultra_sensitive_1.35-02.jpg",
    //     alt2: "denkmit_vollwaschmittel_ultra_sensitive_1.35-02",
    //     url3: "./images/shop/household_chemicals/laundry_detergents/washing_powder/denkmit_vollwaschmittel_ultra_sensitive_1.35-03.jpg",
    //     alt3: "denkmit_vollwaschmittel_ultra_sensitive_1.35-03",
    //     url4: "./images/shop/household_chemicals/laundry_detergents/washing_powder/denkmit_vollwaschmittel_ultra_sensitive_1.35-04.jpg",
    //     alt4: "denkmit_vollwaschmittel_ultra_sensitive_1.35-04",
    //     url5: "./images/shop/household_chemicals/laundry_detergents/softeners/frosch_zero_750-01.jpg",
    //     alt5: "frosch_zero_750-01",
    //     url6: "./images/shop/household_chemicals/laundry_detergents/softeners/frosch_zero_750-02.jpg",
    //     alt6: "frosch_zero_750-02",
    //     marker: "SALE217",
    //     brand: "Denkmit & Frosch",
    //     search: "денкміт денкмит стиральный пральний порошок пральні порошки универсальный чутливі тканини чувствительные ткани для чувствительных тканей фрош зеро ополаскиватель помякшувач пом'якшувач кондиціонер кондиционер для нежной чуствительной чувствительной кожи нежная чувствительная кожа ніжна чутлива шкіра",
    //     nameUKR: "Екологічно чистий набір: порошок універсальний та ополіскувач (для чутливих тканин та шкіри)",
    //     nameEN: "Vollwaschmittel Ultra Sensitive & Zero%",
    //     companyName: "dm-drogerie markt GmbH + Co. & Werner & Mertz GmbH",
    //     countryName: "Німеччина",
    //     quantityName: "Кількість",
    //     quantity: "2 шт.",
    //     priceGRN: 324,
    //     quantityOnStorage: 4,
    //     description01: "Отримайте екологічно чистий набір &#171Denkmit & Frosch - Vollwaschmittel Ultra Sensitive & Zero%&#187 для догляду за одягом: універсальний порошок та ополіскувач для чутливих тканин та шкіри!",
    //     description02: "Універсальний порошок &#171Denkmit - Vollwaschmittel Ultra Sensitive&#187 дбайливо видаляє забруднення з будь-яких тканин, зберігаючи їхню яскравість та цілісність.",
    //     description03: "Ополіскувач &#171Frosch - Zero%&#187 спеціально розроблений для чутливих тканин та шкіри, забезпечуючи м'якість і свіжість без алергенів.",
    //     description04: "<strong>Набір, екологічно чистий: порошок універсальний (для чутливих тканин; без запаху, без барників, без консервуючих домішок; розрахований на 20 прань); ополіскувач (кондиціонер) (без фосфатів, барвників та консервантів, розрахований на 31 прання).</strong>",
    //     description05: "Оберіть екологічний догляд за вашим одягом та здоров'ям, скориставшись акційною пропозицією: набір &#171Denkmit & Frosch - Vollwaschmittel Ultra Sensitive & Zero%&#187!"
    // },
    // {
    //     type: "retail",
    //     url: "./images/shop/sale/dermo_almond_cynosure_10_off.jpg",
    //     alt: "dermo_almond_cynosure_10_off",
    //     url1: "./images/shop/sale/dermo_almond_cynosure_10_off-01.jpg",
    //     alt1: "dermo_almond_cynosure_10_off-01",
    //     marker: "SALE200",
    //     brand: "Dermomed & Cynosure",
    //     search: "гель дермомед гелі гели для душа мигдаль миндаль міндаль серветка салфетка салфетки с кислотой макіяж макияж для снятия зняття гіалуронова кислота",
    //     nameUKR: "Дует &#171Магія мигдалю&#187 з гіалуроновою кислотою",
    //     nameEN: "The Magic Of Almonds",
    //     companyName: "Pharmalife Research & Lachmund",
    //     countryName: "Німеччина & Італія",
    //     volumeName: "Об'єм",
    //     volume: "1 л.",
    //     priceGRN: 152,
    //     quantityOnStorage: 5,
    //     description01: "&#171Dermomed - Shower Gel Almond&#187 - гель для душу з мигдалем та гіалуроновою кислотою. Дбайливо очищає, забезпечує глибоке зволоження та живлення шкіри.",
    //     description02: "Інноваційна формула гелю містить гіалуронову кислоту, яка відома своєю здатністю притягувати та утримувати вологу, забезпечуючи інтенсивне зволоження шкіри навіть після душу. Ваша шкіра залишиться м'якою, еластичною та свіжою.",
    //     description03: "&#171Cynosure - Micellar Cleansing Wipes&#187 - це секрет бездоганної і яскравої шкіри. Ці зволожуючі і збагачені гіалуроновою кислотою серветки забезпечують ефективне очищення, одночасно зволожуючи і заспокоюючи вашу шкіру.",
    //     description04: "<strong>Комплект з гіалуроновою кислотою: гель для душу (1 л.) та міцерялні серветки (25 шт.). Підходять для будь-якого типу шкіри.</strong>",
    //     description05: "Забезпечте свою шкіру найкращим доглядом: дует &#171Магія мигдалю&#187 чекає саме на Вас, щоб подарувати ексклюзивну можливість отримати неперевершену свіжість та сяючу красу!"
    // },
    // {
    //     type: "retail",
    //     url: "./images/shop/sale/dermo_aloe_cynosure_10_off.jpg",
    //     alt: "dermo_aloe_cynosure_10_off",
    //     url1: "./images/shop/sale/dermo_aloe_cynosure_10_off-01.jpg",
    //     alt1: "dermo_aloe_cynosure_10_off-01",
    //     marker: "SALE202",
    //     brand: "Dermomed & Cynosure",
    //     search: "гель дермомед гелі гели для душа алое алоє алоэ серветка салфетка салфетки с кислотой макіяж макияж для снятия зняття гіалуронова кислота",
    //     nameUKR: "Дует &#171Магія алое&#187 з гіалуроновою кислотою",
    //     nameEN: "The Magic Of Aloe",
    //     companyName: "Pharmalife Research & Lachmund",
    //     countryName: "Німеччина & Італія",
    //     volumeName: "Об'єм",
    //     volume: "1 л.",
    //     priceGRN: 152,
    //     quantityOnStorage: 5,
    //     description01: "&#171Dermomed - Shower Gel Aloe&#187 - гель для душу, який відкриває новий рівень догляду за вашою шкірою на основі алое та гіалуронової кислоти. Він допомагає не тільки зберегти природну красу вашої шкіри, а й забезпечує її здоров'я.",
    //     description02: "Збагачений натуральними екстрактами алое, гель дбайливо очищає та заспокоює шкіру, даруючи приємне відчуття комфорту під час душу.",
    //     description03: "&#171Cynosure - Micellar Cleansing Wipes&#187 - це секрет бездоганної і яскравої шкіри. Ці зволожуючі і збагачені гіалуроновою кислотою серветки забезпечують ефективне очищення, одночасно зволожуючи і заспокоюючи вашу шкіру.",
    //     description04: "<strong>Комплект з гіалуроновою кислотою: гель для душу (1 л.) та міцерялні серветки (25 шт.). Підходять для будь-якого типу шкіри.</strong>",
    //     description05: "Запрошуємо вас у світ елегантного догляду за шкірою з нашим комплектом &#171Магія алое&#187 – вигідний та неперевершений дует, який подарує вашій шкірі відчуття дивовижної м'якості та бездоганного зволоження!"
    // },
    // {
    //     type: "retail",
    //     url: "./images/shop/sale/dermo_argan_cynosure_10_off.jpg",
    //     alt: "dermo_argan_cynosure_10_off",
    //     url1: "./images/shop/sale/dermo_argan_cynosure_10_off-01.jpg",
    //     alt1: "dermo_argan_cynosure_10_off-01",
    //     marker: "SALE204",
    //     brand: "Dermomed & Cynosure",
    //     search: "гель дермомед гелі гели для душа арган арганова олія аргановое масло серветка салфетка салфетки с кислотой макіяж макияж для снятия зняття гіалуронова кислота",
    //     nameUKR: "Дует &#171Магія аргану&#187 з гіалуроновою кислотою",
    //     nameEN: "The Magic Of Argan",
    //     companyName: "Pharmalife Research & Lachmund",
    //     countryName: "Німеччина & Італія",
    //     volumeName: "Об'єм",
    //     volume: "1 л.",
    //     priceGRN: 152,
    //     quantityOnStorage: 5,
    //     description01: "&#171Dermomed - Shower Gel Argan&#187 пропонує Вам відкрити таємницю догляду за шкірою на основі арганової олії та гіалуронової кислоти. Цей унікальний продукт дарує вашій шкірі відновлення та глибоке зволоження.",
    //     description02: "Завдяки багатому складу, що містить натуральні компоненти арганової олії, гель ефективно живить та пом'якшує шкіру, надаючи їй шовковистість та здоровий вигляд.",
    //     description03: "&#171Cynosure - Micellar Cleansing Wipes&#187 - це секрет бездоганної і яскравої шкіри. Ці зволожуючі і збагачені гіалуроновою кислотою серветки забезпечують ефективне очищення, одночасно зволожуючи і заспокоюючи вашу шкіру.",
    //     description04: "<strong>Комплект з гіалуроновою кислотою: гель для душу (1 л.) та міцерялні серветки (25 шт.). Підходять для будь-якого типу шкіри.</strong>",
    //     description05: "Надайте своїй шкірі арганового догляду з нашим унікальним комплектом &#171Магія аргану&#187 – збалансоване поєднання гелю для душу та міцелярних серветок з гіалуроновою кислотою, яке надає вашій шкірі неймовірне зволоження та блиск, сповнюючи її ексклюзивними відчуттями благополуччя!"
    // },
    // {
    //     type: "retail",
    //     url: "./images/shop/sale/dermo_frangipani_cynosure_10_off.jpg",
    //     alt: "dermo_frangipani_cynosure_10_off",
    //     url1: "./images/shop/sale/dermo_frangipani_cynosure_10_off-01.jpg",
    //     alt1: "dermo_frangipani_cynosure_10_off-01",
    //     marker: "SALE206",
    //     brand: "Dermomed & Cynosure",
    //     search: "гель дермомед гелі гели для душа плюмерія плюмерії плюмерия серветка салфетка салфетки с кислотой макіяж макияж для снятия зняття гіалуронова кислота",
    //     nameUKR: "Дует &#171Магія плюмерії&#187 з гіалуроновою кислотою",
    //     nameEN: "The Magic Of Frangipani",
    //     companyName: "Pharmalife Research & Lachmund",
    //     countryName: "Німеччина & Італія",
    //     volumeName: "Об'єм",
    //     volume: "1 л.",
    //     priceGRN: 152,
    //     quantityOnStorage: 5,
    //     description01: "&#171Dermomed - Shower Gel Frangipani&#187 відкриває перед вами чарівний світ догляду за шкірою на основі плюмерії та гіалуронової кислоти. Цей гель для душу надасть вашій шкірі розкішний і водночас ніжний дотик.",
    //     description02: "Глибоке живлення та зволоження - ось, що робить цей гель особливим. Аромат плюмерії додасть нотку екзотики та розслаблення.",
    //     description03: "&#171Cynosure - Micellar Cleansing Wipes&#187 - це секрет бездоганної і яскравої шкіри. Ці зволожуючі і збагачені гіалуроновою кислотою серветки забезпечують ефективне очищення, одночасно зволожуючи і заспокоюючи вашу шкіру.",
    //     description04: "<strong>Комплект з гіалуроновою кислотою: гель для душу (1 л.) та міцерялні серветки (25 шт.). Підходять для будь-якого типу шкіри.</strong>",
    //     description05: "Надайте вашій шкірі неймовірне омолодження та витончений аромат з дуетом &#171Магія плюмерії&#187, перетворюючи кожен момент догляду у неперевершений ритуал краси!"
    // },
    // {
    //     type: "retail",
    //     url: "./images/shop/sale/dermo_iris_cynosure_10_off.jpg",
    //     alt: "dermo_iris_cynosure_10_off",
    //     url1: "./images/shop/sale/dermo_iris_cynosure_10_off-01.jpg",
    //     alt1: "dermo_iris_cynosure_10_off-01",
    //     marker: "SALE208",
    //     brand: "Dermomed & Cynosure",
    //     search: "гель дермомед гелі гели для душа ірис іріс ирис серветка салфетка салфетки с кислотой макіяж макияж для снятия зняття гіалуронова кислота",
    //     nameUKR: "Дует &#171Магія ірису&#187 з гіалуроновою кислотою",
    //     nameEN: "The Magic Of Iris",
    //     companyName: "Pharmalife Research & Lachmund",
    //     countryName: "Німеччина & Італія",
    //     volumeName: "Об'єм",
    //     volume: "1 л.",
    //     priceGRN: 152,
    //     quantityOnStorage: 5,
    //     description01: "&#171Dermomed - Shower Gel Iris&#187 - новий інноваційний продукт, гель для душу з екстрактом ірису та гіалуроновою кислотою. Його формула дбайливо доглядає за шкірою, забезпечуючи відчуття комфорту та свіжості.",
    //     description02: "Відчуйте аромат ніжних квітів ірису, який доповнить ваш душовий ритуал відчуттям спокою та релаксації.",
    //     description03: "&#171Cynosure - Micellar Cleansing Wipes&#187 - це секрет бездоганної і яскравої шкіри. Ці зволожуючі і збагачені гіалуроновою кислотою серветки забезпечують ефективне очищення, одночасно зволожуючи і заспокоюючи вашу шкіру.",
    //     description04: "<strong>Комплект з гіалуроновою кислотою: гель для душу (1 л.) та міцерялні серветки (25 шт.). Підходять для будь-якого типу шкіри.</strong>",
    //     description05: "Осяйте вашу шкіру чарівною красою з нашим комплектом &#171Магія ірису&#187 – неперевершений дует гелю для душу та міцелярних серветок з гіалуроновою кислотою, який дарує вашій шкірі ніжність і бездоганне зволоження, створюючи справжню магію догляду!"
    // },
    // {
    //     type: "retail",
    //     url: "./images/shop/sale/fairy_granuls_WP.jpg",
    //     alt: "fairy_granuls_WP",
    //     url1: "./images/shop/sale/fairy_granuls_WP-01.jpg",
    //     alt1: "fairy_granuls_WP-01",
    //     url2: "./images/shop/household_chemicals/laundry_detergents/scent_booster_granuls/fairy_scent_booster_almond_manuka_245-01.jpg",
    //     alt2: "fairy_scent_booster_almond_manuka_245-01",
    //     url3: "./images/shop/household_chemicals/laundry_detergents/scent_booster_granuls/fairy_scent_booster_almond_manuka_245-02.jpg",
    //     alt3: "fairy_scent_booster_almond_manuka_245-02",
    //     url4: "./images/shop/household_chemicals/laundry_detergents/washing_powder/fairy_non_bio_3.9-01.jpg",
    //     alt4: "fairy_non_bio_3.9-01",
    //     url5: "./images/shop/household_chemicals/laundry_detergents/washing_powder/fairy_non_bio_3.9-02.jpg",
    //     alt5: "fairy_non_bio_3.9-02",
    //     url6: "./images/shop/household_chemicals/laundry_detergents/washing_powder/fairy_non_bio_3.9-03.jpg",
    //     alt6: "fairy_non_bio_3.9-03",
    //     url7: "./images/shop/household_chemicals/laundry_detergents/washing_powder/fairy_non_bio_3.9-04.jpg",
    //     alt7: "fairy_non_bio_3.9-04",
    //     marker: "SALE270",
    //     brand: "Fairy",
    //     search: "In-Wash in wash Scent Booster фейри фейрі фери фері детский для дітей для детей підсилювач запаху запах усилитель запаха ароматизатор в гранулах в гранулах парфюм гранулы гранули гранула чутлива шкіра чуствительноя кожа чувствительная кожа для чуствительной кожи для чувствительрой кожи мигдаль миндаль детский стиральный пральний порошок пральні порошки дитячі детские стиральные порошки для дітей для детей универсальный",
    //     nameUKR: "Набір &#171Дитяча несподіванка&#187 (порошок та гранили)",
    //     nameEN: "Fresh Almond Milk & Manuka Honey Scent + Non Bio",
    //     companyName: "The Procter & Gamble Company",
    //     countryName: "Італія",
    //     weightName: "Вага",
    //     weight: "4.145 кг.",
    //     priceGRN: 785,
    //     quantityOnStorage: 1,
    //     description01: "Відкрийте для себе світ неймовірного аромату та надзвичайної свіжості з дитячим парфумом у гранулах &#171Fairy - Fresh Almond Milk & Manuka Honey Scent&#187.",
    //     description02: "Цей продукт витончено поєднує аромат мигдального молока та меду Манука, надаючи вашій білизні не лише неперевершену чистоту, але й надзвичайно приємний аромат.",
    //     description03: "Бажаєте, щоб ваша білизна не лише сяяла, але й пахла чарівно? Ви неодмінно захочете вибрати &#171Fairy - Fresh Almond Milk & Manuka Honey Scent&#187, щоб кожен дотик до одягу вашого малюка приносив насолоду ароматною свіжістю.",
    //     description04: "<strong>Набір: дитячий парфум (підсилювач запаху) для прання у гранулах з ароматами мигдального молока та меду Манука, не містить важких парфумів та барвників, для чутливої шкіри; порошок універсальний, дитячий. Розрахований на 60 прань.</strong>",
    //     description05: "Вдихніть аромат розкоші у кожен день вашого малюка - додайте &#171Fairy - Fresh Almond Milk & Manuka Honey Scent&#187 у Ваше прання та насолоджуйтеся бездоганною свіжістю одягу!"
    // },
    {
        type: "retail",
        url: "./images/shop/sale/felce_azzurra_laundry_detergent_softener.jpg",
        alt: "felce_azzurra_laundry_detergent_softener",
        url1: "./images/shop/sale/felce_azzurra_laundry_detergent_softener-01.jpg",
        alt1: "felce_azzurra_laundry_detergent_softener-01",
        url2: "./images/shop/household_chemicals/laundry_detergents/washing_gels/felce_azzurra_color_32-01.jpg",
        alt2: "felce_azzurra_color_32-01",
        url3: "./images/shop/household_chemicals/laundry_detergents/washing_gels/felce_azzurra_aleppo_soap_32-01.jpg",
        alt3: "felce_azzurra_aleppo_soap_32-01",
        url4: "./images/shop/household_chemicals/laundry_detergents/washing_gels/felce_azzurra_original_32-01.jpg",
        alt4: "felce_azzurra_original_32-01",
        url5: "./images/shop/household_chemicals/laundry_detergents/softeners/felce_azzurra_amber_40-01.jpg",
        alt5: "felce_azzurra_amber_40-01",
        url6: "./images/shop/household_chemicals/laundry_detergents/softeners/felce_azzurra_lavender_iris_40-01.jpg",
        alt6: "felce_azzurra_lavender_iris_40-01",
        url7: "./images/shop/household_chemicals/laundry_detergents/softeners/felce_azzurra_original_40-01.jpg",
        alt7: "felce_azzurra_original_40-01",
        url8: "./images/shop/household_chemicals/laundry_detergents/softeners/felce_azzurra_pure_freshness_40-01.jpg",
        alt8: "felce_azzurra_pure_freshness_40-01",
        url9: "./images/shop/household_chemicals/laundry_detergents/softeners/felce_azzurra_rose_lotus_40-01.jpg",
        alt9: "felce_azzurra_rose_lotus_40-01",
        marker: "SALE280",
        brand: "Felce Azzurra",
        search: "фелче азура аззурра аззура азурра гели гелі для прання стирки ополаскиватель помякшувач кондиционер смягчитель ополіскувач",
        nameUKR: "Гель та кондиціонер для прання &#171Felce Azzurra&#187",
        nameEN: "Laundry Detergent & Softener",
        companyName: "Paglieri S.P.A.",
        countryName: "Італія",
        volumeName: "Об'єм",
        volume: "3.595 л.",
        priceGRN: 524,
        quantityOnStorage: 7,
        description01: "Відчуйте неперевершену чистоту та свіжість з акційною пропозицією для &#171Felce Azzurra&#187.",
        description02: "Оберіть один з гелів для прання &#171Felce Azzurra&#187, які ефективно видаляють плями та зберігають яскравість Ваших улюблених речей.",
        description03: "Додайте до свого вибору один з кондиціонерів для прання &#171Felce Azzurra&#187, що дарують одягу ніжність і тривалий аромат.",
        description04: "<strong>Набір: гель для прання, розрахований на 32 прання (1.595 л.); ополіскувач, пом'якшувач, розрахований на 40 прань (2 л.).</strong>",
        description05: "Забезпечте своєму одягу найкращий догляд з продуктами &#171Felce Azzurra&#187 та насолоджуйтесь результатами!"
    },
    {
        type: "retail",
        url: "./images/shop/sale/felce_azzurra_laundry_detergent_softener_big.jpg",
        alt: "felce_azzurra_laundry_detergent_softener_big",
        url1: "./images/shop/sale/felce_azzurra_laundry_detergent_softener_big-01.jpg",
        alt1: "felce_azzurra_laundry_detergent_softener_big-01",
        url2: "./images/shop/household_chemicals/laundry_detergents/washing_gels/felce_azzurra_color_32-01.jpg",
        alt2: "felce_azzurra_color_32-01",
        url3: "./images/shop/household_chemicals/laundry_detergents/washing_gels/felce_azzurra_aleppo_soap_32-01.jpg",
        alt3: "felce_azzurra_aleppo_soap_32-01",
        url4: "./images/shop/household_chemicals/laundry_detergents/washing_gels/felce_azzurra_original_32-01.jpg",
        alt4: "felce_azzurra_original_32-01",
        url5: "./images/shop/household_chemicals/laundry_detergents/softeners/felce_azzurra_amber_45-01.jpg",
        alt5: "felce_azzurra_amber_45-01",
        // url6: "./images/shop/household_chemicals/laundry_detergents/softeners/felce_azzurra_lavanda_iris_45-01.jpg",
        // alt6: "felce_azzurra_lavender_iris_45-01",
        url6: "./images/shop/household_chemicals/laundry_detergents/softeners/felce_azzurra_original_45-01.jpg",
        alt6: "felce_azzurra_original_45-01",
        // url8: "./images/shop/household_chemicals/laundry_detergents/softeners/felce_azzurra_pura_freschezza_45-01.jpg",
        // alt8: "felce_azzurra_pure_freshness_45-01",
        url7: "./images/shop/household_chemicals/laundry_detergents/softeners/felce_azzurra_rose_lotus_45-01.jpg",
        alt7: "felce_azzurra_rose_lotus_45-01",
        marker: "SALE282",
        brand: "Felce Azzurra",
        search: "фелче азура аззурра аззура азурра гели гелі для прання стирки ополаскиватель помякшувач кондиционер смягчитель ополіскувач",
        nameUKR: "Гель та кондиціонер для прання &#171Felce Azzurra&#187",
        nameEN: "Laundry Detergent & Softener",
        companyName: "Paglieri S.P.A.",
        countryName: "Італія",
        volumeName: "Об'єм",
        volume: "4.595 л.",
        priceGRN: 535,
        quantityOnStorage: 7,
        description01: "Відчуйте неперевершену чистоту та свіжість з акційною пропозицією для &#171Felce Azzurra&#187.",
        description02: "Оберіть один з гелів для прання &#171Felce Azzurra&#187, які ефективно видаляють плями та зберігають яскравість Ваших улюблених речей.",
        description03: "Додайте до свого вибору один з кондиціонерів для прання &#171Felce Azzurra&#187, що дарують одягу ніжність і тривалий аромат.",
        description04: "<strong>Набір: гель для прання, розрахований на 32 прання (1.595 л.); ополіскувач, пом'якшувач, розрахований на 45 прань (3 л.).</strong>",
        description05: "Забезпечте своєму одягу найкращий догляд з продуктами &#171Felce Azzurra&#187 та насолоджуйтесь результатами!"
    },
    // {
    //     type: "retail",
    //     url: "./images/shop/sale/ferrero_kinder_mix_131.jpg",
    //     alt: "ferrero_kinder_mix_131",
    //     url1: "./images/shop/sale/ferrero_kinder_mix_131-01.jpg",
    //     alt1: "ferrero_kinder_mix_131-02",
    //     url2: "./images/shop/sale/ferrero_kinder_mix_131-02.jpg",
    //     alt2: "ferrero_kinder_mix_131-03",
    //     url3: "./images/shop/sale/ferrero_kinder_mix_131-03.jpg",
    //     alt3: "ferrero_kinder_mix_131-04",
    //     marker: "SALE300",
    //     brand: "Ferrero",
    //     search: "фереро ферреро kusschen шоколад цукерка шоколадні цукерки конфета конфеты",
    //     nameUKR: "Подарунковий набір",
    //     nameEN: "Kinder Mix",
    //     companyName: "Ferrero SpA",
    //     countryName: "Німеччина",
    //     weightName: "Вага",
    //     weight: "131 гр.",
    //     priceGRN: 509,
    //     quantityOnStorage: 7,
    //     description01: "Перетворіть свої святкові моменти у незабутню подорож солодощами за допомогою подарункового набору &#171Ferrero - Kinder Mix&#187.",
    //     description02: "Збалансована комбінація улюблених лакомств подарує святнковий настрій всій вашій родині. Кожен шматочок – це витончено зроблений солодкий келих насолоди, готовий розкрити для Вас справжній смаковий рай.",
    //     description03: "Насолоджуйтеся розкішшю кожного моменту з &#171Ferrero - Kinder Mix&#187 та бажанням поділитися цією неймовірною насолодою з близькими.",
    //     description04: "<strong>Набір подарунковий, плюшевий на блискавці: батончики &#171Kinder#187 (4 шт.), шоколадна фігурка Діда Мороза, пакетик &#171Kinder Schoko-Bons#187, шоколадне яйце &#171Kinder - Surprise#187</strong>",
    //     description05: "Створіть миті неймовірного смаку – замовте &#171Ferrero - Kinder Mix&#187 зараз та подаруйте унікальний набір насолоди тим, кого Ви любите!"
    // },
    // {
    //     type: "retail",
    //     url: "./images/shop/sale/ferrero_kusschen_200.jpg",
    //     alt: "ferrero_kusschen_200",
    //     url1: "./images/shop/sale/ferrero_kusschen_200-01.jpg",
    //     alt1: "ferrero_kusschen_200-01",
    //     url2: "./images/shop/sale/ferrero_kusschen_200-02.jpg",
    //     alt2: "ferrero_kusschen_200-02",
    //     marker: "SALE320",
    //     brand: "Ferrero",
    //     search: "фереро ферреро kusschen адвенткалендар шоколад цукерка шоколадні цукерки конфета конфеты",
    //     nameUKR: "Адвент календар",
    //     nameEN: "Küsschen",
    //     companyName: "Ferrero SpA",
    //     countryName: "Німеччина",
    //     weightName: "Вага",
    //     weight: "200 гр.",
    //     priceGRN: 879,
    //     quantityOnStorage: 7,
    //     description01: "Оновіть своє святкове очікування з чарівним адвент календарем &#171Ferrero - Küsschen&#187 - це магія солодкого очікування, яка заволодіє вашим серцем.",
    //     description02: "Кожна комірочка таємничого календаря розкривається своєю унікальною формою та вишуканістю дизайну. Кожен день Вас очікує відкриття нового сюрпризу – ароматного та неперевершеного шоколадного задоволення.",
    //     description03: "Солодкі &#171Ferrero - Küsschen&#187 в асортименті – це не просто шоколадні цукерки, це справжня феєрія смаку, яка пробуджує Ваши найтепліші бажання. Відчуйте бажання розкривати нові смаки та пориньте у світ неперевершеного задоволення.",
    //     description04: "<strong>Цукерки шоколадні, асорті (5 видів). 24 шт.</strong>",
    //     description05: "Замовте свій адвент календар &#171Ferrero - Küsschen&#187 прямо зараз та даруйте собі та близьким незабутні миті солодкого захоплення!"
    // },
    // {
    //     type: "retail",
    //     url: "./images/shop/sale/firago_bears_50.jpg",
    //     alt: "firago_bears_50",
    //     url1: "./images/shop/sale/firago_bears_50.jpg",
    //     alt1: "firago_bears_50",
    //     marker: "SALE380",
    //     brand: "Figaro",
    //     search: "фигаро фігаро адвенткалендар молочный шоколад цукерка шоколадні цукерки конфета конфеты медведь медведи ведмідь ведмеді ведмедик ведмедики",
    //     nameUKR: "Адвент календар",
    //     nameEN: "Medvedíky Z Mliečnej Čokolády",
    //     companyName: "I.D.C. Holding, a.s.",
    //     countryName: "Словаччина",
    //     weightName: "Вага",
    //     weight: "50 гр.",
    //     priceGRN: 60,
    //     quantityOnStorage: 13,
    //     description01: "Приготуйтеся до чарівної подорожі у світ солодкого очікування з адвент календарем &#171Figaro - Medvedíky Z Mliečnej Čokolády&#187. Він робить кожен день особливим і неповторним.",
    //     description02: "Розкрийте таємницю смаку молочного шоколаду у кожній комірці та відкрийте веселий світ ведмедиків-фігурок, які прикрашають ялинку.",
    //     description03: "Збуджуйте своє бажання насолоджуватися святковими моментами, розпаковуючи щоденні сюрпризи від &#171Figaro - Medvedíky Z Mliečnej Čokolády&#187.",
    //     description04: "<strong>Шоколад молочний, 24 шт. Фігрурки вирізні, на ялинку.</strong>",
    //     description05: "Зробіть свої свята яскравішими та солодшими – замовте &#171Figaro - Medvedíky Z Mliečnej Čokolády&#187 адвент календар прямо зараз та пориньте у світ святкового захоплення!"
    // },
    // {
    //     type: "retail",
    //     url: "./images/shop/sale/frosch_zero_soft_hand_1250.jpg",
    //     alt: "frosch_zero_soft_hand_1250",
    //     url1: "./images/shop/household_chemicals/laundry_detergents/softeners/frosch_zero_750-01.jpg",
    //     alt1: "frosch_zero_750-01",
    //     url2: "./images/shop/household_chemicals/laundry_detergents/softeners/frosch_zero_750-02.jpg",
    //     alt2: "frosch_zero_750-02",
    //     url3: "./images/shop/household_chemicals/means_for_washing_dishes/hands/frosch_zero_detergente_loica_500-01.jpg",
    //     alt3: "frosch_zero_detergente_loica_500-01",
    //     url4: "./images/shop/household_chemicals/means_for_washing_dishes/hands/frosch_zero_detergente_loica_500-02.jpg",
    //     alt4: "frosch_zero_detergente_loica_500-02",
    //     marker: "SALE310",
    //     brand: "Frosch",
    //     search: "фрош зеро ополаскиватель помякшувач пом'якшувач кондиціонер кондиционер для нежной чуствительной чувствительной кожи нежная чувствительная кожа ніжна чутлива шкіра loica sensiveis средство для мытья мийний мийні забоси стредства посуды посуда чувствительная кожа для чувствительной кожи экологический экологическое чистое",
    //     nameUKR: "Екологічний набір: ополіскувач та засіб для миття посуду (для чутливої шкіри)",
    //     nameEN: "Zero%",
    //     companyName: "Werner & Mertz GmbH",
    //     countryName: "Німеччина",
    //     volumeName: "Об'єм",
    //     volume: "1250 мл.",
    //     priceGRN: 144,
    //     quantityOnStorage: 5,
    //     description01: "Відкрийте для себе екологічно чистий набір &#171Frosch - Zero%&#187, спеціально створений для догляду за чутливою шкірою!",
    //     description02: "Ополіскувач забезпечує м'якість Вашого одягу, зберігаючи його свіжість і не викликаючи подразнень.",
    //     description03: "Засіб для миття посуду ефективно видаляє жир і залишки їжі, дбаючи про Ваші руки завдяки делікатній формулі.",
    //     description04: "<strong>Екологічний набір: ополіскувач (розрахований на 31 прання) та засіб для миття посуду (для чутливої шкіри). Без фосфатів, барвників та консервантів.</strong>",
    //     description05: "Скористайтеся нашою акційною пропозицією &#171Frosch - Zero%&#187 та зробіть крок до екологічного догляду за Вашим домом і здоров'ям!"
    // },
    // {
    //     type: "retail",
    //     url: "./images/shop/sale/gallus_konzentriertes_washing_gel_concentrated_softener_3l.jpg",
    //     alt: "gallus_konzentriertes_washing_gel_concentrated_softener_3l",
    //     url1: "./images/shop/sale/gallus_konzentriertes_washing_gel_concentrated_softener_3l-01.jpg",
    //     alt1: "gallus_konzentriertes_washing_gel_concentrated_softener_3l-01",
    //     url2: "./images/shop/household_chemicals/laundry_detergents/washing_gels/gallus_black_gel_2l-01.jpg",
    //     alt2: "gallus_black_gel_2l-01",
    //     url3: "./images/shop/household_chemicals/laundry_detergents/washing_gels/gallus_color_gel_2l-01.jpg",
    //     alt3: "gallus_color_gel_2l-01",
    //     url4: "./images/shop/household_chemicals/laundry_detergents/washing_gels/gallus_sensitive_gel_2l-01.jpg",
    //     alt4: "gallus_sensitive_gel_2l-01",
    //     url5: "./images/shop/household_chemicals/laundry_detergents/washing_gels/gallus_sport_gel_2l-01.jpg",
    //     alt5: "gallus_sport_gel_2l-01",
    //     url6: "./images/shop/household_chemicals/laundry_detergents/washing_gels/gallus_universal_gel_2l-01.jpg",
    //     alt6: "gallus_universal_gel_2l-01",
    //     url7: "./images/shop/household_chemicals/laundry_detergents/washing_gels/gallus_white_gel_2l-01.jpg",
    //     alt7: "gallus_white_gel_2l-01",
    //     url8: "./images/shop/household_chemicals/laundry_detergents/softeners/gallus_frisch_1l-01.jpg",
    //     alt8: "gallus_frisch_1l-01",
    //     url9: "./images/shop/household_chemicals/laundry_detergents/softeners/gallus_orchidee_1l-01.jpg",
    //     alt9: "gallus_orchidee_1l-01",
    //     marker: "SALE350",
    //     brand: "Gallus",
    //     search: "галлус галус хенкель гели гелі для прання стирки ополаскиватель помякшувач кондиционер смягчитель ополіскувач",
    //     nameUKR: "Гель та кондиціонер для прання &#171Gallus&#187",
    //     nameEN: "Konzentriertes Washing Gel & Concentrated Softener",
    //     companyName: "Henkel",
    //     countryName: "Німеччина",
    //     volumeName: "Об'єм",
    //     volume: "3 л.",
    //     priceGRN: 220,
    //     quantityOnStorage: 5,
    //     description01: "Не пропустіть вигідну акційну пропозицію для &#171Gallus&#187, яка допоможе Вам забезпечити бездоганний догляд за Вашим одягом.",
    //     description02: "Виберіть один з високоякісних гелів для прання &#171Gallus&#187, що ефективно видаляють плями та зберігають яскравість тканин.",
    //     description03: "Додайте до свого вибору один з кондиціонерів для прання &#171Gallus&#187, які дарують речам ніжність і тривалий свіжий аромат.",
    //     description04: "<strong>Набір: гель для прання, концентрат, розрахований на 57 прань (2 л.); ополіскувач, пом'якшувач, концентрат, розрахований на 40 прань (1 л.).</strong>",
    //     description05: "Забезпечте своєму одягу найкращий догляд з продукцією &#171Gallus&#187 та відчуйте різницю вже після першого прання!"
    // },
    // {
    //     type: "retail",
    //     url: "./images/shop/sale/gallus_perfumed_washing_gel_concentrated_softener_4.02l.jpg",
    //     alt: "gallus_perfumed_washing_gel_concentrated_softener_4.02l",
    //     url1: "./images/shop/sale/gallus_perfumed_washing_gel_concentrated_softener_4.02l-01.jpg",
    //     alt1: "gallus_perfumed_washing_gel_concentrated_softener_4.02l-01",
    //     url2: "./images/shop/household_chemicals/laundry_detergents/washing_gels/gallus_colorwaschmittel_1.98l-01.jpg",
    //     alt2: "gallus_colorwaschmittel_1.98l-01",
    //     url3: "./images/shop/household_chemicals/laundry_detergents/washing_gels/gallus_vollwaschmittel_1.98l-01.jpg",
    //     alt3: "gallus_vollwaschmittel_1.98l-01",
    //     url4: "./images/shop/household_chemicals/laundry_detergents/softeners/gallus_frisch_2l-01.jpg",
    //     alt4: "gallus_frisch_2l-01",
    //     url5: "./images/shop/household_chemicals/laundry_detergents/softeners/gallus_orchidee_2l-01.jpg",
    //     alt5: "gallus_orchidee_2l-01",
    //     marker: "SALE352",
    //     brand: "Gallus",
    //     search: "галлус галус хенкель гели гелі для прання стирки ополаскиватель помякшувач кондиционер смягчитель ополіскувач",
    //     nameUKR: "Безфосфатрий гель та кондиціонер для прання &#171Gallus&#187",
    //     nameEN: "Perfumed Washing Gel & Concentrated Softener",
    //     companyName: "Henkel",
    //     countryName: "Німеччина",
    //     volumeName: "Об'єм",
    //     volume: "4.02 л.",
    //     priceGRN: 266,
    //     quantityOnStorage: 5,
    //     description01: "Унікальна акція: виберіть будь-який гель для прання та будь-який кондиціонер для прання &#171Gallus&#187 без фосфатів!",
    //     description02: "Ці засоби забезпечать Вам ідеальну чистоту та свіжість Вашого одягу завдяки своїм природним та ефективним складникам.",
    //     description03: "Забудьте про подразнення шкіри та пошкодження тканин - тепер Ваш одяг буде доглянутим та безпечним для всієї родини разом з &#171Gallus&#187.",
    //     description04: "<strong>Набір: безфосфатний гель для прання, розрахований на 55 прань (1.98 л.); ополіскувач, пом'якшувач, концентрат, розрахований на 60 прань (2.04 л.).</strong>",
    //     description05: "Не втрачайте шанс зробити своє прання приємнішим та безпечнішим скориставшить ексклюзивною пропозицією від &#171Gallus&#187!"
    // },
    // {
    //     type: "retail",
    //     url: "./images/shop/sale/gallus_perfumed_washing_gel_concentrated_softener_8.13l.jpg",
    //     alt: "gallus_perfumed_washing_gel_concentrated_softener_8.13l",
    //     url1: "./images/shop/sale/gallus_perfumed_washing_gel_concentrated_softener_8.13l-01.jpg",
    //     alt1: "gallus_perfumed_washing_gel_concentrated_softener_8.13l-01",
    //     url1: "./images/shop/household_chemicals/laundry_detergents/washing_gels/gallus_colorwaschmittel_4l-01.jpg",
    //     alt1: "gallus_colorwaschmittel_4l-01",
    //     url1: "./images/shop/household_chemicals/laundry_detergents/washing_gels/gallus_vollwaschmittel_4l-01.jpg",
    //     alt1: "gallus_vollwaschmittel_4l-01",
    //     url1: "./images/shop/household_chemicals/laundry_detergents/softeners/gallus_frisch_4l-01.jpg",
    //     alt1: "gallus_frisch_4l-01",
    //     url1: "./images/shop/household_chemicals/laundry_detergents/softeners/gallus_orchidee_4l-01.jpg",
    //     alt1: "gallus_orchidee_4l-01",
    //     marker: "SALE354",
    //     brand: "Gallus",
    //     search: "галлус галус хенкель гели гелі для прання стирки ополаскиватель помякшувач кондиционер смягчитель ополіскувач",
    //     nameUKR: "Безфосфатрий гель та кондиціонер для прання &#171Gallus&#187",
    //     nameEN: "Perfumed Washing Gel & Concentrated Softener",
    //     companyName: "Henkel",
    //     countryName: "Німеччина",
    //     volumeName: "Об'єм",
    //     volume: "8.13 л.",
    //     priceGRN: 478,
    //     quantityOnStorage: 5,
    //     description01: "Унікальна акція: виберіть будь-який гель для прання та будь-який кондиціонер для прання &#171Gallus&#187 без фосфатів!",
    //     description02: "Ці засоби забезпечать Вам ідеальну чистоту та свіжість Вашого одягу завдяки своїм природним та ефективним складникам.",
    //     description03: "Забудьте про подразнення шкіри та пошкодження тканин - тепер Ваш одяг буде доглянутим та безпечним для всієї родини разом з &#171Gallus&#187.",
    //     description04: "<strong>Набір: безфосфатний гель для прання, розрахований на 112 прань (4.05 л.); ополіскувач, пом'якшувач, концентрат, розрахований на 120 прань (4.08 л.).</strong>",
    //     description05: "Не втрачайте шанс зробити своє прання приємнішим та безпечнішим скориставшить ексклюзивною пропозицією від &#171Gallus&#187!"
    // },
    // {
    //     type: "retail",
    //     url: "./images/shop/sale/la_salud_detergente_suavizante_concentrado_3l.jpg",
    //     alt: "la_salud_detergente_suavizante_concentrado_3l",
    //     url1: "./images/shop/sale/la_salud_detergente_suavizante_concentrado_3l-01.jpg",
    //     alt1: "la_salud_detergente_suavizante_concentrado_3l-01",
    //     url2: "./images/shop/household_chemicals/laundry_detergents/washing_gels/la_salud_color_40-01.jpg",
    //     alt2: "la_salud_color_40-01",
    //     url3: "./images/shop/household_chemicals/laundry_detergents/washing_gels/la_salud_marsella_40-01.jpg",
    //     alt3: "la_salud_marsella_40-01",
    //     url4: "./images/shop/household_chemicals/laundry_detergents/washing_gels/la_salud_original_40-01.jpg",
    //     alt4: "la_salud_original_40-01",
    //     url5: "./images/shop/household_chemicals/laundry_detergents/washing_gels/la_salud_ropa_negra_40-01.jpg",
    //     alt5: "la_salud_ropa_negra_40-01",
    //     url6: "./images/shop/household_chemicals/laundry_detergents/softeners/la_salud_nature_aloe_1350-01.jpg",
    //     alt6: "la_salud_nature_aloe_1350-01",
    //     url7: "./images/shop/household_chemicals/laundry_detergents/softeners/la_salud_esencia_azul_1350-01.jpg",
    //     alt7: "la_salud_esencia_azul_1350-01",
    //     url8: "./images/shop/household_chemicals/laundry_detergents/softeners/la_salud_dolce_1350-01.jpg",
    //     alt8: "la_salud_dolce_1350-01",
    //     url9: "./images/shop/household_chemicals/laundry_detergents/softeners/la_salud_spa_1350-01.jpg",
    //     alt9: "la_salud_spa_1350-01",
    //     marker: "SALE480",
    //     brand: "La Salud",
    //     search: "ла салуд салюд гели гелі для прання стирки ополаскиватель помякшувач кондиционер смягчитель ополіскувач",
    //     nameUKR: "Гель та кондиціонер для прання &#171La Salud&#187",
    //     nameEN: "Detergente & Suavizante Concentrado",
    //     companyName: "Inquivisa",
    //     countryName: "Іспанія",
    //     volumeName: "Об'єм",
    //     volume: "3 л.",
    //     priceGRN: 427,
    //     quantityOnStorage: 5,
    //     description01: "Не пропустіть неймовірну акційну пропозицію від &#171La Salud&#187 для бездоганного догляду за Вашим одягом.",
    //     description02: "Виберіть один з гелів для прання &#171La Salud&#187, який забезпечить ефективне очищення та збереження кольорів Ваших речей.",
    //     description03: "Додайте до цього один з кондиціонерів для прання &#171La Salud&#187, який подарує вашому одягу ніжність і тривалий свіжий аромат.",
    //     description04: "<strong>Набір: гель для прання, розрахований на 40 прань (2650 мл.); ополіскувач, пом'якшувач, розрахований на 60 прань (1350 мл.).</strong>",
    //     description05: "Скористайтеся цією унікальною пропозицією для &#171La Salud&#187 та надайте своєму одягу найкращий догляд!"
    // },
    // {
    //     type: "retail",
    //     url: "./images/shop/sale/la_salud_oxy_ropa_blanca_color_2kg.jpg",
    //     alt: "la_salud_oxy_ropa_blanca_color_2kg",
    //     url1: "./images/shop/household_chemicals/laundry_detergents/stain_removers/la_salud_oxy_ropa_blanca_1kg-01.jpg",
    //     alt1: "la_salud_oxy_ropa_blanca_1kg-01",
    //     url2: "./images/shop/household_chemicals/laundry_detergents/stain_removers/la_salud_oxy_ropa_blanca_1kg-02.jpg",
    //     alt2: "la_salud_oxy_ropa_blanca_1kg-02",
    //     url3: "./images/shop/household_chemicals/laundry_detergents/stain_removers/la_salud_oxy_ropa_blanca_1kg-03.jpg",
    //     alt3: "la_salud_oxy_ropa_blanca_1kg-03",
    //     url4: "./images/shop/household_chemicals/laundry_detergents/stain_removers/la_salud_oxy_ropa_color_1kg-01.jpg",
    //     alt4: "la_salud_oxy_ropa_color_1kg-01",
    //     url5: "./images/shop/household_chemicals/laundry_detergents/stain_removers/la_salud_oxy_ropa_color_1kg-02.jpg",
    //     alt5: "la_salud_oxy_ropa_color_1kg-02",
    //     url6: "./images/shop/household_chemicals/laundry_detergents/stain_removers/la_salud_oxy_ropa_color_1kg-03.jpg",
    //     alt6: "la_salud_oxy_ropa_color_1kg-03",
    //     marker: "SALE490",
    //     brand: "La Salud",
    //     search: "ла салуд салюд білого белого белых вещей засоби для видалення пляма пятновыводитель пятновыдодители средство для удаления пятен активний кислород с активним кислородом з активним киснем экологический кольорові речі цветные вещи для цветных вещей",
    //     nameUKR: "Екологічний набір: кисневі плямовивідники для білих та кольорових речей (порошок)",
    //     nameEN: "Oxy Ropa Blanca & Ropa Color",
    //     companyName: "Inquivisa",
    //     countryName: "Іспанія",
    //     weightName: "Вага",
    //     weight: "2 кг.",
    //     priceGRN: 476,
    //     quantityOnStorage: 4,
    //     description01: "Відкрийте для себе екологічний набір &#171La Salud - Oxy Ropa Blanca & Ropa Color&#187 - кисневі плямовивідники для білих та кольорових речей.",
    //     description02: "Цей набір включає порошок з активним киснем, який ефективно видаляє плями та забезпечує бездоганну чистоту Вашого одягу.",
    //     description03: "Засоби підходять для делікатного догляду за білими та кольоровими речами, зберігаючи їхню яскравість і не пошкоджуючи тканини.",
    //     description04: "<strong>Екологічний набір: кисневі плямовивідники для білих та кольорових речей. Порошок. Активний кисень. Розрахований на 33 прання.</strong>",
    //     description05: "Скористайтеся нашою акційною пропозицією &#171La Salud - Oxy Ropa Blanca & Ropa Color&#187 та додайте до свого прання екологічну ефективність!"
    // },
    // {
    //     type: "retail",
    //     url: "./images/shop/sale/la_salud_oxy_ropa_blanca_color_3000.jpg",
    //     alt: "la_salud_oxy_ropa_blanca_color_3000",
    //     url1: "./images/shop/household_chemicals/laundry_detergents/stain_removers/la_salud_oxy_ropa_blanca_16-01.jpg",
    //     alt1: "la_salud_oxy_ropa_blanca_16-01",
    //     url2: "./images/shop/household_chemicals/laundry_detergents/stain_removers/la_salud_oxy_ropa_blanca_16-02.jpg",
    //     alt2: "la_salud_oxy_ropa_blanca_16-02",
    //     url3: "./images/shop/household_chemicals/laundry_detergents/stain_removers/la_salud_oxy_ropa_blanca_16-03.jpg",
    //     alt3: "la_salud_oxy_ropa_blanca_16-03",
    //     url4: "./images/shop/household_chemicals/laundry_detergents/stain_removers/la_salud_oxy_ropa_color_16-01.jpg",
    //     alt4: "la_salud_oxy_ropa_color_16-01",
    //     url5: "./images/shop/household_chemicals/laundry_detergents/stain_removers/la_salud_oxy_ropa_color_16-02.jpg",
    //     alt5: "la_salud_oxy_ropa_color_16-02",
    //     url6: "./images/shop/household_chemicals/laundry_detergents/stain_removers/la_salud_oxy_ropa_color_16-03.jpg",
    //     alt6: "la_salud_oxy_ropa_color_16-03",
    //     marker: "SALE492",
    //     brand: "La Salud",
    //     search: "ла салуд салюд білого белого белых вещей засоби для видалення пляма пятновыводитель пятновыдодители средство для удаления пятен активний кислород с активним кислородом з активним киснем экологический кольорові речі цветные вещи для цветных вещей",
    //     nameUKR: "Екологічний набір: кисневі плямовивідники для білих та кольорових речей",
    //     nameEN: "Oxy Ropa Blanca",
    //     companyName: "Inquivisa",
    //     countryName: "Іспанія",
    //     volumeName: "Об'єм",
    //     volume: "3000 мл.",
    //     priceGRN: 286,
    //     quantityOnStorage: 4,
    //     description01: "Відкрийте для себе екологічний набір &#171La Salud - Oxy Ropa Blanca & Ropa Color&#187 - кисневі плямовивідники для білих та кольорових речей.",
    //     description02: "Цей набір включає порошок з активним киснем, який ефективно видаляє плями та забезпечує бездоганну чистоту Вашого одягу.",
    //     description03: "Засоби підходять для делікатного догляду за білими та кольоровими речами, зберігаючи їхню яскравість і не пошкоджуючи тканини.",
    //     description04: "<strong>Екологічний набір: кисневі плямовивідники для білих та кольорових речей. Активний кисень. Розрахований на 16 прань.</strong>",
    //     description05: "Скористайтеся нашою акційною пропозицією &#171La Salud - Oxy Ropa Blanca & Ropa Color&#187 та додайте до свого прання екологічну ефективність!"
    // },
    // {
    //     type: "retail",
    //     url: "./images/shop/sale/lindt_teddy_243.jpg",
    //     alt: "lindt_teddy_243",
    //     url1: "./images/shop/sale/lindt_teddy_243-01.jpg",
    //     alt1: "lindt_teddy_243-01",
    //     url2: "./images/shop/sale/lindt_teddy_243-02.jpg",
    //     alt2: "lindt_teddy_243-02",
    //     url3: "./images/shop/sale/lindt_teddy_243-03.jpg",
    //     alt3: "lindt_teddy_243-03",
    //     marker: "SALE500",
    //     brand: "Lindt",
    //     search: "линдт ліндт адвенткалендар молочный шоколад белый білий шоколад цукерка шоколадні цукерки конфета конфеты трюфель медведь медведи ведмідь ведмеді ведмедик ведмедики",
    //     nameUKR: "Адвент календар",
    //     nameEN: "Teddy",
    //     companyName: "Lindt & Sprüngli Sp.",
    //     countryName: "Німеччина",
    //     weightName: "Вага",
    //     weight: "243 гр.",
    //     priceGRN: 1049,
    //     quantityOnStorage: 7,
    //     description01: "Запрошуємо вас в захопливий світ адвент календаря &#171Lindt - Teddy&#187, де кожен день переповнений солодощами та чарівністю. Цей календар не лише лічильник днів, але й магічна коробочка, яка робить ваші свята ще більш неповторними.",
    //     description02: "Це не просто шматочоки шоколаду - це маленька м'яка ведмежа ніжність, що прихована під чарівним шоколадним вбранням. Вишукана якість та вишуканий смак роблять кожен день особливим.",
    //     description03: "Завдяки неперевершеному поєднанню ніжного шоколаду &#171Lindt - Teddy&#187, Ви не тільки розпаковуєте нові подарунки кожного дня, але надихаєтесь теплом і радістю.",
    //     description04: "<strong>Цукерки, молочний шоколад, асорті: в золотій обгорці олені та ведмедики, цукерки з пролісками з білого шоколаду, міні-трюфелі &#171Lindor&#187, наполітани, повнорозмірний ведмедик. 24 шт.</strong>",
    //     description05: "Зробіть свої свята незабутніми – замовте свій &#171Lindt - Teddy&#187 адвент календар вже зараз та пориньте у світ магії та солодкого очікування!"
    // },
    // {
    //     type: "retail",
    //     url: "./images/shop/sale/lindt_weihnachtsmarkt_115.jpg",
    //     alt: "lindt_weihnachtsmarkt_115",
    //     url1: "./images/shop/sale/lindt_weihnachtsmarkt_115-01.jpg",
    //     alt1: "lindt_weihnachtsmarkt_115-01",
    //     url2: "./images/shop/sale/lindt_weihnachtsmarkt_115-02.jpg",
    //     alt2: "lindt_weihnachtsmarkt_115-02",
    //     marker: "SALE520",
    //     brand: "Lindt",
    //     search: "линдт ліндт адвенткалендар молочный шоколад цукерка шоколадні цукерки конфета конфеты",
    //     nameUKR: "Адвент календар",
    //     nameEN: "Weihnachtsmarkt",
    //     companyName: "Lindt & Sprüngli Sp.",
    //     countryName: "Німеччина",
    //     weightName: "Вага",
    //     weight: "115 гр.",
    //     priceGRN: 299,
    //     quantityOnStorage: 13,
    //     description01: "Пориньтесь в атмосферу святкового настрою з адвент календарем &#171Lindt - Weihnachtsmarkt&#187. Це не просто календар – це келих справжнього захоплення, який принесе вашій душі радість та тепло.",
    //     description02: "Кожен день розкриває новий секрет солодкого задоволення у вигляді розкішного молочного шоколаду. Інтригуючі форми та вишукана якість створюють світ, де кожен шматочок – це миттєвий вихід у світ Різдвяної ярмарки.",
    //     description03: "Відчуйте бажання відзначати кожен день зі смаком витонченості та тепла. Бажання розпаковувати подарунки солодощів &#171Lindt - Weihnachtsmarkt&#187, які роблять свята ще більш неповторними.",
    //     description04: "<strong>Цукерки шоколадні, асорті (5 видів). 24 шт.</strong>",
    //     description05: "Створіть свої унікальні моменти святкової насолоди – замовте адвент календар &#171Lindt - Weihnachtsmarkt&#187 прямо зараз та зануртеся у світ солодкого очікування!"
    // },
    // {
    //     type: "retail",
    //     url: "./images/shop/sale/magnetic_merry_christmas_200.jpg",
    //     alt: "magnetic_merry_christmas_200",
    //     url1: "./images/shop/sale/magnetic_merry_christmas_200.jpg",
    //     alt1: "magnetic_merry_christmas_200",
    //     marker: "SALE605",
    //     brand: "Magnetic",
    //     search: "магнетик магнетік адвенткалендар молочный шоколад цукерка шоколадні цукерки конфета конфеты",
    //     nameUKR: "Адвент календар",
    //     nameEN: "Merry Christmas",
    //     companyName: "Jeronimo Martis Polska S.A.",
    //     countryName: "Польща",
    //     weightName: "Вага",
    //     weight: "200 гр.",
    //     priceGRN: 189,
    //     quantityOnStorage: 6,
    //     description01: "Закликаємо Dас відкрити двері до солодкого світу з адвент календарем &#171Magnetic - Merry Christmas&#187. Він обіцяє подарувати Вам щоденні радощі та шоколадной вибух смаку.",
    //     description02: "Кожен день відкривайте комірочку солодощів – вишукані шоколадні цукерки з різноманітними смаками та формами. Велика кількість варіацій та якість складу пробуджують інтерес до невідомих смакових вражень.",
    //     description03: "Бажання відчути той особливий смак свята, втілений у кожній шоколадній цукерці &#171Magnetic - Merry Christmas&#187, нехай подарує Вам теплі миті веселих свят та незабутню насолоду.",
    //     description04: "<strong>Цукерки шоколадні, асорті. 24 шт.</strong>",
    //     description05: "Не вагайтеся - замовте адвент календар &#171Magnetic - Merry Christmas&#187 прямо зараз та подаруйте собі та своїм близьким незабутні солодкі миті!"
    // },
    // {
    //     type: "retail",
    //     url: "./images/shop/sale/magnetic_happy_200.jpg",
    //     alt: "magnetic_happy_200",
    //     url1: "./images/shop/sale/magnetic_happy_200.jpg",
    //     alt1: "magnetic_happy_200",
    //     marker: "SALE610",
    //     brand: "Magnetic",
    //     search: "магнетик магнетік адвенткалендар молочный шоколад цукерка шоколадні цукерки конфета конфеты wesolych swiat",
    //     nameUKR: "Адвент календар",
    //     nameEN: "Wesołych Swiąt",
    //     companyName: "Jeronimo Martis Polska S.A.",
    //     countryName: "Польща",
    //     weightName: "Вага",
    //     weight: "200 гр.",
    //     priceGRN: 189,
    //     quantityOnStorage: 6,
    //     description01: "Запрошуємо Вас у світ шоколадного чарівництва з адвент календарем &#171Magnetic - Wesołych Świąt&#187. Цей неперевершений календар відрізняється своєю елегантністю та обіцяє кожного дня приносити Вам частинку святкового задоволення.",
    //     description02: "Розкрийте таємницю кожного дня, смакуючи шоколадні цукерки різних смаків і форм. Миті радості, які дарує цей календар, створюють інтригу та відчуття святкової таємниці.",
    //     description03: "Шоколадні цукерки &#171Magnetic - Wesołych Świąt&#187, що відкриваються щодня, будять бажання поділитися цими неповторними смаковими враженнями з близькими.",
    //     description04: "<strong>Цукерки шоколадні, асорті. 28 шт.</strong>",
    //     description05: "Зробіть свої свята незабутніми – замовте адвент календар &#171Magnetic - Wesołych Świąt&#187 вже зараз та дозвольте собі кожен день насолоджуватися найкращим смаком!"
    // },
    // {
    //     type: "retail",
    //     url: "./images/shop/sale/merci_happy_christmas_255.jpg",
    //     alt: "merci_happy_christmas_255",
    //     url1: "./images/shop/sale/merci_happy_christmas_255.jpg",
    //     alt1: "merci_happy_christmas_255",
    //     marker: "SALE630",
    //     brand: "Merci",
    //     search: "мерси мерсі адвенткалендар молочный шоколад цукерка шоколадні цукерки конфета конфеты сердечки сердца серця",
    //     nameUKR: "Адвент календар",
    //     nameEN: "Happy Christmas",
    //     companyName: "Storck KG",
    //     countryName: "Німеччина",
    //     weightName: "Вага",
    //     weight: "255 гр.",
    //     priceGRN: 595,
    //     quantityOnStorage: 6,
    //     description01: "Зануртеся e святковий настрій з адвент календарем &#171Merci - Happy Christmas&#187, який робить свята особливими та неймовірно солодкими. Цей календар не просто відлічує дні, але подарує Вам кожного дня новий, неповторний смак святкової радості.",
    //     description02: "Розкрийте секретні віконця та відкрийте для себе різноманіття смаків вишуканого шоколаду. Від карамельного до горіхового - кожен день приховує у собі новий витончений смак, що розкриває неперевершені відчуття.",
    //     description03: "&#171Merci - Happy Christmas&#187 - це бажання насолоджуватися кожним днем перед святами, отримуючи щодня новий привід для радості.",
    //     description04: "<strong>Цукерки шоколадні, асорті. Містить: шоколадні плитки, сердечки, конфети. 24 шт.</strong>",
    //     description05: "Замовте свій &#171Merci - Happy Christmas&#187 адвент календар вже зараз та робіть кожен день неперевершеним!"
    // },
    // {
    //     type: "retail",
    //     url: "./images/shop/sale/merci_happy_christmas_same_255.jpg",
    //     alt: "merci_happy_christmas_same_255",
    //     url1: "./images/shop/sale/merci_happy_christmas_same_255.jpg",
    //     alt1: "merci_happy_christmas_same_255",
    //     marker: "SALE635",
    //     brand: "Merci",
    //     search: "мерси мерсі адвенткалендар молочный шоколад цукерка шоколадні цукерки конфета конфеты сердечки сердца серця",
    //     nameUKR: "Адвент календар",
    //     nameEN: "Happy Christmas",
    //     companyName: "Storck KG",
    //     countryName: "Німеччина",
    //     weightName: "Вага",
    //     weight: "255 гр.",
    //     priceGRN: 595,
    //     quantityOnStorage: 6,
    //     description01: "Зануртеся e святковий настрій з адвент календарем &#171Merci - Happy Christmas&#187, який робить свята особливими та неймовірно солодкими. Цей календар не просто відлічує дні, але подарує Вам кожного дня новий, неповторний смак святкової радості.",
    //     description02: "Розкрийте секретні віконця та відкрийте для себе різноманіття смаків вишуканого шоколаду. Від карамельного до горіхового - кожен день приховує у собі новий витончений смак, що розкриває неперевершені відчуття.",
    //     description03: "&#171Merci - Happy Christmas&#187 - це бажання насолоджуватися кожним днем перед святами, отримуючи щодня новий привід для радості.",
    //     description04: "<strong>Цукерки шоколадні, асорті. Містить: шоколадні плитки, сердечки, конфети. 24 шт.</strong>",
    //     description05: "Замовте свій &#171Merci - Happy Christmas&#187 адвент календар вже зараз та робіть кожен день неперевершеним!"
    // },
    // {
    //     type: "retail",
    //     url: "./images/shop/sale/milka_elf_236.jpg",
    //     alt: "milka_elf_236",
    //     url1: "./images/shop/sale/milka_elf_236-01.jpg",
    //     alt1: "milka_elf_236-02",
    //     url2: "./images/shop/sale/milka_elf_236-02.jpg",
    //     alt2: "milka_elf_236-03",
    //     url3: "./images/shop/sale/milka_elf_236-03.jpg",
    //     alt3: "milka_elf_236-04",
    //     marker: "SALE650",
    //     brand: "Milka",
    //     search: "милка мілка адвенткалендар молочный шоколад цукерка шоколадні цукерки конфета конфеты сердечки сердца серця",
    //     nameUKR: "Адвент календар",
    //     nameEN: "Adventskalender",
    //     companyName: "Mondelez International",
    //     countryName: "Швейцарія",
    //     weightName: "Вага",
    //     weight: "236 гр.",
    //     priceGRN: 510,
    //     quantityOnStorage: 9,
    //     description01: "Запрошуємо Вас у чарівний світ солодкого очікування з адвент календарем &#171Milka - Adventskalender&#187. Його неперевершений дизайн та вишуканість шоколадних сюрпризів зроблять ваші святковы дні надзвичайно особливими та незабутніми.",
    //     description02: "Кожне віконечко адвент календаря розкриває новий смак шоколаду. Вишуканість та неповторність кожного шматочка викличе інтерес до вивчення різноманітних ароматів та текстур, які Вам принесе цей чарівний календар.",
    //     description03: "Відчуйте бажання доторкнутися до справжнього свята смаку та витонченості. &#171Milka - Adventskalender&#187 пробуджує бажання Вас радувати кожного дня найкращими шоколадними насолодами.",
    //     description04: "<strong>Цукерки шоколадні, асорті. Містить: шоколадні плитки, конфети, фігурки. 24 шт.</strong>",
    //     description05: "Замовте свій адвент календар &#171Milka - Adventskalender&#187 зараз та створіть свою унікальну традицію солодких пригод до свят!"
    // },
    // {
    //     type: "retail",
    //     url: "./images/shop/sale/parmigiano_reggiano_no_alco_6.jpg",
    //     alt: "parmigiano_reggiano_no_alco_6",
    //     url1: "./images/shop/sale/parmigiano_reggiano_no_alco_6-01.jpg",
    //     alt1: "parmigiano_reggiano_no_alco_6-01",
    //     url2: "./images/shop/sale/parmigiano_reggiano_no_alco_6-02.jpg",
    //     alt2: "parmigiano_reggiano_no_alco_6-02",
    //     marker: "SALE700",
    //     brand: "Parmareggio",
    //     search: "твердый сыр твердые сыры твердий сир тверді сири соус соусы соуси паста пасти пасты оцет печиво книга рецептів рецепт",
    //     nameUKR: "Подарунковий набір",
    //     nameEN: "Parmigiano Reggiano Tradizione Italiana",
    //     companyName: "Parmareggio S.p.a.",
    //     countryName: "Італія",
    //     quantityName: "Кількість",
    //     quantity: "6 шт.",
    //     priceGRN: 1023,
    //     quantityOnStorage: 6,
    //     description01: "Запрошуємо вас у подорож по справжньому італійському смаку з &#171Parmareggio - Parmigiano Reggiano Tradizione Italiana&#187 - витонченість і аутентичність італійської кухні, яка зачаровує з першого погляду.",
    //     description02: "Подаруйте смакову насолоду та вишуканість вашим близьким. &#171Parmareggio - Parmigiano Reggiano Tradizione Italiana&#187 - справжній дарунок для цінителів вишуканих смаків та аутентичності італійської кулінарії.",
    //     description03: "",
    //     description04: "<strong>Набір подарунковий. Містить: міні-книга рецептів &#171Parmigiano Reggiano Consortium&#187;; твердий італійський сир пармезан &#171Parmigiano Reggiano DOP&#187, 12 місяців витримки, 140 гр.; бальзамічний оцет &#171Modena IGP Senso Mengazzoli&#187, 250 мл.; макорони &#171Pennoni Rigati Garofalo PGI&#187, 250 гр.; банка соусу &#171Tenuta del Cervo Arrabbiata&#187, 185 гр.; пакет печива &#171Tarallini Grano d'Oro&#187, 100 гр.</strong>",
    //     description05: "Зробіть свій подарунок неперевершеним – замовте &#171Parmareggio - Parmigiano Reggiano Tradizione Italiana&#187 прямо зараз та даруйте особливий смаку та елегантність італійської кухні!"
    // },
        {
        type: "retail",
        url: "./images/shop/sale/power_wash_vir_10_off.jpg",
        alt: "power_wash_vir_10_off",
        url1: "./images/shop/sale/power_wash_vir_10_off-01.jpg",
        alt1: "power_wash_vir_10_off-01",
        url2: "./images/shop/household_chemicals/laundry_detergents/washing_gels/power_wash_color_4l-01.jpg",
        alt2: "power_wash_color_4l-01",
        url3: "./images/shop/household_chemicals/laundry_detergents/washing_gels/power_wash_universal_4l-01.jpg",
        alt3: "power_wash_universal_4l-01",
        url4: "./images/shop/household_chemicals/laundry_detergents/softeners/vir_magnetisch_37-01.jpg",
        alt4: "vir_magnetisch_37-01",
        url5: "./images/shop/household_chemicals/laundry_detergents/softeners/vir_muse_37-01.jpg",
        alt5: "vir_muse_37-01",
        url6: "./images/shop/household_chemicals/laundry_detergents/softeners/vir_romantisch_37-01.jpg",
        alt6: "vir_romantisch_37-01",
        marker: "SALE700",
        brand: "Power Wash & Vir",
        search: "хенкель павер вош повер гели гелі для прання стирки универсальный кольорові речі цветных вещей цветные вещи вир вір ополаскиватель помякшувач кондиціонер кондиционер",
        nameUKR: "Набір для прання (гель та кондиціонер), на вибір",
        nameEN: "Color, Universal & Magnetisch, Muse, Romantisch",
        companyName: "Henkel, Mekson SH.P.K.",
        countryName: "Німеччина & Болгарія",
        volumeName: "Об'єм",
        volume: "4925 мл.",
        priceGRN: 337,
        quantityOnStorage: 6,
        description01: "Акційна пропозиція на набір для прання від &#171Power Wash & Vir&#187 - це ваш шанс отримати бездоганну чистоту білизни за вигідною ціною.",
        description02: "У комплект входять гель та кондиціонер на вибір, які забезпечують інтенсивний догляд та свіжість.",
        description03: "Завдяки спеціальним формулам, засоби &#171Power Wash & Vir&#187 ефективно борються з плямами та зберігають яскравість кольорів навіть після численних прань.",
        description04: "<strong>Набір для прання. Гель (кольоровий, універсальний) та кондиціонер(концентрат). (4000 + 925) мл.</strong>",
        description05: "Не втратьте можливість отримати максимальний результат з економією та задоволенням від кожного прання тільки з &#171Power Wash & Vir&#187!"
    },
    {
        type: "retail",
        url: "./images/shop/sale/right_guard_15_off.jpg",
        alt: "right_guard_15_off",
        url1: "./images/shop/sale/right_guard_15_off-01.jpg",
        alt1: "right_guard_15_off-01",
        url2: "./images/shop/gigiena/bath_gels/right_guard_sport_300-02.jpg",
        alt2: "right_guard_sport_300-02",
        url3: "./images/shop/gigiena/bath_gels/right_guard_sensual_300-02.jpg",
        alt3: "right_guard_sensual_300-02",
        marker: "SALE750",
        brand: "Right Guard",
        search: "райт гуард шампуні гель гелі гели для душа шварцкопф хенкель чоловічий чоловічі чоловічій",
        nameUKR: "Сімейний набір",
        nameEN: "Sport Recharge, Sensual & Oil",
        companyName: "Schwarzkopf & Henkel",
        countryName: "Англія",
        volumeName: "Об'єм",
        volume: "600 мл.",
        priceGRN: 161,
        quantityOnStorage: 9,
        description01: "&#171Right Guard - Sport Recharge, Sensual & Oil&#187 - це унікальна акційна пропозиція для динамічних чоловіків та чутливих жінок.",
        description02: "&#171Sport Recharge&#187 - це секрет успіху активних чоловіків. Його потужна формула дарує свіжість та захист протягом усього дня. Цей потужний і відновлюючий комплексний засіб для душу, ідеально підходить для очищення тіла, обличчя та волосся.",
        description03: "&#171Sensual & Oil&#187 - це елегантний захист, що розкриває вашу справжню жіночу силу. Його спеціально розроблена формула збагачена натуральними оліями, що живлять і пом'якшують вашу шкіру.",
        description04: "<strong>Набір для чоловіків (гель для душу, шампунь) та жінок (гель для душу). 2 Х 300 мл.</strong>",
        description05: "Замовляйте &#171Right Guard - Sport Recharge, Sensual & Oil&#187 вже сьогодні та насолоджуйтесь вигідною покупкою, де якість завжди на першому місці!"
    },
    // {
    //     type: "retail",
    //     url: "./images/shop/sale/well_done_zsiroldo_1650.jpg",
    //     alt: "well_done_zsiroldo_1650",
    //     url1: "./images/shop/sale/well_done_zsiroldo_1650-01.jpg",
    //     alt1: "well_done_zsiroldo_1650-01",
    //     url2: "./images/shop/household_chemicals/means_for_cleaning/kitchen_bathroom/well_done_zsiroldo_650-01.jpg",
    //     alt2: "well_done_zsiroldo_650-01",
    //     url3: "./images/shop/household_chemicals/means_for_cleaning/kitchen_bathroom/well_done_zsiroldo_650-02.jpg",
    //     alt3: "well_done_zsiroldo_650-02",
    //     url4: "./images/shop/household_chemicals/means_for_cleaning/kitchen_bathroom/well_done_zsiroldo_1000-01.jpg",
    //     alt4: "well_done_zsiroldo_1000-01",
    //     url5: "./images/shop/household_chemicals/means_for_cleaning/kitchen_bathroom/well_done_zsiroldo_1000-02.jpg",
    //     alt5: "well_done_zsiroldo_1000-02",
    //     marker: "SALE905",
    //     brand: "Well Done",
    //     search: "Hideg Zsiroldo велл дан доне засоби для чищення проти жиру обезжириватель средство средства против жира средства средство для чистки",
    //     nameUKR: "Набір з засібу для чищення та знежирення + запаска",
    //     nameEN: "Hideg Zsíroldó",
    //     companyName: "Well Done St. Moritz Kft.",
    //     countryName: "Угорщина",
    //     volumeName: "Об'єм",
    //     volume: "1650 мл.",
    //     priceGRN: 205,
    //     uantityOnStorage: 9,
    //     description01: "Скористайтеся акційною пропозицією на комплект &#171Well Done - Hideg Zsíroldó&#187 для чищення та знежирення!",
    //     description02: "Цей засіб забезпечує ефективне видалення жиру та бруду з будь-яких поверхонь, залишаючи їх ідеально чистими.",
    //     description03: "Зручний комплект &#171Well Done - Hideg Zsíroldó&#187 із запаскою та пшикалкою дозволяє завжди мати під рукою необхідний обсяг для швидкого і легкого прибирання.",
    //     description04: "<strong>Комплект! Засіб для чищення та знежирення.</strong>",
    //     description05: "Придбайте комплект &#171Well Done - Hideg Zsíroldó&#187 і насолоджуйтеся бездоганною чистотою Вашої кухні!"
    // },
]