export const shopLotsForWC = [
    {
        type: "wholesale",
        url: "./images/shop/household_chemicals/means_for_cleaning/for_wc/ace_wc_gel_candeggina_700.jpg",
        alt: "ace_wc_gel_candeggina_700",
        url1: "./images/shop/household_chemicals/means_for_cleaning/for_wc/ace_wc_gel_candeggina_700-01.jpg",
        alt1: "ace_wc_gel_candeggina_700-01",
        url2: "./images/shop/household_chemicals/means_for_cleaning/for_wc/ace_wc_gel_candeggina_700-02.jpg",
        alt2: "ace_wc_gel_candeggina_700-02",
        marker: "LDWC010",
        brand: "Ace",
        search: "ейс аце эйс средство для чистки чищення чистка забоси стредства туалет для туалета унитаз для унитаза унітаз для унітаза унітазу відбілювачі отбеливатель отбеливатели",
        nameUKR: "Засіб для чищення туалету з відбілювачем",
        nameEN: "WC Gel Candeggina",
        companyName: "Fater S.P.A.",
        countryName: "Італія",
        volumeName: "Об'єм",
        volume: "700 мл.",
        priceGRN: 96,
        priceGRNOpt: 82,
        description01: "Забезпечте ідеальну чистоту та свіжість Вашого туалету за допомогою &#171Ace - WC Gel Candeggina&#187.",
        description02: "Цей гель з відбілювачем ефективно видаляє бруд, наліт та бактерії, залишаючи Ваш туалет бездоганно чистим. Активні компоненти проникають у важкодоступні місця, забезпечуючи глибоке очищення.",
        description03: "&#171Ace - WC Gel Candeggina&#187 не тільки очищує, але й відбілює поверхні, даруючи їм новий вигляд. Забудьте про неприємні запахи та насолоджуйтесь свіжістю кожного дня.",
        description04: "<strong>Засіб для чищення унітазу. Не дезінфекующий засіб. Містить відбілювач.</strong>",
        description05: "Купуйте &#171Ace - WC Gel Candeggina&#187 сьогодні та зробіть свій туалет ідеально чистим і свіжим!"
    },
    {
        type: "wholesale",
        url: "./images/shop/household_chemicals/means_for_cleaning/for_wc/brait_lilac_garden_3x45.jpg",
        alt: "brait_lilac_garden_3x45",
        url1: "./images/shop/household_chemicals/means_for_cleaning/for_wc/brait_lilac_garden_3x45-01.jpg",
        alt1: "brait_lilac_garden_3x45-01",
        url2: "./images/shop/household_chemicals/means_for_cleaning/for_wc/brait_lilac_garden_3x45-02.jpg",
        alt2: "brait_lilac_garden_3x45-02",
        marker: "LDWC050",
        brand: "Brait",
        search: "браит браіт брайт средство для чистки чищення чистка забоси стредства туалет для туалета унитаз для унитаза унітаз для унітаза унітазу вапняний нальот",
        nameUKR: "Засіб для чищення туалету, проти вапняного нальоту (бузковий сад)",
        nameEN: "Lilac Garden",
        companyName: "Dramers S.A. Rabowice",
        countryName: "Польща",
        quantityName: "Кількість",
        quantity: "3 шт.",
        priceGRN: 98,
        priceGRNOpt: 88,
        description01: "&#171Brait - Lilac Garden&#187 здивує Вас своєю потужністю та ароматом. Цей засіб проникає навіть у важкодоступні місця та ефективно видаляє вапняний нальот, залишаючи ваш туалет блискучим і свіжим.",
        description02: "Він не лише робить чистку легшою і швидшою, а й забезпечує приємний аромат, який легко розповсюджується по всьому приміщенню, надаючи приємний запах.",
        description03: "Спробуйте &#171Brait - Lilac Garden&#187 і відчуйте, як Ваш туалет стає місцем, куди хочеться повертатися знову і знову.",
        description04: "<strong>Засіб для чищення унітазу. Проти вапняного нальоту. Підвісний блок. 3 х 45 гр. Аромат: бузок.</strong>",
        description05: "Очистіть свій туалет від вапняного нальоту з &#171Brait - Lilac Garden&#187 сьогодні, і насолоджуйтесь чистотою та свіжістю в вашій ванній кімнаті!"
    },
    {
        type: "wholesale",
        url: "./images/shop/household_chemicals/means_for_cleaning/for_wc/brait_oceanic_3x45.jpg",
        alt: "brait_oceanic_3x45",
        url1: "./images/shop/household_chemicals/means_for_cleaning/for_wc/brait_oceanic_3x45-01.jpg",
        alt1: "brait_oceanic_3x45-01",
        url2: "./images/shop/household_chemicals/means_for_cleaning/for_wc/brait_oceanic_3x45-02.jpg",
        alt2: "brait_oceanic_3x45-02",
        marker: "LDWC055",
        brand: "Brait",
        search: "браит браіт брайт средство для чистки чищення чистка забоси стредства туалет для туалета унитаз для унитаза унітаз для унітаза унітазу вапняний нальот",
        nameUKR: "Засіб для чищення туалету, проти вапняного нальоту (океан)",
        nameEN: "Oceanic",
        companyName: "Dramers S.A. Rabowice",
        countryName: "Польща",
        quantityName: "Кількість",
        quantity: "3 шт.",
        priceGRN: 98,
        priceGRNOpt: 88,
        description01: "Представляємо вам революційний засіб для чищення туалету - &#171Brait - Oceanic&#187. Забудьте про проблему вапняного нальоту та насолоджуйтеся бездоганною чистотою.",
        description02: "Його спеціальна формула не лише ефективно видаляє вапняний нальот, але також залишає приємний аромат свіжості, що надає туалету атмосферу чистоти.",
        description03: "Мрієте про те, щоб Ваш туалет завжди був ідеально чистим і приємно пахнучим? &#171Brait - Oceanic&#187 робить Ваші мрії реальністю, забезпечуючи найвищу якість чистоти та свіжості.",
        description04: "<strong>Засіб для чищення унітазу. Проти вапняного нальоту. Підвісний блок. 3 х 45 гр. Аромат: океан.</strong>",
        description05: "Допоможіть Вашому туалету стати місцем чистоти та свіжості, без сліду від вапняного нальоту разом з &#171Brait - Oceanic&#187!"
    },
    {
        type: "wholesale",
        url: "./images/shop/household_chemicals/means_for_cleaning/for_wc/brait_pine_3x45.jpg",
        alt: "brait_pine_3x45",
        url1: "./images/shop/household_chemicals/means_for_cleaning/for_wc/brait_pine_3x45-01.jpg",
        alt1: "brait_pine_3x45-01",
        url2: "./images/shop/household_chemicals/means_for_cleaning/for_wc/brait_pine_3x45-02.jpg",
        alt2: "brait_pine_3x45-02",
        marker: "LDWC060",
        brand: "Brait",
        search: "браит браіт брайт средство для чистки чищення чистка забоси стредства туалет для туалета унитаз для унитаза унітаз для унітаза унітазу вапняний нальот",
        nameUKR: "Засіб для чищення туалету, проти вапняного нальоту (сосна)",
        nameEN: "Pine",
        companyName: "Dramers S.A. Rabowice",
        countryName: "Польща",
        quantityName: "Кількість",
        quantity: "3 шт.",
        priceGRN: 98,
        priceGRNOpt: 88,
        description01: "Шукаєте ефективний засіб для чищення туалету та боротьби з вапняним нальотом? Ознайомтеся з &#171Brait - Pine&#187, Вашим надійним помічником у цій справі.",
        description02: "Цей засіб не лише чудово видаляє вапняний нальот, але й має приємний аромат сосни, який створить атмосферу свіжості у Вашому туалеті.",
        description03: "Мрієте про бездоганну чистоту та відсутність вапняного нальоту у туалеті? &#171Brait - Pine&#187 здійснить Ваші найсміливіші бажання, залишаючи поверхні блискучими та чистими.",
        description04: "<strong>Засіб для чищення унітазу. Проти вапняного нальоту. Підвісний блок. 3 х 45 гр. Аромат: сосна.</strong>",
        description05: "Забезпечте своєму туалету ідеальну чистоту за допомогою &#171Brait - Pine&#187 і туалет стане місцем чистоти та свіжості."
    },
    {
        type: "wholesale",
        url: "./images/shop/household_chemicals/means_for_cleaning/for_wc/denkmit_wc_reineiger_1l.jpg",
        alt: "denkmit_wc_reineiger_1l",
        url1: "./images/shop/household_chemicals/means_for_cleaning/for_wc/denkmit_wc_reineiger_1l-01.jpg",
        alt1: "denkmit_wc_reineiger_1l-01",
        url2: "./images/shop/household_chemicals/means_for_cleaning/for_wc/denkmit_wc_reineiger_1l-02.jpg",
        alt2: "denkmit_wc_reineiger_1l-02",
        marker: "LDWC200",
        brand: "Denkmit",
        search: "денкмит денкміт средство для чистки чищення чистка забоси стредства туалет для туалета унитаз для унитаза унітаз для унітаза унітазу",
        nameUKR: "Засіб для чищення туалету (свіжість океану)",
        nameEN: "WC-Reiniger Ozean Frische",
        companyName: "dm-drogerie markt GmbH + Co.",
        countryName: "Німеччина",
        volumeName: "Об'єм",
        volume: "1 л.",
        priceGRN: 94,
        priceGRNOpt: 80,
        description01: "Знайомтесь із чудодійним засобом для чищення унітазів &#171Denkmit - WC-Reiniger Ozean Frische&#187. Завдяки інноваційній формулі, він ефективно усуває бруд та неприємні запахи, перетворюючи ванну кімнату у куточок свіжості.",
        description02: "Аромат океану подарує Вашому унітазу неймовірну свіжість та бездоганну чистоту. Спробуйте його один раз - і Ви залишитесь вражені результатом!",
        description03: "Ідеальна чистота, об'єднана з приємним ароматом - ось що робить &#171Denkmit - WC-Reiniger Ozean Frische&#187 чудовим вибором для догляду за Вашою ванною кімнатою. Почуття свіжості, яке Ви будете відчувати, зробить цей засіб для чищення унітазів Вашим улюбленим.",
        description04: "<strong>Засіб для чищення унітазу. Не використовувати на мармурі.</strong>",
        description05: "Покажіть своїй ванні кімнаті, що вона заслуговує на краще! Замовте &#171Denkmit - WC-Reiniger Ozean Frische&#187 вже сьогодні та даруйте своєму унітазу освіжаючу атмосферу!"
    },
    {
        type: "wholesale",
        url: "./images/shop/household_chemicals/means_for_cleaning/for_wc/gallus_oriental_flowers_2x45.jpg",
        alt: "gallus_oriental_flowers_2x45",
        url1: "./images/shop/household_chemicals/means_for_cleaning/for_wc/gallus_oriental_flowers_2x45-01.jpg",
        alt1: "gallus_oriental_flowers_2x45-01",
        url2: "./images/shop/household_chemicals/means_for_cleaning/for_wc/gallus_oriental_flowers_2x45-02.jpg",
        alt2: "gallus_oriental_flowers_2x45-02",
        marker: "LDWC350",
        brand: "Gallus",
        search: "хенкель галус галлус средство для чистки чищення чистка забоси стредства туалет для туалета унитаз для унитаза унітаз для унітаза унітазу восточные цветы",
        nameUKR: "Засіб для чищення туалету (східні квіти)",
        nameEN: "Oriental Flowers",
        companyName: "Henkel",
        countryName: "Німеччина",
        quantityName: "Кількість",
        quantity: "2 шт.",
        priceGRN: 93,
        priceGRNOpt: 83,
        description01: "Представляємо новий рівень чистоти та свіжості - підвісний блок для чищення туалету &#171Gallus - Oriental Flowers&#187 з ароматом східних квітів.",
        description02: "Його унікальна формула забезпечує тривалу чистоту і неймовірний аромат, заповнюючи Ваш туалет екзотичними нотками квітів.",
        description03: "Мрієте про те, щоб туалет завжди пахнув свіжістю та був захищений від бруду? &#171Gallus - Oriental Flowers&#187 здійснить Ваші найсміливіші бажання, надаючи бездоганну чистоту та аромат.",
        description04: "<strong>Засіб для чищення унітазу. Підвісний блок. Фарбує воду у синій колір. 2 х 45 гр. Аромат: східні квіти.</strong>",
        description05: "Просто зачепіть блок &#171Gallus - Oriental Flowers&#187 у Вашому туалеті і насолоджуйтеся чистотою та ароматом, які він надає!"
    },
    {
        type: "wholesale",
        url: "./images/shop/household_chemicals/means_for_cleaning/for_wc/gallus_tropical_flowers_2x45.jpg",
        alt: "gallus_tropical_flowers_2x45",
        url1: "./images/shop/household_chemicals/means_for_cleaning/for_wc/gallus_tropical_flowers_2x45-01.jpg",
        alt1: "gallus_tropical_flowers_2x45-01",
        url2: "./images/shop/household_chemicals/means_for_cleaning/for_wc/gallus_tropical_flowers_2x45-02.jpg",
        alt2: "gallus_tropical_flowers_2x45-02",
        marker: "LDWC355",
        brand: "Gallus",
        search: "хенкель галус галлус средство для чистки чищення чистка забоси стредства туалет для туалета унитаз для унитаза унітаз для унітаза унітазу тропические цветы",
        nameUKR: "Засіб для чищення туалету (тропічні квіти)",
        nameEN: "Tropical Flowers",
        companyName: "Henkel",
        countryName: "Німеччина",
        quantityName: "Кількість",
        quantity: "2 шт.",
        priceGRN: 93,
        priceGRNOpt: 83,
        description01: "Спробуйте свіжість та аромат тропічних квітів з підвісним блоком &#171Gallus - Tropical Flowers&#187.",
        description02: "Цей блок не лише ефективно бореться з брудом, але й заповнює приміщення атмосферою екзотики завдяки своєму свіжому аромату тропічних квітів.",
        description03: "Мрієте про те, щоб туалет завжди пахнув приємно та був захищений від бруду? &#171Gallus - Tropical Flowers&#187 робить Ваші бажання реальністю, забезпечуючи тривалу свіжість та чистоту.",
        description04: "<strong>Засіб для чищення унітазу. Підвісний блок. Фарбує воду у бірюзовий колір. 2 х 45 гр. Аромат: тропічні квіти.</strong>",
        description05: "Просто зачепіть блок &#171Gallus - Tropical Flowers&#187 у Вашому туалеті, і він самостійно забезпечить неймовірну свіжість та чистоту!"
    },
    {
        type: "wholesale",
        url: "./images/shop/household_chemicals/means_for_cleaning/for_wc/la_salud_wc_cerezo_1l.jpg",
        alt: "la_salud_wc_cerezo_1l",
        url1: "./images/shop/household_chemicals/means_for_cleaning/for_wc/la_salud_wc_cerezo_1l-01.jpg",
        alt1: "la_salud_wc_cerezo_1l-01",
        url2: "./images/shop/household_chemicals/means_for_cleaning/for_wc/la_salud_wc_cerezo_1l-02.jpg",
        alt2: "la_salud_wc_cerezo_1l-02",
        marker: "LDWC505",
        brand: "La Salud",
        search: "ла салуд средство для чистки чищення чистка забоси стредства туалет для туалета унитаз для унитаза унітаз для унітаза унітазу вишня",
        nameUKR: "Засіб для чищення туалету (вишневий цвіт)",
        nameEN: "Gel WC Flor De Cerezo",
        companyName: "Inquivisa",
        countryName: "Іспанія",
        volumeName: "Об'єм",
        volume: "1 л.",
        priceGRN: 122,
        priceGRNOpt: 110,
        description01: "Шукаєте ідеальний засіб для чистоти вашого туалету? Зустрічайте &#171La Salud - Gel WC Flor De Cerezo&#187!",
        description02: "Цей засіб не тільки ефективно очищує туалет, але й залишає приємний аромат вишневого цвіту. Його гелева формула проникає у важкодоступні місця, забезпечуючи ідеальну чистоту.",
        description03: "З &#171La Salud - Gel WC Flor De Cerezo&#187 Ваш туалет завжди буде свіжим і чистим. Насолоджуйтесь ароматом вишневого цвіту після кожного використання, забувши про неприємні запахи та бактерії.",
        description04: "<strong>Засіб для чищення унітазу. Аромат: вишневий цвіт.</strong>",
        description05: "Придбайте La Salud - Gel WC Flor De Cerezo&#171La Salud - Gel WC Flor De Cerezo&#187 вже сьогодні та подаруйте своєму туалету неперевершену чистоту і свіжість!"
    },
    {
        type: "wholesale",
        url: "./images/shop/household_chemicals/means_for_cleaning/for_wc/la_salud_wc_ocean_1l.jpg",
        alt: "la_salud_wc_ocean_1l",
        url1: "./images/shop/household_chemicals/means_for_cleaning/for_wc/la_salud_wc_ocean_1l-01.jpg",
        alt1: "la_salud_wc_ocean_1l-01",
        url2: "./images/shop/household_chemicals/means_for_cleaning/for_wc/la_salud_wc_ocean_1l-02.jpg",
        alt2: "la_salud_wc_ocean_1l-02",
        marker: "LDWC510",
        brand: "La Salud",
        search: "ла салуд средство для чистки чищення чистка забоси стредства туалет для туалета унитаз для унитаза унітаз для унітаза унітазу",
        nameUKR: "Засіб для чищення туалету (океан)",
        nameEN: "Gel WC Ocean",
        companyName: "Inquivisa",
        countryName: "Іспанія",
        volumeName: "Об'єм",
        volume: "1 л.",
        priceGRN: 122,
        priceGRNOpt: 110,
        description01: "Хочете, щоб ваш туалет був ідеально чистим та свіжим? Спробуйте &#171La Salud - Gel WC Ocean&#187!",
        description02: "Цей гель забезпечує глибоке очищення, видаляючи навіть найстійкіший бруд і залишаючи приємний аромат океанської свіжості. Його інноваційна формула проникає у важкодоступні місця, гарантуючи повну гігієну.",
        description03: "З &#171La Salud - Gel WC Ocean& Ваш туалет буде сяяти чистотою, а аромат свіжого океану створить атмосферу свіжості та чистоти на довгий час. Забудьте про неприємні запахи та бактерії!",
        description04: "<strong>Засіб для чищення унітазу. Аромат: океан.</strong>",
        description05: "Придбайте  &#171La Salud - Gel WC Ocean& вже сьогодні та насолоджуйтесь бездоганною чистотою і свіжістю вашого туалету!"
    },
    {
        type: "wholesale",
        url: "./images/shop/household_chemicals/means_for_cleaning/for_wc/la_salud_wc_oxi_eucalipto_1l.jpg",
        alt: "la_salud_wc_oxi_eucalipto_1l",
        url1: "./images/shop/household_chemicals/means_for_cleaning/for_wc/la_salud_wc_oxi_eucalipto_1l-01.jpg",
        alt1: "la_salud_wc_oxi_eucalipto_1l-01",
        url2: "./images/shop/household_chemicals/means_for_cleaning/for_wc/la_salud_wc_oxi_eucalipto_1l-02.jpg",
        alt2: "la_salud_wc_oxi_eucalipto_1l-02",
        marker: "LDWC515",
        brand: "La Salud",
        search: "ла салуд средство для чистки чищення чистка забоси стредства туалет для туалета унитаз для унитаза унітаз для унітаза унітазу відбілювачі отбеливатель отбеливатели эвкалипт с эвкалиптом с активным кислородом активный кислород",
        nameUKR: "Засіб для чищення туалету з активнем киснем, відбілювач (евкаліпт)",
        nameEN: "Oxi Active Eucalipto",
        companyName: "Inquivisa",
        countryName: "Іспанія",
        volumeName: "Об'єм",
        volume: "1 л.",
        priceGRN: 122,
        priceGRNOpt: 110,
        description01: "Забудьте про труднощі з усуненням бруду - &#171La Salud - Oxi Active Eucalipto&#187 гарантує ефективну чистоту і свіжість.",
        description02: "Завдяки активному кисню та евкаліптовому аромату він проникає глибоко у забруднення, легко видаляються, та залишає приємний аромат у Вашому туалеті.",
        description03: "Прагнете мати ідеально чистий та свіжий туалет з мінімальними зусиллями?  &#171La Salud - Oxi Active Eucalipto&#187 перетворює Ваші мрії у реальність, надаючи неймовірну чистоту та захищаючи від неприємних запахів.",
        description04: "<strong>Засіб для чищення унітазу з активним киснем. Аромат: евкаліпт. Містить відбілювач.</strong>",
        description05: "Очистіть свій туалет швидко та ефективно з &#171La Salud - Oxi Active Eucalipto&#187 - Ваш ключ до бездоганної чистоти та свіжості!"
    },
    {
        type: "wholesale",
        url: "./images/shop/household_chemicals/means_for_cleaning/for_wc/la_salud_wc_pine_1l.jpg",
        alt: "la_salud_wc_pine_1l",
        url1: "./images/shop/household_chemicals/means_for_cleaning/for_wc/la_salud_wc_pine_1l-01.jpg",
        alt1: "la_salud_wc_pine_1l-01",
        url2: "./images/shop/household_chemicals/means_for_cleaning/for_wc/la_salud_wc_pine_1l-02.jpg",
        alt2: "la_salud_wc_pine_1l-02",
        marker: "LDWC520",
        brand: "La Salud",
        search: "ла салуд средство для чистки чищення чистка забоси стредства туалет для туалета унитаз для унитаза унітаз для унітаза унітазу",
        nameUKR: "Засіб для чищення туалету (сосна)",
        nameEN: "Gel WC Pino",
        companyName: "Inquivisa",
        countryName: "Іспанія",
        volumeName: "Об'єм",
        volume: "1 л.",
        priceGRN: 122,
        priceGRNOpt: 110,
        description01: "Відкрийте для себе ідеальний засіб для чищення туалету з ароматом сосни &#171La Salud - Gel WC Pino&#187, потужна формула якого забезпечить неперевершену чистоту у Вашому туалеті.",
        description02: "Цей гель миттєво розподіляється по поверхні, неймовірно зручний у використанні і має приємний аромат сосни, який зробить Ваш туалет запашним та свіжим.",
        description03: "&#171La Salud - Gel WC Pino&#187 здійснить Ваші найсміливіші бажання, забезпечуючи не лише чистоту, але і приємний аромат.",
        description04: "<strong>Засіб для чищення унітазу. Аромат: сосна.</strong>",
        description05: "Очистіть свій туалет легко та швидко з &#171La Salud - Gel WC Pino&#187 - Ваш надійний помічник у боротьбі з брудом та запахами!"
    },
]