export const shopLotsForWC = [
    // {
    //     type: "retail",
    //     url: "./images/shop/household_chemicals/means_for_cleaning/for_wc/ace_wc_gel_candeggina_700.jpg",
    //     alt: "ace_wc_gel_candeggina_700",
    //     url1: "./images/shop/household_chemicals/means_for_cleaning/for_wc/ace_wc_gel_candeggina_700-01.jpg",
    //     alt1: "ace_wc_gel_candeggina_700-01",
    //     url2: "./images/shop/household_chemicals/means_for_cleaning/for_wc/ace_wc_gel_candeggina_700-02.jpg",
    //     alt2: "ace_wc_gel_candeggina_700-02",
    //     marker: "LDWC010",
    //     brand: "Ace",
    //     search: "ейс аце эйс средство для чистки чищення чистка забоси стредства туалет для туалета унитаз для унитаза унітаз для унітаза унітазу відбілювачі отбеливатель отбеливатели",
    //     nameUKR: "Засіб для чищення туалету з відбілювачем",
    //     nameEN: "WC Gel Candeggina",
    //     companyName: "Fater S.P.A.",
    //     countryName: "Італія",
    //     volumeName: "Об'єм",
    //     volume: "700 мл.",
    //     priceGRN: 96,
    //     pquantityOnStorage: 1,
    //     description01: "Забезпечте ідеальну чистоту та свіжість Вашого туалету за допомогою &#171Ace - WC Gel Candeggina&#187.",
    //     description02: "Цей гель з відбілювачем ефективно видаляє бруд, наліт та бактерії, залишаючи Ваш туалет бездоганно чистим. Активні компоненти проникають у важкодоступні місця, забезпечуючи глибоке очищення.",
    //     description03: "&#171Ace - WC Gel Candeggina&#187 не тільки очищує, але й відбілює поверхні, даруючи їм новий вигляд. Забудьте про неприємні запахи та насолоджуйтесь свіжістю кожного дня.",
    //     description04: "<strong>Засіб для чищення унітазу. Не дезінфекующий засіб. Містить відбілювач.</strong>",
    //     description05: "Купуйте &#171Ace - WC Gel Candeggina&#187 сьогодні та зробіть свій туалет ідеально чистим і свіжим!"
    // },
    {
        type: "retail",
        url: "./images/shop/household_chemicals/universal_tools/ace_spray_multiuso_eco_ricarica_15.jpg",
        alt: "ace_spray_multiuso_eco_ricarica_15",
        url1: "./images/shop/household_chemicals/universal_tools/ace_spray_multiuso_eco_ricarica_15-01.jpg",
        alt1: "ace_spray_multiuso_eco_ricarica_15-01",
        url2: "./images/shop/household_chemicals/universal_tools/ace_spray_multiuso_eco_ricarica_15-02.jpg",
        alt2: "ace_spray_multiuso_eco_ricarica_15-02",
        url3: "./images/shop/household_chemicals/universal_tools/ace_spray_multiuso_eco_ricarica_15-03.jpg",
        alt3: "ace_spray_multiuso_eco_ricarica_15-03",
        marker: "HCUT082",
        brand: "Ace",
        search: "ейс аце эйс засоби ванна кімната ванна ванная комната для ванны средство для чистки ванной комнаты ванны проти жиру обезжириватель средство средства против жира с з лимоном",
        nameUKR: "Екологічний засіб для чищення, спрей (лимон)",
        nameEN: "Ace Pavimenti Eco-Ricarica Spray Multiuso",
        companyName: "Fater S.P.A.",
        countryName: "Італія",
        weightName: "Вага",
        weight: "15 гр.",
        priceGRN: 10,
        quantityOnStorage: 16,
        description01: "Забезпечте Вёашому дому бездоганну чистоту з екологічним засобом для чищення &#171Ace - Pavimenti Eco-Ricarica Spray Multiuso&#187, який поєднує ефективність і турботу про довкілля.",
        description02: "Має потужну формулу з натуральними інгредієнтами та свіжим ароматом лимону. Він легко видаляє бруд, жир і плями з будь-яких поверхонь, залишаючи їх чистими та блискучими.",
        description03: " З &#171Ace - Pavimenti Eco-Ricarica Spray Multiuso&#187 Ваші поверхні будуть бездоганно чистими та свіжими без шкоди для природи.",
        description04: "<strong>Запаска! Екологічний засіб для чищення, спрей. Аромат: лимон.</strong>",
        description05: "Замовляйте &#171Ace - Pavimenti Eco-Ricarica Spray Multiuso&#187 зараз і насолоджуйтеся ідеальною чистотою та свіжістю Вашого дому!"
    },
    // {
    //     type: "retail",
    //     url: "./images/shop/household_chemicals/means_for_cleaning/universal/at_home_clean_all_purpose_lime_eucalyptus.jpg",
    //     alt: "at_home_clean_all_purpose_lime_eucalyptus",
    //     url1: "./images/shop/household_chemicals/means_for_cleaning/universal/at_home_clean_all_purpose_lime_eucalyptus-01.jpg",
    //     alt1: "at_home_clean_all_purpose_lime_eucalyptus-01",
    //     url2: "./images/shop/household_chemicals/means_for_cleaning/universal/at_home_clean_all_purpose_lime_eucalyptus-02.jpg",
    //     alt2: "at_home_clean_all_purpose_lime_eucalyptus-02",
    //     marker: "MCU015",
    //     brand: "at home Clean",
    //     search: "клин клін универсальний универсальное средство средства для чистки засоби для чищення для підлоги пола підлога с лаймом эвкалиптом",
    //     nameUKR: "Універсальний засіб для чищення з ароматом лайму та евкаліпту",
    //     nameEN: "All Purpose Lime & Eucalyptus",
    //     companyName: "Maxbrands Marketing B.V.",
    //     countryName: "Німеччина",
    //     volumeName: "Об'єм",
    //     volume: "1 л.",
    //     priceGRN: 76,
    //     quantityOnStorage: 1,
    //     description01: "&#171at home Clean - All Purpose Lime & Eucalyptus&#187 - це універсальний засіб для прибирання з освіжаючим ароматом лайму та евкаліпту. Його потужна формула легко видаляє жир, забруднення і брудні сліди з різних поверхонь.",
    //     description02: "З цим засобом прибирання стає легким та приємним. Він ефективно очищає підлоги, столи, кухонні поверхні та ванні кімнати, залишаючи їх свіжими і блискучими.",
    //     description03: "&#171at home Clean - All Purpose Lime & Eucalyptus&#187 дарує вашому дому атмосферу чистоти та свіжості. Його натуральні аромати лайму та евкаліпту допомагають зняти втому і стрес, заряджають енергією і позитивним настроєм.",
    //     description04: "<strong>Універсальний засіб для чищення. Не підходить для дерева, алюмінію. Аромат: лайм, евкаліпт.</strong>",
    //     description05: "Зробіть свій будинок чистим і охайним разом з &#171at home Clean - All Purpose Lime & Eucalyptus&#187, який створить атмосферу затишку та чистоти в кожному куточку вашого дому."
    // },
    {
        type: "wholesale",
        url: "./images/shop/household_chemicals/means_for_cleaning/for_wc/brait_cistern_block_blue_water_50.jpg",
        alt: "brait_cistern_block_blue_water_50",
        url1: "./images/shop/household_chemicals/means_for_cleaning/for_wc/brait_cistern_block_blue_water_50-01.jpg",
        alt1: "brait_cistern_block_blue_water_50-01",
        url2: "./images/shop/household_chemicals/means_for_cleaning/for_wc/brait_cistern_block_blue_water_50-02.jpg",
        alt2: "brait_cistern_block_blue_water_50-02",
        marker: "LDWC040",
        brand: "Brait",
        search: "браит браіт брайт таблетки средство для чистки чищення чистка забоси стредства туалет для туалета унитаз для унитаза унітаз для унітаза унітазу таблетка для унитазного бачка унитазный унітазний бачок синяя вода синий цвет",
        nameUKR: "Таблетка для унітазного бачку (синя вода)",
        nameEN: "Cistern Block Blue Water Effect",
        companyName: "Dramers S.A. Rabowice",
        countryName: "Польща",
        weightName: "Вага",
        weight: "50 гр.",
        priceGRN: 35,
        priceGRNOpt: 29,
        description01: "Освіжіть Ваш туалет з таблеткою для унітазного бачку &#171Brait - Cistern Block Blue Water Effect&#187.",
        description02: "Завдяки синьому водному ефекту, Ваш унітаз завжди виглядатиме чистим та свіжим.",
        description03: "Активні компоненти &#171Brait - Cistern Block Blue Water Effect&#187 ефективно видаляють наліт та запобігають утворенню нових забруднень.",
        description04: "<strong>Таблетка для унітазного бачка. Фарбує воду у синій колір. Робить піну.</strong>",
        description05: "Насолоджуйтеся приємним ароматом та кришталево чистою водою та перетворіть догляд за туалетом у задоволення з &#171Brait - Cistern Block Blue Water Effect&#187!"
    },
    {
        type: "wholesale",
        url: "./images/shop/household_chemicals/means_for_cleaning/for_wc/brait_cistern_block_green_water_50.jpg",
        alt: "brait_cistern_block_green_water_50",
        url1: "./images/shop/household_chemicals/means_for_cleaning/for_wc/brait_cistern_block_green_water_50-01.jpg",
        alt1: "brait_cistern_block_green_water_50-01",
        url2: "./images/shop/household_chemicals/means_for_cleaning/for_wc/brait_cistern_block_green_water_50-02.jpg",
        alt2: "brait_cistern_block_green_water_50-02",
        marker: "LDWC042",
        brand: "Brait",
        search: "браит браіт брайт таблетки средство для чистки чищення чистка забоси стредства туалет для туалета унитаз для унитаза унітаз для унітаза унітазу таблетка для унитазного бачка унитазный унітазний бачок зеленая вода зеленый цвет",
        nameUKR: "Таблетка для унітазного бачку (зелена вода)",
        nameEN: "Cistern Block Green Water Effect",
        companyName: "Dramers S.A. Rabowice",
        countryName: "Польща",
        weightName: "Вага",
        weight: "50 гр.",
        priceGRN: 35,
        priceGRNOpt: 29,
        description01: "Забезпечте бездоганну чистоту Вашого туалету з таблеткою для унітазного бачку &#171Brait - Cistern Block Green Water Effect&#187.",
        description02: "Інноваційна формула, яка фарбує воду у зелений колір гарантує довготривалу свіжість та гігієну.",
        description03: "Активні компоненти &#171Brait - Cistern Block Green Water Effect&#187 не лише ефективно очищають, але й запобігають утворенню нальоту.",
        description04: "<strong>Таблетка для унітазного бачка. Фарбує воду у зелений колір. Робить піну.</strong>",
        description05: "Ваш туалет буде наповнений приємним ароматом, тому спробуйте &#171Brait - Cistern Block Green Water Effect&#187 для неперевершеної чистоти та свіжості!"
    },
    {
        type: "wholesale",
        url: "./images/shop/household_chemicals/means_for_cleaning/for_wc/brait_lilac_garden_3x45.jpg",
        alt: "brait_lilac_garden_3x45",
        url1: "./images/shop/household_chemicals/means_for_cleaning/for_wc/brait_lilac_garden_3x45-01.jpg",
        alt1: "brait_lilac_garden_3x45-01",
        url2: "./images/shop/household_chemicals/means_for_cleaning/for_wc/brait_lilac_garden_3x45-02.jpg",
        alt2: "brait_lilac_garden_3x45-02",
        marker: "LDWC050",
        brand: "Brait",
        search: "браит браіт брайт средство для чистки чищення чистка забоси стредства туалет для туалета унитаз для унитаза унітаз для унітаза унітазу вапняний нальот",
        nameUKR: "Засіб для чищення туалету, проти вапняного нальоту (бузковий сад)",
        nameEN: "Lilac Garden",
        companyName: "Dramers S.A. Rabowice",
        countryName: "Польща",
        quantityName: "Кількість",
        quantity: "3 шт.",
        priceGRN: 110,
        priceGRNOpt: 95,
        description01: "&#171Brait - Lilac Garden&#187 здивує Вас своєю потужністю та ароматом. Цей засіб проникає навіть у важкодоступні місця та ефективно видаляє вапняний нальот, залишаючи ваш туалет блискучим і свіжим.",
        description02: "Він не лише робить чистку легшою і швидшою, а й забезпечує приємний аромат, який легко розповсюджується по всьому приміщенню, надаючи приємний запах.",
        description03: "Спробуйте &#171Brait - Lilac Garden&#187 і відчуйте, як Ваш туалет стає місцем, куди хочеться повертатися знову і знову.",
        description04: "<strong>Засіб для чищення унітазу. Проти вапняного нальоту. Підвісний блок. 3 х 45 гр. Аромат: бузок.</strong>",
        description05: "Очистіть свій туалет від вапняного нальоту з &#171Brait - Lilac Garden&#187 сьогодні, і насолоджуйтесь чистотою та свіжістю в вашій ванній кімнаті!"
    },
    {
        type: "wholesale",
        url: "./images/shop/household_chemicals/means_for_cleaning/for_wc/brait_oceanic_3x45.jpg",
        alt: "brait_oceanic_3x45",
        url1: "./images/shop/household_chemicals/means_for_cleaning/for_wc/brait_oceanic_3x45-01.jpg",
        alt1: "brait_oceanic_3x45-01",
        url2: "./images/shop/household_chemicals/means_for_cleaning/for_wc/brait_oceanic_3x45-02.jpg",
        alt2: "brait_oceanic_3x45-02",
        marker: "LDWC055",
        brand: "Brait",
        search: "браит браіт брайт средство для чистки чищення чистка забоси стредства туалет для туалета унитаз для унитаза унітаз для унітаза унітазу вапняний нальот",
        nameUKR: "Засіб для чищення туалету, проти вапняного нальоту (океан)",
        nameEN: "Oceanic",
        companyName: "Dramers S.A. Rabowice",
        countryName: "Польща",
        quantityName: "Кількість",
        quantity: "3 шт.",
        priceGRN: 110,
        priceGRNOpt: 95,
        description01: "Представляємо вам революційний засіб для чищення туалету - &#171Brait - Oceanic&#187. Забудьте про проблему вапняного нальоту та насолоджуйтеся бездоганною чистотою.",
        description02: "Його спеціальна формула не лише ефективно видаляє вапняний нальот, але також залишає приємний аромат свіжості, що надає туалету атмосферу чистоти.",
        description03: "Мрієте про те, щоб Ваш туалет завжди був ідеально чистим і приємно пахнучим? &#171Brait - Oceanic&#187 робить Ваші мрії реальністю, забезпечуючи найвищу якість чистоти та свіжості.",
        description04: "<strong>Засіб для чищення унітазу. Проти вапняного нальоту. Підвісний блок. 3 х 45 гр. Аромат: океан.</strong>",
        description05: "Допоможіть Вашому туалету стати місцем чистоти та свіжості, без сліду від вапняного нальоту разом з &#171Brait - Oceanic&#187!"
    },
    {
        type: "wholesale",
        url: "./images/shop/household_chemicals/means_for_cleaning/for_wc/brait_pine_3x45.jpg",
        alt: "brait_pine_3x45",
        url1: "./images/shop/household_chemicals/means_for_cleaning/for_wc/brait_pine_3x45-01.jpg",
        alt1: "brait_pine_3x45-01",
        url2: "./images/shop/household_chemicals/means_for_cleaning/for_wc/brait_pine_3x45-02.jpg",
        alt2: "brait_pine_3x45-02",
        marker: "LDWC060",
        brand: "Brait",
        search: "браит браіт брайт средство для чистки чищення чистка забоси стредства туалет для туалета унитаз для унитаза унітаз для унітаза унітазу вапняний нальот",
        nameUKR: "Засіб для чищення туалету, проти вапняного нальоту (сосна)",
        nameEN: "Pine",
        companyName: "Dramers S.A. Rabowice",
        countryName: "Польща",
        quantityName: "Кількість",
        quantity: "3 шт.",
        priceGRN: 110,
        priceGRNOpt: 95,
        description01: "Шукаєте ефективний засіб для чищення туалету та боротьби з вапняним нальотом? Ознайомтеся з &#171Brait - Pine&#187, Вашим надійним помічником у цій справі.",
        description02: "Цей засіб не лише чудово видаляє вапняний нальот, але й має приємний аромат сосни, який створить атмосферу свіжості у Вашому туалеті.",
        description03: "Мрієте про бездоганну чистоту та відсутність вапняного нальоту у туалеті? &#171Brait - Pine&#187 здійснить Ваші найсміливіші бажання, залишаючи поверхні блискучими та чистими.",
        description04: "<strong>Засіб для чищення унітазу. Проти вапняного нальоту. Підвісний блок. 3 х 45 гр. Аромат: сосна.</strong>",
        description05: "Забезпечте своєму туалету ідеальну чистоту за допомогою &#171Brait - Pine&#187 і туалет стане місцем чистоти та свіжості."
    },
    // {
    //     type: "retail",
    //     url: "./images/shop/household_chemicals/means_for_cleaning/universal/clinair_allesreiniger_arctic.jpg",
    //     alt: "clinair_allesreiniger_arctic",
    //     url1: "./images/shop/household_chemicals/means_for_cleaning/universal/clinair_allesreiniger_arctic-01.jpg",
    //     alt1: "clinair_allesreiniger_arctic-01",
    //     url2: "./images/shop/household_chemicals/means_for_cleaning/universal/clinair_allesreiniger_arctic-02.jpg",
    //     alt2: "clinair_allesreiniger_arctic-02",
    //     marker: "MCU150",
    //     brand: "Clinair",
    //     search: "алді алди клінаір клинаир для кухни кухні кухня ванной комнаті ванної кімнати универсальний универсальное средство средства для чистки засоби для чищення для підлоги пола підлога",
    //     nameUKR: "Універсальний засіб для чищення (арктика)",
    //     nameEN: "Allesreiniger Arctic",
    //     companyName: "Aldi",
    //     countryName: "Німеччина",
    //     volumeName: "Об'єм",
    //     volume: "1 л.",
    //     priceGRN: 75,
    //     quantityOnStorage: 1,
    //     description01: "&#171Clinair - Allesreiniger Arctic&#187 - це універсальний засіб для прибирання з приємним ароматом арктичного свіжого повітря. Його потужна формула забезпечує ефективне видалення жиру, бруду і бактерій з усіх поверхонь у Вашому домі.",
    //     description02: "Цей засіб робить прибирання легким і швидким, залишаючи за собою бездоганну чистоту та приємний аромат. Він ідеально підходить для кухні, ванної кімнати, підлоги та інших поверхонь.",
    //     description03: "&#171Clinair - Allesreiniger Arctic&#187 додасть свіжості і особливого шарму Вашому дому, створюючи атмосферу арктичної чистоти.",
    //     description04: "<strong>Універсальний засіб для чищення. Аромат: арктика. Розрахований на 44 порції.</strong>",
    //     description05: "Насолоджуйтеся прибиранням та насиченим ароматом від &#171Clinair - Allesreiniger Arctic&#187, який перетворить Ваше прибирання на приємну пригоду."
    // },
    // {
    //     type: "retail",
    //     url: "./images/shop/household_chemicals/means_for_cleaning/universal/clinair_allesreiniger_fresh_green.jpg",
    //     alt: "clinair_allesreiniger_fresh_green",
    //     url1: "./images/shop/household_chemicals/means_for_cleaning/universal/clinair_allesreiniger_fresh_green-01.jpg",
    //     alt1: "clinair_allesreiniger_fresh_green-01",
    //     url2: "./images/shop/household_chemicals/means_for_cleaning/universal/clinair_allesreiniger_fresh_green-02.jpg",
    //     alt2: "clinair_allesreiniger_fresh_green-02",
    //     marker: "MCU155",
    //     brand: "Clinair",
    //     search: "алді алди клінаір клинаир для кухни кухні кухня ванной комнаті ванної кімнати универсальний универсальное средство средства для чистки засоби для чищення для підлоги пола підлога зеленая свежесть",
    //     nameUKR: "Універсальний засіб для чищення (зелена свіжість)",
    //     nameEN: "Allesreiniger Fresh Green",
    //     companyName: "Aldi",
    //     countryName: "Німеччина",
    //     volumeName: "Об'єм",
    //     volume: "1 л.",
    //     priceGRN: 75,
    //     quantityOnStorage: 1,
    //     description01: "&#171Clinair - Allesreiniger Fresh Green&#187 - це універсальний засіб для прибирання з освіжаючим ароматом зеленого яблука. Його потужна формула легко впорається з різноманітними забрудненнями, забезпечуючи бездоганну чистоту на різних поверхнях у Вашому домі.",
    //     description02: "Цей засіб забезпечує ефективне видалення жиру, бруду і бактерій, зберігаючи при цьому природну свіжість. Він ідеально підходить для кухні, ванної кімнати, підлоги та інших поверхонь.",
    //     description03: "&#171Clinair - Allesreiniger Fresh Green&#187 додасть Вашому дому приємний аромат зеленого яблука, створюючи атмосферу чистоти та комфорту.",
    //     description04: "<strong>Універсальний засіб для чищення. Аромат: зелена свіжість. Розрахований на 44 порції.</strong>",
    //     description05: "Насолоджуйтеся прибиранням разом з &#171Clinair - Allesreiniger Fresh Green&#187, який зробить Ваш дім справжнім оазисом свіжості."
    // },
    {
        type: "retail",
        url: "./images/shop/household_chemicals/means_for_cleaning/universal/clinair_allesreiniger_lemon.jpg",
        alt: "clinair_allesreiniger_lemon",
        url1: "./images/shop/household_chemicals/means_for_cleaning/universal/clinair_allesreiniger_lemon-01.jpg",
        alt1: "clinair_allesreiniger_lemon-01",
        url2: "./images/shop/household_chemicals/means_for_cleaning/universal/clinair_allesreiniger_lemon-02.jpg",
        alt2: "clinair_allesreiniger_lemon-02",
        marker: "MCU160",
        brand: "Clinair",
        search: "алді алди клінаір клинаир для кухни кухні кухня ванной комнаті ванної кімнати универсальний универсальное средство средства для чистки засоби для чищення для підлоги пола підлога лімон с з лимоном",
        nameUKR: "Універсальний засіб для чищення (лимон)",
        nameEN: "Allesreiniger Lemon",
        companyName: "Aldi",
        countryName: "Німеччина",
        volumeName: "Об'єм",
        volume: "1 л.",
        priceGRN: 75,
        quantityOnStorage: 9,
        description01: "&#171Clinair - Allesreiniger Lemon&#187 - це універсальний засіб для прибирання з освіжаючим ароматом лимона. Його потужна формула допомагає легко і ефективно видаляти жир, бруд та бактерії з усіх поверхонь у Вашому домі.",
        description02: "Завдяки своїй унікальній формулі, &#171Clinair - Allesreiniger Lemon&#187 гарантує бездоганну чистоту та залишає за собою приємний аромат свіжості.",
        description03: "Він ідеально підходить для кухні, ванної кімнати, підлоги та інших поверхонь.",
        description04: "<strong>Універсальний засіб для чищення. Аромат: лимон. Розрахований на 44 порції.</strong>",
        description05: "Насолоджуйтесь прибиранням з &#171Clinair - Allesreiniger Lemon&#187, який забезпечує миттєвий блиск і залишає Ваш дім наповненим свіжістю ароматного лимону."
    },
    {
        type: "retail",
        url: "./images/shop/household_chemicals/means_for_cleaning/universal/clinair_allesreiniger_purple_flower.jpg",
        alt: "clinair_allesreiniger_purple_flower",
        url1: "./images/shop/household_chemicals/means_for_cleaning/universal/clinair_allesreiniger_purple_flower-01.jpg",
        alt1: "clinair_allesreiniger_purple_flower-01",
        url2: "./images/shop/household_chemicals/means_for_cleaning/universal/clinair_allesreiniger_purple_flower-02.jpg",
        alt2: "clinair_allesreiniger_purple_flower-02",
        marker: "MCU165",
        brand: "Clinair",
        search: "алді алди клінаір клинаир для кухни кухні кухня ванной комнаті ванної кімнати универсальний универсальное средство средства для чистки засоби для чищення для підлоги пола підлога фиалка ",
        nameUKR: "Універсальний засіб для чищення (фіалка)",
        nameEN: "Allesreiniger Purple Flower",
        companyName: "Aldi",
        countryName: "Німеччина",
        volumeName: "Об'єм",
        volume: "1 л.",
        priceGRN: 75,
        quantityOnStorage: 1,
        description01: "&#171Clinair - Allesreiniger Purple Flower&#187 - це чудовий засіб для прибирання з вишуканим ароматом фіалки, який дарує Вашому дому чистоту та свіжість. Завдяки унікальній формулі, він легко впорається із забрудненнями на будь-яких поверхнях - від кухонного столу до ванної кімнати.",
        description02: "&#171Clinair - Allesreiniger Purple Flower&#187 має потужну дію, що допомагає ефективно видаляти жир, бруд та бактерії, забезпечуючи бездоганну гігієну у Вашому домі.",
        description03: "Його свіжий та приємний аромат фіалки створює атмосферу комфорту та спокою.",
        description04: "<strong>Універсальний засіб для чищення. Аромат: фіалка. Розрахований на 44 порції.</strong>",
        description05: "Насолоджуйтеся легким та приємним прибиранням з &#171Clinair - Allesreiniger Purple Flower&#187, який не лише дарує чистоту, але і підносить настрій своїм неповторним ароматом."
    },
    {
        type: "retail",
        url: "./images/shop/household_chemicals/means_for_cleaning/universal/denkmit_fruhlings_moment.jpg",
        alt: "denkmit_fruhlings_moment",
        url1: "./images/shop/household_chemicals/means_for_cleaning/universal/denkmit_fruhlings_moment-01.jpg",
        alt1: "denkmit_fruhlings_moment-01",
        url2: "./images/shop/household_chemicals/means_for_cleaning/universal/denkmit_fruhlings_moment-02.jpg",
        alt2: "denkmit_fruhlings_moment-02",
        marker: "MCU200",
        brand: "Denkmit",
        search: "денкмит денкміт Fruhlings Moment для кухни кухні кухня ванной комнаті ванної кімнати универсальний универсальное средство средства для чистки засоби для чищення для підлоги пола весенние цветы",
        nameUKR: "Універсальний засіб для чищення (весняна мить)",
        nameEN: "Allzweckreiniger Frühlings Moment",
        companyName: "dm-drogerie markt GmbH + Co.",
        countryName: "Німеччина",
        volumeName: "Об'єм",
        volume: "1 л.",
        priceGRN: 79,
        quantityOnStorage: 11,
        description01: "&#171Denkmit - Allzweckreiniger Frühlings Moment&#187 - це чарівний відпочинок для твого дому, який запрошує весняні емоції у твоє життя. Цей універсальний засіб створений, щоб розкрити яскраві моменти радості і свіжості кожного дня.",
        description02: "Його освіжаючий аромат весняних квітів наповнить приміщення свіжістю, а унікальна формула забезпечить бездоганну чистоту різних поверхонь.",
        description03: "&#171Denkmit - Allzweckreiniger Frühlings Moment&#187 має потужну дію при митті та дезінфекції, легко справляючись зі складними забрудненнями. Цей універсальний засіб є ефективним і економним у використанні, забезпечуючи довгий термін використання.",
        description04: "<strong>Універсальний засіб для чищення. Не для підлог з відкритими порами. Аромат: весняні квіти.</strong>",
        description05: "Надай своєму дому аромат весни з &#171Denkmit - Allzweckreiniger Frühlings Moment&#187, і твоя домівка буде пахнути ніжними квітами і випромінювати чистоту та затишок."
    },
    {
        type: "wholesale",
        url: "./images/shop/household_chemicals/means_for_cleaning/for_wc/denkmit_wc_reineiger_1l.jpg",
        alt: "denkmit_wc_reineiger_1l",
        url1: "./images/shop/household_chemicals/means_for_cleaning/for_wc/denkmit_wc_reineiger_1l-01.jpg",
        alt1: "denkmit_wc_reineiger_1l-01",
        url2: "./images/shop/household_chemicals/means_for_cleaning/for_wc/denkmit_wc_reineiger_1l-02.jpg",
        alt2: "denkmit_wc_reineiger_1l-02",
        marker: "LDWC200",
        brand: "Denkmit",
        search: "денкмит денкміт средство для чистки чищення чистка забоси стредства туалет для туалета унитаз для унитаза унітаз для унітаза унітазу",
        nameUKR: "Засіб для чищення туалету (свіжість океану)",
        nameEN: "WC-Reiniger Ozean Frische",
        companyName: "dm-drogerie markt GmbH + Co.",
        countryName: "Німеччина",
        volumeName: "Об'єм",
        volume: "1 л.",
        priceGRN: 94,
        priceGRNOpt: 80,
        description01: "Знайомтесь із чудодійним засобом для чищення унітазів &#171Denkmit - WC-Reiniger Ozean Frische&#187. Завдяки інноваційній формулі, він ефективно усуває бруд та неприємні запахи, перетворюючи ванну кімнату у куточок свіжості.",
        description02: "Аромат океану подарує Вашому унітазу неймовірну свіжість та бездоганну чистоту. Спробуйте його один раз - і Ви залишитесь вражені результатом!",
        description03: "Ідеальна чистота, об'єднана з приємним ароматом - ось що робить &#171Denkmit - WC-Reiniger Ozean Frische&#187 чудовим вибором для догляду за Вашою ванною кімнатою. Почуття свіжості, яке Ви будете відчувати, зробить цей засіб для чищення унітазів Вашим улюбленим.",
        description04: "<strong>Засіб для чищення унітазу. Не використовувати на мармурі.</strong>",
        description05: "Покажіть своїй ванні кімнаті, що вона заслуговує на краще! Замовте &#171Denkmit - WC-Reiniger Ozean Frische&#187 вже сьогодні та даруйте своєму унітазу освіжаючу атмосферу!"
    },
    {
        type: "wholesale",
        url: "./images/shop/household_chemicals/means_for_cleaning/for_wc/denkmit_wc-tabs_16.jpg",
        alt: "denkmit_wc-tabs_16",
        url1: "./images/shop/household_chemicals/means_for_cleaning/for_wc/denkmit_wc-tabs_16-01.jpg",
        alt1: "denkmit_wc-tabs_16-01",
        url2: "./images/shop/household_chemicals/means_for_cleaning/for_wc/denkmit_wc-tabs_16-02.jpg",
        alt2: "denkmit_wc-tabs_16-02",
        url3: "./images/shop/household_chemicals/means_for_cleaning/for_wc/denkmit_wc-tabs_16-03.jpg",
        alt3: "denkmit_wc-tabs_16-03",
        marker: "LDWC210",
        brand: "Denkmit",
        search: "денкмит денкміт средство для чистки чищення чистка забоси стредства туалет для туалета унитаз для унитаза унітаз для унітаза унітазу",
        nameUKR: "Таблетки для унітазу (3 фази)",
        nameEN: "WC-Tabs Mit 3-Phasen-Kraft",
        companyName: "dm-drogerie markt GmbH + Co.",
        countryName: "Німеччина",
        quantityName: "Кількість",
        quantity: "16 шт.",
        priceGRN: 132,
        priceGRNOpt: 114,
        description01: "Таблетки для унітазу &#171Denkmit - WC-Tabs Mit 3-Phasen-Kraft&#187 забезпечують ефективну очистку з кожним змивом.",
        description02: "Завдяки трифазовій формулі, вони одночасно видаляють наліт, дезінфікують поверхню та залишають приємний аромат.",
        description03: "Використання таблеток &#171Denkmit - WC-Tabs Mit 3-Phasen-Kraft&#187 дозволяє підтримувати свіжість і гігієну Вашого унітазу без зайвих зусиль.",
        description04: "<strong>Таблетки для унітазу. Застосовуються у каналізацію, унітаз, бачок. 16 штук х 25 гр.</strong>",
        description05: "Замовляйте вже сьогодні та підтримуйте ідеальну чистоту за допомогою таблеток &#171Denkmit - WC-Tabs Mit 3-Phasen-Kraft&#187!"
    },
    {
        type: "wholesale",
        url: "./images/shop/household_chemicals/means_for_cleaning/for_wc/denkmit_wc-wasserkasten-tabletten_4.jpg",
        alt: "denkmit_wc-wasserkasten-tabletten_4",
        url1: "./images/shop/household_chemicals/means_for_cleaning/for_wc/denkmit_wc-wasserkasten-tabletten_4-01.jpg",
        alt1: "denkmit_wc-wasserkasten-tabletten_4-01",
        url2: "./images/shop/household_chemicals/means_for_cleaning/for_wc/denkmit_wc-wasserkasten-tabletten_4-02.jpg",
        alt2: "denkmit_wc-wasserkasten-tabletten_4-02",
        url3: "./images/shop/household_chemicals/means_for_cleaning/for_wc/denkmit_wc-wasserkasten-tabletten_4-03.jpg",
        alt3: "denkmit_wc-wasserkasten-tabletten_4-03",
        marker: "LDWC215",
        brand: "Denkmit",
        search: "денкмит денкміт средство для чистки чищення чистка забоси стредства туалет для туалета унитаз для унитаза унітаз для унітаза унітазу",
        nameUKR: "Таблетки у туалетний бачок для видалення накипу та забруднень",
        nameEN: "WC-Wasserkasten-Tabletten 2 in 1",
        companyName: "dm-drogerie markt GmbH + Co.",
        countryName: "Німеччина",
        quantityName: "Кількість",
        quantity: "4 шт.",
        priceGRN: 132,
        priceGRNOpt: 114,
        description01: "Таблетки &#171Denkmit - WC-Wasserkasten-Tabletten 2 in 1&#187 для видалення накипу та забруднень у туалетному бачку забезпечують потужну дію з кожним змивом.",
        description02: "Їх інноваційна формула 2 в 1 одночасно бореться з накипом і запобігає утворенню нових забруднень.",
        description03: "Використання цих таблеток дозволяє підтримувати чистоту Вашого туалету без зусиль, забезпечуючи свіжий аромат і гігієну.",
        description04: "<strong>Таблетки для унітазного бачку. Видаляють накип та забруднення. 4 штуки х 50 гр.</strong>",
        description05: "Оцініть переваги бездоганної чистоти з таблетками &#171Denkmit - WC-Wasserkasten-Tabletten 2 in 1&#187 для туалетного бачка!"
    },
    {
        type: "retail",
        url: "./images/shop/household_chemicals/means_for_cleaning/for_wc/denkmit_wc-reinigungsschaum_500.jpg",
        alt: "denkmit_wc-reinigungsschaum_500",
        url1: "./images/shop/household_chemicals/means_for_cleaning/for_wc/denkmit_wc-reinigungsschaum_500-01.jpg",
        alt1: "denkmit_wc-reinigungsschaum_500-01",
        url2: "./images/shop/household_chemicals/means_for_cleaning/for_wc/denkmit_wc-reinigungsschaum_500-02.jpg",
        alt2: "denkmit_wc-reinigungsschaum_500-02",
        url3: "./images/shop/household_chemicals/means_for_cleaning/for_wc/denkmit_wc-reinigungsschaum_500-03.jpg",
        alt3: "denkmit_wc-reinigungsschaum_500-03",
        marker: "LDWC220",
        brand: "Denkmit",
        search: "денкмит денкміт пена пеной средство для чистки чищення чистка забоси стредства туалет для туалета унитаз для унитаза унітаз для унітаза унітазу с лимоном ароматом лимона",
        nameUKR: "Піна для чистки туалету з ароматом лимону",
        nameEN: "WC-Reinigungsschaum Zitrone",
        companyName: "dm-drogerie markt GmbH + Co.",
        countryName: "Німеччина",
        volumeName: "Об'єм",
        volume: "500 мл.",
        priceGRN: 112,
        quantityOnStorage: 5,
        description01: "Піна для чистки туалету з ароматом лимону &#171Denkmit - WC-Reinigungsschaum Zitrone&#187 забезпечує миттєву свіжість та ефективне видалення забруднень.",
        description02: "Спеціальна формула піни проникає навіть у важкодоступні місця, забезпечуючи ретельну чистку.",
        description03: "Аромат лимону &#171Denkmit - WC-Reinigungsschaum Zitrone&#187 залишає приємний запах, перетворюючи прибирання на задоволення.",
        description04: "<strong>Піна для чистки туалету. Аромат: лимон. Не підходить для мармуру, алюмінію, дерева.</strong>",
        description05: "Відчуйте переваги бездоганної чистоти та свіжості з піною &#171Denkmit - WC-Reinigungsschaum Zitrone&#187 для чистки туалету!"
    },
    {
        type: "retail",
        url: "./images/shop/household_chemicals/means_for_cleaning/universal/der_general_sensitive_aloe_vera.jpg",
        alt: "der_general_sensitive_aloe_vera",
        url1: "./images/shop/household_chemicals/means_for_cleaning/universal/der_general_sensitive_aloe_vera-01.jpg",
        alt1: "der_general_sensitive_aloe_vera-01",
        url2: "./images/shop/household_chemicals/means_for_cleaning/universal/der_general_sensitive_aloe_vera-02.jpg",
        alt2: "der_general_sensitive_aloe_vera-02",
        marker: "MCU250",
        brand: "Der General",
        search: "генерал для кухни кухні кухня ванной комнаті ванної кімнати универсальний универсальное средство средства для чистки засоби для чищення для підлоги пола",
        nameUKR: "Універсальний засіб для чищення з екстрактом алое вера",
        nameEN: "Sensitive Aloe Vera",
        companyName: "Henkel",
        countryName: "Німеччина",
        volumeName: "Об'єм",
        volume: "750 мл.",
        priceGRN: 135,
        quantityOnStorage: 1,
        description01: "&#171Der General - Sensitive Aloe Vera&#187 - це надійний та ефективний засіб, створений спеціально для бездоганної чистоти. З його допомогою легко очистити будь-які поверхні в домі, забезпечуючи надійний захист від бактерій та забруднень.",
        description02: "Його потужна формула забезпечує миття без зусиль, ефективно видаляючи жир, залишки їжі та інші забруднення.",
        description03: "&#171Der General - Sensitive Aloe Vera&#187 має приємний аромат, який створює атмосферу свіжості та чистоти у Вашому домі. Він ідеально підходить для всіх поверхонь, забезпечуючи гігієнічну чистоту та комфорт у Вашій оселі.",
        description04: "<strong>Універсальний засіб для чищення. Підходить для чутливих поверхонь.</strong>",
        description05: "Зробіть прибирання простим та приємним з &#171Der General - Sensitive Aloe Vera&#187, який надає Вашому дому бездоганну чистоту та надійний захист."
    },
    {
        type: "retail",
        url: "./images/shop/household_chemicals/means_for_cleaning/universal/der_general_universal_bergfruhling.jpg",
        alt: "der_general_universal_bergfruhling",
        url1: "./images/shop/household_chemicals/means_for_cleaning/universal/der_general_universal_bergfruhling-01.jpg",
        alt1: "der_general_universal_bergfruhling-01",
        url2: "./images/shop/household_chemicals/means_for_cleaning/universal/der_general_universal_bergfruhling-02.jpg",
        alt2: "der_general_universal_bergfruhling-02",
        marker: "MCU255",
        brand: "Der General",
        search: "генерал для кухни кухні кухня ванной комнаті ванної кімнати универсальний универсальное средство средства для чистки засоби для чищення для підлоги пола горная весна",
        nameUKR: "Універсальний засіб для чищення (гірська весна)",
        nameEN: "Universal Bergfrühling",
        companyName: "Henkel",
        countryName: "Німеччина",
        volumeName: "Об'єм",
        volume: "750 мл.",
        priceGRN: 135,
        quantityOnStorage: 1,
        description01: "&#171Der General - Universal Bergfrühling&#187 - це універсальний засіб з приємним ароматом гірського весняного бризу. З його допомогою легко очистити будь-які поверхні в Вашому домі, забезпечуючи високий рівень гігієни та чистоти.",
        description02: "Цей універсальний засіб ефективно видаляє жир, забруднення та сліди, залишаючи поверхні блискучими і свіжими. Він має потужну формулу, яка допомагає забезпечити гігієнічну чистоту і захист від бактерій.",
        description03: "&#171Der General - Universal Bergfrühling&#187 має освіжаючий аромат гірського весняного бризу, який зробить прибирання приємним і комфортним. Він ідеально підходить для різних поверхонь, включаючи підлоги, столи, ванні кімнати та кухні.",
        description04: "<strong>Універсальний засіб для чищення. Аромат: гірська весна.</strong>",
        description05: "Зробіть свій будинок бездоганно чистим з &#171Der General - Universal Bergfrühling&#187, який надає Вашому дому приємний аромат і надійний захист від бактерій."
    },
    {
        type: "wholesale",
        url: "./images/shop/household_chemicals/means_for_cleaning/for_wc/gallus_oriental_flowers_2x45.jpg",
        alt: "gallus_oriental_flowers_2x45",
        url1: "./images/shop/household_chemicals/means_for_cleaning/for_wc/gallus_oriental_flowers_2x45-01.jpg",
        alt1: "gallus_oriental_flowers_2x45-01",
        url2: "./images/shop/household_chemicals/means_for_cleaning/for_wc/gallus_oriental_flowers_2x45-02.jpg",
        alt2: "gallus_oriental_flowers_2x45-02",
        marker: "LDWC350",
        brand: "Gallus",
        search: "хенкель галус галлус средство для чистки чищення чистка забоси стредства туалет для туалета унитаз для унитаза унітаз для унітаза унітазу восточные цветы",
        nameUKR: "Засіб для чищення туалету (східні квіти)",
        nameEN: "Oriental Flowers",
        companyName: "Henkel",
        countryName: "Німеччина",
        quantityName: "Кількість",
        quantity: "2 шт.",
        priceGRN: 96,
        priceGRNOpt: 86,
        description01: "Представляємо новий рівень чистоти та свіжості - підвісний блок для чищення туалету &#171Gallus - Oriental Flowers&#187 з ароматом східних квітів.",
        description02: "Його унікальна формула забезпечує тривалу чистоту і неймовірний аромат, заповнюючи Ваш туалет екзотичними нотками квітів.",
        description03: "Мрієте про те, щоб туалет завжди пахнув свіжістю та був захищений від бруду? &#171Gallus - Oriental Flowers&#187 здійснить Ваші найсміливіші бажання, надаючи бездоганну чистоту та аромат.",
        description04: "<strong>Засіб для чищення унітазу. Підвісний блок. Фарбує воду у синій колір. 2 х 45 гр. Аромат: східні квіти.</strong>",
        description05: "Просто зачепіть блок &#171Gallus - Oriental Flowers&#187 у Вашому туалеті і насолоджуйтеся чистотою та ароматом, які він надає!"
    },
    {
        type: "wholesale",
        url: "./images/shop/household_chemicals/means_for_cleaning/for_wc/gallus_tropical_flowers_2x45.jpg",
        alt: "gallus_tropical_flowers_2x45",
        url1: "./images/shop/household_chemicals/means_for_cleaning/for_wc/gallus_tropical_flowers_2x45-01.jpg",
        alt1: "gallus_tropical_flowers_2x45-01",
        url2: "./images/shop/household_chemicals/means_for_cleaning/for_wc/gallus_tropical_flowers_2x45-02.jpg",
        alt2: "gallus_tropical_flowers_2x45-02",
        marker: "LDWC355",
        brand: "Gallus",
        search: "хенкель галус галлус средство для чистки чищення чистка забоси стредства туалет для туалета унитаз для унитаза унітаз для унітаза унітазу тропические цветы",
        nameUKR: "Засіб для чищення туалету (тропічні квіти)",
        nameEN: "Tropical Flowers",
        companyName: "Henkel",
        countryName: "Німеччина",
        quantityName: "Кількість",
        quantity: "2 шт.",
        priceGRN: 96,
        priceGRNOpt: 86,
        description01: "Спробуйте свіжість та аромат тропічних квітів з підвісним блоком &#171Gallus - Tropical Flowers&#187.",
        description02: "Цей блок не лише ефективно бореться з брудом, але й заповнює приміщення атмосферою екзотики завдяки своєму свіжому аромату тропічних квітів.",
        description03: "Мрієте про те, щоб туалет завжди пахнув приємно та був захищений від бруду? &#171Gallus - Tropical Flowers&#187 робить Ваші бажання реальністю, забезпечуючи тривалу свіжість та чистоту.",
        description04: "<strong>Засіб для чищення унітазу. Підвісний блок. Фарбує воду у бірюзовий колір. 2 х 45 гр. Аромат: тропічні квіти.</strong>",
        description05: "Просто зачепіть блок &#171Gallus - Tropical Flowers&#187 у Вашому туалеті, і він самостійно забезпечить неймовірну свіжість та чистоту!"
    },
    {
        type: "retail",
        url: "./images/shop/household_chemicals/means_for_cleaning/universal/gut_gunstig_allzweckreiniger_bergfrische.jpg",
        alt: "gut_gunstig_allzweckreiniger_bergfrische",
        url1: "./images/shop/household_chemicals/means_for_cleaning/universal/gut_gunstig_allzweckreiniger_bergfrische-01.jpg",
        alt1: "gut_gunstig_allzweckreiniger_bergfrische-01",
        url2: "./images/shop/household_chemicals/means_for_cleaning/universal/gut_gunstig_allzweckreiniger_bergfrische-02.jpg",
        alt2: "gut_gunstig_allzweckreiniger_bergfrische-02",
        marker: "MCU350",
        brand: "Gut & Günstig",
        search: "гуд гут гунстиг гунстіг Gut & Gunstig едека эдека для кухни кухні кухня ванной комнаті ванної кімнати универсальний универсальное средство средства для чистки засоби для чищення для підлоги пола горная весна",
        nameUKR: "Універсальний засіб для чищення (гірська весна)",
        nameEN: "Allzweckreiniger Bergfrische",
        companyName: "Edeka",
        countryName: "Німеччина",
        volumeName: "Об'єм",
        volume: "1 л.",
        priceGRN: 84,
        quantityOnStorage: 7,
        description01: "&#171Gut Günstig - Allzweckreiniger Bergfrische&#187 - це універсальний засіб для прибирання, який привносить свіжість гірських вершин у Ваш дім. З його допомогою легко і швидко можна очистити різні поверхні, забезпечивши бездоганну чистоту.",
        description02: "Засіб ефективно бореться з жиром, забрудненням і бактеріями, залишаючи поверхні блискучими і з приємним ароматом. Він має спеціальну формулу, яка забезпечує гігієнічну чистоту і захист від мікробів.",
        description03: "&#171Gut Günstig - Allzweckreiniger Bergfrische&#187 має неповторний аромат свіжості гірських долин, що створює приємну атмосферу у Вашому домі. Він ідеально підходить для прибирання різних поверхонь, включаючи підлоги, столи, ванні кімнати та кухні.",
        description04: "<strong>Універсальний засіб для чищення. Аромат: гірська весна.</strong>",
        description05: "Зробіть прибирання легким з &#171Gut Günstig - Allzweckreiniger Bergfrische&#187, який забезпечить Вашому дому бездоганну чистоту і освіжаючий аромат гірських вершин."
    },
    {
        type: "retail",
        url: "./images/shop/household_chemicals/means_for_cleaning/universal/ja!_allzweckreiniger_lemon.jpg",
        alt: "ja!_allzweckreiniger_lemon",
        url1: "./images/shop/household_chemicals/means_for_cleaning/universal/ja!_allzweckreiniger_lemon-01.jpg",
        alt1: "ja!_allzweckreiniger_lemon-01",
        url2: "./images/shop/household_chemicals/means_for_cleaning/universal/ja!_allzweckreiniger_lemon-02.jpg",
        alt2: "ja!_allzweckreiniger_lemon-02",
        marker: "MCU400",
        brand: "Ja!",
        search: "реве для кухни кухні кухня ванной комнаті ванної кімнати универсальний универсальное средство средства для чистки засоби для чищення для підлоги пола лимон",
        nameUKR: "Універсальний засіб для чищення з ароматом лимону",
        nameEN: "Allzweckreiniger Lemon",
        companyName: "REWE Group",
        countryName: "Німеччина",
        volumeName: "Об'єм",
        volume: "1 л.",
        priceGRN: 78,
        quantityOnStorage: 1,
        description01: "&#171Ja! - Allzweckreiniger Lemon&#187 - це енергія свіжості, яка дарує яскраві емоції під час прибирання. Цей універсальний засіб створений, щоб легко справлятися з будь-якими забрудненнями і плямами на різних поверхнях.",
        description02: "Його освіжаючий аромат лимона наповнить Ваш дім бадьорістю і позитивним настроєм.",
        description03: "&#171Ja! - Allzweckreiniger Lemon&#187 має потужну дію у боротьбі з бактеріями і грибками, забезпечуючи чистоту та гігієну Вашого простору. Цей засіб ефективний, а водночас економічний у використанні, завдяки чому його вистачить на довгий час.",
        description04: "<strong>Універсальний засіб для чищення. Не для поверхонь з відкритими порами. Аромат: лимон.</strong>",
        description05: "Виберіть яскравість та свіжість для свого дому з &#171Ja! - Allzweckreiniger Lemon&#187 і насолоджуйся неймовірно чистою і ароматною атмосферою."
    },
    {
        type: "retail",
        url: "./images/shop/household_chemicals/means_for_cleaning/universal/ja!_allzweckreiniger_ocean.jpg",
        alt: "ja!_allzweckreiniger_ocean",
        url1: "./images/shop/household_chemicals/means_for_cleaning/universal/ja!_allzweckreiniger_ocean-01.jpg",
        alt1: "ja!_allzweckreiniger_ocean-01",
        url2: "./images/shop/household_chemicals/means_for_cleaning/universal/ja!_allzweckreiniger_ocean-02.jpg",
        alt2: "ja!_allzweckreiniger_ocean-02",
        marker: "MCU405",
        brand: "Ja!",
        search: "реве для кухни кухні кухня ванной комнаті ванної кімнати универсальний универсальное средство средства для чистки засоби для чищення для підлоги пола",
        nameUKR: "Універсальний засіб для чищення з ароматом океану",
        nameEN: "Allzweckreiniger Ocean",
        companyName: "REWE Group",
        countryName: "Німеччина",
        volumeName: "Об'єм",
        volume: "1 л.",
        priceGRN: 78,
        quantityOnStorage: 12,
        description01: "&#171Ja! - Allzweckreiniger Ocean&#187 - це свіжість океану, яка здатна оживити Ваш дім і створити атмосферу чистоти та комфорту. Цей універсальний засіб приносить бадьорий аромат океану прямо до Вашої кухні або ванної кімнати.",
        description02: "Завдяки потужній формулі, &#171Ja! - Allzweckreiniger Ocean&#187 легко справляється зі всіма типами забруднень, залишаючи поверхні бездоганно чистими. Цей засіб ефективний і економічний у використанні, забезпечуючи тривалий термін служби.",
        description03: "Вирушайте у подорож до далеких морських просторів під час прибирання та дозвольте оживити свіжість природи у Вашому домі.",
        description04: "<strong>Універсальний засіб для чищення. Не для поверхонь з відкритими порами. Аромат: океан.</strong>",
        description05: "Звільніть себе від турботи про прибирання і насолоджуйтесь свіжістю океану з &#171Ja! - Allzweckreiniger Ocean&#187, який дарує Вашому дому неперевершений аромат і бездоганну чистоту."
    },
    {
        type: "retail",
        url: "./images/shop/household_chemicals/means_for_cleaning/universal/k-classic_allesreiniger_fresh_breeze.jpg",
        alt: "k-classic_allesreiniger_fresh_breeze",
        url1: "./images/shop/household_chemicals/means_for_cleaning/universal/k-classic_allesreiniger_fresh_breeze-01.jpg",
        alt1: "k-classic_allesreiniger_fresh_breeze-01",
        url2: "./images/shop/household_chemicals/means_for_cleaning/universal/k-classic_allesreiniger_fresh_breeze-02.jpg",
        alt2: "k-classic_allesreiniger_fresh_breeze-02",
        marker: "MCU450",
        brand: "K-Classic",
        search: "класик классик класік классік кауфланд для кухни кухні кухня ванной комнаті ванної кімнати универсальний универсальное средство средства для чистки засоби для чищення для підлоги пола свежий бриз",
        nameUKR: "Універсальний засіб для чищення (свіжий бриз)",
        nameEN: "Allesreiniger Fresh Breeze",
        companyName: "Kaufland",
        countryName: "Німеччина",
        volumeName: "Об'єм",
        volume: "1.1 л.",
        priceGRN: 73,
        quantityOnStorage: 3,
        description01: "&#171K-Classic - Allesreiniger Fresh Breeze&#187 - це супер універсальний засіб для прибирання, який подарує Вашому дому освіжаючий аромат свіжого бризу. З його допомогою ви легко і ефективно очистите всі поверхні, забезпечивши ідеальну чистоту.",
        description02: "Цей засіб справляється з різноманітними забрудненнями, жиром і бактеріями, гарантуючи чистоту та гігієну у Вашому домі. Його спеціальна формула дозволяє швидко і легко прибрати все, що потрібно.",
        description03: "&#171K-Classic - Allesreiniger Fresh Breeze&#187 має приємний аромат свіжого бризу, який створить чудову атмосферу в Вашому домі. Він ідеально підходить для прибирання кухні, ванної кімнати, підлоги та багатьох інших поверхонь.",
        description04: "<strong>Універсальний засіб для чищення. Аромат: свіжий бриз.</strong>",
        description05: "Зробіть прибирання простим та приємним разом з &#171K-Classic - Allesreiniger Fresh Breeze&#187, який забезпечить Вашому дому ідеальну чистоту та свіжість."
    },
    {
        type: "retail",
        url: "./images/shop/household_chemicals/means_for_cleaning/universal/k-classic_allesreiniger_lemon_fresh.jpg",
        alt: "k-classic_allesreiniger_lemon_fresh",
        url1: "./images/shop/household_chemicals/means_for_cleaning/universal/k-classic_allesreiniger_lemon_fresh-01.jpg",
        alt1: "k-classic_allesreiniger_lemon_fresh-01",
        url2: "./images/shop/household_chemicals/means_for_cleaning/universal/k-classic_allesreiniger_lemon_fresh-02.jpg",
        alt2: "k-classic_allesreiniger_lemon_fresh-02",
        marker: "MCU455",
        brand: "K-Classic",
        search: "класик классик класік классік кауфланд для кухни кухні кухня ванной комнаті ванної кімнати универсальний универсальное средство средства для чистки засоби для чищення для підлоги пола свежесть лимона",
        nameUKR: "Універсальний засіб для чищення (свіжіть лимону)",
        nameEN: "Allesreiniger Lemon Fresh",
        companyName: "Kaufland",
        countryName: "Німеччина",
        volumeName: "Об'єм",
        volume: "1.1 л.",
        priceGRN: 73,
        quantityOnStorage: 5,
        description01: "&#171K-Classic - Allesreiniger Lemon Fresh&#187 - це універсальний засіб для прибирання з освіжаючим ароматом лимона. Його потужна формула допоможе легко і швидко очистити різні поверхні, залишаючи їх блискучими і свіжими.",
        description02: "Засіб ефективно знімає жир, забруднення і бактерії, гарантуючи бездоганну чистоту Вашого дому. Його універсальність дозволяє використовувати його на кухні, у ванній кімнаті, на підлозі та інших поверхнях.",
        description03: "&#171K-Classic - Allesreiniger Lemon Fresh&#187 має приємний і натуральний аромат лимона, який створить свіжу та приємну атмосферу у Вашому домі. Він ідеально підходить для повсякденного прибирання і забезпечить чистоту та комфорт у Вашій оселі.",
        description04: "<strong>Універсальний засіб для чищення. Аромат: лимон.</strong>",
        description05: "Робіть прибирання легким та приємним разом з &#171K-Classic - Allesreiniger Lemon Fresh&#187, щоб Ваш дім завжди блищав чистотою і свіжістю."
    },
    {
        type: "retail",
        url: "./images/shop/household_chemicals/means_for_cleaning/universal/k-classic_allesreiniger_tropical_flower.jpg",
        alt: "k-classic_allesreiniger_tropical_flower",
        url1: "./images/shop/household_chemicals/means_for_cleaning/universal/k-classic_allesreiniger_tropical_flower-01.jpg",
        alt1: "k-classic_allesreiniger_tropical_flower-01",
        url2: "./images/shop/household_chemicals/means_for_cleaning/universal/k-classic_allesreiniger_tropical_flower-02.jpg",
        alt2: "k-classic_allesreiniger_tropical_flower-02",
        marker: "MCU460",
        brand: "K-Classic",
        search: "класик классик класік классік кауфланд для кухни кухні кухня ванной комнаті ванної кімнати универсальний универсальное средство средства для чистки засоби для чищення для підлоги пола тропический цветок квіти цветы",
        nameUKR: "Універсальний засіб для чищення (тропічна квітка)",
        nameEN: "Allesreiniger Tropical Flower",
        companyName: "Kaufland",
        countryName: "Німеччина",
        volumeName: "Об'єм",
        volume: "1.1 л.",
        priceGRN: 73,
        quantityOnStorage: 5,
        description01: "&#171K-Classic - Allesreiniger Tropical Flower&#187 - це універсальний засіб для прибирання з екзотичним ароматом тропічного квіткового саду. Він ефективно видаляє жир, бруд та бактерії з різних поверхонь, залишаючи їх чистими і свіжими.",
        description02: "Цей засіб має потужну формулу, що допомагає легко і швидко впоратися з різноманітними забрудненнями, забезпечуючи бездоганну чистоту у Вашому домі.",
        description03: "&#171K-Classic - Allesreiniger Tropical Flower&#187 має приємний аромат тропічних квітів, який створить приємну атмосферу і освіжить Ваш дім. Цей засіб ідеально підходить для прибирання на кухні, у ванній кімнаті, на підлозі та інших поверхнях.",
        description04: "<strong>Універсальний засіб для чищення. Аромат: тропічна квітка.</strong>",
        description05: "Зробіть прибирання приємною насолодою разом з &#171K-Classic - Allesreiniger Tropical Flower&#187, який подарує Вашому дому чистоту і аромат тропічного райського саду."
    },
    {
        type: "wholesale",
        url: "./images/shop/household_chemicals/means_for_cleaning/for_wc/la_salud_wc_cerezo_1l.jpg",
        alt: "la_salud_wc_cerezo_1l",
        url1: "./images/shop/household_chemicals/means_for_cleaning/for_wc/la_salud_wc_cerezo_1l-01.jpg",
        alt1: "la_salud_wc_cerezo_1l-01",
        url2: "./images/shop/household_chemicals/means_for_cleaning/for_wc/la_salud_wc_cerezo_1l-02.jpg",
        alt2: "la_salud_wc_cerezo_1l-02",
        marker: "LDWC505",
        brand: "La Salud",
        search: "ла салуд средство для чистки чищення чистка забоси стредства туалет для туалета унитаз для унитаза унітаз для унітаза унітазу вишня",
        nameUKR: "Засіб для чищення туалету (вишневий цвіт)",
        nameEN: "Gel WC Flor De Cerezo",
        companyName: "Inquivisa",
        countryName: "Іспанія",
        volumeName: "Об'єм",
        volume: "1 л.",
        priceGRN: 122,
        priceGRNOpt: 110,
        description01: "Шукаєте ідеальний засіб для чистоти вашого туалету? Зустрічайте &#171La Salud - Gel WC Flor De Cerezo&#187!",
        description02: "Цей засіб не тільки ефективно очищує туалет, але й залишає приємний аромат вишневого цвіту. Його гелева формула проникає у важкодоступні місця, забезпечуючи ідеальну чистоту.",
        description03: "З &#171La Salud - Gel WC Flor De Cerezo&#187 Ваш туалет завжди буде свіжим і чистим. Насолоджуйтесь ароматом вишневого цвіту після кожного використання, забувши про неприємні запахи та бактерії.",
        description04: "<strong>Засіб для чищення унітазу. Аромат: вишневий цвіт.</strong>",
        description05: "Придбайте La Salud - Gel WC Flor De Cerezo&#171La Salud - Gel WC Flor De Cerezo&#187 вже сьогодні та подаруйте своєму туалету неперевершену чистоту і свіжість!"
    },
    {
        type: "wholesale",
        url: "./images/shop/household_chemicals/means_for_cleaning/for_wc/la_salud_wc_ocean_1l.jpg",
        alt: "la_salud_wc_ocean_1l",
        url1: "./images/shop/household_chemicals/means_for_cleaning/for_wc/la_salud_wc_ocean_1l-01.jpg",
        alt1: "la_salud_wc_ocean_1l-01",
        url2: "./images/shop/household_chemicals/means_for_cleaning/for_wc/la_salud_wc_ocean_1l-02.jpg",
        alt2: "la_salud_wc_ocean_1l-02",
        marker: "LDWC510",
        brand: "La Salud",
        search: "ла салуд средство для чистки чищення чистка забоси стредства туалет для туалета унитаз для унитаза унітаз для унітаза унітазу",
        nameUKR: "Засіб для чищення туалету (океан)",
        nameEN: "Gel WC Ocean",
        companyName: "Inquivisa",
        countryName: "Іспанія",
        volumeName: "Об'єм",
        volume: "1 л.",
        priceGRN: 122,
        priceGRNOpt: 110,
        description01: "Хочете, щоб ваш туалет був ідеально чистим та свіжим? Спробуйте &#171La Salud - Gel WC Ocean&#187!",
        description02: "Цей гель забезпечує глибоке очищення, видаляючи навіть найстійкіший бруд і залишаючи приємний аромат океанської свіжості. Його інноваційна формула проникає у важкодоступні місця, гарантуючи повну гігієну.",
        description03: "З &#171La Salud - Gel WC Ocean& Ваш туалет буде сяяти чистотою, а аромат свіжого океану створить атмосферу свіжості та чистоти на довгий час. Забудьте про неприємні запахи та бактерії!",
        description04: "<strong>Засіб для чищення унітазу. Аромат: океан.</strong>",
        description05: "Придбайте  &#171La Salud - Gel WC Ocean& вже сьогодні та насолоджуйтесь бездоганною чистотою і свіжістю вашого туалету!"
    },
    {
        type: "wholesale",
        url: "./images/shop/household_chemicals/means_for_cleaning/for_wc/la_salud_wc_oxi_eucalipto_1l.jpg",
        alt: "la_salud_wc_oxi_eucalipto_1l",
        url1: "./images/shop/household_chemicals/means_for_cleaning/for_wc/la_salud_wc_oxi_eucalipto_1l-01.jpg",
        alt1: "la_salud_wc_oxi_eucalipto_1l-01",
        url2: "./images/shop/household_chemicals/means_for_cleaning/for_wc/la_salud_wc_oxi_eucalipto_1l-02.jpg",
        alt2: "la_salud_wc_oxi_eucalipto_1l-02",
        marker: "LDWC515",
        brand: "La Salud",
        search: "ла салуд средство для чистки чищення чистка забоси стредства туалет для туалета унитаз для унитаза унітаз для унітаза унітазу відбілювачі отбеливатель отбеливатели эвкалипт с эвкалиптом с активным кислородом активный кислород",
        nameUKR: "Засіб для чищення туалету з активнем киснем, відбілювач (евкаліпт)",
        nameEN: "Oxi Active Eucalipto",
        companyName: "Inquivisa",
        countryName: "Іспанія",
        volumeName: "Об'єм",
        volume: "1 л.",
        priceGRN: 122,
        priceGRNOpt: 110,
        description01: "Забудьте про труднощі з усуненням бруду - &#171La Salud - Oxi Active Eucalipto&#187 гарантує ефективну чистоту і свіжість.",
        description02: "Завдяки активному кисню та евкаліптовому аромату він проникає глибоко у забруднення, легко видаляються, та залишає приємний аромат у Вашому туалеті.",
        description03: "Прагнете мати ідеально чистий та свіжий туалет з мінімальними зусиллями?  &#171La Salud - Oxi Active Eucalipto&#187 перетворює Ваші мрії у реальність, надаючи неймовірну чистоту та захищаючи від неприємних запахів.",
        description04: "<strong>Засіб для чищення унітазу з активним киснем. Аромат: евкаліпт. Містить відбілювач.</strong>",
        description05: "Очистіть свій туалет швидко та ефективно з &#171La Salud - Oxi Active Eucalipto&#187 - Ваш ключ до бездоганної чистоти та свіжості!"
    },
    {
        type: "wholesale",
        url: "./images/shop/household_chemicals/means_for_cleaning/for_wc/la_salud_wc_pine_1l.jpg",
        alt: "la_salud_wc_pine_1l",
        url1: "./images/shop/household_chemicals/means_for_cleaning/for_wc/la_salud_wc_pine_1l-01.jpg",
        alt1: "la_salud_wc_pine_1l-01",
        url2: "./images/shop/household_chemicals/means_for_cleaning/for_wc/la_salud_wc_pine_1l-02.jpg",
        alt2: "la_salud_wc_pine_1l-02",
        marker: "LDWC520",
        brand: "La Salud",
        search: "ла салуд средство для чистки чищення чистка забоси стредства туалет для туалета унитаз для унитаза унітаз для унітаза унітазу",
        nameUKR: "Засіб для чищення туалету (сосна)",
        nameEN: "Gel WC Pino",
        companyName: "Inquivisa",
        countryName: "Іспанія",
        volumeName: "Об'єм",
        volume: "1 л.",
        priceGRN: 122,
        priceGRNOpt: 110,
        description01: "Відкрийте для себе ідеальний засіб для чищення туалету з ароматом сосни &#171La Salud - Gel WC Pino&#187, потужна формула якого забезпечить неперевершену чистоту у Вашому туалеті.",
        description02: "Цей гель миттєво розподіляється по поверхні, неймовірно зручний у використанні і має приємний аромат сосни, який зробить Ваш туалет запашним та свіжим.",
        description03: "&#171La Salud - Gel WC Pino&#187 здійснить Ваші найсміливіші бажання, забезпечуючи не лише чистоту, але і приємний аромат.",
        description04: "<strong>Засіб для чищення унітазу. Аромат: сосна.</strong>",
        description05: "Очистіть свій туалет легко та швидко з &#171La Salud - Gel WC Pino&#187 - Ваш надійний помічник у боротьбі з брудом та запахами!"
    },
    {
        type: "retail",
        url: "./images/shop/household_chemicals/means_for_cleaning/universal/reinex_apfel_fresh.jpg",
        alt: "reinex_apfel_fresh",
        url1: "./images/shop/household_chemicals/means_for_cleaning/universal/reinex_apfel_fresh-01.jpg",
        alt1: "reinex_apfel_fresh-01",
        url2: "./images/shop/household_chemicals/means_for_cleaning/universal/reinex_apfel_fresh-02.jpg",
        alt2: "reinex_apfel_fresh-02",
        marker: "MCU700",
        brand: "Reinex",
        search: "рейнекс райнекс для кухни кухні кухня ванной комнаті ванної кімнати универсальний универсальное средство средства для чистки засоби для чищення для підлоги пола свежесть яблока яблоко яблуко",
        nameUKR: "Універсальний засіб для чищення (свіжість яблука)",
        nameEN: "Allzweckreiniger Apfel-Fresh",
        companyName: "Reinwx GmbH & Co.",
        countryName: "Німеччина",
        volumeName: "Об'єм",
        volume: "1 л.",
        priceGRN: 76,
        quantityOnStorage: 1,
        description01: "&#171Reinex - Allzweckreiniger Apfel-Fresh&#187 - це потужний універсальний засіб для прибирання з освіжаючим ароматом свіжих яблук. З його допомогою легко і швидко очистити різні поверхні в будинку, забезпечивши бездоганну чистоту.",
        description02: "Засіб ефективно впорається з жиром, забрудненням, слідами і бактеріями, залишаючи поверхні блискучими. Його спеціальна формула забезпечує гігієнічну чистоту і захист.",
        description03: "&#171Reinex - Allzweckreiniger Apfel-Fresh&#187 має натуральний аромат свіжих яблук, який створює атмосферу чистоти і свіжості у Вашому домі. Він ідеально підходить для різних поверхонь, таких як підлоги, столи, ванні кімнати та кухні.",
        description04: "<strong>Універсальний засіб для чищення. Аромат: свіжість яблука.</strong>",
        description05: "Зробіть прибирання легким та приємним з &#171Reinex - Allzweckreiniger Apfel-Fresh&#187, який надасть Вашому дому чистоту, свіжість та безпеку."
    },
    {
        type: "retail",
        url: "./images/shop/household_chemicals/means_for_cleaning/universal/respekt_allzweckreiniger_sommertraum.jpg",
        alt: "respekt_allzweckreiniger_sommertraum",
        url1: "./images/shop/household_chemicals/means_for_cleaning/universal/respekt_allzweckreiniger_sommertraum-01.jpg",
        alt1: "respekt_allzweckreiniger_sommertraum-01",
        url2: "./images/shop/household_chemicals/means_for_cleaning/universal/respekt_allzweckreiniger_sommertraum-02.jpg",
        alt2: "respekt_allzweckreiniger_sommertraum-02",
        marker: "MCU720",
        brand: "Respekt",
        search: "респект для кухни кухні кухня ванной комнаті ванної кімнати универсальний универсальное средство средства для чистки засоби для чищення для підлоги пола летняя мечта эколокический",
        nameUKR: "Екологічний універсальний засіб для чищення (літня мрія)",
        nameEN: "Allzweckreiniger Sommertraum",
        companyName: "Edeka",
        countryName: "Німеччина",
        volumeName: "Об'єм",
        volume: "1 л.",
        priceGRN: 99,
        quantityOnStorage: 3,
        description01: "&#171Respekt - Allzweckreiniger Sommertraum&#187 - це чудовий універсальний засіб, який перенесе вас у світ свіжості і літнього настрою. З його допомогою легко очистити різні поверхні в Вашому домі, забезпечивши бездоганну чистоту і приємний аромат.",
        description02: "Засіб ефективно впорається з жиром, забрудненням і бактеріями, залишаючи поверхні блискучими і свіжими. Він має спеціальну формулу, яка забезпечує гігієнічну чистоту і захист від бактерій.",
        description03: "&#171Respekt - Allzweckreiniger Sommertraum&#187 має аромат літнього настрою, що створює приємну атмосферу у Вашому домі. Він ідеально підходить для прибирання різних поверхонь, включаючи підлоги, столи, ванні кімнати та кухні.",
        description04: "<strong>Універсальний засіб для чищення. Аромат: літня мрія.</strong>",
        description05: "Зробіть прибирання легким і приємним разом з &#171Respekt - Allzweckreiniger Sommertraum&#187, який забезпечить Вашому дому бездоганну чистоту і свіжість."
    },
]