export const shopLotsNoodles = [
    // {
    //     type: "retail",
    //     url: "./images/shop/food/pasta/noodles/barilla_tagliatelle_16_500.jpg",
    //     alt: "barilla_tagliatelle_16_500",
    //     url1: "./images/shop/food/pasta/noodles/barilla_tagliatelle_16_500-01.jpg",
    //     alt1: "barilla_tagliatelle_16_500-01",
    //     url2: "./images/shop/food/pasta/noodles/barilla_tagliatelle_16_500-02.jpg",
    //     alt2: "barilla_tagliatelle_16_500-02",
    //     url3: "./images/shop/food/pasta/noodles/barilla_tagliatelle_16_500-03.jpg",
    //     alt3: "barilla_tagliatelle_16_500-03",
    //     url4: "./images/shop/food/pasta/noodles/barilla_tagliatelle_16_500-04.jpg",
    //     alt4: "barilla_tagliatelle_16_500-04",
    //     url5: "./images/shop/food/pasta/noodles/barilla_tagliatelle_16_500-05.jpg",
    //     alt5: "barilla_tagliatelle_16_500-05",
    //     url6: "./images/shop/food/pasta/noodles/barilla_tagliatelle_16_500-06.jpg",
    //     alt6: "barilla_tagliatelle_16_500-06",
    //     marker: "FDNO030",
    //     brand: "Barilla",
    //     search: "барила барилла баріла барілла лапша таглиателе таглиателле тагліателе тагліаталле 16 твердый твердий сорт тверді сорта твердые сорта с твердых сортов",
    //     nameUKR: "Локшина з твердих сортів",
    //     nameEN: "Tagliatelle №16",
    //     companyName: "Barilla G. e R.",
    //     countryName: "Італія",
    //     weightName: "Вага",
    //     weight: "500 гр.",
    //     priceGRN: 97,
    //     quantityOnStorage: "7",
    //     description01: "&#171Barilla - Tagliatelle №16&#187 - це справжній шедевр італійського мистецтва приготування макаронів. Ця довга, тонка локшина виготовлена з відбірної пшениці, що надає їй неповторний смак і стійкість під час готування.",
    //     description02: "Ця локшина чудово поєднується з різноманітними соусами - від класичного песто до вершкового з лососем, відкриваючи безмежжя смакових можливостей.",
    //     description03: "&#171Barilla - Tagliatelle №16&#187 створені для того, щоб Ви могли насолодитися справжньою італійською кухнею у затишку свого дому.",
    //     description04: "<strong>Локшина з твердих сортів пшениці.</strong>",
    //     description05: "Подаруйте собі смак Італії, замовивши &#171Barilla - Tagliatelle №16&#187 вже сьогодні!"
    // },
    {
        type: "wholesale",
        url: "./images/shop/food/pasta/noodles/pasta_reggia_fettuce_500.jpg",
        alt: "pasta_reggia_fettuce_500",
        url1: "./images/shop/food/pasta/noodles/pasta_reggia_fettuce_500-01.jpg",
        alt1: "pasta_reggia_fettuce_500-01",
        url2: "./images/shop/food/pasta/noodles/pasta_reggia_fettuce_500-02.jpg",
        alt2: "pasta_reggia_fettuce_500-02",
        url3: "./images/shop/food/pasta/noodles/pasta_reggia_fettuce_500-03.jpg",
        alt3: "pasta_reggia_fettuce_500-03",
        url4: "./images/shop/food/pasta/noodles/pasta_reggia_fettuce_500-04.jpg",
        alt4: "pasta_reggia_fettuce_500-04",
        marker: "FDNO505",
        brand: "Pasta Reggia",
        search: "паста реггіа регіа реггія регія реггиа региа реггия регия феттучче фетуче 615 лапша твердый твердий сорт тверді сорта твердые сорта с твердых сортов",
        nameUKR: "Локшина з твердих сортів",
        nameEN: "Fettucce №615",
        companyName: "P.A.P. sri",
        countryName: "Італія",
        weightName: "Вага",
        weight: "500 гр.",
        priceGRN: 84,
        priceGRNOpt: 77,
        description01: "Відкрийте для себе найвищий стандарт якості з локшею &#171Pasta Reggia - Fettucce №615&#187.",
        description02: "Це вишукана локшинa, здатна додати розкіш і смак будь-якому обіду чи вечері.",
        description03: "Насолоджуйтеся розкішними кульками смаку &#171Pasta Reggia - Fettucce №615&#187, завдяки яким Ви знову і знову будете повертатися до цього неперевершеного джерела задоволення.",
        description04: "<strong>Локшина з твердих сортів пшениці.</strong>",
        description05: "Придбайте &#171Pasta Reggia - Fettucce №615&#187 вже зараз і відчуйте аутентичний смак італійської кухні у кожному шматочку!"
    },
]