export const shopLotsCacao = [
  {
    type: "only-wholesale оптом",
    mainCategory: "foodstuffs",
    subcategory: "drinks",
    url: "./images/shop/food/drinks/cacao/kruger_mixfix_150.jpg",
    alt: "kruger_mixfix_150",
    marker: "FDCC040",
    brand: "Krüger",
    search: "kruger крюгер какао миксфикс микс фикс міксфікс мікс фікс",
    nameUKR: "Какао",
    nameEN: "MixFix",
    companyName: "Krüger Polska Sp.",
    countryName: "Польща",
    weightName: "Вага",
    weight: "150 гр.",
    priceGRN: "--",
    priceGRNOpt: 110,
    description01: "&#171Krüger - MixFix&#187 - це справжнє джерело радості для маленьких гурманів. Цей какао-напій розроблений спеціально для дітей і має ніжний солодкий смак, який припаде до смаку навіть найвибагливішим малятам.",
    description02: "Прекрасна комбінація какао та молока, яка миттєво розчиняється у гарячій воді або молоці, створюючи ароматний і смачний напій. Цей продукт не містить шкідливих барвників і консервантів, що робить його безпечним для дітей.",
    description03: "Крім того, &#171Krüger - MixFix&#187 збагачений вітамінами та мінералами, які підтримують здоров'я і рост малюка. Він стане чудовим способом пожвавити дитячий ранок або створити атмосферу тепла та затишку перед сном.",
    description04: "<strong>Без шкідливих барвників та концерогенів.</strong>",
    description05: "Зробіть радість своєму малюкові і подаруйте йому найсмачніше дитяче какао &#171Krüger - MixFix&#187!"
  },
  {
    type: "only-wholesale оптом",
    mainCategory: "foodstuffs",
    subcategory: "drinks",
    url: "./images/shop/food/drinks/cacao/kruger_mixfix_375.jpg",
    alt: "kruger_mixfix_375",
    url1: "./images/shop/food/drinks/cacao/kruger_mixfix_375-01.jpg",
    alt1: "kruger_mixfix_375-01",
    url2: "./images/shop/food/drinks/cacao/kruger_mixfix_375-02.jpg",
    alt2: "kruger_mixfix_375-02",
    url3: "./images/shop/food/drinks/cacao/kruger_mixfix_375-03.jpg",
    alt3: "kruger_mixfix_375-03",
    url4: "./images/shop/food/drinks/cacao/kruger_mixfix_375-04.jpg",
    alt4: "kruger_mixfix_375-04",
    marker: "FDCC410",
    brand: "Krüger",
    search: "kruger крюгер какао миксфикс микс фикс міксфікс мікс фікс",
    nameUKR: "Какао",
    nameEN: "MixFix",
    companyName: "Krüger Polska Sp.",
    countryName: "Польща",
    weightName: "Вага",
    weight: "375 гр.",
    priceGRN: "--",
    priceGRNOpt: 153,
    description01: "&#171Krüger - MixFix&#187 - це справжнє джерело радості для маленьких гурманів. Цей какао-напій розроблений спеціально для дітей і має ніжний солодкий смак, який припаде до смаку навіть найвибагливішим малятам.",
    description02: "Прекрасна комбінація какао та молока, яка миттєво розчиняється у гарячій воді або молоці, створюючи ароматний і смачний напій. Цей продукт не містить шкідливих барвників і консервантів, що робить його безпечним для дітей.",
    description03: "Крім того, &#171Krüger - MixFix&#187 збагачений вітамінами та мінералами, які підтримують здоров'я і рост малюка. Він стане чудовим способом пожвавити дитячий ранок або створити атмосферу тепла та затишку перед сном.",
    description04: "<strong>Без шкідливих барвників та концерогенів.</strong>",
    description05: "Зробіть радість своєму малюкові і подаруйте йому найсмачніше дитяче какао &#171Krüger - MixFix&#187!"
  },
  {
    type: "retail",
    mainCategory: "foodstuffs",
    subcategory: "drinks",
    url: "./images/shop/food/drinks/cacao/kruger_mixfix_500.jpg",
    alt: "kruger_mixfix_500",
    url1: "./images/shop/food/drinks/cacao/kruger_mixfix_500-01.jpg",
    alt1: "kruger_mixfix_500-01",
    url2: "./images/shop/food/drinks/cacao/kruger_mixfix_500-02.jpg",
    alt2: "kruger_mixfix_500-02",
    marker: "FDCC420",
    brand: "Krüger",
    search: "kruger крюгер какао миксфикс микс фикс міксфікс мікс фікс",
    nameUKR: "Какао",
    nameEN: "MixFix",
    companyName: "Krüger Polska Sp.",
    countryName: "Польща",
    weightName: "Вага",
    weight: "500 гр.",
    priceGRN: 107,
    quantityOnStorage: 1,
    description01: "&#171Krüger - MixFix&#187 - це справжнє джерело радості для маленьких гурманів. Цей какао-напій розроблений спеціально для дітей і має ніжний солодкий смак, який припаде до смаку навіть найвибагливішим малятам.",
    description02: "Прекрасна комбінація какао та молока, яка миттєво розчиняється у гарячій воді або молоці, створюючи ароматний і смачний напій. Цей продукт не містить шкідливих барвників і консервантів, що робить його безпечним для дітей.",
    description03: "Крім того, &#171Krüger - MixFix&#187 збагачений вітамінами та мінералами, які підтримують здоров'я і рост малюка. Він стане чудовим способом пожвавити дитячий ранок або створити атмосферу тепла та затишку перед сном.",
    description04: "<strong>Без шкідливих барвників та концерогенів.</strong>",
    description05: "Зробіть радість своєму малюкові і подаруйте йому найсмачніше дитяче какао &#171Krüger - MixFix&#187!"
  },
  {
    type: "retail",
    mainCategory: "foodstuffs",
    subcategory: "drinks",
    url: "./images/shop/food/drinks/cacao/nesquik_classic_500.jpg",
    alt: "nesquik_classic_500",
    url1: "./images/shop/food/drinks/cacao/nesquik_classic_500-01.jpg",
    alt1: "nesquik_classic_500-01",
    url2: "./images/shop/food/drinks/cacao/nesquik_classic_500-02.jpg",
    alt2: "nesquik_classic_500-02",
    marker: "FDCC450",
    brand: "Nesquik",
    search: "нестле несквик несквік какао классик класик класік",
    nameUKR: "Какао",
    nameEN: "Classic",
    companyName: "Nestle",
    countryName: "Швейцарія",
    weightName: "Вага",
    weight: "500 гр.",
    priceGRN: 182,
    quantityOnStorage: 3,
    description01: "&#171Nestle - Nesquik Classic&#187 - це незамінний продукт для всієї родини, який додасть радість і користь до вашого ранку. Це справжнє шоколадне задоволення, яке легко розчиняється у молоці та надає йому неперевершений смак какао. Цей напій також багатий вітаміном D, необхідним для здоров'я кісток та імунної системи.",
    description02: "Він має солодкий смак та приємний аромат, які діти та дорослі обожнюють. Миттєво розчиняється у теплому або холодному молоці, створюючи ідеальний напій для сніданку, перекусу або просто для задоволення солодким смаком шоколаду у будь-який час.",
    description03: "Нехай ваші ранки стануть яскравішими і смачнішими з &#171;Nestle - Nesquik Classic&#187; та вітаміном D.",
    description04: "<strong>Без шкідливих барвників та концерогенів. Без глютену.</strong>",
    description05: "Замовляйте &#171Nestle - Nesquik Classic&#187 вже сьогодні та насолоджуйтесь найкращими моментами життя разом з вашою родиною!"
  },
  {
    type: "only-wholesale оптом",
    mainCategory: "foodstuffs",
    subcategory: "drinks",
    url: "./images/shop/food/drinks/cacao/nesquik_classic_700.jpg",
    alt: "nesquik_classic_700",
    url1: "./images/shop/food/drinks/cacao/nesquik_classic_700.jpg",
    alt1: "nesquik_classic_700",
    marker: "FDCC455",
    brand: "Nesquik",
    search: "нестле несквик несквік какао классик класик класік",
    nameUKR: "Какао",
    nameEN: "Classic",
    companyName: "Nestle",
    countryName: "Угорщина",
    weightName: "Вага",
    weight: "700 гр.",
    priceGRN: "--",
    priceGRNOpt: 290,
    description01: "&#171Nestle - Nesquik Classic&#187 - це незамінний продукт для всієї родини, який додасть радість і користь до вашого ранку. Це справжнє шоколадне задоволення, яке легко розчиняється у молоці та надає йому неперевершений смак какао. Цей напій також багатий вітаміном D, необхідним для здоров'я кісток та імунної системи.",
    description02: "Він має солодкий смак та приємний аромат, які діти та дорослі обожнюють. Миттєво розчиняється у теплому або холодному молоці, створюючи ідеальний напій для сніданку, перекусу або просто для задоволення солодким смаком шоколаду у будь-який час.",
    description03: "Нехай ваші ранки стануть яскравішими і смачнішими з &#171;Nestle - Nesquik Classic&#187; та вітаміном D.",
    description04: "<strong>Без шкідливих барвників та концерогенів.</strong>",
    description05: "Замовляйте &#171Nestle - Nesquik Classic&#187 вже сьогодні та насолоджуйтесь найкращими моментами життя разом з вашою родиною!"
  },
];