export const shopLotsMustard = [
    {
        type: "retail",
        url: "./images/shop/food/taste_modifier/mustard/madero_dijon_original_270.jpg",
        alt: "madero_dijon_original_270",
        marker: "MSRD300",
        brand: "Madero",
        search: "мадеро дижон діжон горчица оригінал оригинал без глютена",
        nameUKR: "Гірчиця",
        nameEN: "Musztarda Dijon",
        companyName: "Jeronimo Martins S.A.",
        countryName: "Польща",
        weightName: "Вага",
        weight: "270 гр.",
        priceGRN: 50,
        quantityOnStorage: "4",
        description01: "&#171Madero - Musztarda Dijon&#187 - це витончений дарунок для тих, хто цінує якість та смак у кожному приготуванні. Ця гірчиця без глютену розкриває справжній смак, додаючи неповторну пікантність та аромат вашим стравам.",
        description02: "Це синтез класичної рецептури та високоякісних інгредієнтів. Гладка текстура та насичений смак гірчиці створять ідеальний баланс для ваших улюблених страв.",
        description03: "&#171Madero - Musztarda Dijon&#187 - ідеальне рішення для людей з певними дієтичними обмеженнями, які не хочуть компромітувати смак.",
        description04: "<strong>Гірчиця, без глютену.</strong>",
        description05: "Запрошуємо Вас відкрити для себе світ гірчиці &#171Madero - Musztarda Dijon&#187, яка відзначається вишуканістю та смаковим багатством!"
    },
    {
        type: "retail",
        url: "./images/shop/food/taste_modifier/mustard/madero_francuska_270.jpg",
        alt: "madero_francuska_270",
        marker: "MSRD310",
        brand: "Madero",
        search: "мадеро французька французская француская горчица без глютена горох горошина в горошину",
        nameUKR: "Гірчиця",
        nameEN: "Musztarda Francuska",
        companyName: "Jeronimo Martins S.A.",
        countryName: "Польща",
        weightName: "Вага",
        weight: "270 гр.",
        priceGRN: 50,
        quantityOnStorage: "4",
        description01: "&#171Madero - Musztarda Francuska&#187 - справжній епіцентр неперевершеного смаку та вишуканості. Ця гірчиця без глютену розкриває перед Вами багатий аромат та характер класичної французької гірчиці, зберігаючи всі традиційні якості цього чудового продукту.",
        description02: "Вражає не тільки своїм вишуканим смаком, але й гладкістю консистенції. Тонка пікантність робить її ідеальним доповненням до різноманітних страв.",
        description03: "Щоб задовольнити потреби сучасного споживача, &#171Madero - Musztarda Francuska&#187 пропонує гірчицю без глютену, що особливо актуально для тих, хто дотримується специфічних дієтичних обмежень.",
        description04: "<strong>Гірчиця французька, без глютену.</strong>",
        description05: "Наважтеся розкрити перед собою багатий смаковий пейзаж, який надає стравам особливий шарм та витонченість разом з &#171Madero - Musztarda Francuska&#187!"
    },
]