export const shopLotsSalmon = [
    // {
    //     type: "only-wholesale оптом",
    //     mainCategory: "foodstuffs",
    //     subcategory: "conservation",
    //     url: "./images/shop/food/canned_food/salmon/m&k_losos_w_sosie_wlasnym_170.jpg",
    //     alt: "m&k_losos_w_sosie_wlasnym_170",
    //     url1: "./images/shop/food/canned_food/salmon/m&k_losos_w_sosie_wlasnym_170.jpg",
    //     alt1: "m&k_losos_w_sosie_wlasnym_170",
    //     marker: "SLMN400",
    //     brand: "M & K",
    //     search: "рыба в собственном соку риба losos w sosie wlasnym",
    //     nameUKR: "Лосось у власному соку",
    //     nameEN: "Łosoś W Sosie Własnym",
    //     companyName: "Kasprzyk SP. K.",
    //     countryName: "Польща",
    //     weightName: "Вага",
    //     weight: "170 гр.",
    //     priceGRN: "--",
    //     priceGRNOpt: 100,
    //     description01: "&#171M & K - Łosoś W Sosie Własnym&#187 - найкращимй та неперевершений лосось у власному соку, справжній діамант серед рибних дельікатесів.",
    //     description02: "Він вирізняється вишуканим поєднанням свіжості і смаку. Кожен кусочок насичений корисними речовинами, які роблять його ідеальним для здорового харчування.",
    //     description03: "Спробуйте &#171M & K - Łosoś W Sosie Własnym&#187 і Ви відчуєте той неповторний смак, що розцінює справжній гурман. Його ніжна консистенція та смакові властивості роблять його неперевершеним вибором для ваших насолод.",
    //     description04: "<strong>Лосось у власному соку, шматочками.</strong>",
    //     description05: "Замовте лосося у власному соку &#171M & K - Łosoś W Sosie Własnym&#187 зараз і відчуйте розкіш смаку рибних делікатесів!"
    // },
        {
        type: "wholesale оптом",
        mainCategory: "foodstuffs",
        subcategory: "conservation",       
        url: "./images/shop/food/canned_food/salmon/marinero_losos_tomato_150.jpg",
        alt: "marinero_losos_tomato_150",
        url1: "./images/shop/food/canned_food/salmon/marinero_losos_tomato_150-01.jpg",
        alt1: "marinero_losos_tomato_150-01",
        url2: "./images/shop/food/canned_food/salmon/marinero_losos_tomato_150-02.jpg",
        alt2: "marinero_losos_tomato_150-02",
        url3: "./images/shop/food/canned_food/salmon/marinero_losos_tomato_150-03.jpg",
        alt3: "marinero_losos_tomato_150-03",
        url4: "./images/shop/food/canned_food/salmon/marinero_losos_tomato_150-04.jpg",
        alt4: "marinero_losos_tomato_150-04",
        marker: "SLMN450",
        brand: "Marinero",
        search: "losos kawalki маринеро марінеро томат томати помидор помидоры помідор помідори соус соусы рыба риба losos kawalki в томатном соусе кусочками кусками",
        nameUKR: "Лосось у томатному соусі (шматочки)",
        nameEN: "Łosoś Kawałki W Sosie Pomidorowym",
        companyName: "Jeronimo Martins S.A.",
        countryName: "Польща",
        weightName: "Вага",
        weight: "150 гр.",
        priceGRN: 95,
        priceGRNOpt: 86,
        description01: "&#171Marinero - Łosoś Kawałki&#187 вражають своєю свіжістю та ніжністю, надаючи вашому столу смакове розмаїття.",
        description02: "Це ідеальне поєднання смаку та користі для вашого організму. Вони багаті Омега-3 кислотами та білками, забезпечуючи Вас енергію та підтримуючи здоров'я серця. Виготовлені з любов'ю, вони стануть гідним доповненням вашого раціону.",
        description03: "Кожен шматочок ретельно відбирається та піддається дбайливій обробці, щоб зберегти його природний смак та користь. Довірте свій вибір професіоналам смаку - обирайте &#171Marinero - Łosoś Kawałki&#187.",
        description04: "<strong>Лосось у томатному соусі, шматочками.</strong>",
        description05: "Спробуйте &#171Marinero - Łosoś Kawałki&#187 і зануртеся у світ смаку та задоволення!"
    },
]