export const shopLotsCheese = [
    {
        type: "wholesale",
        url: "./images/shop/food/dairy/cheese/g_g_gouda_mittelalt_450.jpg",
        alt: "g_g_gouda_mittelalt_450",
        marker: "FDEE020",
        brand: "Gut & Günstig",
        search: "эдека едека гут гунстиг гюнстиг гунстіг гюнстіг гоуда сыр мягкие сыры м'який мягкий сир м'які сири",
        nameUKR: "Молочний сир",
        nameEN: "Gouda 48% Fett",
        companyName: "Edeka",
        countryName: "Німеччина",
        weightName: "Вага",
        weight: "450 гр.",
        priceGRN: 130,
        priceGRNOpt: 119,
        description01: "&#171Gut & Günstig - Gouda 48% Fett&#187 - ідеально збалансований смак, ніжна текстура і аромат. Виготовлений із найкращих інгредієнтів, цей сир гарантує найвищу якість та смак.",
        description02: "Цей сир - вибір для кулінарних шедеврів та смачних сендвічів. Його ніжний смак і аромат створюють гастрономічні враження, які залишаються у пам'яті. Ви можете його подавати на святковому столі або в кожноденному меню - цей сир завжди додає шарму.",
        description03: "&#171Gut & Günstig - Gouda 48% Fett&#187 має найвищу якість та відповідає найвищим стандартам сиру.",
        description04: "<strong>Сир молочний. 48% жиру. Мінімальна витримка - 16 тижнів.</strong>",
        description05: "Не вагайтесь, спробуйте &#171Gut & Günstig - Gouda 48% Fett&#187 і насолоджуйтесь неперевершеним смаком. Переконайтеся самі у його чудовому смаку та якості!"
    },
    {
        type: "retail",
        url: "./images/shop/food/dairy/cheese/mlekivita_brie_classic_125.jpg",
        alt: "mlekivita_brie_classic_125",
        marker: "FDEE060",
        brand: "Mlekovita",
        search: "млековита млековіта бри брі сыр с плесенью плесень пліснява мягкие сыры м'який мягкий сир м'які сири классичний класичний классік класік классический класический классик класик",
        nameUKR: "Cир з пліснявою",
        nameEN: "Brie Classic",
        companyName: "SM Mlekovita",
        countryName: "Польща",
        weightName: "Вага",
        weight: "125 гр.",
        priceGRN: 57,
        quantityOnStorage: "11",
        description01: "&#171Mlekovita - Brie Classic&#187 - це вишуканий сир з пліснявою, що дарує неповторний смак. Цей сир має ніжну текстуру та гладку корку, яка робить його ідеальним для сервірування на столі. Він гарантує найвищу якість та смак.",
        description02: "Це ідеальний вибір для справжніх цінителів сиру. Його ніжний смак і неперевершена м'якість роблять його ідеальним додатком до смачних закусок, сендвічів або сирних тарілок. Цей сир може бути частиною вашого щоденного задоволення або особливого святкування.",
        description03: "Завдяки своїй унікальній якості та аромату, &#171Mlekovita - Brie Classic&#187 може перетворити будь-яку звичайну страву у шедевр.",
        description04: "<strong>Сир м'який, з пліснявою.</strong>",
        description05: "Приготуйте вишукані страви або просто насолоджуйтеся ніжністю &#171Mlekovita - Brie Classic&#187 на хлібі!"
    },
    {
        type: "retail",
        url: "./images/shop/food/dairy/cheese/mlekivita_camembert_classic_120.jpg",
        alt: "mlekivita_camembert_classic_120",
        marker: "FDEE070",
        brand: "Mlekovita",
        search: "млековита млековіта камемберт сыр с плесенью плесень пліснява мягкие сыры м'який мягкий сир м'які сири классичний класичний классік класік классический класический классик класик",
        nameUKR: "Cир з пліснявою",
        nameEN: "Camembert",
        companyName: "SM Mlekovita",
        countryName: "Польща",
        weightName: "Вага",
        weight: "120 гр.",
        priceGRN: 57,
        quantityOnStorage: "11",
        description01: "&#171Mlekovita - Camembert&#187 - це справжній сирний діамант з ніжною коркою та неперевершеним смаком. Цей сир володіє неповторнОю ніжною текстурою, що тане в роті. Виготовлений із відібраних інгредієнтів, він гарантує найвищу якість та смак.",
        description02: "Це ідеальний вибір для гурманів та цінителів справжнього смаку. Ніжний смак робить його ідеальним для смачних закусок, сендвічів або сирних тарілок. Цей сир може стати справжньою окрасою будь-якого заходу.",
        description03: "Завдяки &#171Mlekovita - Camembert&#187, Ви можете подарувати собі та гостям неперевершений смак справжнього французького сиру.",
        description04: "<strong>Сир м'який, з пліснявою.</strong>",
        description05: "Подаруйте собі миті справжнього задоволення та насолоди разом з&#171Mlekovita - Camembert&#187!"
    },
    {
        type: "retail",
        url: "./images/shop/food/dairy/cheese/mlekpol_ser_gouda_400.jpg",
        alt: "mlekpol_ser_gouda_400",
        marker: "FDEE280",
        brand: "Mlekpol",
        search: "млекпол мягкие сыры м'який мягкий сир м'які сири гоуда гауда",
        nameUKR: "Cир скибочками",
        nameEN: "Gouda",
        companyName: "Mlekpol",
        countryName: "Польща",
        weightName: "Вага",
        weight: "400 гр.",
        priceGRN: 127,
        quantityOnStorage: "5",
        description01: "&#171Mlekpol - Gouda&#187 - сир, який здобув світову славу завдяки своєму неповторному смаку та кремастійній текстурі. Кожен шматочок цього сиру розкривається справжнім багатством молочних нот і дарує гурманам експлозію насолоди.",
        description02: "Його ніжна консистенція та легкий горіховий присмак роблять його відмінним вибором для сирних тарілок та закусок.",
        description03: "&#171Mlekpol - Gouda&#187 виробляється з дотриманням традиційних рецептів, щоб забезпечити Вам справжній гастрономічний досвід.",
        description04: "<strong>Сир м'який, скибочками.</strong>",
        description05: "Зробіть свої смакові подорожі неповторними з сиром &#171Mlekpol - Gouda&#187 - визнаним шедевром світового сиру!"
    },
    {
        type: "retail",
        url: "./images/shop/food/dairy/cheese/mlekpol_ser_krolewski_z_kolna_400.jpg",
        alt: "mlekpol_ser_krolewski_z_kolna_400",
        marker: "FDEE282",
        brand: "Mlekpol",
        search: "млекпол мягкие сыры м'який мягкий сир м'які сири",
        nameUKR: "Cир скибочками",
        nameEN: "Krolewski Z Kolna",
        companyName: "Mlekpol",
        countryName: "Польща",
        weightName: "Вага",
        weight: "400 гр.",
        priceGRN: 127,
        quantityOnStorage: "5",
        description01: "&#171Mlekpol - Krolewski Z Kolna&#187 - це справжня королівська насолода для вашого смаку. Кожна скибочка цього сиру - це справжній шедевр, виготовлений із найкращого молока та відібраних інгредієнтів. Його ніжна консистенція робить його ідеальним для швидкого перекусу або сервірування на закуску.",
        description02: "Цей сир прекрасно поєднується з вином, фруктами та горіхами, створюючи неперевершений смаковий букет. Його аромат та смак надихають на справжнє задоволення.",
        description03: "&#171Mlekpol - Krolewski Z Kolna&#187 ідеально підходить для смачних сендвічів, закусок та канапок.",
        description04: "<strong>Сир м'який, скибочками.</strong>",
        description05: "Спробуйте королівський сир &#171Mlekpol - Krolewski Z Kolna&#187 та додайте аристократичного смаку своїм стравам!"
    },
    {
        type: "retail",
        url: "./images/shop/food/dairy/cheese/mlekpol_ser_salami_400.jpg",
        alt: "mlekpol_ser_salami_400",
        marker: "FDEE284",
        brand: "Mlekpol",
        search: "млекпол мягкие сыры м'який мягкий сир м'які сири саламі салами салями салямі",
        nameUKR: "Cир скибочками",
        nameEN: "Salami",
        companyName: "Mlekpol",
        countryName: "Польща",
        weightName: "Вага",
        weight: "400 гр.",
        priceGRN: 127,
        quantityOnStorage: "5",
        description01: "&#171Mlekpol - Salami&#187 - це не просто сир, а справжнє втілення італійської традиції та смаку. Цей унікальний продукт поєднує в собі вишуканість сиру та форму салямі, створюючи екзотичний та апетитний дует, який неодмінно припаде до душі гурманам.",
        description02: "Завдяки особливому методу виготовлення, сир досяг виняткової гармонії смаків. Кожен шматочок цього сиру наповнений інтенсивним ароматом та вираженим смаком.",
        description03: "&#171Mlekpol - Salami&#187 вирізняється ніжністю та еластичністю текстури, дозволяючи Вам отримати справжню насолоду від кожної скибочки.",
        description04: "<strong>Сир м'який, скибочками.</strong>",
        description05: "Запрошуємо Вас відкрити для себе неповторний смак &#171Mlekpol - Salami&#187 та вности елементи італійської страви у ваші кулінарні традиції!"
    },
    {
        type: "retail",
        url: "./images/shop/food/dairy/cheese/mlekpol_ser_zloty_mazur_400.jpg",
        alt: "mlekpol_ser_zloty_mazur_400",
        marker: "FDEE286",
        brand: "Mlekpol",
        search: "млекпол мягкие сыры м'який мягкий сир м'які сири zloty mazur",
        nameUKR: "Cир скибочками",
        nameEN: "Złoty Mazur",
        companyName: "Mlekpol",
        countryName: "Польща",
        weightName: "Вага",
        weight: "400 гр.",
        priceGRN: 127,
        quantityOnStorage: "5",
        description01: "&#171Mlekpol - Złoty Mazur&#187 - сир скибочками, що завоював серця гурманів своєю неперевершеною якістю та багатством смакових відтінків.",
        description02: "Це справжній діамант у світі сирів, виготовлений зі свіжого коров'ячого молока. Кожна скибочка вражає багатим, оксамитовим смаком, ідеальною текстурою та ароматом найкращих молочних продуктів.",
        description03: "&#171Mlekpol - Złoty Mazur&#187 пробуджує бажання відкривати нові смакові грані та додає вишуканості кожній страві. Нехай ваш стіл стане справжнім гастрономічним майданчиком.",
        description04: "<strong>Сир м'який, скибочками.</strong>",
        description05: "Дозвольте собі смакову розкіш з &#171Mlekpol - Złoty Mazur&#187. Замовте вже зараз і насолоджуйтеся смаком вишуканого сиру у кожному сімейному обіді чи святковому застіллі!"
    },
    {
        type: "retail",
        url: "./images/shop/food/dairy/cheese/mlekpol_ser_gouda_edan_500.jpg",
        alt: "mlekpol_ser_gouda_edan_500",
        marker: "FDEE290",
        brand: "Mlekpol",
        search: "млекпол мягкие сыры м'який мягкий сир м'які сири гоуда эдам едам",
        nameUKR: "Cири скибочками",
        nameEN: "Gouda & Edam",
        companyName: "Mlekpol",
        countryName: "Польща",
        weightName: "Вага",
        weight: "500 гр.",
        priceGRN: 158,
        quantityOnStorage: "5",
        description01: "&#171Mlekpol - Gouda & Edam&#187 - це унікальна можливість скуштувати два найпопулярніших голландських сири в одній упаковці. Гармонія смаку Gouda та ніжність Edam поєднуються, створюючи справжній симфонічний ансамбль, який зачаровує.",
        description02: "&#171Gouda&#187, з вираженим смаком і легким присмаком горіхів, поєднується з &#171Edam&#187, відомим своєю ніжністю та кремастістю. Ця комбінація стає ідеальним вибором для тих, хто хоче насолоджуватися різноманіттям смаків у кожному шматочку.",
        description03: "Кожен сир &#171Mlekpol - Gouda & Edam&#187 у цій упаковці виробляється за високими стандартами, щоб гарантувати Вам справжній гастрономічний досвід.",
        description04: "<strong>Сири м'які, скибочками. 2 упаковки по 250 грн.</strong>",
        description05: "Поглибіться у світ смаку та відкрийте для себе витонченість голландських традицій з дуєтом сирів &#171Mlekpol - Gouda & Edam&#187!"
    },
    {
        type: "wholesale",
        url: "./images/shop/food/dairy/cheese/parmareggio_parmigiano_reggiano_30_mesi_250.jpg",
        alt: "parmareggio_parmigiano_reggiano_30_mesi_250",
        marker: "FDEE520",
        brand: "Parmareggio",
        search: "твердый сыр твердые сыры твердий сир тверді сири 30 месяцев",
        nameUKR: "Пармезан",
        nameEN: "Parmigiano Reggiano 30 Mesi",
        companyName: "Parmareggio S.p.a.",
        countryName: "Італія",
        weightName: "Вага",
        weight: "250 гр.",
        priceGRN: 148,
        priceGRNOpt: 134,
        description01: "&#171Parmareggio - Parmigiano Reggiano 30 Mesi&#187 - це вишуканий італійський сир, який здивує навіть найвибагливіших гурманів. Відзначається терпким, багатим смаком та крихкими кришталевими гранулами, що роблять його неперевершеним.",
        description02: "Цей сир витримується протягом 30 місяців, дозволяючи йому розвинути неймовірні аромати та неперевершений смак. Справжній шедевр італійського мистецтва.",
        description03: "Використовуйте &#171Parmareggio - Parmigiano Reggiano 30 Mesi&#187 для приготування паст, салатів та сирних тарілок. Поступайте як справжній гурман та розкрийте всі нюанси смаку італійської кухні.",
        description04: "<strong>Сир твердий. Пармезан. 30 місяців витримки.</strong>",
        description05: "Не втрачайте можливості спробувати &#171Parmareggio - Parmigiano Reggiano 30 Mesi&#187 - доторкніться до смакової вишуканості Італії вже сьогодні!"
    },
    {
        type: "wholesale",
        url: "./images/shop/food/dairy/cheese/parmareggio_parmigiano_reggiano_naturale_30_mesi_250.jpg",
        alt: "parmareggio_parmigiano_reggiano_naturale_30_mesi_250",
        marker: "FDEE530",
        brand: "Parmareggio",
        search: "твердый сыр твердые сыры твердий сир тверді сири 30 месяцев с кальцием кальций с протеинами протеин",
        nameUKR: "Пармезан з кальцієм та протеїнами",
        nameEN: "Parmigiano Reggiano Oltre 30 Mesi",
        companyName: "Parmareggio S.p.a.",
        countryName: "Італія",
        weightName: "Вага",
        weight: "250 гр.",
        priceGRN: 148,
        priceGRNOpt: 134,
        description01: "&#171Parmareggio - Parmigiano Reggiano Oltre 30 Mesi&#187 - сир пармезан відомий своєю витримкою та розкішним смаком. Це справжнє витвір мистецтва для істинних поціновувачів сиру.",
        description02: "Це не тільки сир, але і вираження традиційної італійської майстерності. Його інтенсивний смак збагачений кальцієм та протеїнами. Цей сир витримується понад 30 місяців, щоб подарувати Вам неповторний гастрономічний досвід.",
        description03: "&#171Parmareggio - Parmigiano Reggiano Oltre 30 Mesi&#187 буде ідеальним вибором для справжніх естетів. Подаруйте собі унікальний смак та вишуканість італійської гастрономії.",
        description04: "<strong>Сир твердий. Пармезан. Без лактози, з кальцієм, протеїнами. 30 місяців витримки.</strong>",
        description05: "Спробуйте витончений смак справжнього італійського пармезану &#171Parmareggio - Parmigiano Reggiano Oltre 30 Mesi&#187, який зробить ваші страви неперевершеними!"
    },
]