export const shopLotsTuna = [
    {
        type: "wholesale",
        url: "./images/shop/food/canned_food/tuna/albo_atun_clato_oliva_195.jpg",
        alt: "albo_atun_clato_oliva_195",
        url1: "./images/shop/food/canned_food/tuna/albo_atun_clato_oliva_195.jpg",
        alt1: "albo_atun_clato_oliva_195",
        marker: "FDTA010",
        brand: "Albo",
        search: "албо тунець тунец в оливковом оливковое масле масло оливкова олія масло рыба риба",
        nameUKR: "Тунець в оливковій олії",
        nameEN: "Atun Claro En Aceite De Oliva",
        companyName: "Hijos de Carlos Albo S.L.U.",
        countryName: "Іспанія",
        weightName: "Вага",
        weight: "195 гр.",
        priceGRN: 132,
        priceGRNOpt: 118,
        description01: "&#171Albo - Atun Claro En Aceite De Oliva&#187 - це вершина смаку та якості у світі морських продуктів. Кожен шматочок тунця - це справжній шедевр кулінарного мистецтва. Він виробляється з найкращих якісних інгредієнтів і зберігається в оливковій олії найвищої якості.",
        description02: "Олія, в якій тунець знаходиться, додає страві неперевершений аромат та м'якість. Кожен шматочок тунця має неймовірно ніжну текстуру та багатий смак. Це ідеальний варіант для приготування салатів, суші або просто як джерело натурального білка.",
        description03: "Спробуйте &#171Albo - Atun Claro En Aceite De Oliva&#187 і відкрийте для себе справжній смак тунця. Цей продукт - це не просто страва, це смаковий досвід, який надихне вас на кулінарні експерименти та задовольнить найвибагливіших гурманів.",
        description04: "<strong>Тунець у оливковій олії. Без консервантів.</strong>",
        description05: "Не гайте часу даремно! Замовте &#171Albo - Atun Claro En Aceite De Oliva&#187 вже сьогодні і пориньте у світ смаку та задоволення, яким можна насолоджуватися щодня!"
    },
    {
        type: "wholesale",
        url: "./images/shop/food/canned_food/tuna/helcom_tunczyk_z_olejem_roslynnym_170.jpg",
        alt: "helcom_tunczyk_z_olejem_roslynnym_170",
        url1: "./images/shop/food/canned_food/tuna/helcom_tunczyk_z_olejem_roslynnym_170.jpg",
        alt1: "helcom_tunczyk_z_olejem_roslynnym_170",
        marker: "FDTA400",
        brand: "Helcom",
        search: "хелком тунець тунец в масле масло рослинна растительное растительном олія масло рыба риба",
        nameUKR: "Тунець у рослинній олії",
        nameEN: "Tuńczyk Z Olejem Roślynnym",
        companyName: "Greek Trade Sp.",
        countryName: "Польща",
        weightName: "Вага",
        weight: "170 гр.",
        priceGRN: 60,
        priceGRNOpt: 55,
        description01: "&#171Helcom - Tuńczyk Z Olejem Roślynnym&#187 - це чудовий вибір для тих, хто прагне поєднати смак і користь для здоров'я. Цей продукт припаде до смаку всім шанувальникам тунця, оскільки він поєднує найкращі якості морського подарунка з натуральністю рослинної олії.",
        description02: "Кожна консерва містить ніжний кусочок тунця, який зберігає свою природність та аромат завдяки використанню високоякісної рослинної олії. Це гармонійне поєднання дозволяє Вам отримувати задоволення від смаку тунця, зберігаючи всі його корисні властивості.",
        description03: "&#171Helcom - Tuńczyk Z Olejem Roślynnym&#187 - це не тільки джерело відмінного смаку, але і важливий додаток до збалансованого харчування. Завдяки багатому вмісту білка та Омега-3 жирних кислот, він підтримує ваше здоров'я та додає енергії на кожен день.",
        description04: "<strong>Тунець у рослинній олії, шматочками. Без консервантів.</strong>",
        description05: "Оберіть якість і користь для вашого організму та придбайте &#171Helcom - Tuńczyk Z Olejem Roślynnym&#187, насолоджуйтесь смаком та вигідними властивостями цього вишуканого продукту!"
    },
    {
        type: "retail",
        url: "./images/shop/food/canned_food/tuna/mk_tunczyk_olej_roslin_170.jpg",
        alt: "mk_tunczyk_olej_roslin_170",
        url1: "./images/shop/food/canned_food/tuna/mk_tunczyk_olej_roslin_170.jpg",
        alt1: "mk_tunczyk_olej_roslin_170",
        marker: "FDTA450",
        brand: "M & K",
        search: "тунець тунец в масле масло рослинна растительное растительном олія масло рыба риба",
        nameUKR: "Тунець у рослинній олії",
        nameEN: "Tuńczyk W Oleju Roślynnym",
        companyName: "Kasprzyk SP. K.",
        countryName: "Польща",
        weightName: "Вага",
        weight: "170 гр.",
        priceGRN: 70,
        quantityOnStorage: 1,
        description01: "Кожен шматочок тунця &#171M & K - Tuńczyk W Oleju Roślynnym&#187 насичений свіжістю морського бризу, а рослинна олія робить цей продукт легким і дієтичним, даруючи Вам справжній океанський смак.",
        description02: "Виготовлений з високоякісного тунця, багатого вітамінами та Омега-3 кислотами. Цей продукт не тільки додасть есклюзивності вашим стравам, але й забезпечить ваше тіло корисними речовинами, необхідними для здоров'я.",
        description03: "&#171Helcom - Tuńczyk Z Olejem Roślynnym&#187 виготовляється за унікальним рецептом, що гарантує насичений смак і дотримання найвищих стандартів якості. Кожен шматочок тунця - це поєднання смаку та здоров'я в одному блюді.",
        description04: "<strong>Тунець у рослинній олії, шматочками. Без консервантів.</strong>",
        description05: "Створіть вишукані страви легко та швидко, дозволяючи собі насолоджуватися неперевершеним смаком тунця &#171M & K - Tuńczyk W Oleju Roślynnym&#187!"
    },
    {
        type: "wholesale",
        url: "./images/shop/food/canned_food/tuna/rio_mare_tonno_al_naturale_80.jpg",
        alt: "rio_mare_tonno_al_naturale_80",
        url1: "./images/shop/food/canned_food/tuna/rio_mare_tonno_al_naturale_80.jpg",
        alt1: "rio_mare_tonno_al_naturale_80",
        marker: "FDTA600",
        brand: "Rio Mare",
        search: "рио ріо маре тунець тунец в собственном соку рыба риба",
        nameUKR: "Тунець у власному соку",
        nameEN: "Tonno Al Naturale",
        companyName: "Bolton Food S.P.A.",
        countryName: "Італія",
        weightName: "Вага",
        weight: "80 гр.",
        priceGRN: 63,
        priceGRNOpt: 58,
        description01: "&#171Rio Mare - Tonno Al Naturale&#187 - це найкращий вибір для тих, хто цінує природність і якість. Цей тунець у власному соку - це справжня смакова насолода. Він відзначається своєю ніжністю і неперевершеним смаком, який зберігається завдяки відсутності доданих спецій та соусів.",
        description02: "Кожен шматочок тунця ретельно обробляється і консервується, зберігаючи всю свою користь та аромат. Ви можете впевнено включити цей продукт до вашого раціону, оскільки він багатий білком та Омега-3 жирними кислотами, корисними для здоров'я серця та мозку.",
        description03: "&#171Rio Mare - Tonno Al Naturale&#187 - це смак і якість, які говорять самі за себе. Оберіть натуральність і смак природи.",
        description04: "<strong>Тунець у власному соку. Без консервантів.</strong>",
        description05: "Придбайте &#171Rio Mare - Tonno Al Naturale&#187 вже сьогодні і насолоджуйтесь найкращим, що може запропонувати природа!"
    },
    {
        type: "wholesale",
        url: "./images/shop/food/canned_food/tuna/rio_mare_tonno_al_naturale_320.jpg",
        alt: "rio_mare_tonno_al_naturale_320",
        url1: "./images/shop/food/canned_food/tuna/rio_mare_tonno_al_naturale_320.jpg",
        alt1: "rio_mare_tonno_al_naturale_320",
        marker: "FDTA610",
        brand: "Rio Mare",
        search: "рио ріо маре тунець тунец в собственном соку рыба риба",
        nameUKR: "Тунець у власному соку",
        nameEN: "Tonno Al Naturale",
        companyName: "Bolton Food S.P.A.",
        countryName: "Італія",
        weightName: "Вага",
        weight: "320 гр.",
        priceGRN: 250,
        priceGRNOpt: 230,
        description01: "&#171Rio Mare - Tonno Al Naturale&#187 - це найкращий вибір для тих, хто цінує природність і якість. Цей тунець у власному соку - це справжня смакова насолода. Він відзначається своєю ніжністю і неперевершеним смаком, який зберігається завдяки відсутності доданих спецій та соусів.",
        description02: "Кожен шматочок тунця ретельно обробляється і консервується, зберігаючи всю свою користь та аромат. Ви можете впевнено включити цей продукт до вашого раціону, оскільки він багатий білком та Омега-3 жирними кислотами, корисними для здоров'я серця та мозку.",
        description03: "&#171Rio Mare - Tonno Al Naturale&#187 - це смак і якість, які говорять самі за себе. Оберіть натуральність і смак природи.",
        description04: "<strong>Тунець у власному соку. Без консервантів. 4 шт. в упаковці.</strong>",
        description05: "Придбайте &#171Rio Mare - Tonno Al Naturale&#187 вже сьогодні і насолоджуйтесь найкращим, що може запропонувати природа!"
    },
    {
        type: "retail",
        url: "./images/shop/food/canned_food/tuna/rio_mare_tonno_al_naturale_480.jpg",
        alt: "rio_mare_tonno_al_naturale_480",
        url1: "./images/shop/food/canned_food/tuna/rio_mare_tonno_al_naturale_480.jpg",
        alt1: "rio_mare_tonno_al_naturale_480",
        marker: "FDTA615",
        brand: "Rio Mare",
        search: "рио ріо маре тунець тунец в собственном соку рыба риба",
        nameUKR: "Тунець у власному соку",
        nameEN: "Tonno Al Naturale",
        companyName: "Bolton Food S.P.A.",
        countryName: "Італія",
        weightName: "Вага",
        weight: "480 гр.",
        priceGRN: 380,
        quantityOnStorage: 1,
        description01: "&#171Rio Mare - Tonno Al Naturale&#187 - це найкращий вибір для тих, хто цінує природність і якість. Цей тунець у власному соку - це справжня смакова насолода. Він відзначається своєю ніжністю і неперевершеним смаком, який зберігається завдяки відсутності доданих спецій та соусів.",
        description02: "Кожен шматочок тунця ретельно обробляється і консервується, зберігаючи всю свою користь та аромат. Ви можете впевнено включити цей продукт до вашого раціону, оскільки він багатий білком та Омега-3 жирними кислотами, корисними для здоров'я серця та мозку.",
        description03: "&#171Rio Mare - Tonno Al Naturale&#187 - це смак і якість, які говорять самі за себе. Оберіть натуральність і смак природи.",
        description04: "<strong>Тунець у власному соку. Без консервантів. 6 шт. в упаковці.</strong>",
        description05: "Придбайте &#171Rio Mare - Tonno Al Naturale&#187 вже сьогодні і насолоджуйтесь найкращим, що може запропонувати природа!"
    },
    {
        type: "wholesale",
        url: "./images/shop/food/canned_food/tuna/rio_mare_tonno_al'Olio_di_oliva_80.jpg",
        alt: "rio_mare_tonno_al'Olio_di_oliva_80",
        url1: "./images/shop/food/canned_food/tuna/rio_mare_tonno_al'Olio_di_oliva_80.jpg",
        alt1: "rio_mare_tonno_al'Olio_di_oliva_80",
        marker: "FDTA630",
        brand: "Rio Mare",
        search: "рио ріо маре тунець тунец в оливковом оливковое масле масло оливкова олія масло рыба риба",
        nameUKR: "Тунець в оливковій олії",
        nameEN: "Tonno al'Olio di Oliva",
        companyName: "Bolton Food S.P.A.",
        countryName: "Італія",
        weightName: "Вага",
        weight: "80 гр.",
        priceGRN: 63,
        priceGRNOpt: 58,
        description01: "&#171Rio Mare - Tonno al'Olio di Oliva&#187 - це справжня вишуканість для справжніх гурманів. Цей продукт вражає своєю неперевершеною якістю та натуральністю. Кожен шматочок ніжної тунцевої страви знаходиться в оливковій олії, яка підкреслює його неповторний смак.",
        description02: "Коли Ви розкриваєте тунця, то отримуєте можливість насолоджуватися найкращими смаковими відчуттями без зайвих зусиль. Тунець ретельно відібраний та приготований так, щоб кожен шматочок був надзвичайно ніжним і соковитим.",
        description03: "&#171Rio Mare - Tonno al'Olio di Oliva&#187 стане чудовим доповненням до вашого столу із здоровою їжею. Вона має високий вміст білка та Омега-3 жирних кислот, що корисно для вашого організму.",
        description04: "<strong>Тунець у оливковій олії. Без консервантів.</strong>",
        description05: "Придбайте &#171Rio Mare - Tonno al'Olio di Oliva&#187 вже сьогодні та дозвольте собі насолодитися неперевершеним смаком та користью для здоров'я!"
    },
]