export const shopLotsCod = [
    {
        type: "retail",
        url: "./images/shop/food/canned_food/cod/giana_tresci_jatra_115.jpg",
        alt: "giana_tresci_jatra_115",
        url1: "./images/shop/food/canned_food/cod/giana_tresci_jatra_115.jpg",
        alt1: "giana_tresci_jatra_115",
        marker: "FDCD300",
        brand: "Giana",
        search: "гіана гиана тріска треска печень трески",
        nameUKR: "Печінка тріски у власному соку",
        nameEN: "Trešči játra ve vlasnim oleji",
        companyName: "Gaston s.r.o.",
        countryName: "Чехія",
        weightName: "Вага",
        weight: "115 гр.",
        priceGRN: 59,
        quantityOnStorage: 9,
        description01: "&#171Giana - Trešči játra ve vlasnim oleji&#187 - це дійсно вишукана делікатесна страва для справжніх гурманів. Ця консервована печінка тріски має неперевершений смак та текстуру, які роблять її неповторною.",
        description02: "Тріска у власному соку створює справжнє смакове відкриття. Ця страва - це джерело корисних жирів та білків, які підтримують ваше здоров'я. Вона ідеально підходить для сніданку, ланчу або вечері.",
        description03: "Забудьте про звичайні консерви - &#171Giana - Trešči játra ve vlasnim oleji&#187 варта спроби. Додайте її до вашого щоденного меню та насолоджуйтеся унікальним смаком та користью для здоров'я.",
        description04: "<strong>Печінка тріски у власному соку.</strong>",
        description05: "Замовте цю делікатесну печінку тріски &#171Giana - Trešči játra ve vlasnim oleji&#187 вже сьогодні і розкрийте перед собою справжній світ морських насолод!"
    },
    {
        type: "wholesale",
        url: "./images/shop/food/canned_food/cod/juor_240.jpg",
        alt: "juor_240",
        url1: "./images/shop/food/canned_food/cod/juor_240.jpg",
        alt1: "juor_240",
        marker: "FDCD350",
        brand: "Juor",
        search: "джуор тріска треска печень трески",
        nameUKR: "Печінка тріски у власному соку",
        nameEN: "Wątróbka Dorszowa W Tłuszczu Własnym",
        companyName: "Pn. Wsch Atlantyk FAO",
        countryName: "Польща",
        weightName: "Вага",
        weight: "240 гр.",
        priceGRN: 94,
        priceGRNOpt: 85,
        description01: "&#171Juor - Wątróbka Dorszowa W Tłuszczu Własnym&#187 - це справжня родзинка для шанувальників морських делікатесів. Ця консервована печінка тріски пропонує бездоганний смак та текстуру, які роблять її неперевершеною.",
        description02: "Ця страва - справжнє джерело корисних жирів та білків, які допоможуть Вам підтримувати здоров'я та насолоджуватися неперевершеним смаком.",
        description03: "Не вагайтесь додати &#171Juor - Wątróbka Dorszowa W Tłuszczu Własnym&#187 до свого меню. Пориньте у смак морської вишуканості та насолоджуйтеся кожним шматочком печінки.",
        description04: "<strong>Печінка тріски у власному соку.</strong>",
        description05: "Насолоджуйтеся кулінарною магією морського смаку не виходячи зі свого дому разом з &#171Juor - Wątróbka Dorszowa W Tłuszczu Własnym&#187!"
    },
]