export const shopLotsOlives = [
    // {
    //     type: "wholesale оптом",
    //     url: "./images/shop/food/olives_oil/olives/baresa_czarne_oliwki_bez_340.jpg",
    //     alt: "baresa_czarne_oliwki_bez_340",
    //     url1: "./images/shop/food/olives_oil/olives/baresa_czarne_oliwki_bez_340.jpg",
    //     alt1: "baresa_czarne_oliwki_bez_340",
    //     marker: "OLVS050",
    //     brand: "Baresa",
    //     search: "бареса лідл лидл черные чорные оливки маслины маслина маслини без косточки косточек кісточки",
    //     nameUKR: "Чорні оливки без кісточок",
    //     nameEN: "Czarne Oliwki Bez Pestek",
    //     companyName: "Lidl",
    //     countryName: "Іспанія",
    //     weightName: "Вага",
    //     weight: "340 гр.",
    //     priceGRN: 53,
    //     priceGRNOpt: 48,
    //     description01: "Дозвольте собі витончену естетику смаку з чорними оливками без кісточки &#171Baresa - Czarne Oliwki Bez Pestek&#187. Їхні ідеально вибрані плоди створюють справжню симфонію смаку, де присутність легкої гірчинки і насиченої пікантності робить смак неповторним.",
    //     description02: "Ці оливки - не просто продукт, це витончений додаток до вашого столу, що перетворить звичайний обід або вечерю у вишукане задоволення.",
    //     description03: "Природна свіжість та вишуканий смак &#171Baresa - Czarne Oliwki Bez Pestek&#187 роблять ці оливки ідеальним доповненням до будь-якої страви.",
    //     description04: "<strong>Оливки чорні, без кісточки.</strong>",
    //     description05: "Замовте чорні оливки без кісточки &#171Baresa - Czarne Oliwki Bez Pestek&#187 зараз і дозвольте собі насолоджуватися ексклюзивним смаком кожен день!"
    // },
    // {
    //     type: "wholesale оптом",
    //     url: "./images/shop/food/olives_oil/olives/baresa_zielone_oliwki_bez_340.jpg",
    //     alt: "baresa_zielone_oliwki_bez_340",
    //     url1: "./images/shop/food/olives_oil/olives/baresa_zielone_oliwki_bez_340.jpg",
    //     alt1: "baresa_zielone_oliwki_bez_340",
    //     marker: "OLVS060",
    //     brand: "Baresa",
    //     search: "бареса лидл лідл зеленые оливки маслины маслина маслини без косточки косточек кісточки",
    //     nameUKR: "Зелені оливки без кісточок",
    //     nameEN: "Zielone Oliwki Bez Pestek",
    //     companyName: "Lidl",
    //     countryName: "Іспанія",
    //     weightName: "Вага",
    //     weight: "340 гр.",
    //     priceGRN: 53,
    //     priceGRNOpt: 48,
    //     description01: "Зануртеся у світ природної смакової екстравагантності з зеленими оливками без кісточки &#171Baresa - Zielone Oliwki Bez Pestek&#187.",
    //     description02: "Їхні ніжні, м'які текстури поєднуються з виразними нотами солодкого та легкого гіркого смаку, створюючи неперевершений букет для вашого задоволення.",
    //     description03: "Приготуйте смачні страви з елітним акцентом, обираючи &#171Baresa - Zielone Oliwki Bez Pestek&#187. Їхні бездоганні плоди ідеально підходять для салатів, паст та закусок, надаючи кожній страві унікальний смак та естетичний вигляд.",
    //     description04: "<strong>Оливки зелені, без кісточки.</strong>",
    //     description05: "Спробуйте цей натуральний дарунок природи і відчуйте вишуканий захід разом з &#171Baresa - Zielone Oliwki Bez Pestek&#187!"
    // },
    // {
    //     type: "retail",
    //     url: "./images/shop/food/olives_oil/olives/corbi_green_big_700.jpg",
    //     alt: "corbi_green_big_700",
    //     url1: "./images/shop/food/olives_oil/olives/corbi_green_big_700.jpg",
    //     alt1: "corbi_green_big_700",
    //     marker: "OLVS150",
    //     brand: "Corbi",
    //     search: "корби корбі зеленые большие крупные великі крупні оливки маслины маслина маслини без косточки косточек кісточки",
    //     nameUKR: "Зелені оливки без кісточок",
    //     nameEN: "Aceituna Gordal",
    //     companyName: "Encurtidos L'olivera Pda",
    //     countryName: "Іспанія",
    //     weightName: "Вага",
    //     weight: "700 гр.",
    //     priceGRN: 200,
    //     quantityOnStorage: 5,
    //     description01: "&#171Corbi - Aceituna Gordal&#187 - це ексклюзивні оливки, які підкреслять смак будь-якої страви. Їх легка гірчинка і фруктовий наліт створюють неповторний кулінарний досвід.",
    //     description02: "Тільки найякісніші оливки, ретельно відібрані та збережені у натуральному соку, вони зберігають свіжість та неповторний смак.",
    //     description03: "&#171Corbi - Aceituna Gordal&#187 - це не просто продукт, а витвір майстерності і традицій. Кожна оливка, бездоганно велика та м'ясиста, має виразний смак та ніжну текстуру.",
    //     description04: "<strong>Оливки зелені, крупні. Без кісточки.</strong>",
    //     description05: "Відчуйте енергію сонця та гармонію природи в кожній оливці &#171Corbi - Aceituna Gordal&#187!"
    // },
    {
        type: "retail",
        url: "./images/shop/food/olives_oil/olives/el_toro_rojo_ oliwki_czarne_340.jpg",
        alt: "el_toro_rojo_ oliwki_czarne_340",
        url1: "./images/shop/food/olives_oil/olives/el_toro_rojo_ oliwki_czarne_340.jpg",
        alt1: "el_toro_rojo_ oliwki_czarne_340",
        marker: "OLVS250",
        brand: "El Toro Rojo",
        search: "эль эл торо роджо черные чорные оливки маслины маслина маслини без косточки косточек кісточки",
        nameUKR: "Чорні оливки без кісточок",
        nameEN: "Oliwki Czarne",
        companyName: "Jeronimo Martins S.A.",
        countryName: "Іспанія",
        weightName: "Вага",
        weight: "340 гр.",
        priceGRN: 63,
        quantityOnStorage: 7,
        description01: "&#171El Toro Rojo - Oliwki Czarne&#187 - це майстерність іспанської олівкової традиції в кожній банці. Ретельно відібрані на південних схилах Іспанії, ці оливки без кісточки вражають насиченим смаком і вишуканим ароматом.",
        description02: "М'ясисті та неймовірно соковиті, вони стануть ідеальним доповненням до салатів, закусок чи антипасто, додаючи елегантний штрих вашому столу.",
        description03: "&#171El Toro Rojo - Oliwki Czarne&#187 збережені у спеціальному соусі, розкривають багатий букет смаку, нагадуючи про сонячні дні і теплий бриз середземноморського узбережжя.",
        description04: "<strong>Оливки чорні, без кісточки.</strong>",
        description05: "Спробуйте &#171El Toro Rojo - Oliwki Czarne&#187 і пориньте у світ вишуканого смаку!"
    },
    {
        type: "retail",
        url: "./images/shop/food/olives_oil/olives/el_toro_rojo_ oliwki_zielone_340.jpg",
        alt: "el_toro_rojo_ oliwki_zielone_340",
        url1: "./images/shop/food/olives_oil/olives/el_toro_rojo_ oliwki_zielone_340.jpg",
        alt1: "el_toro_rojo_ oliwki_zielone_340",
        marker: "OLVS260",
        brand: "El Toro Rojo",
        search: "эль эл торо роджо зелные оливки маслины маслина маслини без косточки косточек кісточки",
        nameUKR: "Зелені оливки без кісточок",
        nameEN: "Oliwki Zielone",
        companyName: "Jeronimo Martins S.A.",
        countryName: "Іспанія",
        weightName: "Вага",
        weight: "340 гр.",
        priceGRN: 63,
        quantityOnStorage: 5,
        description01: "&#171El Toro Rojo - Oliwki Zielone&#187 - це справжнє джерело енергії в кожній зеленій оливці. Зібрані на високогірних галявинах Іспанії, ці оливки вражають своєю свіжістю та насиченим смаком.",
        description02: "Це справжній кулінарний експеримент. М'ясисті, з тонкою гірчинкою, вони стають ідеальним доповненням до закусок та салатів, додаючи екзотичний шарм вашому столу.",
        description03: "Завдяки особливому методу збереження, зелені оливки &#171El Toro Rojo - Oliwki Zielone&#187 залишають свою неповторну структуру і витончений смак.",
        description04: "<strong>Оливки зелені, без кісточки.</strong>",
        description05: "Спробуйте ці витончені оливки &#171El Toro Rojo - Oliwki Zielone&#187 та відчуйте у собі справжню силу сонця Іспанії!"
    },
    {
        type: "wholesale оптом",
        url: "./images/shop/food/olives_oil/olives/helcom_oliwli_czarne_330.jpg",
        alt: "helcom_oliwli_czarne_330",
        url1: "./images/shop/food/olives_oil/olives/helcom_oliwli_czarne_330-01.jpg",
        alt1: "helcom_oliwli_czarne_330-01",
        url2: "./images/shop/food/olives_oil/olives/helcom_oliwli_czarne_330-02.jpg",
        alt2: "helcom_oliwli_czarne_330-02",
        url3: "./images/shop/food/olives_oil/olives/helcom_oliwli_czarne_330-03.jpg",
        alt3: "helcom_oliwli_czarne_330-03",
        marker: "OLVS280",
        brand: "Helcom",
        search: "хелком черные чорные оливки маслины маслина маслини без косточки косточек кісточки",
        nameUKR: "Чорні оливки без кісточок",
        nameEN: "Oliwki Czarne Drylowane",
        companyName: "Greek Trade Sp.",
        countryName: "Польща",
        weightName: "Вага",
        weight: "330 гр.",
        priceGRN: 75,
        priceGRNOpt: 69,
        description01: "Відкрийте для себе вишуканий смак чорних оливок без кісточок &#171Helcom - Oliwki Czarne Drylowane&#187, які стануть справжньою окрасою Вашого столу.",
        description02: "Ці оливки вирізняються своєю м'якою текстурою та насиченим ароматом, що робить їх ідеальними для різноманітних кулінарних шедеврів.",
        description03: "Додайте &#171Helcom - Oliwki Czarne Drylowane&#187 до салатів, піци або закусок, і насолоджуйтесь багатством смаку, що привносить у Ваші страви неповторний середземноморський акцент.",
        description04: "<strong>Оливки чорні, без кісточки.</strong>",
        description05: "Придбайте &#171Helcom - Oliwki Czarne Drylowane&#187 вже сьогодні і підніміть свої кулінарні враження на новий рівень!"
    },
    {
        type: "wholesale оптом",
        url: "./images/shop/food/olives_oil/olives/helcom_oliwli_zielone_330.jpg",
        alt: "helcom_oliwli_zielone_330",
        url1: "./images/shop/food/olives_oil/olives/helcom_oliwli_zielone_330-01.jpg",
        alt1: "helcom_oliwli_zielone_330-01",
        url2: "./images/shop/food/olives_oil/olives/helcom_oliwli_zielone_330-02.jpg",
        alt2: "helcom_oliwli_zielone_330-02",
        url3: "./images/shop/food/olives_oil/olives/helcom_oliwli_zielone_330-03.jpg",
        alt3: "helcom_oliwli_zielone_330-03",
        marker: "OLVS285",
        brand: "Helcom",
        search: "хелком зелные оливки маслины маслина маслини без косточки косточек кісточки",
        nameUKR: "Зелені оливки без кісточок",
        nameEN: "Oliwki Zielone Drylowane",
        companyName: "Greek Trade Sp.",
        countryName: "Польща",
        weightName: "Вага",
        weight: "330 гр.",
        priceGRN: 75,
        priceGRNOpt: 69,
        description01: "Спробуйте неймовірно смачні зелені оливки без кісточок &#171Helcom - Oliwki Zielone Drylowane&#187, які стануть ідеальним доповненням до Вашого столу.",
        description02: "Ці оливки вирізняються своїм насиченим смаком і відмінною якістю, що робить їх чудовою закускою або інгредієнтом для Ваших улюблених страв.",
        description03: "&#171Helcom - Oliwki Zielone Drylowane&#187 додають нотку середземноморського аромату до кожного прийому їжі, даруючи неперевершене задоволення від смаку.",
        description04: "<strong>Оливки зелені, без кісточки.</strong>",
        description05: "Замовте зараз &#171Helcom - Oliwki Zielone Drylowane&#187 і насолоджуйтесь ідеальним поєднанням смаку та користі!"
    },
    {
        type: "wholesale оптом",
        url: "./images/shop/food/olives_oil/olives/hutesa_olives_pitted_black_350.jpg",
        alt: "hutesa_olives_pitted_black_350",
        url1: "./images/shop/food/olives_oil/olives/hutesa_olives_pitted_black_350-01.jpg",
        alt1: "hutesa_olives_pitted_black_350-01",
        url2: "./images/shop/food/olives_oil/olives/hutesa_olives_pitted_black_350-02.jpg",
        alt2: "hutesa_olives_pitted_black_350-02",
        url3: "./images/shop/food/olives_oil/olives/hutesa_olives_pitted_black_350-03.jpg",
        alt3: "hutesa_olives_pitted_black_350-03",
        marker: "OLVS310",
        brand: "Hutesa",
        search: "хутеса черные оливки маслины маслина маслини без косточки косточек кісточки",
        nameUKR: "Чорні оливки без кісточок",
        nameEN: "Olive Pitted",
        companyName: "Hutesa Agroalimentaria, S.A.",
        countryName: "Іспанія",
        weightName: "Вага",
        weight: "350 гр.",
        priceGRN: 75,
        priceGRNOpt: 69,
        description01: "&#171Hutesa - Olive Pitted&#187 - це чиста екзотика, яка стане справжньою прикрасою вашого столу і часу для вишуканого смаку.",
        description02: "Ці оливки вражають своєю насиченістю та вишуканістю смаку, виносячи ваші кулінарні експерименти на новий рівень. Вони ідеально підходять для закусок, салатів чи просто як додаток до ваших улюблених страв.",
        description03: "Бажаєте відчути той справжній іспанський аромат і смак? Чорні оливки &#171Hutesa - Olive Pitted&#187 гарантують Вам неперевершену якість і надзвичайний гастрономічний досвід, щоб ваші кулінарні фантазії стали реальністю.",
        description04: "<strong>Оливки чорні, без кісточки. Стерилізовані.</strong>",
        description05: "Поглибтеся у світ екзотичних вражень і пройдіть шляхом смакових відкриттів разом з &#171Hutesa - Olive Pitted&#187!"
    },
    {
        type: "wholesale оптом",
        url: "./images/shop/food/olives_oil/olives/hutesa_olives_pitted_green_350.jpg",
        alt: "hutesa_olives_pitted_green_350",
        url1: "./images/shop/food/olives_oil/olives/hutesa_olives_pitted_green_350-01.jpg",
        alt1: "hutesa_olives_pitted_green_350-01",
        url2: "./images/shop/food/olives_oil/olives/hutesa_olives_pitted_green_350-02.jpg",
        alt2: "hutesa_olives_pitted_green_350-02",
        url3: "./images/shop/food/olives_oil/olives/hutesa_olives_pitted_green_350-03.jpg",
        alt3: "hutesa_olives_pitted_green_350-03",
        marker: "OLVS300",
        brand: "Hutesa",
        search: "хутеса зелные оливки маслины маслина маслини без косточки косточек кісточки",
        nameUKR: "Зелені оливки без кісточок",
        nameEN: "Olive Pitted",
        companyName: "Hutesa Agroalimentaria, S.A.",
        countryName: "Іспанія",
        weightName: "Вага",
        weight: "350 гр.",
        priceGRN: 75,
        priceGRNOpt: 69,
        description01: "Бажаєте відчути вибух смаку? &#171Hutesa - Olive Pitted&#187 - яскрава симфонія ароматів та смаків, яка зачаровує з першого погляду.",
        description02: "Ці зелені оливки не тільки смакова експлозія, але й високий стандарт якості. Вони додають вашим стравам свіжість та екзотичний присмак.",
        description03: "Прагнете відкрити для себе істину іспанської гастрономії? Замовте зелені оливки &#171Hutesa - Olive Pitted&#187 та відчуйте справжню радість від досконалого поєднання смаку та якості.",
        description04: "<strong>Оливки зелені, без кісточки. Стерилізовані.</strong>",
        description05: "Не вагайтеся – замовте зелені оливки без кісточок &#171Hutesa - Olive Pitted&#187 вже зараз і зануртеся у безмежний світ смакових вражень, які Вам принесуть подолання гастрономічних вершин!"
    },
    {
        type: "wholesale оптом",
        url: "./images/shop/food/olives_oil/olives/hutesa_olives_pitted_black_900.jpg",
        alt: "hutesa_olives_pitted_black_900",
        url1: "./images/shop/food/olives_oil/olives/hutesa_olives_pitted_black_900-01.jpg",
        alt1: "hutesa_olives_pitted_black_900-01",
        url2: "./images/shop/food/olives_oil/olives/hutesa_olives_pitted_black_900-02.jpg",
        alt2: "hutesa_olives_pitted_black_900-02",
        url3: "./images/shop/food/olives_oil/olives/hutesa_olives_pitted_black_900-03.jpg",
        alt3: "hutesa_olives_pitted_black_900-03",
        marker: "OLVS305",
        brand: "Hutesa",
        search: "хутеса черные оливки маслины маслина маслини без косточки косточек кісточки",
        nameUKR: "Чорні оливки без кісточок",
        nameEN: "Olive Pitted",
        companyName: "Hutesa Agroalimentaria, S.A.",
        countryName: "Іспанія",
        weightName: "Вага",
        weight: "900 гр.",
        priceGRN: 145,
        priceGRNOpt: 133,
        description01: "&#171Hutesa - Olive Pitted&#187 - це чиста екзотика, яка стане справжньою прикрасою вашого столу і часу для вишуканого смаку.",
        description02: "Ці оливки вражають своєю насиченістю та вишуканістю смаку, виносячи ваші кулінарні експерименти на новий рівень. Вони ідеально підходять для закусок, салатів чи просто як додаток до ваших улюблених страв.",
        description03: "Бажаєте відчути той справжній іспанський аромат і смак? Чорні оливки &#171Hutesa - Olive Pitted&#187 гарантують Вам неперевершену якість і надзвичайний гастрономічний досвід, щоб ваші кулінарні фантазії стали реальністю.",
        description04: "<strong>Оливки чорні, без кісточки. Стерилізовані.</strong>",
        description05: "Поглибтеся у світ екзотичних вражень і пройдіть шляхом смакових відкриттів разом з &#171Hutesa - Olive Pitted&#187!"
    },
    {
        type: "wholesale оптом",
        url: "./images/shop/food/olives_oil/olives/hutesa_olives_pitted_green_900.jpg",
        alt: "hutesa_olives_pitted_green_900",
        url1: "./images/shop/food/olives_oil/olives/hutesa_olives_pitted_green_900-01.jpg",
        alt1: "hutesa_olives_pitted_green_900-01",
        url2: "./images/shop/food/olives_oil/olives/hutesa_olives_pitted_green_900-02.jpg",
        alt2: "hutesa_olives_pitted_green_900-02",
        url3: "./images/shop/food/olives_oil/olives/hutesa_olives_pitted_green_900-03.jpg",
        alt3: "hutesa_olives_pitted_green_900-03",
        marker: "OLVS315",
        brand: "Hutesa",
        search: "хутеса зелные оливки маслины маслина маслини без косточки косточек кісточки",
        nameUKR: "Зелені оливки без кісточок",
        nameEN: "Olive Pitted",
        companyName: "Hutesa Agroalimentaria, S.A.",
        countryName: "Іспанія",
        weightName: "Вага",
        weight: "900 гр.",
        priceGRN: 145,
        priceGRNOpt: 133,
        description01: "Бажаєте відчути вибух смаку? &#171Hutesa - Olive Pitted&#187 - яскрава симфонія ароматів та смаків, яка зачаровує з першого погляду.",
        description02: "Ці зелені оливки не тільки смакова експлозія, але й високий стандарт якості. Вони додають вашим стравам свіжість та екзотичний присмак.",
        description03: "Прагнете відкрити для себе істину іспанської гастрономії? Замовте зелені оливки &#171Hutesa - Olive Pitted&#187 та відчуйте справжню радість від досконалого поєднання смаку та якості.",
        description04: "<strong>Оливки зелені, без кісточки. Стерилізовані.</strong>",
        description05: "Не вагайтеся – замовте зелені оливки без кісточок &#171Hutesa - Olive Pitted&#187 вже зараз і зануртеся у безмежний світ смакових вражень, які Вам принесуть подолання гастрономічних вершин!"
    },
]
