export const shopLotsOil = [
    {
        type: "wholesale оптом",
        url: "./images/shop/food/olives_oil/oil/nordolio_olio_di_semi_di_mais_1l.jpg",
        alt: "nordolio_olio_di_semi_di_mais_1l",
        url1: "./images/shop/food/olives_oil/oil/nordolio_olio_di_semi_di_mais_1l.jpg",
        alt1: "nordolio_olio_di_semi_di_mais_1l",
        marker: "FDOI400",
        brand: "Nordolio",
        search: "кукуруза кукурудза кукурузное масло",
        nameUKR: "Кукурудзяна олія",
        nameEN: "Olio Di Seni Di Mais",
        companyName: "Gruppo ASA",
        countryName: "Італія",
        volumeName: "Об'єм",
        volume: "1 л.",
        priceGRN: 325,
        priceGRNOpt: 293,
        description01: "&#171Nordolio - Olio Di Seni Di Mais&#187 - це справжнє втілення природної чистоти та смаку. Вироблена зі свіжих зерен кукурудзи, ця олія вражає найкращими властивостями рослинної олії. Інтенсивний аромат та насичений смак роблять її ідеальним доповненням до салатів, супів і смажених страв.",
        description02: "Виробляється з великою увагою до деталей та з використанням найсучасніших технологій. Вона є багатим джерелом Омега-3 жирних кислот та вітаміну Е, які сприяють збереженню вашого здоров'я і додають приємний блиск вашим стравам.",
        description03: "Почувайте себе гурманом і додайте смаку своїм стравам з &#171Nordolio - Olio Di Seni Di Mais&#187, тому що Ви заслуговуєте на найкраще!",
        description04: "<strong>Зберігати у сухому та прохолодному місці.</strong>",
        description05: "Не вагайтесь спробувати цю неймовірну кукурудзяну олію &#171Nordolio - Olio Di Seni Di Mais&#187 вже сьогодні та насолоджуйтесь неперевершеним смаком і користью для вашого організму!"
    },
    // {
    //     type: "wholesale оптом",
    //     url: "./images/shop/food/olives_oil/oil/vesuvio_avocado_oil_250.jpg",
    //     alt: "vesuvio_avocado_oil_250",
    //     url1: "./images/shop/food/olives_oil/oil/vesuvio_avocado_oil_250.jpg",
    //     alt1: "vesuvio_avocado_oil_250",
    //     marker: "FDOI850",
    //     brand: "Vesuvio",
    //     search: "масло",
    //     nameUKR: "Олія з авокадо",
    //     nameEN: "Avocado Oil",
    //     companyName: "Vesuvio G.I.R",
    //     countryName: "Греція",
    //     volumeName: "Об'єм",
    //     volume: "250 мл.",
    //     priceGRN: 88,
    //     priceGRNOpt: 81,
    //     description01: "&#171Vesuvio - Avocado Oil&#187 - це справжній дарунок для вашого здоров'я і кулінарного мистецтва. Вона виготовлена із зрілих авокадо, надаючи вашим стравам неперевершений смак і текстуру. Що робить цю олію особливою - це її висока концентрація Омега 3, 6, 9 жирних кислот, які корисні для серця, шкіри та загального здоров'я.",
    //     description02: "Це ідеальний вибір для гурманів та тих, хто піклується про своє здоров'я. Вона підходить для смаження, заправок та приготування салатів. Олія володіє вишуканим смаком та ароматом, що підкреслить унікальний смак кожної страви.",
    //     description03: "Піднесіть своє кулінарне мистецтво на новий рівень за допомогою &#171Vesuvio - Avocado Oil&#187. Підкресліть натуральний смак своїх улюблених страв і забезпечте своєму організму необхідні Омега-жирні кислоти.",
    //     description04: "<strong>Зберігати у сухому та прохолодному місці.</strong>",
    //     description05: "Покладіть &#171Vesuvio - Avocado Oil&#187 у свій кошик та насолжуйтесь безмежними можливостями, які ця олія пропонує Вам!"
    // },
    {
        type: "wholesale оптом",
        url: "./images/shop/food/olives_oil/oil/vesuvio_avocado_oil_500.jpg",
        alt: "vesuvio_avocado_oil_500",
        url1: "./images/shop/food/olives_oil/oil/vesuvio_avocado_oil_500.jpg",
        alt1: "vesuvio_avocado_oil_500",
        marker: "FDOI855",
        brand: "Vesuvio",
        search: "масло c",
        nameUKR: "Олія з авокадо",
        nameEN: "Avocado Oil",
        companyName: "Vesuvio G.I.R",
        countryName: "Греція",
        volumeName: "Об'єм",
        volume: "500 мл.",
        priceGRN: 163,
        priceGRNOpt: 150,
        description01: "&#171Vesuvio - Avocado Oil&#187 - це справжній дарунок для вашого здоров'я і кулінарного мистецтва. Вона виготовлена із зрілих авокадо, надаючи вашим стравам неперевершений смак і текстуру. Що робить цю олію особливою - це її висока концентрація Омега 3, 6, 9 жирних кислот, які корисні для серця, шкіри та загального здоров'я.",
        description02: "Це ідеальний вибір для гурманів та тих, хто піклується про своє здоров'я. Вона підходить для смаження, заправок та приготування салатів. Олія володіє вишуканим смаком та ароматом, що підкреслить унікальний смак кожної страви.",
        description03: "Піднесіть своє кулінарне мистецтво на новий рівень за допомогою &#171Vesuvio - Avocado Oil&#187. Підкресліть натуральний смак своїх улюблених страв і забезпечте своєму організму необхідні Омега-жирні кислоти.",
        description04: "<strong>Зберігати у сухому та прохолодному місці.</strong>",
        description05: "Покладіть &#171Vesuvio - Avocado Oil&#187 у свій кошик та насолжуйтесь безмежними можливостями, які ця олія пропонує Вам!"
    },
    {
        type: "wholesale оптом",
        url: "./images/shop/food/olives_oil/oil/vesuvio_corn_oil_1000.jpg",
        alt: "vesuvio_corn_oil_1000",
        url1: "./images/shop/food/olives_oil/oil/vesuvio_corn_oil_1000-01.jpg",
        alt1: "vesuvio_corn_oil_1000-01",
        url2: "./images/shop/food/olives_oil/oil/vesuvio_corn_oil_1000-02.jpg",
        alt2: "vesuvio_corn_oil_1000-02",
        marker: "FDOI885",
        brand: "Vesuvio",
        search: "кукуруза кукурузное масло",
        nameUKR: "Кукурудзяна олія",
        nameEN: "Corn Oil",
        companyName: "Vesuvio G.I.R",
        countryName: "Греція",
        volumeName: "Об'єм",
        volume: "1000 мл.",
        priceGRN: 200,
        priceGRNOpt: 184,
        description01: "Представляємо &#171Vesuvio - Corn Oil&#187, що здобула увагу своєю чистотою та вишуканістю. Ця кукурудзяна олія - справжнє джерело здоров'я та гастрономічних вражень.",
        description02: "Ця олія це не лише відмінне джерело ОМЕГА-6, але і чудовий спосіб надати стравам неповторний смак та аромат. Відмінна термостійкість цієї олії робить її ідеальною для приготування різноманітних страв.",
        description03: "Прагнете приготувати здорові та смачні страви? Почуття бажання виникає, коли ви думаєте про те, як &#171Vesuvio - Corn Oil&#187 додає смак та користь кожному обіду чи вечері.",
        description04: "<strong>Зберігати у сухому та прохолодному місці.</strong>",
        description05: "Зробіть правильний вибір для свого здоров'я - виберіть &#171Vesuvio - Corn Oil&#187 прямо зараз та насолоджуйтеся експлозією смаку та користі у кожній кулькарині вашого столу!"
    },
    {
        type: "wholesale оптом",
        url: "./images/shop/food/olives_oil/oil/vesuvio_grapeseed_oil_250.jpg",
        alt: "vesuvio_grapeseed_oil_250",
        url1: "./images/shop/food/olives_oil/oil/vesuvio_grapeseed_oil_250.jpg",
        alt1: "vesuvio_grapeseed_oil_250",
        marker: "FDOI890",
        brand: "Vesuvio",
        search: "виноград виноградное масло",
        nameUKR: "Виноградова олія",
        nameEN: "Grapeseed Oil",
        companyName: "Vesuvio G.I.R",
        countryName: "Греція",
        volumeName: "Об'єм",
        volume: "250 мл.",
        priceGRN: 88,
        priceGRNOpt: 81,
        description01: "&#171Vesuvio - Grapeseed Oil&#187 - це справжня перлина серед різноманітних олій. Виготовлена із виноградних зерен, вона вразить Вас своєю ніжністю та вишуканим смаком. Ця олія має високий вміст Омега-6 жирних кислот та антиоксидантів, сприяючи вашому здоров'ю і добробуту.",
        description02: "Завдяки своєму легкому та нейтральному смаку, виноградова олія відмінно підходить для смаження, заправок та приготування салатів. Вона робить ваші страви ніжними та смачними, зберігаючи при цьому всі корисні властивості.",
        description03: "Оберіть якість та користь для свого організму та заволяйте вже сьогодні виноградову олію &#171Vesuvio - Grapeseed Oil&#187.",
        description04: "<strong>Зберігати у сухому та прохолодному місці.</strong>",
        description05: "Підкресліть смак своїх улюблених страв та насолоджуйтеся кулінарними витворами, які Вам подарить &#171Vesuvio - Grapeseed Oil&#187!"
    },
    {
        type: "wholesale оптом",
        url: "./images/shop/food/olives_oil/oil/vesuvio_grapeseed_oil_500.jpg",
        alt: "vesuvio_grapeseed_oil_500",
        url1: "./images/shop/food/olives_oil/oil/vesuvio_grapeseed_oil_500.jpg",
        alt1: "vesuvio_grapeseed_oil_500",
        marker: "FDOI895",
        brand: "Vesuvio",
        search: "виноград виноградное масло",
        nameUKR: "Виноградова олія",
        nameEN: "Grapeseed Oil",
        companyName: "Vesuvio G.I.R",
        countryName: "Греція",
        volumeName: "Об'єм",
        volume: "500 мл.",
        priceGRN: 163,
        priceGRNOpt: 150,
        description01: "&#171Vesuvio - Grapeseed Oil&#187 - це справжня перлина серед різноманітних олій. Виготовлена із виноградних зерен, вона вразить Вас своєю ніжністю та вишуканим смаком. Ця олія має високий вміст Омега-6 жирних кислот та антиоксидантів, сприяючи вашому здоров'ю і добробуту.",
        description02: "Завдяки своєму легкому та нейтральному смаку, виноградова олія відмінно підходить для смаження, заправок та приготування салатів. Вона робить ваші страви ніжними та смачними, зберігаючи при цьому всі корисні властивості.",
        description03: "Оберіть якість та користь для свого організму та заволяйте вже сьогодні виноградову олію &#171Vesuvio - Grapeseed Oil&#187.",
        description04: "<strong>Зберігати у сухому та прохолодному місці.</strong>",
        description05: "Підкресліть смак своїх улюблених страв та насолоджуйтеся кулінарними витворами, які Вам подарить &#171Vesuvio - Grapeseed Oil&#187!"
    },
    // {
    //     type: "wholesale оптом",
    //     url: "./images/shop/food/olives_oil/oil/vesuvio_grapeseed_oil_1000.jpg",
    //     alt: "vesuvio_grapeseed_oil_1000",
    //     url1: "./images/shop/food/olives_oil/oil/vesuvio_grapeseed_oil_1000-01.jpg",
    //     alt1: "vesuvio_grapeseed_oil_1000-01",
    //     url2: "./images/shop/food/olives_oil/oil/vesuvio_grapeseed_oil_1000-02.jpg",
    //     alt2: "vesuvio_grapeseed_oil_1000-02",
    //     marker: "FDOI900",
    //     brand: "Vesuvio",
    //     search: "виноград виноградное масло",
    //     nameUKR: "Виноградова олія",
    //     nameEN: "Grapeseed Oil",
    //     companyName: "Vesuvio G.I.R",
    //     countryName: "Греція",
    //     volumeName: "Об'єм",
    //     volume: "1000 мл.",
    //     priceGRN: 200,
    //     priceGRNOpt: 184,
    //     description01: "&#171Vesuvio - Grapeseed Oil&#187 - це справжня перлина серед різноманітних олій. Виготовлена із виноградних зерен, вона вразить Вас своєю ніжністю та вишуканим смаком. Ця олія має високий вміст Омега-6 жирних кислот та антиоксидантів, сприяючи вашому здоров'ю і добробуту.",
    //     description02: "Завдяки своєму легкому та нейтральному смаку, виноградова олія відмінно підходить для смаження, заправок та приготування салатів. Вона робить ваші страви ніжними та смачними, зберігаючи при цьому всі корисні властивості.",
    //     description03: "Оберіть якість та користь для свого організму та заволяйте вже сьогодні виноградову олію &#171Vesuvio - Grapeseed Oil&#187.",
    //     description04: "<strong>Зберігати у сухому та прохолодному місці.</strong>",
    //     description05: "Підкресліть смак своїх улюблених страв та насолоджуйтеся кулінарними витворами, які Вам подарить &#171Vesuvio - Grapeseed Oil&#187!"
    // },
    {
        type: "wholesale оптом",
        url: "./images/shop/food/olives_oil/oil/vesuvio_mais_corn_oil_1l.jpg",
        alt: "vesuvio_mais_corn_oil_1l",
        url1: "./images/shop/food/olives_oil/oil/vesuvio_mais_corn_oil_1l.jpg",
        alt1: "vesuvio_mais_corn_oil_1l",
        marker: "FDOI960",
        brand: "Vesuvio",
        search: "кукуруза кукурудза кукурузное масло",
        nameUKR: "Кукурудзяна олія",
        nameEN: "Mais Corn Oil",
        companyName: "Vesuvio G.I.R",
        countryName: "Італія",
        volumeName: "Об'єм",
        volume: "1 л.",
        priceGRN: 137,
        priceGRNOpt: 121,
        description01: "&#171Vesuvio - Mais Corn Oil&#187 - це справжній скарб для вашої кулінарії. Виготовлена з відібраних кукурузних зерен, вона пройшла обережну обробку, щоб зберегти дивовижний смак. Ця олія - ідеальний вибір для тих, хто цінує найвищу якість у своїх стравах.",
        description02: "&#171Vesuvio - Mais Corn Oil&#187 має високий рівень кульового кипіння, що робить її ідеальною для глибокого смаження та обсмажування на великих вогнищах. Вона зберігає всі корисні властивості при високих температурах, допомагаючи створювати страви, які справді захоплюють.",
        description03: "Олія стане незамінним помічником у вашій кулінарній майстерності. Вирушайте у смачну подорож та експериментуйте з різноманітними стравами, використовуючи цю чудову олію. Ви неодмінно залишитеся враженими від її якості та смаку!",
        description04: "<strong>Зберігати у сухому та прохолодному місці.</strong>",
        description05: "Не вагайтеся, спробуйте &#171Vesuvio - Mais Corn Oil&#187 прямо зараз та підкоріть кулінарний світ разом з нами."
    },
]