export const shopLotsOil = [
    {
        type: "retail",
        mainCategory: "foodstuffs",
        subcategory: "olives-oils",
        url: "./images/shop/food/olives_oil/oil/nordolio_olio_di_semi_di_mais_1l.jpg",
        alt: "nordolio_olio_di_semi_di_mais_1l",
        url1: "./images/shop/food/olives_oil/oil/nordolio_olio_di_semi_di_mais_1l.jpg",
        alt1: "nordolio_olio_di_semi_di_mais_1l",
        marker: "FDOI400",
        brand: "Nordolio",
        search: "кукуруза кукурудза кукурузное масло",
        nameUKR: "Кукурудзяна олія",
        nameEN: "Olio Di Seni Di Mais",
        companyName: "Gruppo ASA",
        countryName: "Італія",
        volumeName: "Об'єм",
        volume: "1 л.",
        priceGRN: 350,
        quantityOnStorage: 2,
        description01: "&#171Nordolio - Olio Di Seni Di Mais&#187 - це справжнє втілення природної чистоти та смаку. Вироблена зі свіжих зерен кукурудзи, ця олія вражає найкращими властивостями рослинної олії. Інтенсивний аромат та насичений смак роблять її ідеальним доповненням до салатів, супів і смажених страв.",
        description02: "Виробляється з великою увагою до деталей та з використанням найсучасніших технологій. Вона є багатим джерелом Омега-3 жирних кислот та вітаміну Е, які сприяють збереженню вашого здоров'я і додають приємний блиск вашим стравам.",
        description03: "Почувайте себе гурманом і додайте смаку своїм стравам з &#171Nordolio - Olio Di Seni Di Mais&#187, тому що Ви заслуговуєте на найкраще!",
        description04: "<strong>Зберігати у сухому та прохолодному місці.</strong>",
        description05: "Не вагайтесь спробувати цю неймовірну кукурудзяну олію &#171Nordolio - Olio Di Seni Di Mais&#187 вже сьогодні та насолоджуйтесь неперевершеним смаком і користью для вашого організму!"
    },
]