export const shopLotsCod = [
    {
        type: "retail",
        mainCategory: "foodstuffs",
        subcategory: "conservation",
        url: "./images/shop/food/canned_food/cod/giana_tresci_jatra_115.jpg",
        alt: "giana_tresci_jatra_115",
        url1: "./images/shop/food/canned_food/cod/giana_tresci_jatra_115.jpg",
        alt1: "giana_tresci_jatra_115",
        marker: "FDCD300",
        brand: "Giana",
        search: "tresci jatra гіана гиана тріска треска печень трески",
        nameUKR: "Печінка тріски у власному соку",
        nameEN: "Trešči játra ve vlasnim oleji",
        companyName: "Gaston s.r.o.",
        countryName: "Чехія",
        weightName: "Вага",
        weight: "115 гр.",
        priceGRN: 104,
        quantityOnStorage: 10,
        description01: "&#171Giana - Trešči játra ve vlasnim oleji&#187 - це дійсно вишукана делікатесна страва для справжніх гурманів. Ця консервована печінка тріски має неперевершений смак та текстуру, які роблять її неповторною.",
        description02: "Тріска у власному соку створює справжнє смакове відкриття. Ця страва - це джерело корисних жирів та білків, які підтримують ваше здоров'я. Вона ідеально підходить для сніданку, ланчу або вечері.",
        description03: "Забудьте про звичайні консерви - &#171Giana - Trešči játra ve vlasnim oleji&#187 варта спроби. Додайте її до вашого щоденного меню та насолоджуйтеся унікальним смаком та користью для здоров'я.",
        description04: "<strong>Печінка тріски у власному соку.</strong>",
        description05: "Замовте цю делікатесну печінку тріски &#171Giana - Trešči játra ve vlasnim oleji&#187 вже сьогодні і розкрийте перед собою справжній світ морських насолод!"
    },
    {
        type: "only-wholesale оптом",
        mainCategory: "foodstuffs",
        subcategory: "conservation",    
        url: "./images/shop/food/canned_food/cod/juor_240.jpg",
        alt: "juor_240",
        url1: "./images/shop/food/canned_food/cod/juor_240.jpg",
        alt1: "juor_240",
        marker: "FDCD350",
        brand: "Juor",
        search: "watrobka dorszowa w tluszczu wlasnym джуор тріска треска печень трески",
        nameUKR: "Печінка тріски у власному соку",
        nameEN: "Wątróbka Dorszowa W Tłuszczu Własnym",
        companyName: "Pn. Wsch Atlantyk FAO",
        countryName: "Польща",
        weightName: "Вага",
        weight: "240 гр.",
        priceGRN: "--",
        priceGRNOpt: 105,
        description01: "&#171Juor - Wątróbka Dorszowa W Tłuszczu Własnym&#187 - це справжня родзинка для шанувальників морських делікатесів. Ця консервована печінка тріски пропонує бездоганний смак та текстуру, які роблять її неперевершеною.",
        description02: "Ця страва - справжнє джерело корисних жирів та білків, які допоможуть Вам підтримувати здоров'я та насолоджуватися неперевершеним смаком.",
        description03: "Не вагайтесь додати &#171Juor - Wątróbka Dorszowa W Tłuszczu Własnym&#187 до свого меню. Пориньте у смак морської вишуканості та насолоджуйтеся кожним шматочком печінки.",
        description04: "<strong>Печінка тріски у власному соку.</strong>",
        description05: "Насолоджуйтеся кулінарною магією морського смаку не виходячи зі свого дому разом з &#171Juor - Wątróbka Dorszowa W Tłuszczu Własnym&#187!"
    },
    {
        type: "only-wholesale оптом",
        mainCategory: "foodstuffs",
        subcategory: "conservation",
        url: "./images/shop/food/canned_food/cod/king_oscar_watrobki_z_dorsza_115.jpg",
        alt: "king_oscar_watrobki_z_dorsza_115",
        url1: "./images/shop/food/canned_food/cod/king_oscar_watrobki_z_dorsza_115-01.jpg",
        alt1: "king_oscar_watrobki_z_dorsza_115-01",
        url2: "./images/shop/food/canned_food/cod/king_oscar_watrobki_z_dorsza_115-02.jpg",
        alt2: "king_oscar_watrobki_z_dorsza_115-02",
        marker: "FDCD390",
        brand: "King Oscar",
        search: "watrobki z dorsza w tluszczu wlasnym король кинг кінг оскар тріска треска печень трески",
        nameUKR: "Печінка тріски у власному соку з ОМЕГА-3",
        nameEN: "Wątróbki Z Dorsza W Tłuszczu Własnym OMEGA-3",
        companyName: "Thai Union Poland Sp.",
        countryName: "Польща",
        weightName: "Вага",
        weight: "115 гр.",
        priceGRN: "--",
        priceGRNOpt: 87,
        description01: "Печінка тріски &#171King Oscar - Wątróbki Z Dorsza W Tłuszczu Własnym OMEGA-3&#187 – це натуральний продукт, збагачений цінними жирними кислотами ОМЕГА-3, що підтримують здоров'я серця і мозку.",
        description02: "Ця печінка у власному соку, що зберігає її природний смак і текстуру, роблячи її ідеальним інгредієнтом для вишуканих страв.",
        description03: "Корисні властивості печінки тріски &#171King Oscar - Wątróbki Z Dorsza W Tłuszczu Własnym OMEGA-3&#187 сприяють загальному зміцненню організму, надаючи необхідні поживні речовини та вітаміни.",
        description04: "<strong>Печінка тріски у власному соку. Містить ОМЕГА-3 жирні кислоти.</strong>",
        description05: "Насолоджуйтеся винятковим смаком і користю печінки тріски &#171King Oscar - Wątróbki Z Dorsza W Tłuszczu Własnym OMEGA-3&#187!"
    },
]