export const shopLotsWaffles = [
    {
        type: "retail",
        url: "./images/shop/food/sweets/waffles/ferrero_hanura_22.jpg",
        alt: "ferrero_hanura_22",
        url1: "./images/shop/food/sweets/waffles/ferrero_hanura_22.jpg",
        alt1: "ferrero_hanura_22",
        marker: "FDWF300",
        brand: "Ferrero",
        search: "фереро ферерро ханута шоколад шоколадные вафли с кусочками фундука фундук",
        nameUKR: "Шоколадні вафлі зі шматочками фундука",
        nameEN: "Hanuta Haselnuss-Schnitte",
        companyName: "Ferrero SpA",
        countryName: "Німеччина",
        weightName: "Вага",
        weight: "22 гр.",
        priceGRN: 15,
        quantityOnStorage: "90",
        description01: "&#171Ferrero - Hanuta Haselnuss-Schnitte&#187 - це справжня насолода для шанувальників вафель. Кожен шматочок цієї ласощі вирізняється неперевершеним поєднанням хрусткого вафельного коржика та ніжного крему з горіховою начинкою.",
        description02: "Насичений смак горіхів і вафель, робить ці вафлі відмінним вибором для сніданку, перекусу або просто забави. Вони чудово підходять для подорожей, офісу або домашнього використання.",
        description03: "Кожна &#171Ferrero - Hanuta Haselnuss-Schnitte&#187 - це результат досконалого поєднання натуральних інгредієнтів високої якості. Вони не містять штучних ароматизаторів або консервантів, що робить їх ще більш привабливими для вашого здоров'я.",
        description04: "<strong>Вафлі шоколадні, зі шматочками фундука.</strong>",
        description05: "Замовляйте вафлі &#171Ferrero - Hanuta Haselnuss-Schnitte&#187 прямо зараз і даруйте собі солодкі радощі кожен день!"
    },
    {
        type: "retail",
        url: "./images/shop/food/sweets/waffles/ferrero_hanura_220.jpg",
        alt: "ferrero_hanura_220",
        url1: "./images/shop/food/sweets/waffles/ferrero_hanura_220.jpg",
        alt1: "ferrero_hanura_220",
        marker: "FDWF320",
        brand: "Ferrero",
        search: "фереро ферерро ханута шоколад шоколадные вафли с кусочками фундука фундук",
        nameUKR: "Шоколадні вафлі зі шматочками фундука",
        nameEN: "Hanuta Haselnuss-Schnitte",
        companyName: "Ferrero SpA",
        countryName: "Німеччина",
        weightName: "Вага",
        weight: "220 гр.",
        priceGRN: 130,
        quantityOnStorage: "9",
        description01: "&#171Ferrero - Hanuta Haselnuss-Schnitte&#187 - це справжня насолода для шанувальників вафель. Кожен шматочок цієї ласощі вирізняється неперевершеним поєднанням хрусткого вафельного коржика та ніжного крему з горіховою начинкою.",
        description02: "Насичений смак горіхів і вафель, робить ці вафлі відмінним вибором для сніданку, перекусу або просто забави. Вони чудово підходять для подорожей, офісу або домашнього використання.",
        description03: "Кожна &#171Ferrero - Hanuta Haselnuss-Schnitte&#187 - це результат досконалого поєднання натуральних інгредієнтів високої якості. Вони не містять штучних ароматизаторів або консервантів, що робить їх ще більш привабливими для вашого здоров'я.",
        description04: "<strong>Вафлі шоколадні, зі шматочками фундука. 10 шт. у пачці.</strong>",
        description05: "Замовляйте вафлі &#171Ferrero - Hanuta Haselnuss-Schnitte&#187 прямо зараз і даруйте собі солодкі радощі кожен день!"
    },
    {
        type: "retail",
        url: "./images/shop/food/sweets/waffles/opavia_tatranky_cokoladove_47.jpg",
        alt: "opavia_tatranky_cokoladove_47",
        url1: "./images/shop/food/sweets/waffles/opavia_tatranky_cokoladove_47.jpg",
        alt1: "opavia_tatranky_cokoladove_47",
        marker: "FDWF500",
        brand: "Opavia",
        search: "опавия опавія татранки татранкі шоколад шоколадные вафли",
        nameUKR: "Шоколадні вафлі",
        nameEN: "Tatranky Čokoládové",
        companyName: "Mondelez s.r.o.",
        countryName: "Чехія",
        weightName: "Вага",
        weight: "47 гр.",
        priceGRN: 22,
        quantityOnStorage: "11",
        description01: "&#171Opavia - Tatranky Čokoládové&#187 - це справжній шедевр для любителів солодкого. Ці шоколадні вафлі вразять вас ніжним та густим шоколадом, що робить їх незабутніми.",
        description02: "Завдяки вишуканому поєднанню вафель та шоколаду, вони стали популярними серед всіх вікових груп. Ця солодка насолода ідеально підходить для перекусу вдома чи у дорозі.",
        description03: "Відчуйте справжню солодкість &#171Opavia - Tatranky Čokoládové&#187 і пориньте у світ насолоди. Вони заслуговують на вашу увагу!",
        description04: "<strong>Вафлі шоколадні. Без шкідливих барвників.</strong>",
        description05: "Не вагайтесь та спробуйте &#171Opavia - Tatranky Čokoládové&#187. Дозвольте собі солодку радість!"
    },
    {
        type: "retail",
        url: "./images/shop/food/sweets/waffles/opavia_tatranky_cokoladove_47_8.jpg",
        alt: "opavia_tatranky_cokoladove_47_8",
        url1: "./images/shop/food/sweets/waffles/opavia_tatranky_cokoladove_47_8.jpg",
        alt1: "opavia_tatranky_cokoladove_47_8",
        marker: "FDWF505",
        brand: "Opavia",
        search: "опавия опавія татранки татранкі шоколад шоколадные вафли",
        nameUKR: "Шоколадні вафлі",
        nameEN: "Tatranky Čokoládové",
        companyName: "Mondelez s.r.o.",
        countryName: "Чехія",
        weightName: "Вага",
        weight: "376 гр.",
        priceGRN: 160,
        quantityOnStorage: "5",
        description01: "&#171Opavia - Tatranky Čokoládové&#187 - це справжній шедевр для любителів солодкого. Ці шоколадні вафлі вразять вас ніжним та густим шоколадом, що робить їх незабутніми.",
        description02: "Завдяки вишуканому поєднанню вафель та шоколаду, вони стали популярними серед всіх вікових груп. Ця солодка насолода ідеально підходить для перекусу вдома чи у дорозі.",
        description03: "Відчуйте справжню солодкість &#171Opavia - Tatranky Čokoládové&#187 і пориньте у світ насолоди. Вони заслуговують на вашу увагу!",
        description04: "<strong>Вафлі шоколадні. Без шкідливих барвників. 8 шт. у пачці.</strong>",
        description05: "Не вагайтесь та спробуйте &#171Opavia - Tatranky Čokoládové&#187. Дозвольте собі солодку радість!"
    },
    {
        type: "retail",
        url: "./images/shop/food/sweets/waffles/opavia_tatranky_mlecne_47.jpg",
        alt: "opavia_tatranky_mlecne_47",
        url1: "./images/shop/food/sweets/waffles/opavia_tatranky_mlecne_47.jpg",
        alt1: "opavia_tatranky_mlecne_47",
        marker: "FDWF510",
        brand: "Opavia",
        search: "опавия опавія татранки татранкі шоколад шоколадные молочные вафли",
        nameUKR: "Молочно-шоколадні вафлі",
        nameEN: "Tatranky Mléčné",
        companyName: "Mondelez s.r.o.",
        countryName: "Чехія",
        weightName: "Вага",
        weight: "47 гр.",
        priceGRN: 22,
        quantityOnStorage: "13",
        description01: "&#171Opavia - Tatranky Mléčné&#187 - це неперевершене поєднання ніжного молочного крему та смачного шоколаду. Ці вафлі - справжнє задоволення для вашого смаку. Ідеально підходять для перекусу вдома чи у дорозі.",
        description02: "Завдяки вишуканому смаку і поживній цінності, вони стали улюбленими ласощами для всієї родини. Їхній хрусткий шар вафель обгорнутий ніжним молочним кремом, а все це покрите справжнім шоколадом.",
        description03: "&#171Opavia - Tatranky Mléčné&#187 - це ідеальний вибір для гурманів та тих, хто цінує справжню якість і смачний десерт.",
        description04: "<strong>Вафлі молочно-шоколадні. Без шкідливих барвників.</strong>",
        description05: "Спробуйте &#171Opavia - Tatranky Mléčné&#187 і зануртесь у безмежний світ смаку та задоволення!"
    },
    {
        type: "retail",
        url: "./images/shop/food/sweets/waffles/opavia_tatranky_orisky_47.jpg",
        alt: "opavia_tatranky_orisky_47",
        url1: "./images/shop/food/sweets/waffles/opavia_tatranky_orisky_47.jpg",
        alt1: "opavia_tatranky_orisky_47",
        marker: "FDWF520",
        brand: "Opavia",
        search: "опавия опавія татранки татранкі шоколад шоколадные c лесными орехами орешками вафли горіх горіхи горіхами",
        nameUKR: "Шоколадні вафлі з лісовими горішками",
        nameEN: "Tatranky S Lískovými Oříšky",
        companyName: "Mondelez s.r.o.",
        countryName: "Чехія",
        weightName: "Вага",
        weight: "47 гр.",
        priceGRN: 22,
        quantityOnStorage: "13",
        description01: "&#171Opavia - Tatranky S Lískovými Oříšky&#187 - це ідеальний вибір для гурманів та прихильників лісових горішків. Ці вафлі поєднують у собі ніжний смак тонких вафель, які доповнюються хрусткими, ароматними горішками.",
        description02: "Ці вафлі виготовлені з найкращих інгредієнтів з урахуванням найвищих стандартів якості. Кожен шматочок - це справжній шедевр, який піднесе настрій та подарує Вам енергію на цілий день.",
        description03: "Завдяки компактній упаковці, &#171Opavia - Tatranky S Lískovými Oříšky&#187 ідеально підходять для подорожей, перекусів на роботі або для солодкого задоволення у будь-який момент.",
        description04: "<strong>Вафлі шоколадні, з лісовими горіхами. Без шкідливих барвників.</strong>",
        description05: "Замовте &#171Opavia - Tatranky S Lískovými Oříšky&#187 сьогодні та розкажіть своїй родині історію неперевершеного задоволення!"
    },
    {
        type: "retail",
        url: "./images/shop/food/sweets/waffles/opavia_tatranky_orisky_47_8.jpg",
        alt: "opavia_tatranky_orisky_47_8",
        url1: "./images/shop/food/sweets/waffles/opavia_tatranky_orisky_47_8.jpg",
        alt1: "opavia_tatranky_orisky_47_8",
        marker: "FDWF525",
        brand: "Opavia",
        search: "опавия опавія татранки татранкі шоколад шоколадные c лесными орехами орешками вафли горіх горіхи горіхами",
        nameUKR: "Шоколадні вафлі з лісовими горішками",
        nameEN: "Tatranky S Lískovými Oříšky",
        companyName: "Mondelez s.r.o.",
        countryName: "Чехія",
        weightName: "Вага",
        weight: "376 гр.",
        priceGRN: 160,
        quantityOnStorage: "5",
        description01: "&#171Opavia - Tatranky S Lískovými Oříšky&#187 - це ідеальний вибір для гурманів та прихильників лісових горішків. Ці вафлі поєднують у собі ніжний смак тонких вафель, які доповнюються хрусткими, ароматними горішками.",
        description02: "Ці вафлі виготовлені з найкращих інгредієнтів з урахуванням найвищих стандартів якості. Кожен шматочок - це справжній шедевр, який піднесе настрій та подарує Вам енергію на цілий день.",
        description03: "Завдяки компактній упаковці, &#171Opavia - Tatranky S Lískovými Oříšky&#187 ідеально підходять для подорожей, перекусів на роботі або для солодкого задоволення у будь-який момент.",
        description04: "<strong>Вафлі шоколадні, з лісовими горіхами. Без шкідливих барвників. 8 шт. у пачці.</strong>",
        description05: "Замовте &#171Opavia - Tatranky S Lískovými Oříšky&#187 сьогодні та розкажіть своїй родині історію неперевершеного задоволення!"
    },
    {
        type: "retail",
        url: "./images/shop/food/sweets/waffles/storck_knoppers_25.jpg",
        alt: "storck_knoppers_25",
        url1: "./images/shop/food/sweets/waffles/storck_knoppers_25.jpg",
        alt1: "storck_knoppers_25",
        marker: "FDWF600",
        brand: "Storck",
        search: "сторк кноперс кнопперс шоколад шоколадные c лесными орехами орешками молочные вафли горіх горіхи горіхами ореховый крем",
        nameUKR: "Молочні вафлі з шоколадно-горіховим кремом",
        nameEN: "Knoppers",
        companyName: "Storck Sp.",
        countryName: "Польща",
        weightName: "Вага",
        weight: "25 гр.",
        priceGRN: 13,
        quantityOnStorage: "40",
        description01: "&#171Storck - Knoppers&#187 - це смачні вафлі з надзвичайною комбінацією смаків. Кожна вафелька має неперевершений смак горіхів та хрусткості вафельних шарів, що робить їх ідеальними для сніданку, перекусу або просто для задоволення.",
        description02: "Ці вафлі є зручними для подорожей, роботи або використання вдома. Вони виготовлені з пошаною і увагою до деталей, використовуючи високоякісні натуральні інгредієнти та без штучних смакових добавок або консервантів.",
        description03: "Незалежно від того, чи Ви їстимете вафлі самостійно, чи поділитеся з друзями - Ви будете насолоджуватися цими вафлями до останнього шматочка.",
        description04: "<strong>Вафлі молочні, з шоколадно-горіховим кремом.</strong>",
        description05: "Замовте &#171Storck - Knoppers&#187 та відчуйте солодку насолоду їх неперевершеного смаку!"
    },
    {
        type: "wholesale",
        url: "./images/shop/food/sweets/waffles/storck_knoppers_125.jpg",
        alt: "storck_knoppers_125",
        url1: "./images/shop/food/sweets/waffles/storck_knoppers_125.jpg",
        alt1: "storck_knoppers_125",
        marker: "FDWF605",
        brand: "Storck",
        search: "сторк кноперс кнопперс шоколад шоколадные c лесными орехами орешками молочные вафли горіх горіхи горіхами ореховый крем",
        nameUKR: "Молочні вафлі з шоколадно-горіховим кремом",
        nameEN: "Knoppers",
        companyName: "Storck Sp.",
        countryName: "Польща",
        weightName: "Вага",
        weight: "125 гр.",
        priceGRN: 62,
        priceGRNOpt: 56,
        description01: "&#171Storck - Knoppers&#187 - це смачні вафлі з надзвичайною комбінацією смаків. Кожна вафелька має неперевершений смак горіхів та хрусткості вафельних шарів, що робить їх ідеальними для сніданку, перекусу або просто для задоволення.",
        description02: "Ці вафлі є зручними для подорожей, роботи або використання вдома. Вони виготовлені з пошаною і увагою до деталей, використовуючи високоякісні натуральні інгредієнти та без штучних смакових добавок або консервантів.",
        description03: "Незалежно від того, чи Ви їстимете вафлі самостійно, чи поділитеся з друзями - Ви будете насолоджуватися цими вафлями до останнього шматочка.",
        description04: "<strong>Вафлі молочні, з шоколадно-горіховим кремом.</strong>",
        description05: "Замовте &#171Storck - Knoppers&#187 та відчуйте солодку насолоду їх неперевершеного смаку!"
    },
    {
        type: "wholesale",
        url: "./images/shop/food/sweets/waffles/storck_knoppers_200.jpg",
        alt: "storck_knoppers_200",
        url1: "./images/shop/food/sweets/waffles/storck_knoppers_200.jpg",
        alt1: "storck_knoppers_200",
        marker: "FDWF610",
        brand: "Storck",
        search: "сторк кноперс кнопперс шоколад шоколадные c лесными орехами орешками молочные вафли горіх горіхи горіхами ореховый крем",
        nameUKR: "Молочні вафлі з шоколадно-горіховим кремом",
        nameEN: "Knoppers",
        companyName: "Storck Sp.",
        countryName: "Польща",
        weightName: "Вага",
        weight: "200 гр.",
        priceGRN: 118,
        priceGRNOpt: 108,
        description01: "&#171Storck - Knoppers&#187 - це смачні вафлі з надзвичайною комбінацією смаків. Кожна вафелька має неперевершений смак горіхів та хрусткості вафельних шарів, що робить їх ідеальними для сніданку, перекусу або просто для задоволення.",
        description02: "Ці вафлі є зручними для подорожей, роботи або використання вдома. Вони виготовлені з пошаною і увагою до деталей, використовуючи високоякісні натуральні інгредієнти та без штучних смакових добавок або консервантів.",
        description03: "Незалежно від того, чи Ви їстимете вафлі самостійно, чи поділитеся з друзями - Ви будете насолоджуватися цими вафлями до останнього шматочка.",
        description04: "<strong>Вафлі молочні, з шоколадно-горіховим кремом.</strong>",
        description05: "Замовте &#171Storck - Knoppers&#187 та відчуйте солодку насолоду їх неперевершеного смаку!"
    },
    {
        type: "retail",
        url: "./images/shop/food/sweets/waffles/storck_knoppers_balck_white_25.jpg",
        alt: "storck_knoppers_balck_white_25",
        url1: "./images/shop/food/sweets/waffles/storck_knoppers_balck_white_25.jpg",
        alt1: "storck_knoppers_balck_white_25",
        marker: "FDWF615",
        brand: "Storck",
        search: "сторк кноперс кнопперс шоколад шоколадные c лесными орехами орешками молочные вафли горіх горіхи горіхами ореховый крем",
        nameUKR: "Молочні вафлі з шоколадно-горіховим кремом",
        nameEN: "Knoppers Black & White",
        companyName: "Storck Sp.",
        countryName: "Німеччина",
        weightName: "Вага",
        weight: "25 гр.",
        priceGRN: 13,
        quantityOnStorage: "40",
        description01: "&#171Storck - Knoppers Black & White&#187 - це смаковиті вафлі, які припадуть до душі шанувальникам чорно-білої комбінації. Кожен шматочок цих вафель має неперевершений смак та текстуру. Кремова начинка з натурального молока і хрусткі горіхи створюють вишукану симфонію смаків.",
        description02: "Завдяки використанню натуральних інгредієнтів без штучних ароматизаторів і консервантів, ці вафлі створюють неповторне задоволення для справжніх гурманів.",
        description03: "&#171Storck - Knoppers Black & White&#187 стане ідеальним доповненням до чаю або кави, а також прекрасним варіантом для швидкого перекусу вдома або в дорозі.",
        description04: "<strong>Вафлі молочні, з шоколадно-горіховим кремом.</strong>",
        description05: "Спробуйте &#171Storck - Knoppers Black & White&#187 і насолоджуйтесь піднесеним смаком та неперевершеною якістю!"
    },
    {
        type: "wholesale",
        url: "./images/shop/food/sweets/waffles/storck_knoppers_balck_white_200.jpg",
        alt: "storck_knoppers_balck_white_200",
        url1: "./images/shop/food/sweets/waffles/storck_knoppers_balck_white_200.jpg",
        alt1: "storck_knoppers_balck_white_200",
        marker: "FDWF625",
        brand: "Storck",
        search: "сторк кноперс кнопперс шоколад шоколадные c лесными орехами орешками молочные вафли горіх горіхи горіхами ореховый крем",
        nameUKR: "Молочні вафлі з шоколадно-горіховим кремом",
        nameEN: "Knoppers Black & White",
        companyName: "Storck Sp.",
        countryName: "Німеччина",
        weightName: "Вага",
        weight: "200 гр.",
        priceGRN: 118,
        priceGRNOpt: 108,
        description01: "&#171Storck - Knoppers Black & White&#187 - це смаковиті вафлі, які припадуть до душі шанувальникам чорно-білої комбінації. Кожен шматочок цих вафель має неперевершений смак та текстуру. Кремова начинка з натурального молока і хрусткі горіхи створюють вишукану симфонію смаків.",
        description02: "Завдяки використанню натуральних інгредієнтів без штучних ароматизаторів і консервантів, ці вафлі створюють неповторне задоволення для справжніх гурманів.",
        description03: "&#171Storck - Knoppers Black & White&#187 стане ідеальним доповненням до чаю або кави, а також прекрасним варіантом для швидкого перекусу вдома або в дорозі.",
        description04: "<strong>Вафлі молочні, з шоколадно-горіховим кремом.</strong>",
        description05: "Спробуйте &#171Storck - Knoppers Black & White&#187 і насолоджуйтесь піднесеним смаком та неперевершеною якістю!"
    },
    {
        type: "retail",
        url: "./images/shop/food/sweets/waffles/storck_knoppers_erdnuss_25.jpg",
        alt: "storck_knoppers_erdnuss_25",
        url1: "./images/shop/food/sweets/waffles/storck_knoppers_erdnuss_25.jpg",
        alt1: "storck_knoppers_erdnuss_25",
        marker: "FDWF630",
        brand: "Storck",
        search: "сторк кноперс кнопперс шоколад шоколадные молочные вафли арахіс арахис арахисовым крем",
        nameUKR: "Молочні вафлі з шоколадно-арахісовим кремом",
        nameEN: "Knoppers Erdnuss",
        companyName: "Storck Sp.",
        countryName: "Німеччина",
        weightName: "Вага",
        weight: "25 гр.",
        priceGRN: 13,
        quantityOnStorage: "40",
        description01: "&#171Storck - Knoppers Erdnuss&#187 - стануть ідеальним доповненням до вашого шаленого ритму життя, оскільки вони можуть задовольнити ваші солодкі і потреби у енергіх на цілий день.",
        description02: "Вони мають неповторний смак, який вас зачарує. Містять у собі натуральні інгредієнти, такі як яйця, молоко та арахіс. Кожна вафля виробляється з великою увагою до деталей, щоб Вам завжди було смачно і корисно.",
        description03: "&#171Storck - Knoppers Erdnuss&#187 є ідеальною закускою для Вас і вашої родини. Вони можуть бути чудовим додатком до кави або чаю.",
        description04: "<strong>Вафлі молочні, з шоколадно-арахісовим кремом.</strong>",
        description05: "Насолоджуйтесь смаком вафель &#171Storck - Knoppers Erdnuss&#187 та додайте енергії своєму дню!"
    },
    {
        type: "wholesale",
        url: "./images/shop/food/sweets/waffles/storck_knoppers_erdnuss_200.jpg",
        alt: "storck_knoppers_erdnuss_200",
        url1: "./images/shop/food/sweets/waffles/storck_knoppers_erdnuss_200.jpg",
        alt1: "storck_knoppers_erdnuss_200",
        marker: "FDWF640",
        brand: "Storck",
        search: "сторк кноперс кнопперс шоколад шоколадные молочные вафли арахіс арахис арахисовым крем",
        nameUKR: "Молочні вафлі з шоколадно-арахісовим кремом",
        nameEN: "Knoppers Erdnuss",
        companyName: "Storck Sp.",
        countryName: "Німеччина",
        weightName: "Вага",
        weight: "200 гр.",
        priceGRN: 118,
        priceGRNOpt: 108,
        description01: "&#171Storck - Knoppers Erdnuss&#187 - стануть ідеальним доповненням до вашого шаленого ритму життя, оскільки вони можуть задовольнити ваші солодкі і потреби у енергіх на цілий день.",
        description02: "Вони мають неповторний смак, який вас зачарує. Містять у собі натуральні інгредієнти, такі як яйця, молоко та арахіс. Кожна вафля виробляється з великою увагою до деталей, щоб Вам завжди було смачно і корисно.",
        description03: "&#171Storck - Knoppers Erdnuss&#187 є ідеальною закускою для Вас і вашої родини. Вони можуть бути чудовим додатком до кави або чаю.",
        description04: "<strong>Вафлі молочні, з шоколадно-арахісовим кремом.</strong>",
        description05: "Насолоджуйтесь смаком вафель &#171Storck - Knoppers Erdnuss&#187 та додайте енергії своєму дню!"
    },
    {
        type: "retail",
        url: "./images/shop/food/sweets/waffles/storck_knoppers_joghurt_25.jpg",
        alt: "storck_knoppers_joghurt_25",
        url1: "./images/shop/food/sweets/waffles/storck_knoppers_joghurt_25.jpg",
        alt1: "storck_knoppers_joghurt_25",
        marker: "FDWF645",
        brand: "Storck",
        search: "сторк кноперс кнопперс шоколад шоколадные c лесными орехами орешками молочные вафли горіх горіхи горіхами ореховый крем йогурт с йогуртом",
        nameUKR: "Молочні вафлі зі смаком йогурту та горіховим кремом",
        nameEN: "Knoppers Joghurt",
        companyName: "Storck Sp.",
        countryName: "Німеччина",
        weightName: "Вага",
        weight: "25 гр.",
        priceGRN: 13,
        quantityOnStorage: "40",
        description01: "&#171Storck - Knoppers Joghurt&#187 - це справжнє задоволення для вашого смаку. Ці хрусткі вафлі з ніжним молочним начинням і хрусткими лісовими горіхами в захоплюючий спосіб поєднують усе, що ви любите у вафлях.",
        description02: "Це по-справжньому унікальне поєднання хрустких вафлів, ніжного молочного начиння та хрустких горіхів. Якщо Ви любите хрустку текстуру і насолоджуватися ніжним смаком молока, ці вафлі точно для вас.",
        description03: "&#171Storck - Knoppers Joghurt&#187 - це не тільки смаколики, але і зручний перекус для поділу з друзями. Завдяки їхньому порційному розміру, ви можете зручно поділитися ними з рідними або друзями.",
        description04: "<strong>Вафлі молочні, зі смаком йогурту та горіховим кремом.</strong>",
        description05: "Замовляйте вже сьогодні &#171Storck - Knoppers Joghurt&#187 і насолоджуйтеся неперевершеним смаком!"
    },
    {
        type: "wholesale",
        url: "./images/shop/food/sweets/waffles/storck_knoppers_joghurt_200.jpg",
        alt: "storck_knoppers_joghurt_200",
        url1: "./images/shop/food/sweets/waffles/storck_knoppers_joghurt_200.jpg",
        alt1: "storck_knoppers_joghurt_200",
        marker: "FDWF655",
        brand: "Storck",
        search: "сторк кноперс кнопперс шоколад шоколадные c лесными орехами орешками молочные вафли горіх горіхи горіхами ореховый крем йогурт с йогуртом",
        nameUKR: "Молочні вафлі зі смаком йогурту та горіховим кремом",
        nameEN: "Knoppers Joghurt",
        companyName: "Storck Sp.",
        countryName: "Німеччина",
        weightName: "Вага",
        weight: "200 гр.",
        priceGRN: 118,
        priceGRNOpt: 108,
        description01: "&#171Storck - Knoppers Joghurt&#187 - це справжнє задоволення для вашого смаку. Ці хрусткі вафлі з ніжним молочним начинням і хрусткими лісовими горіхами в захоплюючий спосіб поєднують усе, що ви любите у вафлях.",
        description02: "Це по-справжньому унікальне поєднання хрустких вафлів, ніжного молочного начиння та хрустких горіхів. Якщо Ви любите хрустку текстуру і насолоджуватися ніжним смаком молока, ці вафлі точно для вас.",
        description03: "&#171Storck - Knoppers Joghurt&#187 - це не тільки смаколики, але і зручний перекус для поділу з друзями. Завдяки їхньому порційному розміру, ви можете зручно поділитися ними з рідними або друзями.",
        description04: "<strong>Вафлі молочні, зі смаком йогурту та горіховим кремом.</strong>",
        description05: "Замовляйте вже сьогодні &#171Storck - Knoppers Joghurt&#187 і насолоджуйтеся неперевершеним смаком!"
    },
    {
        type: "wholesale",
        url: "./images/shop/food/sweets/waffles/tasso_wafelki_kakao_450.jpg",
        alt: "tasso_wafelki_kakao_450",
        url1: "./images/shop/food/sweets/waffles/tasso_wafelki_kakao_450.jpg",
        alt1: "tasso_wafelki_kakao_450",
        marker: "FDWF700",
        brand: "Tasso",
        search: "тассо шоколад шоколадные вафли крем какао с какаовым",
        nameUKR: "Вафлі з какаовим кремом",
        nameEN: "Wafelki Z Kremem Kakaowym",
        companyName: "Jeronimo Martins Polska S.A.",
        countryName: "Польща",
        weightName: "Вага",
        weight: "450 гр.",
        priceGRN: 83,
        priceGRNOpt: 75,
        description01: "&#171Tasso - Wafelki Z Kremem Kakaowym&#187 - це справжній рай для гурманів. Ці вафлі вражають найсміливіше поєднанням ніжного крему з богатим шоколадним смаком. Вас приголомшить їхній неперевершений смак та тонкий шар хрусткої вафлі, який навколо них.",
        description02: "Ідеально підходять для солодкого перекусу або на вечірню чашку кави. Завдяки своїй оригінальності та бездоганному смаку, вони стануть справжньою знахідкою для цінителів солодощів.",
        description03: "Відкрийте для себе новий рівень насолоди разом з &#171Tasso - Wafelki Z Kremem Kakaowym&#187.",
        description04: "<strong>Вафлі з какаовим кремом. Без шкідливих барвників.</strong>",
        description05: "Замовляйте &#171Tasso - Wafelki Z Kremem Kakaowym&#187 прямо зараз та насолоджуйтесь бездоганним смаком!"
    },
    {
        type: "wholesale",
        url: "./images/shop/food/sweets/waffles/tasso_wafelki_orech_450.jpg",
        alt: "tasso_wafelki_orech_450",
        url1: "./images/shop/food/sweets/waffles/tasso_wafelki_orech_450.jpg",
        alt1: "tasso_wafelki_orech_450",
        marker: "FDWF710",
        brand: "Tasso",
        search: "тассо шоколад шоколадные c лесными орехами орешками вафли горіх горіхи горіхами крем",
        nameUKR: "Вафлі з горіховим кремом",
        nameEN: "Wafelki Z Kremem Orzechowym",
        companyName: "Jeronimo Martins Polska S.A.",
        countryName: "Польща",
        weightName: "Вага",
        weight: "450 гр.",
        priceGRN: 83,
        priceGRNOpt: 75,
        description01: "&#171Tasso - Wafelki Z Kremem Orzechowym&#187 - це чудовий десерт для справжніх гурманів. Кожна вафелька - це майстерність і справжній шедевр у світі солодощів. Ці вафлі вражають своєю хрусткою текстурою і ніжним, ароматним кремом зі смаженими горішками.",
        description02: "Солодкий і незвичайно смачний смак цих вафель зачаровує. Вони додають енергії і настрою під час перекусів, дарують миті радості та задоволення.",
        description03: "Завдяки індивідуальній упаковці, &#171Tasso - Wafelki Z Kremem Orzechowym&#187 ідеально підходять для подорожей, перекусів на роботі чи просто для задоволення вдома.",
        description04: "<strong>Вафлі з горіховим кремом. Без шкідливих барвників.</strong>",
        description05: "Спробуйте цей неперевершений смак і дозвольте собі відкрити нові гастрономічні горизонти разом з &#171Tasso - Wafelki Z Kremem Orzechowym&#187!"
    },
]