export const shopLotsSauces = [
    // {
    //     type: "retail",
    // mainCategory: "foodstuffs",
        // subcategory: "taste-modifiers",    
    // url: "./images/shop/food/taste_modifier/sauces/asia_gold_thai_hot_chili_700.jpg",
    //     alt: "asia_gold_thai_hot_chili_700",
    //     url1: "./images/shop/food/taste_modifier/sauces/asia_gold_thai_hot_chili_700.jpg",
    //     alt1: "asia_gold_thai_hot_chili_700",
    //     marker: "FDSU010",
    //     brand: "Asia Gold",
    //     search: "азия азія голд перець гострі острый острые соуси соусы",
    //     nameUKR: "Гострий соус",
    //     nameEN: "Thai Hot Chili Sauce",
    //     companyName: "Asia Gold Ltd.",
    //     countryName: "Німеччина",
    //     volumeName: "Об'єм",
    //     volume: "700 мл.",
    //     priceGRN: 88,
    //     quantityOnStorage: "5",
    //     description01: "&#171Asia Gold - Thai Hot Chili Sauce&#187 - це справжній скарб для прихильників гострих смаків. Цей соус - поєднання традиційного тайського смаку та неймовірної гостроти, яка запалює с першої спроби.",
    //     description02: "Завдяки унікальній рецептурі, цей соус створений для того, щоб робити ваші страви неперевершеними. Використовуйте його для маринування м'яса, смаження, або як соус для суші. Що б ви не обрали, він неодмінно зробить ваші страви незабутніми.",
    //     description03: "Зараз настав час приготувати справжню гостреньку феєрію на вашому столі. І у цьому Вам допоможе &#171Asia Gold - Thai Hot Chili Sauce&#187.",
    //     description04: "<strong>Соус гострий. Не містить шкідливих барвників.</strong>",
    //     description05: "Замовте &#171Asia Gold - Thai Hot Chili Sauce&#187 вже сьогодні та дозвольте собі насолодитися смаком Таїланду, не виходячи з дому!"
    // },
    // {
    //     type: "retail",
    // mainCategory: "foodstuffs",
        // subcategory: "taste-modifiers",    
    // url: "./images/shop/food/taste_modifier/sauces/asia_gold_thai_hot_chili_700.jpg",
    //     alt: "asia_gold_thai_hot_chili_700",
    //     url1: "./images/shop/food/taste_modifier/sauces/asia_gold_thai_hot_chili_700.jpg",
    //     alt1: "asia_gold_thai_hot_chili_700",
    //     marker: "FDSU012",
    //     brand: "Asia Gold",
    //     search: "азия азія голд перець гострі острый острые соуси соусы",
    //     nameUKR: "Гострий соус",
    //     nameEN: "Thai Hot Chili Sauce",
    //     companyName: "Asia Gold Ltd.",
    //     countryName: "Німеччина",
    //     volumeName: "Об'єм",
    //     volume: "700 мл.",
    //     priceGRN: 88,
    //     quantityOnStorage: "5",
    //     description01: "&#171Asia Gold - Thai Hot Chili Sauce&#187 - це справжній скарб для прихильників гострих смаків. Цей соус - поєднання традиційного тайського смаку та неймовірної гостроти, яка запалює с першої спроби.",
    //     description02: "Завдяки унікальній рецептурі, цей соус створений для того, щоб робити ваші страви неперевершеними. Використовуйте його для маринування м'яса, смаження, або як соус для суші. Що б ви не обрали, він неодмінно зробить ваші страви незабутніми.",
    //     description03: "Зараз настав час приготувати справжню гостреньку феєрію на вашому столі. І у цьому Вам допоможе &#171Asia Gold - Thai Hot Chili Sauce&#187.",
    //     description04: "<strong>Соус гострий. Не містить шкідливих барвників.</strong>",
    //     description05: "Замовте &#171Asia Gold - Thai Hot Chili Sauce&#187 вже сьогодні та дозвольте собі насолодитися смаком Таїланду, не виходячи з дому!"
    // },
    // {
    //     type: "retail",
    // mainCategory: "foodstuffs",
        // subcategory: "taste-modifiers",    
    // url: "./images/shop/food/taste_modifier/sauces/barilla_arrabbiata_400.jpg",
    //     alt: "barilla_arrabbiata_400",
    //     url1: "./images/shop/food/taste_modifier/sauces/barilla_arrabbiata_400.jpg",
    //     alt1: "barilla_arrabbiata_400",
    //     marker: "FDSU020",
    //     brand: "Barilla",
    //     search: "барила барилла баріла барілла томат томатный томатные томантні соус перець гострі острый острые соуси соусы помідор помідори помидор помидоры",
    //     nameUKR: "Гострий томатний соус",
    //     nameEN: "Arrabbiata",
    //     companyName: "Barilla G. e R.",
    //     countryName: "Італія",
    //     weightName: "Вага",
    //     weight: "400 гр.",
    //     priceGRN: 94,
    //     quantityOnStorage: "9",
    //     description01: "&#171Barilla - Arrabbiata&#187 - це італійський вогняний шедевр для справжніх поціновувачів пікантних смаків. Цей соус відзначається багатим томатним смаком, який набуває особливого гострого відтінку завдяки чилі перцю.",
    //     description02: "Його текстура м'якка і насичена, ідеально підходить для приготування пасти, піци, або як гарнір до м'ясних страв. З ним Ви зможете легко створити страви з італійським смаком, які вразять навіть найвибагливіших гурманів.",
    //     description03: "Проведіть кулінарну подорож до Італії, не покидаючи свою кухню, завдяки цьому гострому томатному соусу. Додайте &#171Barilla - Arrabbiata&#187 до вашого щоденного меню та насолоджуйтеся італійським гострим смаком.",
    //     description04: "<strong>Соус томатний, гострий. Не містить шкідливих барвників.</strong>",
    //     description05: "Спробуйте цей вогняний соус &#171Barilla - Arrabbiata&#187 і додайте трішки пікантності до свого життя!"
    // },
    // {
    //     type: "retail",
    // mainCategory: "foodstuffs",
        // subcategory: "taste-modifiers",    
    // url: "./images/shop/food/taste_modifier/sauces/barilla_base_per_bolognese_400.jpg",
    //     alt: "barilla_base_per_bolognese_400",
    //     url1: "./images/shop/food/taste_modifier/sauces/barilla_base_per_bolognese_400.jpg",
    //     alt1: "barilla_base_per_bolognese_400",
    //     marker: "FDSU025",
    //     brand: "Barilla",
    //     search: "барила барилла баріла барілла томат томатный томатные томантні соус соуси соусы помідор помідори помидор помидоры болоньезе болоньєзе",
    //     nameUKR: "Томатний соус",
    //     nameEN: "Base Per Bolognese",
    //     companyName: "Barilla G. e R.",
    //     countryName: "Італія",
    //     weightName: "Вага",
    //     weight: "400 гр.",
    //     priceGRN: 94,
    //     quantityOnStorage: 3,
    //     description01: "&#171Barilla - Base Per Bolognese&#187 - томатний соус, який вражає не лише своїм італійським корінням, а й неперевершеним смаком.",
    //     description02: "Цей соус виготовлено зі смачних італійських томатів - ключ до створення найсмачніших болоньєзе.",
    //     description03: "&#171Barilla - Base Per Bolognese&#187 робить кожну страву справжнім шедевром, наповнюючи її ароматом та смаком Італії.",
    //     description04: "<strong>Соус томатний. Не містить шкідливих барвників.</strong>",
    //     description05: "Додайте італійський колорит до вашого столу та замовте &#171Barilla - Base Per Bolognese&#187 вже зараз і насолоджуйтеся італійськими смаками у кожному приготованому вами обіді!"
    // },
    // {
    //     type: "retail",
    // mainCategory: "foodstuffs",
        // subcategory: "taste-modifiers",    
    // url: "./images/shop/food/taste_modifier/sauces/barilla_basilico_400.jpg",
    //     alt: "barilla_basilico_400",
    //     url1: "./images/shop/food/taste_modifier/sauces/barilla_basilico_400.jpg",
    //     alt1: "barilla_basilico_400",
    //     marker: "FDSU030",
    //     brand: "Barilla",
    //     search: "барила барилла баріла барілла томат томатный томатные томантні соус соуси соусы помідор помідори помидор помидоры базилік базилик с базиликом",
    //     nameUKR: "Томатний соус з базиліком",
    //     nameEN: "Basilico",
    //     companyName: "Barilla G. e R.",
    //     countryName: "Італія",
    //     weightName: "Вага",
    //     weight: "400 гр.",
    //     priceGRN: 94,
    //     quantityOnStorage: 2,
    //     description01: "&#171Barilla - Basilico&#187 - це справжня італійська смакова експлозія, яка перетворить ваші страви у шедеври кулінарного мистецтва. Відома своєю яскравою томатною основою та ароматом свіжого базиліку, цей соус надасть вашим стравам неперевершений смак.",
    //     description02: "Цей соус виготовляється з найкращих інгредієнтів за італійськими рецептами, і саме це робить його особливим. Ідеально підходить для пасти, піци, ласощів з риби або м'яса, і навіть як підсмажування для сендвічів.",
    //     description03: "Завдяки своєму свіжому смаку та текстурі, &#171Barilla - Basilico&#187 стає незамінним атрибутом будь-якого гурмана. Надайте вашим стравам італійський акцент і переконайтесь в його бездоганному смаку.",
    //     description04: "<strong>Соус томатний з базиліком. Не містить шкідливих барвників.</strong>",
    //     description05: "Не гайте часу - спробуйте цей чудовий томатний соус &#171Barilla - Basilico&#187 із базиліком вже сьогодні і перетворіть свої страви на справжні шедеври!"
    // },
    // {
    //     type: "retail",
    // mainCategory: "foodstuffs",
        // subcategory: "taste-modifiers",    
    // url: "./images/shop/food/taste_modifier/sauces/barilla_basilico_400a.jpg",
    //     alt: "barilla_basilico_400a",
    //     marker: "FDSU031",
    //     brand: "Barilla",
    //     search: "барила барилла баріла барілла томат томатный томатные томантні соус соуси соусы помідор помідори помидор помидоры базилік базилик с базиликом",
    //     nameUKR: "Томатний соус з базиліком",
    //     nameEN: "Basilico",
    //     companyName: "Barilla G. e R.",
    //     countryName: "Італія",
    //     weightName: "Вага",
    //     weight: "400 гр.",
    //     priceGRN: 94,
    //     quantityOnStorage: "9",
    //     description01: "&#171Barilla - Basilico&#187 - це справжня італійська смакова експлозія, яка перетворить ваші страви у шедеври кулінарного мистецтва. Відома своєю яскравою томатною основою та ароматом свіжого базиліку, цей соус надасть вашим стравам неперевершений смак.",
    //     description02: "Цей соус виготовляється з найкращих інгредієнтів за італійськими рецептами, і саме це робить його особливим. Ідеально підходить для пасти, піци, ласощів з риби або м'яса, і навіть як підсмажування для сендвічів.",
    //     description03: "Завдяки своєму свіжому смаку та текстурі, &#171Barilla - Basilico&#187 стає незамінним атрибутом будь-якого гурмана. Надайте вашим стравам італійський акцент і переконайтесь в його бездоганному смаку.",
    //     description04: "<strong>Соус томатний з базиліком. Не містить шкідливих барвників.</strong>",
    //     description05: "Не гайте часу - спробуйте цей чудовий томатний соус &#171Barilla - Basilico&#187 із базиліком вже сьогодні і перетворіть свої страви на справжні шедеври!"
    // },
    // {
    //     type: "retail",
    // mainCategory: "foodstuffs",
        // subcategory: "taste-modifiers",    
    // url: "./images/shop/food/taste_modifier/sauces/barilla_bolognese_400.jpg",
    //     alt1: "barilla_bolognese_400",
    //     url1: "./images/shop/food/taste_modifier/sauces/barilla_bolognese_400.jpg",
    //     alt: "barilla_bolognese_400",
    //     marker: "FDSU035",
    //     brand: "Barilla",
    //     search: "барила барилла баріла барілла томат томатный томатные томантні соус соуси соусы помідор помідори помидор помидоры болоньезе болоньєзе",
    //     nameUKR: "Томатний соус для спагеті",
    //     nameEN: "Bolognese",
    //     companyName: "Barilla G. e R.",
    //     countryName: "Італія",
    //     weightName: "Вага",
    //     weight: "400 гр.",
    //     priceGRN: 122,
    //     quantityOnStorage: "9",
    //     description01: "&#171Barilla - Bolognese&#187 - це справжній шедевр італійської кухні, який перетворить ваші страви у надзвичайну сопокусу. Цей соус відзначається неперевершеним поєднанням томатів та ароматних приправ, які створюють неповторний смак.",
    //     description02: "Ідеальний соус для паст, лазаньї, різноманітних м'ясних страв і навіть піци. Його густа структура і насичений смак нададуть вашим стравам італійську автентичність, якою можна насолоджуватися у затишку власного дому.",
    //     description03: "Завдяки традиційному рецепту та високій якості інгредієнтів, &#171Barilla - Bolognese&#187 стане вашим незамінним помічником у кулінарних пригодах. Спробуйте цей соус і відкрийте для себе найсмачніший шлях до італійського смаку.",
    //     description04: "<strong>Соус томатний для спагеті. Не містить шкідливих барвників.</strong>",
    //     description05: "Зробіть свої страви надзвичайно смачними з &#171Barilla - Bolognese&#187 та відправляйтесь на справжню кулінарну подорож до Італії!"
    // },
    // {
    //     type: "retail",
    // mainCategory: "foodstuffs",
        // subcategory: "taste-modifiers",    
    // url: "./images/shop/food/taste_modifier/sauces/barilla_napoletana_400.jpg",
    //     alt: "barilla_napoletana_400",
    //     url1: "./images/shop/food/taste_modifier/sauces/barilla_napoletana_400.jpg",
    //     alt1: "barilla_napoletana_400",
    //     marker: "FDSU040",
    //     brand: "Barilla",
    //     search: "барила барилла баріла барілла томат томатный томатные томантні соус соуси соусы помідор помідори помидор помидоры",
    //     nameUKR: "Томатний соус",
    //     nameEN: "Napoletana",
    //     companyName: "Barilla G. e R.",
    //     countryName: "Італія",
    //     weightName: "Вага",
    //     weight: "400 гр.",
    //     priceGRN: 94,
    //     quantityOnStorage: "9",
    //     description01: "&#171Barilla - Napoletana&#187 - справжній шедевр італійської кулінарії. Цей соус відомий своєю насиченою томатною основою, яка виготовляється із соковитих помідорів з регіону Кампанія. Він має легкий, натуральний смак і аромат, які переносять Вас до сонячної Італії.",
    //     description02: "Ідеальний вибір для приготування італійських страв, таких як паста або піца. Він чудово поєднується з інгредієнтами вашого вибору, додаючи смак та аромат.",
    //     description03: "Завдяки вишуканому складу італійських традицій, &#171Barilla - Napoletana&#187 - це гарантія якості та смаку. Поспішайте розвинути свою кулінарну майстерність і створити шедеври з цим соусом.",
    //     description04: "<strong>Соус томатний, классичний. Не містить шкідливих барвників.</strong>",
    //     description05: "Не вагайтеся, спробуйте &#171Barilla - Napoletana&#187 та підкоріть смак Італії прямо на вашій кухні!"
    // },
    // {
    //     type: "retail",
    // mainCategory: "foodstuffs",
        // subcategory: "taste-modifiers",    
    // url: "./images/shop/food/taste_modifier/sauces/barilla_napoletana_400a.jpg",
    //     alt: "barilla_napoletana_400a",
    //     marker: "FDSU040a",
    //     brand: "Barilla",
    //     search: "барила барилла баріла барілла томат томатный томатные томантні соус соуси соусы помідор помідори помидор помидоры",
    //     nameUKR: "Томатний соус",
    //     nameEN: "Napoletana",
    //     companyName: "Barilla G. e R.",
    //     countryName: "Італія",
    //     weightName: "Вага",
    //     weight: "400 гр.",
    //     priceGRN: 94,
    //     quantityOnStorage: 1,
    //     description01: "&#171Barilla - Napoletana&#187 - справжній шедевр італійської кулінарії. Цей соус відомий своєю насиченою томатною основою, яка виготовляється із соковитих помідорів з регіону Кампанія. Він має легкий, натуральний смак і аромат, які переносять Вас до сонячної Італії.",
    //     description02: "Ідеальний вибір для приготування італійських страв, таких як паста або піца. Він чудово поєднується з інгредієнтами вашого вибору, додаючи смак та аромат.",
    //     description03: "Завдяки вишуканому складу італійських традицій, &#171Barilla - Napoletana&#187 - це гарантія якості та смаку. Поспішайте розвинути свою кулінарну майстерність і створити шедеври з цим соусом.",
    //     description04: "<strong>Соус томатний, классичний. Не містить шкідливих барвників.</strong>",
    //     description05: "Не вагайтеся, спробуйте &#171Barilla - Napoletana&#187 та підкоріть смак Італії прямо на вашій кухні!"
    // },
    // {
    //     type: "retail",
    // mainCategory: "foodstuffs",
        // subcategory: "taste-modifiers",    
    // url: "./images/shop/food/taste_modifier/sauces/barilla_olive_400.jpg",
    //     alt: "barilla_olive_400",
    //     url1: "./images/shop/food/taste_modifier/sauces/barilla_olive_400.jpg",
    //     alt1: "barilla_olive_400",
    //     marker: "FDSU045",
    //     brand: "Barilla",
    //     search: "барила барилла баріла барілла томат томатный томатные томантні соус соуси соусы помідор помідори помидор помидоры оливки с оливками",
    //     nameUKR: "Томатний соус з оливками",
    //     nameEN: "Olive",
    //     companyName: "Barilla G. e R.",
    //     countryName: "Італія",
    //     weightName: "Вага",
    //     weight: "400 гр.",
    //     priceGRN: 94,
    //     quantityOnStorage: "9",
    //     description01: "&#171Barilla - Olive&#187 - це справжній шедевр італійської кулінарії, який надає вашим стравам неповторний смак та аромат. Завдяки найкращим інгредієнтам і вишуканому рецепту, цей соус вирізняється свіжістю та смаковим багатством.",
    //     description02: "Основою цього соусу є соковиті помідори, які готуються зі шматочками смачних оливок. Ця комбінація надає соусу неповторний аромат та приємний горіховий смак, що чудово поєднується з різноманітними стравами.",
    //     description03: "&#171Barilla - Olive&#187 ідеально підходить для приготування паст, ризотто, піци та інших італійських страв. Його можна використовувати як основний інгредієнт або додаток до інших страв для надання їм більш насиченого смаку.",
    //     description04: "<strong>Соус томатний, зі шматочками оливок. Не містить шкідливих барвників.</strong>",
    //     description05: "Спробуйте &#171Barilla - Olive&#187 і додайте італійського смаку своїм стравам!"
    // },
    // {
    //     type: "retail",
    // mainCategory: "foodstuffs",
        // subcategory: "taste-modifiers",    
    // url: "./images/shop/food/taste_modifier/sauces/barilla_ricotta_400.jpg",
    //     alt: "barilla_ricotta_400",
    //     url1: "./images/shop/food/taste_modifier/sauces/barilla_ricotta_400.jpg",
    //     alt1: "barilla_ricotta_400",
    //     marker: "FDSU050",
    //     brand: "Barilla",
    //     search: "барила барилла баріла барілла томат томатный томатные томантні соус соуси соусы помідор помідори помидор помидоры рикота рикотта рікота рікотта",
    //     nameUKR: "Томатний соус з сиром &#171Рікотта&#187",
    //     nameEN: "Ricotta",
    //     companyName: "Barilla G. e R.",
    //     countryName: "Італія",
    //     weightName: "Вага",
    //     weight: "400 гр.",
    //     priceGRN: 94,
    //     quantityOnStorage: "9",
    //     description01: "&#171Barilla - Ricotta&#187 - томатний соус, який вражає витонченим поєднанням томатів та ніжного смаку рікотти. Це не просто соус, а справжній кулінарний шедевр.",
    //     description02: "Це унікальна італійська рецептура, в якій зустрічаються найсоковитіші томати та ніжна рікотта. Смак, що заворожує, створений для тих, хто цінує вишуканість.",
    //     description03: "&#171Barilla - Ricotta&#187 додасть вашим стравам вишуканості та неперевершеної смакової глибини.",
    //     description04: "<strong>Соус томатний з сиром &#171Рікотта&#187. Не містить шкідливих барвників.</strong>",
    //     description05: "Замовте сьогодні та додайте власну нотку італійської смакоти до вашого столу з &#171Barilla - Ricotta&#187 - ексклюзивного соусу для тих, хто цінує смакові враження!"
    // },
    // {
    //     type: "retail",
    // mainCategory: "foodstuffs",
        // subcategory: "taste-modifiers",    
    // url: "./images/shop/food/taste_modifier/sauces/barilla_olive_400a.jpg",
    //     alt: "barilla_olive_400a",
    //     marker: "FDSU045a",
    //     brand: "Barilla",
    //     search: "барила барилла баріла барілла томат томатный томатные томантні соус соуси соусы помідор помідори помидор помидоры оливки с оливками",
    //     nameUKR: "Томатний соус з оливками",
    //     nameEN: "Olive",
    //     companyName: "Barilla G. e R.",
    //     countryName: "Італія",
    //     weightName: "Вага",
    //     weight: "400 гр.",
    //     priceGRN: 94,
    //     quantityOnStorage: "9",
    //     description01: "&#171Barilla - Olive&#187 - це справжній шедевр італійської кулінарії, який надає вашим стравам неповторний смак та аромат. Завдяки найкращим інгредієнтам і вишуканому рецепту, цей соус вирізняється свіжістю та смаковим багатством.",
    //     description02: "Основою цього соусу є соковиті помідори, які готуються зі шматочками смачних оливок. Ця комбінація надає соусу неповторний аромат та приємний горіховий смак, що чудово поєднується з різноманітними стравами.",
    //     description03: "&#171Barilla - Olive&#187 ідеально підходить для приготування паст, ризотто, піци та інших італійських страв. Його можна використовувати як основний інгредієнт або додаток до інших страв для надання їм більш насиченого смаку.",
    //     description04: "<strong>Соус томатний, зі шматочками оливок. Не містить шкідливих барвників.</strong>",
    //     description05: "Спробуйте &#171Barilla - Olive&#187 і додайте італійського смаку своїм стравам!"
    // },
    {
        type: "only-wholesale оптом",
        mainCategory: "foodstuffs",
        subcategory: "taste-modifiers",
        url: "./images/shop/food/taste_modifier/sauces/bio_natura_passierte_tomaten_690.jpg",
        alt: "bio_natura_passierte_tomaten_690",
        url1: "./images/shop/food/taste_modifier/sauces/bio_natura_passierte_tomaten_690.jpg",
        alt1: "bio_natura_passierte_tomaten_690",
        marker: "FDSU090",
        brand: "Bio Natura",
        search: "томат томатный томатные томантні соус соуси соусы помідор помідори помидор помидоры",
        nameUKR: "Томатний соус",
        nameEN: "Passierte Tomaten",
        companyName: "Le Due Valli SRL",
        countryName: "Швейцарія",
        weightName: "Вага",
        weight: "690 гр.",
        priceGRN: "--",
        priceGRNOpt: 103,
        description01: "&#171Bio Natura - Passierte Tomaten&#187 - томатний соус, який зберігає смак природи та багатство корисних речовин. Він завоював серця гурманів та тих, хто цінує найвищу якість без зайвих добавок.",
        description02: "Цей соус виготовлений з найсоковитіших томатів, вирощених без хімічних добрив та пестицидів. Він стане відмінним вибором для тих, хто цінує смак і дбає про здоров'я.",
        description03: "&#171Bio Natura - Passierte Tomaten&#187 - це чистий та смачний продукт, який робить ваші страви неперевершеними, додаючи нотку екологічної чистоти.",
        description04: "<strong>Соус томатний. Екологічно чистий продукт.</strong>",
        description05: "Замовте &#171Bio Natura - Passierte Tomaten&#187 вже зараз і насолоджуйтеся натуральним смаком екологічно чистих томатів!"
    },
    // {
    //     type: "retail",
    //     mainCategory: "foodstuffs",
    //     subcategory: "taste-modifiers",
    //     url: "./images/shop/food/taste_modifier/sauces/combino_arrabbiata_400.jpg",
    //     alt: "combino_arrabbiata_400",
    //     url1: "./images/shop/food/taste_modifier/sauces/combino_arrabbiata_400.jpg",
    //     alt1: "combino_arrabbiata_400",
    //     marker: "FDSU132",
    //     brand: "Combino",
    //     search: "лидл лідл комбино комбіно томат томатный томатные томантні перець гострі острый острые соуси соусы помідор помідори помидор помидоры",
    //     nameUKR: "Гострий томатний соус",
    //     nameEN: "Pasta Sauce Arrabbiata",
    //     companyName: "Lidl",
    //     countryName: "Сербія",
    //     volumeName: "Об'єм",
    //     volume: "400 мл.",
    //     priceGRN: 83,
    //     quantityOnStorage: 2,
    //     description01: "&#171Combino - Pasta Sauce Arrabbiata&#187 - це виразний італійський соус з гострим характером. Він вражає своєю гостротою та насиченим смаком завдяки використанню червоних гострих перців, соковитих помідорів та ароматних спецій.",
    //     description02: "Його смак - це влучне поєднання гостроти та аромату, що чудово пасує до будь-яких видів пасти, ласощів і гарячих страв. З цим соусом Ви зможете створити справжні шедеври і поринути у смак Італії.",
    //     description03: "Томатний соус &#171Combino - Pasta Sauce Arrabbiata&#187 - це смакова подорож до сонячної Італії, яка подарує Вам нові враження. Спробуйте його і відкрийте для себе справжню гостроту смаку!",
    //     description04: "<strong>Соус томатний, гострий.</strong>",
    //     description05: "Додайте гостроти до свого життя і страв з &#171Combino - Pasta Sauce Arrabbiata&#187 вже сьогодні!"
    // },
    // {
    //     type: "retail",
    //     mainCategory: "foodstuffs",
    //     subcategory: "taste-modifiers",
    //     url: "./images/shop/food/taste_modifier/sauces/combino_basil_400.jpg",
    //     alt: "combino_basil_400",
    //     url1: "./images/shop/food/taste_modifier/sauces/combino_basil_400.jpg",
    //     alt1: "combino_basil_400",
    //     marker: "FDSU134",
    //     brand: "Combino",
    //     search: "лидл лідл комбино комбіно томат томатный томатные томантні соуси соусы помідор помідори помидор помидоры базилик базилік с базиликом",
    //     nameUKR: "Томатний соус з базиліком",
    //     nameEN: "Pasta Sauce Basil",
    //     companyName: "Lidl",
    //     countryName: "Сербія",
    //     volumeName: "Об'єм",
    //     volume: "400 мл.",
    //     priceGRN: 83,
    //     quantityOnStorage: 1,
    //     description01: "&#171Combino - Pasta Sauce Basil&#187 - це справжня скарбниця смаку та аромату для шанувальників італійської кухні. Його основу становлять найліпші томати та ароматний базилік, який додає неймовірну свіжість та неперевершений смак.",
    //     description02: "Завдяки вишуканому поєднанню інгредієнтів, цей соус створює яскравий букет смакових відчуттів. Він ідеально підходить для приготування пасти, супів та різноманітних гарячих страв.",
    //     description03: "&#171Combino - Pasta Sauce Basil&#187 - це не просто соус, а справжнє шедевр італійської кулінарії. Він дарує можливість створити ароматні та смачні страви власного виробництва, які запам'ятаються надовго.",
    //     description04: "<strong>Соус томатний, з базиліком</strong>",
    //     description05: "Спробуйте &#171Combino - Pasta Sauce Basil&#187 і перетворіть свій кулінарний досвід на справжню подорож до Італії!"
    // },
    // {
    //     type: "retail",
    // mainCategory: "foodstuffs",
        // subcategory: "taste-modifiers",    
    // url: "./images/shop/food/taste_modifier/sauces/combino_bolognese_400.jpg",
    //     alt: "combino_bolognese_400",
    //     marker: "FDSU136",
    //     brand: "Combino",
    //     search: "лидл лідл комбино комбіно томат томатный томатные томантні соуси соусы помідор помідори помидор помидоры болоньезе болоньєзе",
    //     nameUKR: "Томатний соус для спагеті",
    //     nameEN: "Pasta Sauce Bolognese",
    //     companyName: "Lidl",
    //     countryName: "Сербія",
    //     volumeName: "Об'єм",
    //     volume: "400 мл.",
    //     priceGRN: 83,
    //     quantityOnStorage: "10",
    //     description01: "&#171Combino - Pasta Sauce Bolognese&#187 - це ідеальний вибір для справжніх шанувальників італійської кухні. Цей соус виготовляється з найсоковитіших помідорів, відомих своєю солодкістю та насиченим смаком.",
    //     description02: "Sдеально підходить для приготування спагеті, лазаньї, різних видів пасти, а також як начинка для смачних канапе чи піци. Його смак створює атмосферу традиційного італійського обіду, яка не залишить Вас байдужими.",
    //     description03: "&#171Combino - Pasta Sauce Bolognese&#187 не містить штучних барвників і консервантів, що робить його здоровим та смачним вибором для всієї родини. Ви можете насолоджуватися справжньою італійською якістю у кожному кулькарині.",
    //     description04: "<strong>Соус томатний для спагеті.</strong>",
    //     description05: "Перетворіть звичайні страви в шедеври італійської кухні за допомогою &#171Combino - Pasta Sauce Bolognese&#187!"
    // },
    // {
    //     type: "retail",
    //     mainCategory: "foodstuffs",
    //     subcategory: "taste-modifiers",
    //     url: "./images/shop/food/taste_modifier/sauces/combino_vegetables_400.jpg",
    //     alt: "combino_vegetables_400",
    //     url1: "./images/shop/food/taste_modifier/sauces/combino_vegetables_400.jpg",
    //     alt1: "combino_vegetables_400",
    //     marker: "FDSU138",
    //     brand: "Combino",
    //     search: "лидл лідл комбино комбіно томат томатный томатные томантні соус соуси соусы помідор помідори помидор помидоры",
    //     nameUKR: "Томатний соус з овочами",
    //     nameEN: "Pasta Sauce With Vegetales",
    //     companyName: "Lidl",
    //     countryName: "Сербія",
    //     volumeName: "Об'єм",
    //     volume: "400 мл.",
    //     priceGRN: 83,
    //     quantityOnStorage: 1,
    //     description01: "&#171Combino - Pasta Sauce With Vegetales&#187 - це смачний та ситний соус, який втілить ваши кулінарні фантазії. Він відзначається свіжим смаком томатів та ароматним букетом овочів, що додає неповторний смак вашим стравам.",
    //     description02: "Ідеально підходить для паст, піци, супів та багатьох інших страв. Його густа структура та насичений смак роблять його відмінним вибором для всієї родини.",
    //     description03: "Завдяки вишуканій рецептурі та якісним інгредієнтам, &#171Combino - Pasta Sauce With Vegetales&#187 гарантує неперевершений смак вашого обіду. Спробуйте цей соус і переконайтесь, що Ви заслуговуєте на смачні страви кожен день.",
    //     description04: "<strong>Соус томатний з овочами.</strong>",
    //     description05: "Насолоджуйтеся вишуканим смаком італійської кухні просто вдома та пориньте у світ ароматних страв з &#171Combino - Pasta Sauce With Vegetales&#187!"
    // },
    {
        type: "only-wholesale оптом",
        mainCategory: "foodstuffs",
        subcategory: "taste-modifiers",
        url: "./images/shop/food/taste_modifier/sauces/mk_przecier_pomidorowy_500.jpg",
        alt: "mk_przecier_pomidorowy_500",
        url1: "./images/shop/food/taste_modifier/sauces/mk_przecier_pomidorowy_500.jpg",
        alt1: "mk_przecier_pomidorowy_500",
        marker: "FDSU500",
        brand: "M & K",
        search: "томат томатный томатные томантні соус соуси соусы помідор помідори помидор помидоры",
        nameUKR: "Томатний соус",
        nameEN: "Przecier Pomidorowy",
        companyName: "Kasprzyk SP. K.",
        countryName: "Польща",
        weightName: "Вага",
        weight: "500 гр.",
        priceGRN: "--",
        priceGRNOpt: 65,
        description01: "&#171M & K - Przecier Pomidorowy&#187 - це справжня скарбниця природного смаку та аромату. Цей соус виготовлений з найкращих сонячних томатів, що надають йому яскравий, неперевершений смак та природну солодкість.",
        description02: "Підходить для приготування супів, піцци, паст та багатьох інших страв. Він має гладку текстуру та насичений томатний смак, який робить ваші страви особливими.",
        description03: "Завдяки високій якості та натуральності інгредієнтів, &#171M & K - Przecier Pomidorowy&#187 гарантує Вам смак італійської кухні. Спробуйте цей соус і переконайтесь, що він додасть вашим стравам особливого шарму та смаку.",
        description04: "<strong>Соус томатний. Картонна упаковка.</strong>",
        description05: "Насолоджуйтеся природним смаком сонця з &#171M & K - Przecier Pomidorowy&#187 та пориньте у світ справжньої італійської кухні!"
    },
    {
        type: "only-wholesale оптом",
        mainCategory: "foodstuffs",
        subcategory: "taste-modifiers",
        url: "./images/shop/food/taste_modifier/sauces/reggia_passata_di_pomodoro_680.jpg",
        alt: "reggia_passata_di_pomodoro_680",
        url1: "./images/shop/food/taste_modifier/sauces/reggia_passata_di_pomodoro_680-01.jpg",
        alt1: "reggia_passata_di_pomodoro_680-01",
        url2: "./images/shop/food/taste_modifier/sauces/reggia_passata_di_pomodoro_680-02.jpg",
        alt2: "reggia_passata_di_pomodoro_680-02",
        url3: "./images/shop/food/taste_modifier/sauces/reggia_passata_di_pomodoro_680-03.jpg",
        alt3: "reggia_passata_di_pomodoro_680-03",
        marker: "FDSU580",
        brand: "Reggia",
        search: "томат томатный томатные томантні соус соуси соусы помідор помідори помидор помидоры",
        nameUKR: "Томатний соус",
        nameEN: "Passata Di Pomodoro",
        companyName: "Pastificio Antonio Pallante",
        countryName: "Італія",
        weightName: "Вага",
        weight: "680 гр.",
        priceGRN: "--",
        priceGRNOpt: 99,
        description01: "Знайомтеся з італійським витвором - томатним соусом &#171Reggia - Passata Di Pomodoro&#187, який перенесе Вас у сонячну Італію.",
        description02: "Цей соус виробляється з найсоковитіших помідорів, ніжно подрібнених для створення ароматного та насиченого смаку, який ідеально підходить для приготування різноманітних страв.",
        description03: "Бажаєте відчути смак італійських страв у Ваших кулінарних творіннях? Обирайте &#171Reggia - Passata Di Pomodoro&#187 для створення справжніх шедеврів на Вашій кухні.",
        description04: "<strong>Соус томатний. Не містить шкідливих барвників.</strong>",
        description05: "Замовте томатний соус &#171Reggia - Passata Di Pomodoro&#187 прямо зараз і додайте італійського смаку своїм стравам, перетворивши звичайний обід у справжню подорож!"
    },
    {
        type: "wholesale оптом",
        mainCategory: "foodstuffs",
        subcategory: "taste-modifiers",
        url: "./images/shop/food/taste_modifier/sauces/rosso_gargano_passata_di_puglia_690.jpg",
        alt: "rosso_gargano_passata_di_puglia_690",
        url1: "./images/shop/food/taste_modifier/sauces/rosso_gargano_passata_di_puglia_690.jpg",
        alt1: "rosso_gargano_passata_di_puglia_690",
        marker: "FDSU600",
        brand: "Rosso Gargano",
        search: "россо росо гаргано томат томатный томатные томантні соус соуси соусы помідор помідори помидор помидоры",
        nameUKR: "Томатний соус",
        nameEN: "Passata Di Puglia",
        companyName: "Rossogargano S.C.A.P.A.",
        countryName: "Італія",
        weightName: "Вага",
        weight: "690 гр.",
        priceGRN: 132,
        priceGRNOpt: 113,
        description01: "&#171Rosso Gargano - Passata Di Puglia&#187 - це справжній діамант серед томатних соусів, який вразить Вас своєю яскравістю та смаковою насиченістю. Приготований з відбирних помідорів, які вирощені на сонці Італії, не містить штучних добавок, що робить його натуральним та корисним.",
        description02: "Ідеально підходить для приготування паст, супів, піцци та інших італійських страв. Він має гладку консистенцію та неперевершений томатний смак, який розкриє перед вами багатство смаків італійської кухні.",
        description03: "Завдяки високій якості і свіжості інгредієнтів, &#171Rosso Gargano - Passata Di Puglia&#187 гарантує Вам італійський смак прямо вдома.",
        description04: "<strong>Соус томатний. Не містить шкідливих барвників.</strong>",
        description05: "Замовте томатний соус &#171Rosso Gargano - Passata Di Puglia&#187 та насолоджуйтеся найкращими смаками Італії. Погрузьтеся в атмосферу справжньої італійської кухні та даруйте собі насолоду!"
    },
    {
        type: "only-wholesale оптом",
        mainCategory: "foodstuffs",
        subcategory: "taste-modifiers",
        url: "./images/shop/food/taste_modifier/sauces/rosso_gargano_passata_di_puglia_basilico_690.jpg",
        alt: "rosso_gargano_passata_di_puglia_basilico_690",
        url1: "./images/shop/food/taste_modifier/sauces/rosso_gargano_passata_di_puglia_basilico_690.jpg",
        alt1: "rosso_gargano_passata_di_puglia_basilico_690",
        marker: "FDSU610",
        brand: "Rosso Gargano",
        search: "россо росо гаргано томат томатный томатные томантні соус соуси соусы помідор помідори помидор помидоры с базиликом базилик",
        nameUKR: "Томатний соус з базиліком",
        nameEN: "Passata Di Puglia Basilico",
        companyName: "Rossogargano S.C.A.P.A.",
        countryName: "Італія",
        weightName: "Вага",
        weight: "690 гр.",
        priceGRN: "--",
        priceGRNOpt: 113,
        description01: "Зупиніться на мить і відчуйте томатний соус з базиліком &#171Rosso Gargano - Passata Di Puglia Basilico&#187, який вражає своєю неперевершеною якістю та аутентичним італійським смаком.",
        description02: "Цей соус створений з найсвіжіших томатів Пульї, доповнений ароматним базиліком. Збережений у скляній банці, він готовий додати смак італійського сонця до вашого столу.",
        description03: "Бажаєте насолоджуватися справжньою італійською кулінарією вдома? &#171Rosso Gargano - Passata Di Puglia Basilico&#187 робить кожну страву неперевершеною, розкриваючи вишуканість італійського смаку.",
        description04: "<strong>Соус томатний, з базиліком. Не містить шкідливих барвників.</strong>",
        description05: "Освіжіть свої страви італійським смаком з &#171Rosso Gargano - Passata Di Puglia Basilico&#187!"
    },
    // {
    //     type: "retail",
    // mainCategory: "foodstuffs",
        // subcategory: "taste-modifiers",    
    // url: "./images/shop/food/taste_modifier/sauces/santa_rosa_pomodorissimo_700.jpg",
    //     alt: "santa_rosa_pomodorissimo_700",
    //     url1: "./images/shop/food/taste_modifier/sauces/santa_rosa_pomodorissimo_700.jpg",
    //     alt1: "santa_rosa_pomodorissimo_700",
    //     marker: "FDSU700",
    //     brand: "Santa Rosa",
    //     search: "санта роса томат томатный томатные томантні соус соуси соусы помідор помідори помидор помидоры",
    //     nameUKR: "Томатний соус",
    //     nameEN: "Pomodorissimo La Passata",
    //     companyName: "V.B.S. s.p.a.",
    //     countryName: "Італія",
    //     weightName: "Вага",
    //     weight: "700 гр.",
    //     priceGRN: 80,
    //     quantityOnStorage: "4",
    //     description01: "&#171Santa Rosa - Pomodorissimo La Passata&#187 - це ідеальний томатний соус для тих, хто цінує справжній смак Італії. Цей соус виготовлений з відмінних помідорів із середземноморського регіону, що гарантує найвищу якість та смак.",
    //     description02: "Він має гладку текстуру та багатий аромат, який нагадує про сонячні поля Італії. Цей соус ідеально підходить для приготування пасти, піци та інших італійських страв.",
    //     description03: "&#171Santa Rosa - Pomodorissimo La Passata&#187 не містить шкідливих домішок або консервантів, що робить його натуральним вибором для всієї родини. Завдяки його смаку, Ви можете створити смачні італійські страви власноруч.",
    //     description04: "<strong>Соус томатний. Не містить шкідливих барвників.</strong>",
    //     description05: "Приготуйте смачні італійські страви та пориньте у смаковий світ Італії разом з томатним соусом &#171Santa Rosa - Pomodorissimo La Passata&#187!"
    // },
    {
        type: "only-wholesale оптом",
        mainCategory: "foodstuffs",
        subcategory: "taste-modifiers",
        url: "./images/shop/food/taste_modifier/sauces/o_sole_e_napule_la_passata_classica_680.jpg",
        alt: "o_sole_e_napule_la_passata_classica_680",
        url1: "./images/shop/food/taste_modifier/sauces/o_sole_e_napule_la_passata_classica_680-01.jpg",
        alt1: "o_sole_e_napule_la_passata_classica_680-01",
        url2: "./images/shop/food/taste_modifier/sauces/o_sole_e_napule_la_passata_classica_680-02.jpg",
        alt2: "o_sole_e_napule_la_passata_classica_680-02",
        marker: "FDSU720",
        brand: "O Sole E Napule",
        search: "соле э е напуле напулэ томат томатный томатные томантні соус соуси соусы помідор помідори помидор помидоры классика классический",
        nameUKR: "Томатний соус, класичний",
        nameEN: "La Passata Classica",
        companyName: "Calabria s.r.l.",
        countryName: "Італія",
        weightName: "Вага",
        weight: "680 гр.",
        priceGRN: "--",
        priceGRNOpt: 96,
        description01: "Томатний соус &#171O Sole E Napule - La Passata Classica&#187 - це справжня італійська класика на Вашій кухні.",
        description02: "Виготовлений з добірних стиглих томатів, він має ніжну текстуру та насичений природний смак без зайвих добавок.",
        description03: "&#171O Sole E Napule - La Passata Classica&#187 ідеально підходить для приготування соусів, пасти, піци та інших традиційних страв, зберігаючи автентичний італійський аромат.",
        description04: "<strong>Соус томатний, класичний. Після відкриття спожити протягом трьох днів.</strong>",
        description05: "Обирайте &#171O Sole E Napule - La Passata Classica&#187 – натуральну якість та смак сонячної Італії у кожній страві!"
    },
]