export const shopLotsHerring = [
    {
        type: "wholesale оптом",
        mainCategory: "foodstuffs",
        subcategory: "conservation",
        url: "./images/shop/food/canned_food/herring/marinero_sledz_w_oleju_roslinnym_170.jpg",
        alt: "marinero_sledz_w_oleju_roslinnym_170",
        url1: "./images/shop/food/canned_food/herring/marinero_sledz_w_oleju_roslinnym_170-01.jpg",
        alt1: "marinero_sledz_w_oleju_roslinnym_170-01",
        url2: "./images/shop/food/canned_food/herring/marinero_sledz_w_oleju_roslinnym_170-02.jpg",
        alt2: "marinero_sledz_w_oleju_roslinnym_170-02",
        marker: "HRNG450",
        brand: "Marinero",
        search: "filety sledziowe w oleju roslinnym маринеро марінеро филе рыба риба сельдь селедка селедки рослинна олія растительное масло в растительном масле",
        nameUKR: "Філе оселедця у рослинній олії",
        nameEN: "Filety Śledziowe W Oleju Roślinnym",
        companyName: "Jeronimo Martins S.A.",
        countryName: "Польща",
        weightName: "Вага",
        weight: "170 гр.",
        priceGRN: 65,
        priceGRNOpt: 59,
        description01: "Соковите філе оселедця &#171Marinero - Filety Śledziowe W Oleju Roślinnym&#187 у рослинній олії — ідеальне поєднання смаку та користі для Вашого столу!",
        description02: "Виготовлене зі свіжої риби, воно зберігає природну ніжність текстури та насичений аромат.",
        description03: "Подаруйте собі кулінарну насолоду, додавши &#171Marinero - Filety Śledziowe W Oleju Roślinnym&#187 до закусок, салатів або основних страв.",
        description04: "<strong>Філе оселедця у рослинній олії. Зберігати у сухому та прохолодному місці.</strong>",
        description05: "Створіть витончені страви з філе оселедця &#171Marinero - Filety Śledziowe W Oleju Roślinnym&#187!"
    },
    {
        type: "wholesale оптом",
        mainCategory: "foodstuffs",
        subcategory: "conservation",
        url: "./images/shop/food/canned_food/herring/marinero_filety_sledziowe_w_sosie_pomidorowym_170.jpg",
        alt: "marinero_filety_sledziowe_w_sosie_pomidorowym_170",
        url1: "./images/shop/food/canned_food/herring/marinero_filety_sledziowe_w_sosie_pomidorowym_170-01.jpg",
        alt1: "marinero_filety_sledziowe_w_sosie_pomidorowym_170-01",
        url2: "./images/shop/food/canned_food/herring/marinero_filety_sledziowe_w_sosie_pomidorowym_170-02.jpg",
        alt2: "marinero_filety_sledziowe_w_sosie_pomidorowym_170-02",
        marker: "HRNG453",
        brand: "Marinero",
        search: "filety sledziowe w sosie pomidorowym маринеро марінеро филе рыба риба сельдь селедка селедки в томатном соусе томатный соус томатний соус",
        nameUKR: "Філе оселедця у томатному соусі",
        nameEN: "Filety Śledziowe W Sosie Pomidorowym",
        companyName: "Jeronimo Martins S.A.",
        countryName: "Польща",
        weightName: "Вага",
        weight: "170 гр.",
        priceGRN: 56,
        priceGRNOpt: 51,
        description01: "&#171Marinero - Filety Śledziowe W Sosie Pomidorowym&#187 — це ніжний смак риби з соковитим соусом для справжнього гастрономічного задоволення.",
        description02: "Апетитні шматочки філе поєднуються з ароматним томатним соусом, створюючи класичний смак без зайвих добавок.",
        description03: "&#171Marinero - Filety Śledziowe W Sosie Pomidorowym&#187 ідеально підходить для легкої вечері, закуски або швидкого перекусу.",
        description04: "<strong>Філе оселедця у томатному соусі. Зберігати у сухому та прохолодному місці.</strong>",
        description05: "Додайте &#171Marinero - Filety Śledziowe W Sosie Pomidorowym&#187 до свого раціону, щоб завжди мати смачний варіант під рукою!"
    },
    {
        type: "only-wholesale оптом",
        mainCategory: "foodstuffs",
        subcategory: "conservation",       
        url: "./images/shop/food/canned_food/herring/marinero_sledz_w_sosie_pomidorowym_170.jpg",
        alt: "marinero_sledz_w_sosie_pomidorowym_170",
        url1: "./images/shop/food/canned_food/herring/marinero_sledz_w_sosie_pomidorowym_170-01.jpg",
        alt1: "marinero_sledz_w_sosie_pomidorowym_170-01",
        url2: "./images/shop/food/canned_food/herring/marinero_sledz_w_sosie_pomidorowym_170-02.jpg",
        alt2: "marinero_sledz_w_sosie_pomidorowym_170-02",
        marker: "HRNG455",
        brand: "Marinero",
        search: "sledz маринеро марінеро томат томати помидор помидоры помідор помідори соус соусы рыба риба сельдь селедка",
        nameUKR: "Оселедець у томатному соусі",
        nameEN: "Śledź W Sosie Pomidorowym",
        companyName: "Jeronimo Martins S.A.",
        countryName: "Польща",
        weightName: "Вага",
        weight: "170 гр.",
        priceGRN: "--",
        priceGRNOpt: 65,
        description01: "&#171Marinero - Śledź W Sosie Pomidorowym&#187 - це справжня експлозія смаку і багатства корисних речовин. Кожен шматочок оселедця насичений ароматом і ніжністю, а томатний соус додає пікантності, роблячи цей продукт ідеальним додатком до вашого столу.",
        description02: "Оселедець - відоме джерело білка, Омега-3 кислот та вітаміну D. Тому це високоякісний продукт, який надає Вам можливість насолоджуватися не тільки смаком, але й користью для вашого здоров'я.",
        description03: "У &#171Marinero - Śledź W Sosie Pomidorowym&#187 використовуються тільки найсвіжіші оселедці та відібрані інгредієнти для створення неповторного смаку. Цей продукт - втілення якості та гастрономічного задоволення.",
        description04: "<strong>Оселедець у томатному соусі. Зберігати у сухому та прохолодному місці.</strong>",
        description05: "Насолоджуйтеся кращим, обираючи оселедець &#171Marinero - Śledź W Sosie Pomidorowym&#187 - смачно, корисно, неперевершено!"
    },
]