export const shopLotsChips = [
    {
        type: "retail",
        mainCategory: "foodstuffs",
        subcategory: "snacks",
        url: "./images/shop/food/snacks/chips/pringles_cheese_onion_165.jpg",
        alt: "pringles_cheese_onion_165",
        url1: "./images/shop/food/snacks/chips/pringles_cheese_onion_165-01.jpg",
        alt1: "pringles_cheese_onion_165-01",
        url2: "./images/shop/food/snacks/chips/pringles_cheese_onion_165-02.jpg",
        alt2: "pringles_cheese_onion_165-02",
        url3: "./images/shop/food/snacks/chips/pringles_cheese_onion_165-03.jpg",
        alt3: "pringles_cheese_onion_165-03",
        url4: "./images/shop/food/snacks/chips/pringles_cheese_onion_165-04.jpg",
        alt4: "pringles_cheese_onion_165-04",
        marker: "FDCH510",
        brand: "Pringles",
        search: "принглс прінглс чипсы со вкусом сыр с сыром цыбулей цыбуля лук луком цибуля",
        nameUKR: "Чіпси зі смаком сиру та цибулі",
        nameEN: "Cheese & Onion",
        companyName: "Kellogg's",
        countryName: "Англія",
        weightName: "Вага",
        weight: "165 гр.",
        priceGRN: 106,
        quantityOnStorage: 1,
        description01: "&#171Pringles - Cheese & Onion&#187 - це справжня симфонія смаку, яка підкорює серця гурманів по всьому світу. Кожен чіпс має неймовірно насичений смак сиру та цибулі.",
        description02: "Смак &#171Pringles - Cheese & Onion&#187 - це ідеальний баланс між солодкістю цибулі та багатим смаком сиру. Ці чіпси чудово підходять як закуска до фільму, на вечірку з друзями або просто для задоволення свого апетиту у будь-який час.",
        description03: "Вони завжди гарантують свіжість та смакове задоволення завдяки своєму унікальному трубчастому пакуванню. Спробуйте ці чіпси і вперше відчуйте справжню якість та смак в одному.",
        description04: "<strong>Смак: сир та цибуля.</strong>",
        description05: "Не вагайтеся, спробуйте &#171Pringles - Cheese & Onion&#187 вже сьогодні та переконайтесь, які чудові можуть бути закуски. Вас чекає справжнє кулінарне задоволення!"
    },
    {
        type: "retail",
        mainCategory: "foodstuffs",
        subcategory: "snacks",
        url: "./images/shop/food/snacks/chips/pringles_cheesy_cheese_165.jpg",
        alt: "pringles_cheesy_cheese_165",
        url1: "./images/shop/food/snacks/chips/pringles_cheesy_cheese_165-01.jpg",
        alt1: "pringles_cheesy_cheese_165-01",
        url2: "./images/shop/food/snacks/chips/pringles_cheesy_cheese_165-02.jpg",
        alt2: "pringles_cheesy_cheese_165-02",
        url3: "./images/shop/food/snacks/chips/pringles_cheesy_cheese_165-03.jpg",
        alt3: "pringles_cheesy_cheese_165-03",
        url4: "./images/shop/food/snacks/chips/pringles_cheesy_cheese_165-04.jpg",
        alt4: "pringles_cheesy_cheese_165-04",
        marker: "FDCH515",
        brand: "Pringles",
        search: "принглс прінглс чипсы со вкусом сыра сыр с сыром",
        nameUKR: "Чіпси зі смаком сиру",
        nameEN: "Cheesy Cheese",
        companyName: "Kellogg's",
        countryName: "Англія",
        weightName: "Вага",
        weight: "165 гр.",
        priceGRN: 106,
        quantityOnStorage: 2,
        description01: "&#171Pringles - Cheesy Cheese&#187 - це справжня кулінарна вишуканість, яка додасть смаку Вашому життю. Кожен чіпс пропитаний ароматом справжнього сиру, створюючи букет смакових відчуттів, які не мають собі рівних.",
        description02: "Смак &#171Pringles - Cheesy Cheese&#187 - це ідеальне поєднання нот солодкої плавкої текстури сиру, яка залишає вас бажати більше. Ці чіпси чудово пасують до будь-якого виду вечірки.",
        description03: "Завжди гарантують свіжість та смакову насолоду завдяки своєму унікальному трубчастому пакуванню. Спробуйте ці чіпси і Ви отримаєте найкращий смак у кожному ковзку.",
        description04: "<strong>Смак: сир.</strong>",
        description05: "Вирушайте у смачну подорож з &#171Pringles - Cheesy Cheese&#187 даруючи радість собі та Вашим друзям!"
    },
    {
        type: "retail",
        mainCategory: "foodstuffs",
        subcategory: "snacks",
        url: "./images/shop/food/snacks/chips/pringles_hot_spicy_165.jpg",
        alt: "pringles_hot_spicy_165",
        url1: "./images/shop/food/snacks/chips/pringles_hot_spicy_165-01.jpg",
        alt1: "pringles_hot_spicy_165-01",
        url2: "./images/shop/food/snacks/chips/pringles_hot_spicy_165-02.jpg",
        alt2: "pringles_hot_spicy_165-02",
        url3: "./images/shop/food/snacks/chips/pringles_hot_spicy_165-03.jpg",
        alt3: "pringles_hot_spicy_165-03",
        url4: "./images/shop/food/snacks/chips/pringles_hot_spicy_165-04.jpg",
        alt4: "pringles_hot_spicy_165-04",
        marker: "FDCH520",
        brand: "Pringles",
        search: "принглс прінглс чипсы со вкусом острые пряности пряностей острых",
        nameUKR: "Чіпси зі смаком гострих прянощів",
        nameEN: "Hot & Spicy",
        companyName: "Kellogg's",
        countryName: "Англія",
        weightName: "Вага",
        weight: "165 гр.",
        priceGRN: 106,
        quantityOnStorage: 2,
        description01: "&#171Pringles - Hot & Spicy&#187 - це справжній кулінарний вогонь, який принесе неймовірну гостроту у кожен ковзок. Їх виразний смак поєднує пікантні нотки спецій та гострої паприки, створюючи справжню експлозію смаку.",
        description02: "Смак &#171Pringles - Hot & Spicy&#187 - це захоплюючий мікс паприки та спецій, який піднімає адреналін і додає гостроти у Ваше життя. Ці чіпси - ідеальний вибір для сміливих і впертих гурманів, які шукають нові смакові враження.",
        description03: "Вони завжди гарантують свіжість та смакове задоволення завдяки своєму унікальному трубчастому пакуванню. Спробуйте ці чіпси і відчуйте, як вони розпалюють Ваші смакові рецептори.",
        description04: "<strong>Смак: гострі прянощі.</strong>",
        description05: "Вирушайте у смачну подорож та сміливо смакуйте справжній гострий вогонь. Спробуйте &#171Pringles - Hot & Spicy&#187 прямо зараз і отримайте незабутнє смакове враження!"
    },
    // {
    //     type: "wholesale",
    // mainCategory: "foodstuffs",
        // subcategory: "snacks",    
    // url: "./images/shop/food/snacks/chips/pringles_original_40.jpg",
    //     alt: "pringles_original_40",
    //     url1: "./images/shop/food/snacks/chips/pringles_original_40-01.jpg",
    //     alt1: "pringles_original_40-01",
    //     url2: "./images/shop/food/snacks/chips/pringles_original_40-02.jpg",
    //     alt2: "pringles_original_40-02",
    //     url3: "./images/shop/food/snacks/chips/pringles_original_40-03.jpg",
    //     alt3: "pringles_original_40-03",
    //     marker: "FDCH500",
    //     brand: "Pringles",
    //     search: "принглс прінглс чипсы со вкусом оригинал оригінал сіль соль с солью з сілью",
    //     nameUKR: "Чіпси",
    //     nameEN: "Original",
    //     companyName: "Kellogg's",
    //     countryName: "Англія",
    //     weightName: "Вага",
    //     weight: "40 гр.",
    //     priceGRN: 42,
    //     priceGRNOpt: 38,
    //     description01: "&#171Pringles - Original&#187 - це справжня класика серед чіпсів, яка завжди залишається улюбленою. Їх унікальна трубчаста форма робить їх неповторними, а смак бездоганний. Кожен чіпс має ідеальний баланс солі та картоплі, створюючи неповторний смак, який завжди впізнаєш.",
    //     description02: "&#171Pringles - Original&#187 - це ідеальний снек для будь-якого випадку. Ці чіпси підходять для вечірки з друзями, перегляду фільму або навіть просто для швидкої закуски під час перерви на обід.",
    //     description03: "Вони завжди свіжі та смачні, завдяки спеціальній упаковці.",
    //     description04: "<strong>Смак: солений.</strong>",
    //     description05: "Спробуйте &#171Pringles - Original&#187 прямо зараз і відчуйте смак класики!"
    // },
    // {
    //     type: "wholesale",
    // mainCategory: "foodstuffs",
        // subcategory: "snacks",    
    // url: "./images/shop/food/snacks/chips/pringles_original_165.jpg",
    //     alt: "pringles_original_165",
    //     url1: "./images/shop/food/snacks/chips/pringles_original_165-01.jpg",
    //     alt1: "pringles_original_165-01",
    //     url2: "./images/shop/food/snacks/chips/pringles_original_165-02.jpg",
    //     alt2: "pringles_original_165-02",
    //     marker: "FDCH505",
    //     brand: "Pringles",
    //     search: "принглс прінглс чипсы со вкусом оригинал оригінал сіль соль с солью з сілью",
    //     nameUKR: "Чіпси",
    //     nameEN: "Original",
    //     companyName: "Kellogg's",
    //     countryName: "Англія",
    //     weightName: "Вага",
    //     weight: "165 гр.",
    //     priceGRN: 92,
    //     priceGRNOpt: 84,
    //     description01: "&#171Pringles - Original&#187 - це справжня класика серед чіпсів, яка завжди залишається улюбленою. Їх унікальна трубчаста форма робить їх неповторними, а смак бездоганний. Кожен чіпс має ідеальний баланс солі та картоплі, створюючи неповторний смак, який завжди впізнаєш.",
    //     description02: "&#171Pringles - Original&#187 - це ідеальний снек для будь-якого випадку. Ці чіпси підходять для вечірки з друзями, перегляду фільму або навіть просто для швидкої закуски під час перерви на обід.",
    //     description03: "Вони завжди свіжі та смачні, завдяки спеціальній упаковці.",
    //     description04: "<strong>Смак: солений.</strong>",
    //     description05: "Спробуйте &#171Pringles - Original&#187 прямо зараз і відчуйте смак класики!"
    // },
    {
        type: "retail",
        mainCategory: "foodstuffs",
        subcategory: "snacks",
        url: "./images/shop/food/snacks/chips/pringles_paprika_165.jpg",
        alt: "pringles_paprika_165",
        url1: "./images/shop/food/snacks/chips/pringles_paprika_165-01.jpg",
        alt1: "pringles_paprika_165-01",
        url2: "./images/shop/food/snacks/chips/pringles_paprika_165-02.jpg",
        alt2: "pringles_paprika_165-02",
        url3: "./images/shop/food/snacks/chips/pringles_paprika_165-03.jpg",
        alt3: "pringles_paprika_165-03",
        url4: "./images/shop/food/snacks/chips/pringles_paprika_165-04.jpg",
        alt4: "pringles_paprika_165-04",
        marker: "FDCH530",
        brand: "Pringles",
        search: "принглс прінглс чипсы со вкусом классік класік класик класик папріка паприка перец перца с з перцем",
        nameUKR: "Чіпси зі смаком перцю",
        nameEN: "Paprika",
        companyName: "Kellogg's",
        countryName: "Англія",
        weightName: "Вага",
        weight: "165 гр.",
        priceGRN: 106,
        quantityOnStorage: 1,
        description01: "&#171Pringles - Paprika&#187 - це справжній смаковий вибух, який подарує вам неперевершену насолоду. Ці чіпси відзначаються насиченим смаком паприки, який чудово поєднується з хрусткою текстурою.",
        description02: "Смак &#171Pringles - Paprika&#187 - це чудове поєднання ніжності та гостроти, що робить ці чіпси ідеальними для вечірки з друзями, дегустації фільму або просто для задоволення Вашого апетиту.",
        description03: "Чіпси гарантують свіжість і смачну насолоду завдяки своєму унікальному трубчастому пакуванню. Спробуйте та вирушайте у смачну подорож, яка залишить незабутній смак.",
        description04: "<strong>Смак: перець, паприка.</strong>",
        description05: "Не втрачайте шансу підкреслити свою вишуканість. Спробуйте &#171Pringles - Paprika&#187 прямо зараз та переконайтесь в їхній неперевершеній якості."
    },
    {
        ttype: "only-wholesale оптом",
        mainCategory: "foodstuffs",
        subcategory: "snacks",
        url: "./images/shop/food/snacks/chips/pringles_pizza_flavour_165.jpg",
        alt: "pringles_pizza_flavour_165",
        url1: "./images/shop/food/snacks/chips/pringles_pizza_flavour_165.jpg",
        alt1: "pringles_pizza_flavour_165",
        url2: "./images/shop/food/snacks/chips/pringles_pizza_flavour_165-02.jpg",
        alt2: "pringles_pizza_flavour_165-02",
        url3: "./images/shop/food/snacks/chips/pringles_pizza_flavour_165-03.jpg",
        alt3: "pringles_pizza_flavour_165-03",
        url4: "./images/shop/food/snacks/chips/pringles_pizza_flavour_165-04.jpg",
        alt4: "pringles_pizza_flavour_165-04",
        marker: "FDCH535",
        brand: "Pringles",
        search: "принглс прінглс чипсы со вкусом пиццы пицца с пиццой пиццей з піцею",
        nameUKR: "Чіпси зі смаком піци",
        nameEN: "Pizza Flavour",
        companyName: "Kellogg's",
        countryName: "Англія",
        weightName: "Вага",
        weight: "165 гр.",
        priceGRN: "--",
        priceGRNOpt: 106,
        description01: "&#171Pringles - Pizza Flavour&#187 - це справжній шедевр, який переносить Вас до італійської піцерії з кожним ковзком. Їх неперевершений смак відтворює смачну суміш сиру, помідорів та ароматних спецій.",
        description02: "Смак &#171Pringles - Pizza Flavour&#187 - це справжнє поєднання тепла та затишку, які приносить з собою італійська піца. Ці чіпси дозволяють Вам насолоджуватися улюбленим смаком навіть на робочому місці або вдома.",
        description03: "Завжди гарантують свіжість та смакове насолодження завдяки своєму унікальному трубчастому пакуванню. Спробуйте ці чіпси і перенесіть себе до мальовничої Італії кожен раз, коли відкриваєте упаковку.",
        description04: "<strong>Смак: піца.</strong>",
        description05: "Замовте &#171Pringles - Pizza Flavour&#187 прямо зараз та насолоджуйтеся справжньою італійською піцею!"
    },
    // {
    //     type: "wholesale",
    // mainCategory: "foodstuffs",
        // subcategory: "snacks",    
    // url: "./images/shop/food/snacks/chips/pringles_original_175.jpg",
    //     alt: "pringles_original_175",
    //     url1: "./images/shop/food/snacks/chips/pringles_original_175-01.jpg",
    //     alt1: "pringles_original_175-01",
    //     url2: "./images/shop/food/snacks/chips/pringles_original_175-02.jpg",
    //     alt2: "pringles_original_175-02",
    //     url3: "./images/shop/food/snacks/chips/pringles_original_175-03.jpg",
    //     alt3: "pringles_original_175-03",
    //     url4: "./images/shop/food/snacks/chips/pringles_original_175-04.jpg",
    //     alt4: "pringles_original_175-04",
    //     marker: "FDCH507",
    //     brand: "Pringles",
    //     search: "принглс прінглс чипсы со вкусом оригинал оригінал сіль соль с солью з сілью",
    //     nameUKR: "Чіпси",
    //     nameEN: "Original",
    //     companyName: "Kellogg's",
    //     countryName: "Англія",
    //     weightName: "Вага",
    //     weight: "175 гр.",
    //     priceGRN: 96,
    //     priceGRNOpt: 88,
    //     description01: "&#171Pringles - Original&#187 - це справжня класика серед чіпсів, яка завжди залишається улюбленою. Їх унікальна трубчаста форма робить їх неповторними, а смак бездоганний. Кожен чіпс має ідеальний баланс солі та картоплі, створюючи неповторний смак, який завжди впізнаєш.",
    //     description02: "&#171Pringles - Original&#187 - це ідеальний снек для будь-якого випадку. Ці чіпси підходять для вечірки з друзями, перегляду фільму або навіть просто для швидкої закуски під час перерви на обід.",
    //     description03: "Вони завжди свіжі та смачні, завдяки спеціальній упаковці.",
    //     description04: "<strong>Смак: солений.</strong>",
    //     description05: "Спробуйте &#171Pringles - Original&#187 прямо зараз і відчуйте смак класики!"
    // },
    // {
    //     type: "wholesale",
    // mainCategory: "foodstuffs",
        // subcategory: "snacks",    
    // url: "./images/shop/food/snacks/chips/pringles_classic_paprika_40.jpg",
    //     alt: "pringles_classic_paprika_40",
    //     url1: "./images/shop/food/snacks/chips/pringles_classic_paprika_40.jpg",
    //     alt1: "pringles_classic_paprika_40",
    //     marker: "FDCH530",
    //     brand: "Pringles",
    //     search: "принглс прінглс чипсы со вкусом классік класік класик класик папріка паприка перец перца с з перцем",
    //     nameUKR: "Чіпси зі смаком перцю",
    //     nameEN: "Classic Paprika",
    //     companyName: "Kellogg's",
    //     countryName: "Англія",
    //     weightName: "Вага",
    //     weight: "40 гр.",
    //     priceGRN: 40,
    //     priceGRNOpt: 36,
    //     description01: "&#171Pringles - Classic Paprika&#187 - це справжній смаковий вибух, який подарує вам неперевершену насолоду. Ці чіпси відзначаються насиченим смаком паприки, який чудово поєднується з хрусткою текстурою.",
    //     description02: "Смак &#171Pringles - Classic Paprika&#187 - це чудове поєднання ніжності та гостроти, що робить ці чіпси ідеальними для вечірки з друзями, дегустації фільму або просто для задоволення Вашого апетиту.",
    //     description03: "Чіпси гарантують свіжість і смачну насолоду завдяки своєму унікальному трубчастому пакуванню. Спробуйте та вирушайте у смачну подорож, яка залишить незабутній смак.",
    //     description04: "<strong>Смак: перець, паприка.</strong>",
    //     description05: "Не втрачайте шансу підкреслити свою вишуканість. Спробуйте &#171Pringles - Classic Paprika&#187 прямо зараз та переконайтесь в їхній неперевершеній якості."
    // },
    // {
    //     type: "wholesale",
    // mainCategory: "foodstuffs",
        // subcategory: "snacks",    
    // url: "./images/shop/food/snacks/chips/pringles_grilled_paprika_flavour_185.jpg",
    //     alt: "pringles_grilled_paprika_flavour_185",
    //     url1: "./images/shop/food/snacks/chips/pringles_grilled_paprika_flavour_185-01.jpg",
    //     alt1: "pringles_grilled_paprika_flavour_185-01",
    //     url2: "./images/shop/food/snacks/chips/pringles_grilled_paprika_flavour_185-02.jpg",
    //     alt2: "pringles_grilled_paprika_flavour_185-02",
    //     url3: "./images/shop/food/snacks/chips/pringles_grilled_paprika_flavour_185-03.jpg",
    //     alt3: "pringles_grilled_paprika_flavour_185-03",
    //     url4: "./images/shop/food/snacks/chips/pringles_grilled_paprika_flavour_185-04.jpg",
    //     alt4: "pringles_grilled_paprika_flavour_185-04",
    //     marker: "FDCH537",
    //     brand: "Pringles",
    //     search: "принглс прінглс чипсы со вкусом гриль смажений жареный перец папріка жареного перца паприки",
    //     nameUKR: "Чіпси зі смаком смаженої паприки",
    //     nameEN: "Grilled Paprika Flavour",
    //     companyName: "Kellogg's",
    //     countryName: "Англія",
    //     weightName: "Вага",
    //     weight: "185 гр.",
    //     priceGRN: 101,
    //     priceGRNOpt: 92,
    //     description01: "Знайомтеся з неперевершеним смаковим витвором - чіпсами &#171Pringles - Grilled Paprika Flavour&#187.",
    //     description02: "Ці чіпси приготовані за особливим рецептом з печеною паприкою, яка додає неповторного грильованого аромату та пікантності, створюючи справжній феєричний смак.",
    //     description03: "Мрієте про нестандартний смак і непередбачувані враження? Виберіть &#171Pringles - Grilled Paprika Flavour&#187 та зануртесь у світ нових гастрономічних відкриттів.",
    //     description04: "<strong>Смак: смажена паприка.</strong>",
    //     description05: "Спроуйте &#171Pringles - Grilled Paprika Flavour&#187 прямо зараз і насолоджуйтеся смаком вишуканої печеної паприки у кожному шматочку цих неперевершених чипсів!"
    // },
    // {
    //     type: "wholesale",
    // mainCategory: "foodstuffs",
        // subcategory: "snacks",    
    // url: "./images/shop/food/snacks/chips/pringles_hot_spicy_40.jpg",
    //     alt: "pringles_hot_spicy_40",
    //     url1: "./images/shop/food/snacks/chips/pringles_hot_spicy_40-01.jpg",
    //     alt1: "pringles_hot_spicy_40-01",
    //     url2: "./images/shop/food/snacks/chips/pringles_hot_spicy_40-02.jpg",
    //     alt2: "pringles_hot_spicy_40-02",
    //     url3: "./images/shop/food/snacks/chips/pringles_hot_spicy_40-03.jpg",
    //     alt3: "pringles_hot_spicy_40-03",
    //     marker: "FDCH540",
    //     brand: "Pringles",
    //     search: "принглс прінглс чипсы со вкусом острые гострі пряности пряностей острых",
    //     nameUKR: "Чіпси зі смаком гострих прянощів",
    //     nameEN: "Hot & Spicy",
    //     companyName: "Kellogg's",
    //     countryName: "Англія",
    //     weightName: "Вага",
    //     weight: "40 гр.",
    //     priceGRN: 42,
    //     priceGRNOpt: 38,
    //     description01: "&#171Pringles - Hot & Spicy&#187 - це справжній кулінарний вогонь, який принесе неймовірну гостроту у кожен ковзок. Їх виразний смак поєднує пікантні нотки спецій та гострої паприки, створюючи справжню експлозію смаку.",
    //     description02: "Смак &#171Pringles - Hot & Spicy&#187 - це захоплюючий мікс паприки та спецій, який піднімає адреналін і додає гостроти у Ваше життя. Ці чіпси - ідеальний вибір для сміливих і впертих гурманів, які шукають нові смакові враження.",
    //     description03: "Вони завжди гарантують свіжість та смакове задоволення завдяки своєму унікальному трубчастому пакуванню. Спробуйте ці чіпси і відчуйте, як вони розпалюють Ваші смакові рецептори.",
    //     description04: "<strong>Смак: гострий.</strong>",
    //     description05: "Вирушайте у смачну подорож та сміливо смакуйте справжній гострий вогонь. Спробуйте &#171Pringles - Hot & Spicy&#187 прямо зараз і отримайте незабутнє смакове враження!"
    // },
    // {
    //     type: "wholesale",
    // mainCategory: "foodstuffs",
        // subcategory: "snacks",    
    // url: "./images/shop/food/snacks/chips/pringles_ketchup_175.jpg",
    //     alt: "pringles_ketchup_175",
    //     url1: "./images/shop/food/snacks/chips/pringles_ketchup_175-01.jpg",
    //     alt1: "pringles_ketchup_175-01",
    //     url2: "./images/shop/food/snacks/chips/pringles_ketchup_175-02.jpg",
    //     alt2: "pringles_ketchup_175-02",
    //     url3: "./images/shop/food/snacks/chips/pringles_ketchup_175-03.jpg",
    //     alt3: "pringles_ketchup_175-03",
    //     url4: "./images/shop/food/snacks/chips/pringles_ketchup_175-04.jpg",
    //     alt4: "pringles_ketchup_175-04",
    //     marker: "FDCH553",
    //     brand: "Pringles",
    //     search: "принглс прінглс чипсы со вкусом кетчупа",
    //     nameUKR: "Чіпси зі смаком кетчупу",
    //     nameEN: "Ketchup",
    //     companyName: "Kellogg's",
    //     countryName: "Англія",
    //     weightName: "Вага",
    //     weight: "175 гр.",
    //     priceGRN: 96,
    //     priceGRNOpt: 88,
    //     description01: "Запрошуємо Вас на смаковиту подорож із неймовірними чипсами &#171Pringles - Ketchup&#187.",
    //     description02: "Ці чіпси вражають не лише неперевершеним смаком кетчупу, але й хрусткістю, яка робить кожен пелюсток неповторним.",
    //     description03: "Хочете насолоджуватися бездоганним смаком у кожному кусочку? Оберіть &#171Pringles - Ketchup&#187 і насолоджуйтесь унікальним поєднанням хрусткості та смаком кетчупу.",
    //     description04: "<strong>Смак: кетчуп.</strong>",
    //     description05: "Спробуйте ці чудові чипси вже сьогодні, зробіть Ваші перерви смачними - оберіть &#171Pringles - Ketchup&#187 для непередбачуваного смакового враження!"
    // },
    // {
    //     type: "wholesale",
    // mainCategory: "foodstuffs",
        // subcategory: "snacks",    
    // url: "./images/shop/food/snacks/chips/pringles_pizza_flavour_175.jpg",
    //     alt: "pringles_pizza_flavour_175",
    //     url1: "./images/shop/food/snacks/chips/pringles_pizza_flavour_175-01.jpg",
    //     alt1: "pringles_pizza_flavour_175-01",
    //     url2: "./images/shop/food/snacks/chips/pringles_pizza_flavour_175-02.jpg",
    //     alt2: "pringles_pizza_flavour_175-02",
    //     url3: "./images/shop/food/snacks/chips/pringles_pizza_flavour_175-03.jpg",
    //     alt3: "pringles_pizza_flavour_175-03",
    //     url4: "./images/shop/food/snacks/chips/pringles_pizza_flavour_175-04.jpg",
    //     alt4: "pringles_pizza_flavour_175-04",
    //     marker: "FDCH557",
    //     brand: "Pringles",
    //     search: "принглс прінглс чипсы со вкусом пиццы пицца с пиццой пиццей з піцею",
    //     nameUKR: "Чіпси зі смаком піци",
    //     nameEN: "Pizza Flavour",
    //     companyName: "Kellogg's",
    //     countryName: "Англія",
    //     weightName: "Вага",
    //     weight: "175 гр.",
    //     priceGRN: 96,
    //     priceGRNOpt: 88,
    //     description01: "&#171Pringles - Pizza Flavour&#187 - це справжній шедевр, який переносить Вас до італійської піцерії з кожним ковзком. Їх неперевершений смак відтворює смачну суміш сиру, помідорів та ароматних спецій.",
    //     description02: "Смак &#171Pringles - Pizza Flavour&#187 - це справжнє поєднання тепла та затишку, які приносить з собою італійська піца. Ці чіпси дозволяють Вам насолоджуватися улюбленим смаком навіть на робочому місці або вдома.",
    //     description03: "Завжди гарантують свіжість та смакове насолодження завдяки своєму унікальному трубчастому пакуванню. Спробуйте ці чіпси і перенесіть себе до мальовничої Італії кожен раз, коли відкриваєте упаковку.",
    //     description04: "<strong>Смак: піца.</strong>",
    //     description05: "Замовте &#171Pringles - Pizza Flavour&#187 прямо зараз та насолоджуйтеся справжньою італійською піцею!"
    // },
    // {
    //     type: "wholesale",
    // mainCategory: "foodstuffs",
        // subcategory: "snacks",    
    // url: "./images/shop/food/snacks/chips/pringles_prawn_cocktail_165.jpg",
    //     alt: "pringles_prawn_cocktail_165",
    //     url1: "./images/shop/food/snacks/chips/pringles_prawn_cocktail_165-01.jpg",
    //     alt1: "pringles_prawn_cocktail_165-01",
    //     url2: "./images/shop/food/snacks/chips/pringles_prawn_cocktail_165-02.jpg",
    //     alt2: "pringles_prawn_cocktail_165-02",
    //     url3: "./images/shop/food/snacks/chips/pringles_prawn_cocktail_165-03.jpg",
    //     alt3: "pringles_prawn_cocktail_165-03",
    //     url4: "./images/shop/food/snacks/chips/pringles_prawn_cocktail_165-04.jpg",
    //     alt4: "pringles_prawn_cocktail_165-04",
    //     marker: "FDCH565",
    //     brand: "Pringles",
    //     search: "принглс прінглс чипсы со вкусом креветка креветки",
    //     nameUKR: "Чіпси зі смаком креветок",
    //     nameEN: "Prawn Cocktail",
    //     companyName: "Kellogg's",
    //     countryName: "Англія",
    //     weightName: "Вага",
    //     weight: "165 гр.",
    //     priceGRN: 92,
    //     priceGRNOpt: 84,
    //     description01: "&#171Pringles - Prawn Cocktail&#187 - це справжнє відкриття для шанувальників найніжнішого морського смаку. Кожен ковзок цих чіпсів наповнений ароматом тропічних креветок, які створюють неперевершений смак.",
    //     description02: "Справжнє поєднання ніжності морських страв та тропічних фруктів. Ці чіпси ідеально пасують до будь-якого заходу, будь то пікнік на природі чи вечірка з друзями, завжди викликаючи захоплення гостей.",
    //     description03: "&#171Pringles - Prawn Cocktail&#187 завжди гарантують свіжість і смакову насолоду завдяки своєму унікальному трубчастому пакуванню. Спробуйте ці чіпси і насолоджуйтесь смаком літа і моря у будь-який час року.",
    //     description04: "<strong>Смак: креветка.</strong>",
    //     description05: "Замовте &#171Pringles - Prawn Cocktail&#187 прямо зараз і подаруйте собі справжню тропічну вечірку у кожному ковзку. Насолоджуйтеся смаком моря разом з нами!"
    // },
    // {
    //     type: "wholesale",
    // mainCategory: "foodstuffs",
        // subcategory: "snacks",    
    // url: "./images/shop/food/snacks/chips/pringles_salt_vinegar_185.jpg",
    //     alt: "pringles_salt_vinegar_185",
    //     url1: "./images/shop/food/snacks/chips/pringles_salt_vinegar_185-01.jpg",
    //     alt1: "pringles_salt_vinegar_185-01",
    //     url2: "./images/shop/food/snacks/chips/pringles_salt_vinegar_185-02.jpg",
    //     alt2: "pringles_salt_vinegar_185-02",
    //     url3: "./images/shop/food/snacks/chips/pringles_salt_vinegar_185-03.jpg",
    //     alt3: "pringles_salt_vinegar_185-03",
    //     url4: "./images/shop/food/snacks/chips/pringles_salt_vinegar_185-04.jpg",
    //     alt4: "pringles_salt_vinegar_185-04",
    //     marker: "FDCH567",
    //     brand: "Pringles",
    //     search: "принглс прінглс чипсы со вкусом соли соль и уксуса уксус",
    //     nameUKR: "Чіпси зі смаком солі та оцету",
    //     nameEN: "Salt & Vinegar",
    //     companyName: "Kellogg's",
    //     countryName: "Англія",
    //     weightName: "Вага",
    //     weight: "185 гр.",
    //     priceGRN: 101,
    //     priceGRNOpt: 92,
    //     description01: "Відкрийте яскравий смаковий вибух з чудовим поєднанням солі та оцету - чіпси &#171Pringles - Salt & Vinegar&#187.",
    //     description02: "Ці чіпси вирізняються неповторним поєднанням солі та оцету, створюючи неповторний смаковий бум.",
    //     description03: "Якщо Ви шукаєте чіпси, які підкреслять Ваші відчуття, &#171Pringles - Salt & Vinegar&#187 - ідеальний вибір для Вас.",
    //     description04: "<strong>Смак: сіль, оцет.</strong>",
    //     description05: "Замовляйте Pringles - Salt & Vinegar прямо зараз, і відчуйте виразну гармонію солі та оцету у кожному шматочку!"
    // },
    // {
    //     type: "wholesale",
    // mainCategory: "foodstuffs",
        // subcategory: "snacks",    
    // url: "./images/shop/food/snacks/chips/pringles_sour_cream_onion_40.jpg",
    //     alt: "pringles_sour_cream_onion_40",
    //     url1: "./images/shop/food/snacks/chips/pringles_sour_cream_onion_40-01.jpg",
    //     alt1: "pringles_sour_cream_onion_40-01",
    //     url2: "./images/shop/food/snacks/chips/pringles_sour_cream_onion_40-02.jpg",
    //     alt2: "pringles_sour_cream_onion_40-02",
    //     url3: "./images/shop/food/snacks/chips/pringles_sour_cream_onion_40-03.jpg",
    //     alt3: "pringles_sour_cream_onion_40-03",
    //     url4: "./images/shop/food/snacks/chips/pringles_sour_cream_onion_40-04.jpg",
    //     alt4: "pringles_sour_cream_onion_40-04",
    //     marker: "FDCH570",
    //     brand: "Pringles",
    //     search: "принглс прінглс чипсы со вкусом сметаны и лука цибулі лук",
    //     nameUKR: "Чіпси зі смаком сметани та цибулі",
    //     nameEN: "Sour Cream & Onion",
    //     companyName: "Kellogg's",
    //     countryName: "Англія",
    //     weightName: "Вага",
    //     weight: "40 гр.",
    //     priceGRN: 42,
    //     priceGRNOpt: 38,
    //     description01: "&#171Pringles - Sour Cream & Onion&#187 - це справжній смаковий екстаз, який приносить неймовірну насолоду. Кожен ковзок цих чіпсів насичений смаком ніжної сметани та ароматом свіжої цибулі, створюючи неперевершений баланс солодких та гострих ноток.",
    //     description02: "Смак &#171Pringles - Sour Cream & Onion&#187 - це ідеальне поєднання смаку сметани та пікантності цибулі, яке завжди приносить задоволення. Ці чіпси - ідеальний вибір для дегустації під час перегляду фільму, пікніка на природі або як швидка смачна закуска під час перерви на обід.",
    //     description03: "&#171Pringles - Sour Cream & Onion&#187 завжди гарантують свіжість та смакове насолодження завдяки своєму унікальному трубчастому пакуванню. Спробуйте ці чіпси і насолоджуйтесь найкращим смаком в кожному ковзку.",
    //     description04: "<strong>Смак: сметана та цибуля.</strong>",
    //     description05: "Не вагайтеся, зануртесь у смачний світ з &#171Pringles - Sour Cream & Onion&#187 і дайте собі справжню насолоду!"
    // },
    // {
    //     type: "wholesale",
    // mainCategory: "foodstuffs",
        // subcategory: "snacks",    
    // url: "./images/shop/food/snacks/chips/pringles_sour_cream_onion_165.jpg",
    //     alt: "pringles_sour_cream_onion_165",
    //     url1: "./images/shop/food/snacks/chips/pringles_sour_cream_onion_165-01.jpg",
    //     alt1: "pringles_sour_cream_onion_165-01",
    //     url2: "./images/shop/food/snacks/chips/pringles_sour_cream_onion_165-02.jpg",
    //     alt2: "pringles_sour_cream_onion_165-02",
    //     marker: "FDCH575",
    //     brand: "Pringles",
    //     search: "принглс прінглс чипсы со вкусом сметаны и лука цибулі лук",
    //     nameUKR: "Чіпси зі смаком сметани та цибулі",
    //     nameEN: "Sour Cream & Onion",
    //     companyName: "Kellogg's",
    //     countryName: "Англія",
    //     weightName: "Вага",
    //     weight: "165 гр.",
    //     priceGRN: 92,
    //     priceGRNOpt: 84,
    //     description01: "&#171Pringles - Sour Cream & Onion&#187 - це справжній смаковий екстаз, який приносить неймовірну насолоду. Кожен ковзок цих чіпсів насичений смаком ніжної сметани та ароматом свіжої цибулі, створюючи неперевершений баланс солодких та гострих ноток.",
    //     description02: "Смак &#171Pringles - Sour Cream & Onion&#187 - це ідеальне поєднання смаку сметани та пікантності цибулі, яке завжди приносить задоволення. Ці чіпси - ідеальний вибір для дегустації під час перегляду фільму, пікніка на природі або як швидка смачна закуска під час перерви на обід.",
    //     description03: "&#171Pringles - Sour Cream & Onion&#187 завжди гарантують свіжість та смакове насолодження завдяки своєму унікальному трубчастому пакуванню. Спробуйте ці чіпси і насолоджуйтесь найкращим смаком в кожному ковзку.",
    //     description04: "<strong>Смак: сметана та цибуля.</strong>",
    //     description05: "Не вагайтеся, зануртесь у смачний світ з &#171Pringles - Sour Cream & Onion&#187 і дайте собі справжню насолоду!"
    // },
    // {
    //     type: "wholesale",
    // mainCategory: "foodstuffs",
        // subcategory: "snacks",    
    // url: "./images/shop/food/snacks/chips/pringles_texas_bbq_sauce_40.jpg",
    //     alt: "pringles_texas_bbq_sauce_40",
    //     url1: "./images/shop/food/snacks/chips/pringles_texas_bbq_sauce_40-01.jpg",
    //     alt1: "pringles_texas_bbq_sauce_40-01",
    //     url2: "./images/shop/food/snacks/chips/pringles_texas_bbq_sauce_40-02.jpg",
    //     alt2: "pringles_texas_bbq_sauce_40-02",
    //     url3: "./images/shop/food/snacks/chips/pringles_texas_bbq_sauce_40-03.jpg",
    //     alt3: "pringles_texas_bbq_sauce_40-03",
    //     url4: "./images/shop/food/snacks/chips/pringles_texas_bbq_sauce_40-04.jpg",
    //     alt4: "pringles_texas_bbq_sauce_40-04",
    //     marker: "FDCH580",
    //     brand: "Pringles",
    //     search: "принглс прінглс чипсы со вкусом соуса",
    //     nameUKR: "Чіпси зі смаком соусу барбекю",
    //     nameEN: "Texas BBQ Sauce",
    //     companyName: "Kellogg's",
    //     countryName: "Англія",
    //     weightName: "Вага",
    //     weight: "40 гр.",
    //     priceGRN: 42,
    //     priceGRNOpt: 38,
    //     description01: "&#171Pringles - Texas BBQ Sauce&#187 - це справжня смакова подорож на дикий захід, яка переносить Вас до атмосфери Техасу. Кожен ковзок цих чіпсів вирушає в експедицію у пошуках смаженого м'яса та вогняного соусу барбекю.",
    //     description02: "Смак &#171Pringles - Texas BBQ Sauce&#187 - це справжня вибухова суміш солодкості та гостроти. Ці чіпси - ідеальний спосіб насолоджуватися смаком справжнього барбекю без гриля та коптильні.",
    //     description03: "Завжди гарантують свіжість та смакову насолоду завдяки своєму унікальному трубчастому пакуванню. Спробуйте ці чіпси і перенесіть себе на велику прерію Техасу.",
    //     description04: "<strong>Смак: соус барбекю.</strong>",
    //     description05: "Вирушайте у неймовірну смакову подорож і сміливо спробуйте &#171Pringles - Texas BBQ Sauce&#187 прямо зараз!"
    // },
    // {
    //     type: "wholesale",
    // mainCategory: "foodstuffs",
        // subcategory: "snacks",    
    // url: "./images/shop/food/snacks/chips/pringles_texas_bbq_sauce_175.jpg",
    //     alt: "pringles_texas_bbq_sauce_175",
    //     url1: "./images/shop/food/snacks/chips/pringles_texas_bbq_sauce_175-01.jpg",
    //     alt1: "pringles_texas_bbq_sauce_175-01",
    //     url2: "./images/shop/food/snacks/chips/pringles_texas_bbq_sauce_175-02.jpg",
    //     alt2: "pringles_texas_bbq_sauce_175-02",
    //     url3: "./images/shop/food/snacks/chips/pringles_texas_bbq_sauce_175-03.jpg",
    //     alt3: "pringles_texas_bbq_sauce_175-03",
    //     url4: "./images/shop/food/snacks/chips/pringles_texas_bbq_sauce_175-04.jpg",
    //     alt4: "pringles_texas_bbq_sauce_175-04",
    //     marker: "FDCH587",
    //     brand: "Pringles",
    //     search: "принглс прінглс чипсы со вкусом соуса",
    //     nameUKR: "Чіпси зі смаком соусу барбекю",
    //     nameEN: "Texas BBQ Sauce",
    //     companyName: "Kellogg's",
    //     countryName: "Англія",
    //     weightName: "Вага",
    //     weight: "175 гр.",
    //     priceGRN: 96,
    //     priceGRNOpt: 88,
    //     description01: "&#171Pringles - Texas BBQ Sauce&#187 - це справжня смакова подорож на дикий захід, яка переносить Вас до атмосфери Техасу. Кожен ковзок цих чіпсів вирушає в експедицію у пошуках смаженого м'яса та вогняного соусу барбекю.",
    //     description02: "Смак &#171Pringles - Texas BBQ Sauce&#187 - це справжня вибухова суміш солодкості та гостроти. Ці чіпси - ідеальний спосіб насолоджуватися смаком справжнього барбекю без гриля та коптильні.",
    //     description03: "Завжди гарантують свіжість та смакову насолоду завдяки своєму унікальному трубчастому пакуванню. Спробуйте ці чіпси і перенесіть себе на велику прерію Техасу.",
    //     description04: "<strong>Смак: соус барбекю.</strong>",
    //     description05: "Вирушайте у неймовірну смакову подорож і сміливо спробуйте &#171Pringles - Texas BBQ Sauce&#187 прямо зараз!"
    // },
]