export const shopLotsTarhona = [
    {
        type: "wholesale",
        url: "./images/shop/food/pasta/tarhona/combino_tarhona_500.jpg",
        alt: "combino_tarhona_500",
        url1: "./images/shop/food/pasta/tarhona/combino_tarhona_500.jpg",
        alt1: "combino_tarhona_500",
        marker: "FDRH100",
        brand: "Combino",
        search: "лидл лідл комбино комбіно торгоня твердый твердий сорт тверді сорта твердые сорта с твердых сортов яичная",
        nameUKR: "Яєчна тархоня з твердих сортів",
        nameEN: "Tarhoňa",
        companyName: "Lidl",
        countryName: "Чехія",
        weightName: "Вага",
        weight: "500 гр.",
        priceGRN: 60,
        priceGRNOpt: 55,
        description01: "&#171Combino - Tarhoňa&#187 - це вишуканий дарунок для вашого кулінарного репертуару. Цей традиційний угорський вид тархоні виготовлений з високоякісного пшеничного борошна, що додає вашим стравам неповторний смак.",
        description02: "З &#171Combino - Tarhoňa&#187 кожна страва стає непередбачено смачною подорожжю. ЇЇ виготовлення відбувається відповідно до традиційних рецептів, що забезпечує Вам смак угорської кухні прямо на вашому столі.",
        description03: "&#171Combino - Tarhoňa&#187 - це не тільки продукт, це спосіб приготування найсмачніших страв. Його текстура ідеально поєднується з різноманітними соусами та начинками, роблячи ваш обід справжнім відкриттям.",
        description04: "<strong>Тархоня з твердих сортів пшениці. Яєчна.</strong>",
        description05: "Створіть на своїй кухні справжні кулінарні шедеври з &#171Combino - Tarhoňa&#187 та пориньте у світ угорської кухні!"
    },
    {
        type: "wholesale",
        url: "./images/shop/food/pasta/tarhona/csaszar_dorzstarhonya_250.jpg",
        alt: "csaszar_dorzstarhonya_250",
        url1: "./images/shop/food/pasta/tarhona/csaszar_dorzstarhonya_250.jpg",
        alt1: "csaszar_dorzstarhonya_250",
        marker: "FDRH150",
        brand: "Császár",
        search: "рваная торгоня яєчна яичная",
        nameUKR: "Яєчна рвана тархоня",
        nameEN: "Dörzstarhonya",
        companyName: "Familiatészta Kft",
        countryName: "Угорщина",
        weightName: "Вага",
        weight: "250 гр.",
        priceGRN: 49,
        priceGRNOpt: 44,
        description01: "&#171Császár - Dörzstarhonya&#187 - це справжній шедевр кулінарії. Кожен шматочок виготовлений із відбірного борошна, що гарантує Вам неймовірну текстуру та чудовий смак.",
        description02: "Стане відмінним доповненням до будь-якої страви. Її рвана структура не лише приваблює погляд, але і відмінно утримує будь-який соус, даруючи кожному кушту вишуканість та насиченість.",
        description03: "&#171Császár - Dörzstarhonya&#187 виготовляється за старовинними рецептами та з використанням передових технологій для забезпечення Вам продукту вищого стандарту.",
        description04: "<strong>Тархоня, рвана. 8 яєць.</strong>",
        description05: "Варіть &#171Császár - Dörzstarhonya&#187 з улюбленими соусами та насолоджуйтеся якістю і смаковим багатством!"
    },
    {
        type: "wholesale",
        url: "./images/shop/food/pasta/tarhona/hedan_plus_tarhona_370.jpg",
        alt: "hedan_plus_tarhona_370",
        url1: "./images/shop/food/pasta/tarhona/hedan_plus_tarhona_370.jpg",
        alt1: "hedan_plus_tarhona_370",
        marker: "FDRH250",
        brand: "Hedan Plus",
        search: "хедан плюс торгоня твердый твердий сорт тверді сорта твердые сорта с твердых сортов яєчна яичная",
        nameUKR: "Яєчна тархоня з твердих сортів",
        nameEN: "Tarhoňa",
        companyName: "Hedan Plus, s.r.o.",
        countryName: "Словаччина",
        weightName: "Вага",
        weight: "370 гр.",
        priceGRN: 49,
        priceGRNOpt: 44,
        description01: "&#171Hedan Plus - Tarhoňa&#187 - це вишукане доповнення до вашого кулінарного арсеналу. Ці тістечка виробляються з високоякісного борошна, що гарантує їхню ідеальну текстуру та вишуканий смак, який додасть ексклюзивності будь-якій страві.",
        description02: "Вони не лише легко готуються, але і будуть основою для найсмачніших страв. Їх унікальна форма виглядає не лише привабливо, але й утримує соуси та смак.",
        description03: "&#171Hedan Plus - Tarhoňa&#187 зберігає всі корисні властивості пшениці, а висока якість засвідчена традиціями та кваліфікацією майстрів.",
        description04: "<strong>Тархоня з твердих сортів пшениці. 3 яйця.</strong>",
        description05: "Додайте &#171Hedan Plus - Tarhoňa&#187 до вашого улюбленого рецепту та пориньте у світ смакових експлозій!"
    },
    {
        type: "wholesale",
        url: "./images/shop/food/pasta/tarhona/izsaki_eros_pistas_csipetke_200.jpg",
        alt: "izsaki_eros_pistas_csipetke_200",
        url1: "./images/shop/food/pasta/tarhona/izsaki_eros_pistas_csipetke_200.jpg",
        alt1: "izsaki_eros_pistas_csipetke_200",
        marker: "FDRH300",
        brand: "Izsáki Házitészta KFT",
        search: "яєчна яичная рваная торгоня острая острый",
        nameUKR: "Яєчна гостра рвана тархоня",
        nameEN: "Erős Pistás Csipetke",
        companyName: "Izsáki Házitészta KFT",
        countryName: "Угорщина",
        weightName: "Вага",
        weight: "200 гр.",
        priceGRN: 49,
        priceGRNOpt: 44,
        description01: "&#171Izsáki Házitészta KFT - Erős Pistás Csipetke&#187 - це поєднання вишуканості та пікантності стане справжньою окрасою вашого столу, а аромат угорських спецій додасть смаковій палітрі неперевершеної глибини.",
        description02: "Виготовлена з відібраних сортів пшениці, що забезпечують максимальний смак та структуру. Ви відчуєте витонченість інгредієнтів найвищої якості.",
        description03: "Відчуйте справжню цінність та тепло ручної праці у кожному шматочку &#171Izsáki Házitészta KFT - Erős Pistás Csipetke&#187.",
        description04: "<strong>Тархоня гостра, рвана. 4 яйця.</strong>",
        description05: "Дозвольте собі смакову подорож з найкращою &#171Izsáki Házitészta KFT - Erős Pistás Csipetke&#187 та створіть неповторний шедевр просто на власній кухні!"
    },
    {
        type: "wholesale",
        url: "./images/shop/food/pasta/tarhona/jarmi_szarazteszta_mini_500.jpg",
        alt: "jarmi_szarazteszta_mini_500",
        url1: "./images/shop/food/pasta/tarhona/jarmi_szarazteszta_mini_500.jpg",
        alt1: "jarmi_szarazteszta_mini_500",
        marker: "FDRH350",
        brand: "Jármi",
        search: "ярмі ярми мелкая торгоня твердый твердий сорт тверді сорта твердые сорта с твердых сортов",
        nameUKR: "Дрібна тархоня з твердих сортів",
        nameEN: "Száraztészta",
        companyName: "Jármitészta",
        countryName: "Угорщина",
        weightName: "Вага",
        weight: "500 гр.",
        priceGRN: 43,
        priceGRNOpt: 39,
        description01: "&#171Jármi - Száraztészta&#187 - це чудова можливість додати смак угорської кухні до вашого щоденного меню. Ці тістечка виготовлені із відібраного борошна, гарантуючи вам ідеальну текстуру та аромат, які стануть основою для справжніх шедеврів у вашій кухні.",
        description02: "Це не лише продукт, це можливість виразити свою творчість у кулінарії. Його універсальність дозволяє поєднувати з різноманітними соусами та інгредієнтами, створюючи величезний спектр страв для всієї родини.",
        description03: "Кожна пачка &#171Jármi - Száraztészta&#187 - це результат дбайливого відбору сировини та високотехнологічного виробництва. Тістечка зберігають усі корисні властивості пшениці, готуючись швидко та легко.",
        description04: "<strong>Тархоня з твердих сортів пшениці. Без яєць. Дрібна.</strong>",
        description05: "Зберіть родину за стіл, приготуйте свої улюблені страви та насолоджуйтеся унікальним смаком угорської кухні просто у вашому домі разом з &#171Jármi - Száraztészta&#187!"
    },
    {
        type: "wholesale",
        url: "./images/shop/food/pasta/tarhona/jarmi_szarazteszta_max_500.jpg",
        alt: "jarmi_szarazteszta_max_500",
        url1: "./images/shop/food/pasta/tarhona/jarmi_szarazteszta_max_500.jpg",
        alt1: "jarmi_szarazteszta_max_500",
        marker: "FDRH355",
        brand: "Jármi",
        search: "ярмі ярми крупная торгоня твердый твердий сорт тверді сорта твердые сорта с твердых сортов",
        nameUKR: "Крупна тархоня з твердих сортів",
        nameEN: "Száraztészta",
        companyName: "Jármitészta",
        countryName: "Угорщина",
        weightName: "Вага",
        weight: "500 гр.",
        priceGRN: 43,
        priceGRNOpt: 39,
        description01: "&#171Jármi - Száraztészta&#187 - це чудова можливість додати смак угорської кухні до вашого щоденного меню. Ці тістечка виготовлені із відібраного борошна, гарантуючи вам ідеальну текстуру та аромат, які стануть основою для справжніх шедеврів у вашій кухні.",
        description02: "Це не лише продукт, це можливість виразити свою творчість у кулінарії. Його універсальність дозволяє поєднувати з різноманітними соусами та інгредієнтами, створюючи величезний спектр страв для всієї родини.",
        description03: "Кожна пачка &#171Jármi - Száraztészta&#187 - це результат дбайливого відбору сировини та високотехнологічного виробництва. Тістечка зберігають усі корисні властивості пшениці, готуючись швидко та легко.",
        description04: "<strong>Тархоня з твердих сортів пшениці. Без яєць. Крупна.</strong>",
        description05: "Зберіть родину за стілом, приготуйте свої улюблені страви та насолоджуйтеся унікальним смаком угорської кухні просто у вашому домі разом з &#171Jármi - Száraztészta&#187!"
    },
    {
        type: "wholesale",
        url: "./images/shop/food/pasta/tarhona/jarmi_szarazteszta_cut_500.jpg",
        alt: "jarmi_szarazteszta_cut_500",
        url1: "./images/shop/food/pasta/tarhona/jarmi_szarazteszta_cut_500.jpg",
        alt1: "jarmi_szarazteszta_cut_500",
        marker: "FDRH360",
        brand: "Jármi",
        search: "ярмі ярми рваная торгоня твердый твердий сорт тверді сорта твердые сорта с твердых сортов",
        nameUKR: "Рвана тархоня з твердих сортів",
        nameEN: "Száraztészta",
        companyName: "Jármitészta",
        countryName: "Угорщина",
        weightName: "Вага",
        weight: "500 гр.",
        priceGRN: 43,
        priceGRNOpt: 39,
        description01: "&#171Jármi - Száraztészta&#187 виготовлена з відібраних сортів пшениці та води. Ця тістова чудовизна гарантує насичений смак і неповторну текстуру.",
        description02: "Вибір кращих інгредієнтів для тархоні гарантує не тільки смачний вечірній обід, але і збереження корисних властивостей пшениці. З нею Ви отримаєте неабияку порцію білка та інших необхідних елементів для вашого здоров'я.",
        description03: "Завдяки особливому способу виробництва, рвана тархона &#171Jármi - Száraztészta&#187 готується легко та швидко. На кухні Ви швидко перетворите її у справжній шедевр, що подарує Вам і вашій родині незабутні смакові враження.",
        description04: "<strong>Тархоня з твердих сортів пшениці, рвана. Без яєць.</strong>",
        description05: "Покохайте справжню угорську кухню з &#171Jármi - Száraztészta&#187 та пориньте в атмосферу витонченості та враження!"
    },
    {
        type: "wholesale",
        url: "./images/shop/food/pasta/tarhona/jarmi_reszeltteszta_250.jpg",
        alt: "jarmi_reszeltteszta_250",
        url1: "./images/shop/food/pasta/tarhona/jarmi_reszeltteszta_250-01.jpg",
        alt1: "jarmi_reszeltteszta_250-01",
        url2: "./images/shop/food/pasta/tarhona/jarmi_reszeltteszta_250-02.jpg",
        alt2: "jarmi_reszeltteszta_250-02",
        marker: "FDRH365",
        brand: "Jármi",
        search: "ярмі ярми рваная торгоня твердый твердий сорт тверді сорта твердые сорта с твердых сортов",
        nameUKR: "Яєчна рвана тархоня з твердих сортів",
        nameEN: "Reszelttészta",
        companyName: "Jármitészta",
        countryName: "Угорщина",
        weightName: "Вага",
        weight: "250 гр.",
        priceGRN: 47,
        priceGRNOpt: 42,
        description01: "Рвана тархоня з твердих сортів &#171Jármi - Reszelttészta&#187 справжнє відкриття для любителів справжньої угорської кухні.",
        description02: "Ця тархоня вражає своєю витонченою текстурою та багатим смаком, який надається використанням твердих сортів пшениці та з додованням яєць.",
        description03: "Відчуйте бажання справжнього гурмана, насолоджуючись неперевершеним смаком, який переносить Вас у затишок домашньої оселі.",
        description04: "<strong>Тархоня з твердих сортів пшениці, рвана. 8 яэць.</strong>",
        description05: "Замовте &#171Jármi - Reszelttészta&#187 вже зараз і зануртеся в аутентичний смак угорської кухні!"
    },
    // {
    //     type: "wholesale",
    //     url: "./images/shop/food/pasta/tarhona/tiradell_tarhona_500.jpg",
    //     alt: "tiradell_tarhona_500",
    //     url1: "./images/shop/food/pasta/tarhona/tiradell_tarhona_500.jpg",
    //     alt1: "tiradell_tarhona_500",
    //     marker: "FDRH700",
    //     brand: "Tiradell",
    //     search: "тирадел тірадел тіраделл тираделл торгоня твердый твердий сорт тверді сорта твердые сорта с твердых сортов",
    //     nameUKR: "Тархоня з твердих сортів",
    //     nameEN: "Tarhoňa",
    //     companyName: "Lidl",
    //     countryName: "Словаччина",
    //     weightName: "Вага",
    //     weight: "500 гр.",
    //     priceGRN: 43,
    //     priceGRNOpt: 39,
    //     description01: "&#171Tiradell - Tarhoňa&#187 - це справжнє втілення традиційного смаку на вашій кухні. Виготовлені з відібраного пшеничного борошна, ці тістечка мають особливу форму, яка ідеально утримує соуси та створює гармонію смаків.",
    //     description02: "Це не просто страва, а можливість створити власний кулінарний шедевр. З їхньою допомогою Ви зможете створювати найсмачніші страви, додавати оригінальність угорського смаку вашому столу.",
    //     description03: "&#171Tiradell - Tarhoňa&#187 - це обіцянка високої якості та неперевершеного смаку. Традиційний метод виготовлення гарантує, що Ви отримаєте продукт високої якості, який додасть Вам задоволення.",
    //     description04: "<strong>Тархоня з твердих сортів пшениці. Без яєць.</strong>",
    //     description05: "Зробіть ваші кулінарні експерименти захопливими з &#171Tiradell - Tarhoňa&#187 та насолоджуйтеся унікальним смаком, який створить справжню атмосферу на вашій кухні!"
    // },
]