export const shopLotsPeanuts = [
    {
        type: "wholesale оптом",
        mainCategory: "foodstuffs",
        subcategory: "snacks",
        url: "./images/shop/food/snacks/peanuts/alesto_peanuts_roasted_salted_500.jpg",
        alt: "alesto_peanuts_roasted_salted_500",
        url1: "./images/shop/food/snacks/peanuts/alesto_peanuts_roasted_salted_500.jpg",
        alt1: "alesto_peanuts_roasted_salted_500",
        marker: "FDPS010",
        brand: "Alesto",
        search: "лидл лідл алесто сіль соль соленый арахис",
        nameUKR: "Солоний арахіс",
        nameEN: "Peanuts Roasted & Salted",
        companyName: "Lidl",
        countryName: "Німеччина",
        weightName: "Вага",
        weight: "500 гр.",
        priceGRN: 107,
        priceGRNOpt: 98,
        description01: "&#171Alesto - Peanuts Roasted & Salted&#187 - це вишукана закуска, що вражає вас своєю смаковою глибиною. Кожен арахіс ретельно обсмажується для досягнення ідеальної хрусткої текстури і надзвичайно смаку.",
        description02: "&#171Alesto&#187 виводить арахіс на новий рівень, роблячи його відмінним смаковим додатком до вашого дня. Ці обсмажені і посолені арахіси - це ідеальна закуска для вечірнього відпочинку, спортивних заходів або просто задоволення своїх смакових прагнень.",
        description03: "Коли Ви обираєте &#171Alesto - Peanuts Roasted & Salted&#187, Ви обираєте якість та справжню природню насолоду. Завдяки їх багатому смаку та корисним властивостям, Ви можете насолоджуватися  арахісом з повним переконанням у їхній якості.",
        description04: "<strong>Арахіс солоний, підсмажений.</strong>",
        description05: "Замовте &#171Alesto - Peanuts Roasted & Salted&#187 прямо зараз та насолоджуйтеся цією неперевершеною закускою!"
    },
    // {
    //     type: "wholesale оптом",
    // mainCategory: "foodstuffs",
        // subcategory: "snacks",    
    // url: "./images/shop/food/snacks/peanuts/ensa_arasidy_100.jpg",
    //     alt: "ensa_arasidy_100",
    //     url1: "./images/shop/food/snacks/peanuts/ensa_arasidy_100.jpg",
    //     alt1: "ensa_arasidy_100",
    //     marker: "FDPS300",
    //     brand: "Ensa",
    //     search: "энса енса сіль соль соленый арахис",
    //     nameUKR: "Солоний арахіс",
    //     nameEN: "Arašidy Pražené Solené",
    //     companyName: "ENCINGER, spol.",
    //     countryName: "Чехія",
    //     weightName: "Вага",
    //     weight: "100 гр.",
    //     priceGRN: 23,
    //     priceGRNOpt: 19,
    //     description01: "&#171Ensa - Arašidy Pražené Solené&#187 - це справжня вишуканість для любителів арахісу. Кожне зерно арахісу обсмажується з особливою уважністю, щоб забезпечити ідеальний хруст та солодко-солоний смак. Це поєднання хрустких та неперевершених смаків робить цей продукт незабутнім.",
    //     description02: "З &#171Ensa - Arašidy Pražené Solené&#187 Ви отримуєте солоний арахіс, який ідеально підходить для перекусу у будь-який момент. Він підніме ваш настрій і забезпечить вас енергією на весь день. Ця закуска стане вашим найкращим другом під час перегляду фільмів, спортивних подій або просто відпочинку на природі.",
    //     description03: "Ви отримаєте не тільки смачний арахіс, але й корисний додаток до вашого раціону. Відкрийте для себе світ насолоди і енергії завдяки цій унікальній закусці.",
    //     description04: "<strong>Арахіс солоний, підсмажений.</strong>",
    //     description05: "Спробуйте &#171Ensa - Arašidy Pražené Solené&#187 вже сьогодня і насолоджуйтеся смаком і якістю, яку можна отримати тільки від найкращих продуктів."
    // },
    // {
    //     type: "retail",
    // mainCategory: "foodstuffs",
        // subcategory: "snacks",    
    // url: "./images/shop/food/snacks/peanuts/mani_king_tostado_sin_piel_120.jpg",
    //     alt: "mani_king_tostado_sin_piel_120",
    //     url1: "./images/shop/food/snacks/peanuts/mani_king_tostado_sin_piel_120-01.jpg",
    //     alt1: "mani_king_tostado_sin_piel_120-01",
    //     url2: "./images/shop/food/snacks/peanuts/mani_king_tostado_sin_piel_120-02.jpg",
    //     alt2: "mani_king_tostado_sin_piel_120-02",
    //     url3: "./images/shop/food/snacks/peanuts/mani_king_tostado_sin_piel_120-03.jpg",
    //     alt3: "mani_king_tostado_sin_piel_120-03",
    //     marker: "FDPS400",
    //     brand: "Mani King",
    //     search: "мани мані кинг кінг сіль соль соленый арахис",
    //     nameUKR: "Солоний арахіс",
    //     nameEN: "Tostado sin Piel",
    //     companyName: "Prodeman S.A.",
    //     countryName: "Аргентина",
    //     weightName: "Вага",
    //     weight: "120 гр.",
    //     priceGRN: 25,
    //     quantityOnStorage: 2,
    //     description01: "&#171Mani King - Tostado sin Piel&#187 - це справжня закуска для справжніх гурманів. Кожен арахіс  вибирається з найвищою уважністю та обсмажується, щоб забезпечити ідеальний солоний смак та хрустку текстуру. Ця закуска поєднує у собі солодку начинку та солоний післясмак, що робить її неперевершеною.",
    //     description02: "&#171Mani King - Tostado sin Piel&#187 пропонує Вам можливість насолодитися найкращим арахісом, який можна собі уявити. Ця закуска ідеально підходить для перекусу вдома, на вечірці чи в подорожі. Завдяки вишуканому солоному смаку, вона стане улюбленою закускою для всієї родини.",
    //     description03: "Ви обираєте найвищу якість та натуральний смак арахісу. Ця закуска гарантує вашій вечірці або перегляду фільмів особливий шарм та неперевершений смак.",
    //     description04: "<strong>Арахіс солоний.</strong>",
    //     description05: "Не вагайтеся та замовте &#171Mani King - Tostado sin Piel&#187 вже зараз і розважайте свою родину та друзів цією чудовою закускою!"
    // },
    {
        type: "wholesale оптом",
        mainCategory: "foodstuffs",
        subcategory: "snacks",
        url: "./images/shop/food/snacks/peanuts/mogyi_peanuts_roasted_salted_85.jpg",
        alt: "mogyi_peanuts_roasted_salted_85",
        url1: "./images/shop/food/snacks/peanuts/mogyi_peanuts_roasted_salted_85.jpg",
        alt1: "mogyi_peanuts_roasted_salted_85",
        marker: "FDPS450",
        brand: "Mogyi",
        search: "модь сіль соль соленый арахис",
        nameUKR: "Солоний арахіс",
        nameEN: "Peanuts Roasted, Salted",
        companyName: "MOGYI LTD. HU.",
        countryName: "Угорщина",
        weightName: "Вага",
        weight: "85 гр.",
        priceGRN: 24,
        priceGRNOpt: 21,
        description01: "&#171Mogyi - Peanuts Roasted, Salted&#187 - це закуска, яка підкорить Вас з першого разу. Кожен арахіс обсмажується з особливою увагою, щоб досягти ідеальної хрусткої текстури та солоного смаку. Цей арахіс поєднує у собі неперевершений солодкий смак з гармонійною солоністю, створюючи справжню насолоду.",
        description02: "Ця закуска ідеально підходить для перекусу у будь-який час дня. Вона стане відмінним супутником під час вечірки, спортивних змагань або просто для задоволення вашого апетиту.",
        description03: "&#171Mogyi - Peanuts Roasted, Salted&#187 - найкраща якість та неперевершений смак арахісу. Ця закуска додасть смаку вашим дням і зробить кожен момент особливим.",
        description04: "<strong>Арахіс солоний.</strong>",
        description05: "Замовляйте та спробуйте &#171Mogyi - Peanuts Roasted, Salted&#187 вже сьогодня і насолоджуйтеся смаком справжньої арахісової насолоди!"
    },
    {
        type: "wholesale оптом",
        mainCategory: "foodstuffs",
        subcategory: "snacks",
        url: "./images/shop/food/snacks/peanuts/mogyi_peanuts_roasted_salted_150.jpg",
        alt: "mogyi_peanuts_roasted_salted_150",
        url1: "./images/shop/food/snacks/peanuts/mogyi_peanuts_roasted_salted_150.jpg",
        alt1: "mogyi_peanuts_roasted_salted_150",
        marker: "FDPS460",
        brand: "Mogyi",
        search: "модь сіль соль соленый арахис",
        nameUKR: "Солоний арахіс",
        nameEN: "Peanuts Roasted, Salted",
        companyName: "MOGYI LTD. HU.",
        countryName: "Угорщина",
        weightName: "Вага",
        weight: "150 гр.",
        priceGRN: 41,
        priceGRNOpt: 36,
        description01: "&#171Mogyi - Peanuts Roasted, Salted&#187 - це закуска, яка підкорить Вас з першого разу. Кожен арахіс обсмажується з особливою увагою, щоб досягти ідеальної хрусткої текстури та солоного смаку. Цей арахіс поєднує у собі неперевершений солодкий смак з гармонійною солоністю, створюючи справжню насолоду.",
        description02: "Ця закуска ідеально підходить для перекусу у будь-який час дня. Вона стане відмінним супутником під час вечірки, спортивних змагань або просто для задоволення вашого апетиту.",
        description03: "&#171Mogyi - Peanuts Roasted, Salted&#187 - найкраща якість та неперевершений смак арахісу. Ця закуска додасть смаку вашим дням і зробить кожен момент особливим.",
        description04: "<strong>Арахіс солоний.</strong>",
        description05: "Замовляйте та спробуйте &#171Mogyi - Peanuts Roasted, Salted&#187 вже сьогодня і насолоджуйтеся смаком справжньої арахісової насолоди!"
    },
    {
        type: "wholesale оптом",
        mainCategory: "foodstuffs",
        subcategory: "snacks",
        url: "./images/shop/food/snacks/peanuts/mogyi_peanuts_roasted_salted_150.jpg",
        alt: "mogyi_peanuts_roasted_salted_150",
        url1: "./images/shop/food/snacks/peanuts/mogyi_peanuts_roasted_salted_150.jpg",
        alt1: "mogyi_peanuts_roasted_salted_150",
        marker: "FDPS470",
        brand: "Mogyi",
        search: "модь сіль соль соленый арахис",
        nameUKR: "Солоний арахіс",
        nameEN: "Peanuts Roasted, Salted",
        companyName: "MOGYI LTD. HU.",
        countryName: "Угорщина",
        weightName: "Вага",
        weight: "300 гр.",
        priceGRN: 72,
        priceGRNOpt: 66,
        description01: "&#171Mogyi - Peanuts Roasted, Salted&#187 - це закуска, яка підкорить Вас з першого разу. Кожен арахіс обсмажується з особливою увагою, щоб досягти ідеальної хрусткої текстури та солоного смаку. Цей арахіс поєднує у собі неперевершений солодкий смак з гармонійною солоністю, створюючи справжню насолоду.",
        description02: "Ця закуска ідеально підходить для перекусу у будь-який час дня. Вона стане відмінним супутником під час вечірки, спортивних змагань або просто для задоволення вашого апетиту.",
        description03: "&#171Mogyi - Peanuts Roasted, Salted&#187 - найкраща якість та неперевершений смак арахісу. Ця закуска додасть смаку вашим дням і зробить кожен момент особливим.",
        description04: "<strong>Арахіс солоний.</strong>",
        description05: "Замовляйте та спробуйте &#171Mogyi - Peanuts Roasted, Salted&#187 вже сьогодня і насолоджуйтеся смаком справжньої арахісової насолоди!"
    },
    {
        type: "wholesale оптом",
        mainCategory: "foodstuffs",
        subcategory: "snacks",
        url: "./images/shop/food/snacks/peanuts/soltino_roasted_salted_peanuts_100.jpg",
        alt: "soltino_roasted_salted_peanuts_100",
        url1: "./images/shop/food/snacks/peanuts/soltino_roasted_salted_peanuts_100.jpg",
        alt1: "soltino_roasted_salted_peanuts_100",
        marker: "FDPS800",
        brand: "Soltino",
        search: "кауфланд солтино солтіно сіль соль соленый арахис",
        nameUKR: "Солоний арахіс",
        nameEN: "Roasted Salted Peanuts",
        companyName: "Kaufland",
        countryName: "Чехія",
        weightName: "Вага",
        weight: "100 гр.",
        priceGRN: 28,
        priceGRNOpt: 25,
        description01: "&#171Soltino - Roasted Salted Peanuts&#187 - це вишукане джерело задоволення для справжніх гурманів. Кожний горішок обпалений до досконалості та приправлений натуральною сіллю, що надає йому виразного смаку та аромату. Цей арахіс - ідеальний вибір для ваших вечірок.",
        description02: "Він не лише вражає смаком, але і має велику користь для здоров'я: багатий білком, важливими мінералами та вітамінами.",
        description03: "&#171Soltino - Roasted Salted Peanuts&#187 виготовляється із найкращих якісних інгредієнтів, що гарантують безпеку та якість кожного горішка.",
        description04: "<strong>Арахіс солоний.</strong>",
        description05: "Додайте у свій кошик та не пропустіть можливість насолодитися бездоганним смаком солоного арахісу &#171Soltino - Roasted Salted Peanuts&#187!"
    },
    {
        type: "wholesale оптом",
        mainCategory: "foodstuffs",
        subcategory: "snacks",
        url: "./images/shop/food/snacks/peanuts/soltino_roasted_salted_peanuts_500.jpg",
        alt: "soltino_roasted_salted_peanuts_500",
        url1: "./images/shop/food/snacks/peanuts/soltino_roasted_salted_peanuts_500.jpg",
        alt1: "soltino_roasted_salted_peanuts_500",
        marker: "FDPS810",
        brand: "Soltino",
        search: "кауфланд солтино солтіно сіль соль соленый арахис",
        nameUKR: "Солоний арахіс",
        nameEN: "Roasted Salted Peanuts",
        companyName: "Kaufland",
        countryName: "Чехія",
        weightName: "Вага",
        weight: "500 гр.",
        priceGRN: 107,
        priceGRNOpt: 98,
        description01: "&#171Soltino - Roasted Salted Peanuts&#187 - це вишукане джерело задоволення для справжніх гурманів. Кожний горішок обпалений до досконалості та приправлений натуральною сіллю, що надає йому виразного смаку та аромату. Цей арахіс - ідеальний вибір для ваших вечірок.",
        description02: "Він не лише вражає смаком, але і має велику користь для здоров'я: багатий білком, важливими мінералами та вітамінами.",
        description03: "&#171Soltino - Roasted Salted Peanuts&#187 виготовляється із найкращих якісних інгредієнтів, що гарантують безпеку та якість кожного горішка.",
        description04: "<strong>Арахіс солоний.</strong>",
        description05: "Додайте у свій кошик та не пропустіть можливість насолодитися бездоганним смаком солоного арахісу &#171Soltino - Roasted Salted Peanuts&#187!"
    },
]