export const shopLotsTuna = [
    // {
    //     type: "only-wholesale оптом",
    //     mainCategory: "foodstuffs",
    //     subcategory: "conservation",    
    //     url: "./images/shop/food/canned_food/tuna/albo_atun_clato_oliva_195.jpg",
    //     alt: "albo_atun_clato_oliva_195",
    //     url1: "./images/shop/food/canned_food/tuna/albo_atun_clato_oliva_195-01.jpg",
    //     alt1: "albo_atun_clato_oliva_195-01",
    //     url2: "./images/shop/food/canned_food/tuna/albo_atun_clato_oliva_195-02.jpg",
    //     alt2: "albo_atun_clato_oliva_195-02",
    //     marker: "FDTA010",
    //     brand: "Albo",
    //     search: "atun албо тунець тунец в оливковом оливковое масле масло оливкова олія масло рыба риба первого отжима первый отжим",
    //     nameUKR: "Тунець в оливковій олії першого віджимання",
    //     nameEN: "Atún Claro En Aceite De Oliva Virgen Extra Virgen Extra",
    //     companyName: "Hijos de Carlos Albo S.L.U.",
    //     countryName: "Іспанія",
    //     weightName: "Вага",
    //     weight: "195 гр.",
    //     priceGRN: "--",
    //     priceGRNOpt: 146,
    //     description01: "&#171Albo - Atún Claro En Aceite De Oliva Virgen Extra&#187 - це вершина смаку та якості у світі морських продуктів. Кожен шматочок тунця - це справжній шедевр кулінарного мистецтва. Він виробляється з найкращих якісних інгредієнтів і зберігається в оливковій олії найвищої якості.",
    //     description02: "Олія, в якій тунець знаходиться, додає страві неперевершений аромат та м'якість. Кожен шматочок тунця має неймовірно ніжну текстуру та багатий смак. Це ідеальний варіант для приготування салатів, суші або просто як джерело натурального білка.",
    //     description03: "Спробуйте &#171Albo - Atún Claro En Aceite De Oliva Virgen Extra&#187 і відкрийте для себе справжній смак тунця. Цей продукт - це не просто страва, це смаковий досвід, який надихне вас на кулінарні експерименти та задовольнить найвибагливіших гурманів.",
    //     description04: "<strong>Тунець у оливковій олії першого віжимання. Без консервантів. 3 х 65 гр.</strong>",
    //     description05: "Не гайте часу даремно! Замовте &#171Albo - Atún Claro En Aceite De Oliva Virgen Extra&#187 вже сьогодні і пориньте у світ смаку та задоволення, яким можна насолоджуватися щодня!"
    // },
    // {
    //     type: "only-wholesale оптом",
    //     mainCategory: "foodstuffs",
    //     subcategory: "conservation",    
    //     url: "./images/shop/food/canned_food/tuna/helcom_tunczyk_z_olejem_roslynnym_170.jpg",
    //     alt: "helcom_tunczyk_z_olejem_roslynnym_170",
    //     url1: "./images/shop/food/canned_food/tuna/helcom_tunczyk_z_olejem_roslynnym_170.jpg",
    //     alt1: "helcom_tunczyk_z_olejem_roslynnym_170",
    //     marker: "FDTA400",
    //     brand: "Helcom",
    //     search: "хелком тунець тунец в масле масло рослинна растительное растительном олія масло рыба риба",
    //     nameUKR: "Тунець у рослинній олії",
    //     nameEN: "Tuńczyk Z Olejem Roślynnym",
    //     companyName: "Greek Trade Sp.",
    //     countryName: "Польща",
    //     weightName: "Вага",
    //     weight: "170 гр.",
    //     priceGRN: "--",
    //     priceGRNOpt: 70,
    //     description01: "&#171Helcom - Tuńczyk Z Olejem Roślynnym&#187 - це чудовий вибір для тих, хто прагне поєднати смак і користь для здоров'я. Цей продукт припаде до смаку всім шанувальникам тунця, оскільки він поєднує найкращі якості морського подарунка з натуральністю рослинної олії.",
    //     description02: "Кожна консерва містить ніжний кусочок тунця, який зберігає свою природність та аромат завдяки використанню високоякісної рослинної олії. Це гармонійне поєднання дозволяє Вам отримувати задоволення від смаку тунця, зберігаючи всі його корисні властивості.",
    //     description03: "&#171Helcom - Tuńczyk Z Olejem Roślynnym&#187 - це не тільки джерело відмінного смаку, але і важливий додаток до збалансованого харчування. Завдяки багатому вмісту білка та Омега-3 жирних кислот, він підтримує ваше здоров'я та додає енергії на кожен день.",
    //     description04: "<strong>Тунець у рослинній олії, шматочками. Без консервантів.</strong>",
    //     description05: "Оберіть якість і користь для вашого організму та придбайте &#171Helcom - Tuńczyk Z Olejem Roślynnym&#187, насолоджуйтесь смаком та вигідними властивостями цього вишуканого продукту!"
    // },
    // {
    //     type: "only-wholesale оптом",
    //     mainCategory: "foodstuffs",
    //     subcategory: "conservation",
    //     url: "./images/shop/food/canned_food/tuna/mk_tunczyk_olej_roslin_170.jpg",
    //     alt: "mk_tunczyk_olej_roslin_170",
    //     url1: "./images/shop/food/canned_food/tuna/mk_tunczyk_olej_roslin_170-01.jpg",
    //     alt1: "mk_tunczyk_olej_roslin_170-01",
    //     url2: "./images/shop/food/canned_food/tuna/mk_tunczyk_olej_roslin_170-02.jpg",
    //     alt2: "mk_tunczyk_olej_roslin_170-02",
    //     marker: "FDTA450",
    //     brand: "M & K",
    //     search: "tunczyk kawalki w oleju roslynnym тунець тунец кусочками кусочки шматочки в масле масло рослинна растительное растительном олія масло рыба риба",
    //     nameUKR: "Тунець шматочками у рослинній олії",
    //     nameEN: "Tuńczyk Kawałki W Oleju Roślynnym",
    //     companyName: "Kasprzyk SP. K.",
    //     countryName: "Польща",
    //     weightName: "Вага",
    //     weight: "170 гр.",
    //     priceGRN: "--",
    //     priceGRNOpt: 86,
    //     description01: "Кожен шматочок тунця &#171M & K - Tuńczyk Kawałki W Oleju Roślynnym&#187 насичений свіжістю морського бризу, а рослинна олія робить цей продукт легким і дієтичним, даруючи Вам справжній океанський смак.",
    //     description02: "Виготовлений з високоякісного тунця, багатого вітамінами та Омега-3 кислотами. Цей продукт не тільки додасть есклюзивності вашим стравам, але й забезпечить ваше тіло корисними речовинами, необхідними для здоров'я.",
    //     description03: "&#171M & K - Tuńczyk Kawałki W Oleju Roślynnym&#187 виготовляється за унікальним рецептом, що гарантує насичений смак і дотримання найвищих стандартів якості. Кожен шматочок тунця - це поєднання смаку та здоров'я в одному блюді.",
    //     description04: "<strong>Тунець у рослинній олії, шматочками. Без консервантів.</strong>",
    //     description05: "Створіть вишукані страви легко та швидко, дозволяючи собі насолоджуватися неперевершеним смаком тунця &#171M & K - Tuńczyk Kawałki W Oleju Roślynnym&#187!"
    // },
    // {
    //     type: "only-wholesale оптом",
    //     mainCategory: "foodstuffs",
    //     subcategory: "conservation",
    //     url: "./images/shop/food/canned_food/tuna/mk_tunczyk_kawalki_wodzie_170.jpg",
    //     alt: "mk_tunczyk_kawalki_wodzie_170",
    //     url1: "./images/shop/food/canned_food/tuna/mk_tunczyk_kawalki_wodzie_170-01.jpg",
    //     alt1: "mk_tunczyk_kawalki_wodzie_170-01",
    //     url2: "./images/shop/food/canned_food/tuna/mk_tunczyk_kawalki_wodzie_170-02.jpg",
    //     alt2: "mk_tunczyk_kawalki_wodzie_170-02",
    //     marker: "FDTA455",
    //     brand: "M & K",
    //     search: "tunczyk kawalki w wodzie тунець тунец кусочками кусочки шматочки в собственном соку воде вода рыба риба",
    //     nameUKR: "Тунець шматочками у власному соку",
    //     nameEN: "Tuńczyk Kawałki W Wodzie",
    //     companyName: "Kasprzyk SP. K.",
    //     countryName: "Польща",
    //     weightName: "Вага",
    //     weight: "170 гр.",
    //     priceGRN: "--",
    //     priceGRNOpt: 86,
    //     description01: "Відкрийте для себе свіжий і соковитий тунець у власному соку &#171M & K - Tuńczyk Kawałki W Wodzie&#187.",
    //     description02: "Цей тунець відрізняється ніжним смаком і високою якістю, що робить його ідеальним доповненням до будь-якої страви.",
    //     description03: "Завдяки низькому вмісту жиру та високому вмісту білка, &#171M & K - Tuńczyk Kawałki W Wodzie&#187 стане незамінним для Вашого здорового раціону.",
    //     description04: "<strong>Тунець у власному соку, шматочками. Без консервантів.</strong>",
    //     description05: "Замовляйте &#171M & K - Tuńczyk Kawałki W Wodzie&#187 зараз і насолоджуйтеся його чудовим смаком!"
    // },
    // {
    //     type: "only-wholesale оптом",
    //     mainCategory: "foodstuffs",
    //     subcategory: "conservation",
    //     url: "./images/shop/food/canned_food/tuna/mk_tunczyk_rozdrobniony_170.jpg",
    //     alt: "mk_tunczyk_rozdrobniony_170",
    //     url1: "./images/shop/food/canned_food/tuna/mk_tunczyk_rozdrobniony_170-01.jpg",
    //     alt1: "mk_tunczyk_rozdrobniony_170-01",
    //     url2: "./images/shop/food/canned_food/tuna/mk_tunczyk_rozdrobniony_170-02.jpg",
    //     alt2: "mk_tunczyk_rozdrobniony_170-02",
    //     marker: "FDTA460",
    //     brand: "M & K",
    //     search: "tunczyk rozdrobniony тунець тунец дробленый в собственном соку рыба риба",
    //     nameUKR: "Тунець подрібнений у власному соку",
    //     nameEN: "Tuńczyk Rozdrobniony",
    //     companyName: "Kasprzyk SP. K.",
    //     countryName: "Польща",
    //     weightName: "Вага",
    //     weight: "170 гр.",
    //     priceGRN: "--",
    //     priceGRNOpt: 86,
    //     description01: "Відкрийте для себе надзвичайно смачний подрібнений тунець у власному соку &#171M & K - Tuńczyk Rozdrobniony&#187.",
    //     description02: "Цей продукт забезпечить Вам свіжий і насичений смак, який підходить для приготування різноманітних страв.",
    //     description03: "Завдяки високому вмісту білка та низькому вмісту жиру, &#171M & K - Tuńczyk Rozdrobniony&#187 ідеальний для здорового харчування та підтримки активного способу життя.",
    //     description04: "<strong>Тунець у власному соку, подрібнений. Без консервантів.</strong>",
    //     description05: "Не пропустіть можливість насолодитися чудовим смаком та користю для здоров'я - замовляйте &#171M & K - Tuńczyk Rozdrobniony&#187 вже сьогодні!"
    // },
    // {
    //     type: "wholesale оптом",
    //     mainCategory: "foodstuffs",
    //     subcategory: "conservation",
    //     url: "./images/shop/food/canned_food/tuna/rio_mare_tonno_al_naturale_80.jpg",
    //     alt: "rio_mare_tonno_al_naturale_80",
    //     url1: "./images/shop/food/canned_food/tuna/rio_mare_tonno_al_naturale_80-01.jpg",
    //     alt1: "rio_mare_tonno_al_naturale_80-01",
    //     marker: "FDTA600",
    //     brand: "Rio Mare",
    //     search: "рио ріо маре тунець тунец в собственном соку рыба риба",
    //     nameUKR: "Тунець у власному соку",
    //     nameEN: "Tonno Al Naturale",
    //     companyName: "Bolton Food S.P.A.",
    //     countryName: "Італія",
    //     weightName: "Вага",
    //     weight: "80 гр.",
    //     priceGRN: 79,
    //     priceGRNOpt: 72,
    //     description01: "&#171Rio Mare - Tonno Al Naturale&#187 - це найкращий вибір для тих, хто цінує природність і якість. Цей тунець у власному соку - це справжня смакова насолода. Він відзначається своєю ніжністю і неперевершеним смаком, який зберігається завдяки відсутності доданих спецій та соусів.",
    //     description02: "Кожен шматочок тунця ретельно обробляється і консервується, зберігаючи всю свою користь та аромат. Ви можете впевнено включити цей продукт до вашого раціону, оскільки він багатий білком та Омега-3 жирними кислотами, корисними для здоров'я серця та мозку.",
    //     description03: "&#171Rio Mare - Tonno Al Naturale&#187 - це смак і якість, які говорять самі за себе. Оберіть натуральність і смак природи.",
    //     description04: "<strong>Тунець у власному соку. Без консервантів.</strong>",
    //     description05: "Придбайте &#171Rio Mare - Tonno Al Naturale&#187 вже сьогодні і насолоджуйтесь найкращим, що може запропонувати природа!"
    // },
    {
        type: "only-wholesale оптом",
        mainCategory: "foodstuffs",
        subcategory: "conservation",
        url: "./images/shop/food/canned_food/tuna/rio_mare_tonno_al_naturale_240.jpg",
        alt: "rio_mare_tonno_al_naturale_240",
        url1: "./images/shop/food/canned_food/tuna/rio_mare_tonno_al_naturale_240-01.jpg",
        alt1: "rio_mare_tonno_al_naturale_240-01",
        marker: "FDTA605",
        brand: "Rio Mare",
        search: "рио ріо маре тунець тунец в собственном соку рыба риба",
        nameUKR: "Тунець у власному соку",
        nameEN: "Tonno Al Naturale",
        companyName: "Bolton Food S.P.A.",
        countryName: "Італія",
        weightName: "Вага",
        weight: "240 гр.",
        priceGRN: "--",
        priceGRNOpt: 210,
        description01: "&#171Rio Mare - Tonno Al Naturale&#187 - це найкращий вибір для тих, хто цінує природність і якість. Цей тунець у власному соку - це справжня смакова насолода. Він відзначається своєю ніжністю і неперевершеним смаком, який зберігається завдяки відсутності доданих спецій та соусів.",
        description02: "Кожен шматочок тунця ретельно обробляється і консервується, зберігаючи всю свою користь та аромат. Ви можете впевнено включити цей продукт до вашого раціону, оскільки він багатий білком та Омега-3 жирними кислотами, корисними для здоров'я серця та мозку.",
        description03: "&#171Rio Mare - Tonno Al Naturale&#187 - це смак і якість, які говорять самі за себе. Оберіть натуральність і смак природи.",
        description04: "<strong>Тунець у власному соку. Без консервантів. 3 шт. в упаковці.</strong>",
        description05: "Придбайте &#171Rio Mare - Tonno Al Naturale&#187 вже сьогодні і насолоджуйтесь найкращим, що може запропонувати природа!"
    },
    {
        type: "only-wholesale оптом",
        mainCategory: "foodstuffs",
        subcategory: "conservation",    
        url: "./images/shop/food/canned_food/tuna/rio_mare_tonno_al_naturale_320.jpg",
        alt: "rio_mare_tonno_al_naturale_320",
        url1: "./images/shop/food/canned_food/tuna/rio_mare_tonno_al_naturale_320.jpg",
        alt1: "rio_mare_tonno_al_naturale_320",
        marker: "FDTA610",
        brand: "Rio Mare",
        search: "рио ріо маре тунець тунец в собственном соку рыба риба",
        nameUKR: "Тунець у власному соку",
        nameEN: "Tonno Al Naturale",
        companyName: "Bolton Food S.P.A.",
        countryName: "Італія",
        weightName: "Вага",
        weight: "320 гр.",
        priceGRN: "--",
        priceGRNOpt: 290,
        description01: "&#171Rio Mare - Tonno Al Naturale&#187 - це найкращий вибір для тих, хто цінує природність і якість. Цей тунець у власному соку - це справжня смакова насолода. Він відзначається своєю ніжністю і неперевершеним смаком, який зберігається завдяки відсутності доданих спецій та соусів.",
        description02: "Кожен шматочок тунця ретельно обробляється і консервується, зберігаючи всю свою користь та аромат. Ви можете впевнено включити цей продукт до вашого раціону, оскільки він багатий білком та Омега-3 жирними кислотами, корисними для здоров'я серця та мозку.",
        description03: "&#171Rio Mare - Tonno Al Naturale&#187 - це смак і якість, які говорять самі за себе. Оберіть натуральність і смак природи.",
        description04: "<strong>Тунець у власному соку. Без консервантів. 4 шт. в упаковці.</strong>",
        description05: "Придбайте &#171Rio Mare - Tonno Al Naturale&#187 вже сьогодні і насолоджуйтесь найкращим, що може запропонувати природа!"
    },
    {
        type: "only-wholesale оптом",
        mainCategory: "foodstuffs",
        subcategory: "conservation",    
        url: "./images/shop/food/canned_food/tuna/rio_mare_tonno_al_naturale_480.jpg",
        alt: "rio_mare_tonno_al_naturale_480",
        url1: "./images/shop/food/canned_food/tuna/rio_mare_tonno_al_naturale_480.jpg",
        alt1: "rio_mare_tonno_al_naturale_480",
        marker: "FDTA615",
        brand: "Rio Mare",
        search: "рио ріо маре тунець тунец в собственном соку рыба риба",
        nameUKR: "Тунець у власному соку",
        nameEN: "Tonno Al Naturale",
        companyName: "Bolton Food S.P.A.",
        countryName: "Італія",
        weightName: "Вага",
        weight: "480 гр.",
        priceGRN: "--",
        priceGRNOpt: 410,
        description01: "&#171Rio Mare - Tonno Al Naturale&#187 - це найкращий вибір для тих, хто цінує природність і якість. Цей тунець у власному соку - це справжня смакова насолода. Він відзначається своєю ніжністю і неперевершеним смаком, який зберігається завдяки відсутності доданих спецій та соусів.",
        description02: "Кожен шматочок тунця ретельно обробляється і консервується, зберігаючи всю свою користь та аромат. Ви можете впевнено включити цей продукт до вашого раціону, оскільки він багатий білком та Омега-3 жирними кислотами, корисними для здоров'я серця та мозку.",
        description03: "&#171Rio Mare - Tonno Al Naturale&#187 - це смак і якість, які говорять самі за себе. Оберіть натуральність і смак природи.",
        description04: "<strong>Тунець у власному соку. Без консервантів. 6 шт. в упаковці.</strong>",
        description05: "Придбайте &#171Rio Mare - Tonno Al Naturale&#187 вже сьогодні і насолоджуйтесь найкращим, що може запропонувати природа!"
    },
    // {
    //     type: "wholesale оптом",
    //     mainCategory: "foodstuffs",
    //     subcategory: "conservation",
    //     url: "./images/shop/food/canned_food/tuna/rio_mare_tonno_al'Olio_di_oliva_65.jpg",
    //     alt: "rio_mare_tonno_al'Olio_di_oliva_65",
    //     url1: "./images/shop/food/canned_food/tuna/rio_mare_tonno_al'Olio_di_oliva_65-01.jpg",
    //     alt1: "rio_mare_tonno_al'Olio_di_oliva_65-01",
    //     marker: "FDTA630",
    //     brand: "Rio Mare",
    //     search: "рио ріо маре тунець тунец в оливковом оливковое масле масло оливкова олія масло рыба риба",
    //     nameUKR: "Тунець в оливковій олії",
    //     nameEN: "Tonno al'Olio di Oliva",
    //     companyName: "Bolton Food S.P.A.",
    //     countryName: "Італія",
    //     weightName: "Вага",
    //     weight: "65 гр.",
    //     priceGRN: 79,
    //     priceGRNOpt: 72,
    //     description01: "&#171Rio Mare - Tonno al'Olio di Oliva&#187 - це справжня вишуканість для справжніх гурманів. Цей продукт вражає своєю неперевершеною якістю та натуральністю. Кожен шматочок ніжної тунцевої страви знаходиться в оливковій олії, яка підкреслює його неповторний смак.",
    //     description02: "Коли Ви розкриваєте тунця, то отримуєте можливість насолоджуватися найкращими смаковими відчуттями без зайвих зусиль. Тунець ретельно відібраний та приготований так, щоб кожен шматочок був надзвичайно ніжним і соковитим.",
    //     description03: "&#171Rio Mare - Tonno al'Olio di Oliva&#187 стане чудовим доповненням до вашого столу із здоровою їжею. Вона має високий вміст білка та Омега-3 жирних кислот, що корисно для вашого організму.",
    //     description04: "<strong>Тунець у оливковій олії. Без консервантів.</strong>",
    //     description05: "Придбайте &#171Rio Mare - Tonno al'Olio di Oliva&#187 вже сьогодні та дозвольте собі насолодитися неперевершеним смаком та користью для здоров'я!"
    // },
    {
        type: "wholesale оптом",
        mainCategory: "foodstuffs",
        subcategory: "conservation",
        url: "./images/shop/food/canned_food/tuna/rio_mare_tonno_al'Olio_di_oliva_3.jpg",
        alt: "rio_mare_tonno_al'Olio_di_oliva_3",
        url1: "./images/shop/food/canned_food/tuna/rio_mare_tonno_al'Olio_di_oliva_3-01.jpg",
        alt1: "rio_mare_tonno_al'Olio_di_oliva_3-01",
        url2: "./images/shop/food/canned_food/tuna/rio_mare_tonno_al'Olio_di_oliva_3-02.jpg",
        alt2: "rio_mare_tonno_al'Olio_di_oliva_3-02",
        url3: "./images/shop/food/canned_food/tuna/rio_mare_tonno_al'Olio_di_oliva_3-03.jpg",
        alt3: "rio_mare_tonno_al'Olio_di_oliva_3-03",
        marker: "FDTA634",
        brand: "Rio Mare",
        search: "рио ріо маре тунець тунец в оливковом оливковое масле масло оливкова олія масло рыба риба",
        nameUKR: "Тунець в оливковій олії (3 шт.)",
        nameEN: "Tonno al'Olio di Oliva",
        companyName: "Bolton Food S.P.A.",
        countryName: "Італія",
        weightName: "Вага",
        weight: "195 гр.",
        priceGRN: 219,
        priceGRNOpt: 198,
        description01: "&#171Rio Mare - Tonno al'Olio di Oliva&#187 - це справжня вишуканість для справжніх гурманів. Цей продукт вражає своєю неперевершеною якістю та натуральністю. Кожен шматочок ніжної тунцевої страви знаходиться в оливковій олії, яка підкреслює його неповторний смак.",
        description02: "Коли Ви розкриваєте тунця, то отримуєте можливість насолоджуватися найкращими смаковими відчуттями без зайвих зусиль. Тунець ретельно відібраний та приготований так, щоб кожен шматочок був надзвичайно ніжним і соковитим.",
        description03: "&#171Rio Mare - Tonno al'Olio di Oliva&#187 стане чудовим доповненням до вашого столу із здоровою їжею. Вона має високий вміст білка та Омега-3 жирних кислот, що корисно для вашого організму.",
        description04: "<strong>Тунець у оливковій олії. Без консервантів. 3 шт. в упаковці.</strong>",
        description05: "Придбайте &#171Rio Mare - Tonno al'Olio di Oliva&#187 вже сьогодні та дозвольте собі насолодитися неперевершеним смаком та користью для здоров'я!"
    },
    // {
    //     type: "wholesale оптом",
    //     mainCategory: "foodstuffs",
    //     subcategory: "conservation",
    //     url: "./images/shop/food/canned_food/tuna/rio_mare_tonno_al'Olio_di_oliva_4.jpg",
    //     alt: "rio_mare_tonno_al'Olio_di_oliva_4",
    //     url1: "./images/shop/food/canned_food/tuna/rio_mare_tonno_al'Olio_di_oliva_4-01.jpg",
    //     alt1: "rio_mare_tonno_al'Olio_di_oliva_4-01",
    //     url2: "./images/shop/food/canned_food/tuna/rio_mare_tonno_al'Olio_di_oliva_4-02.jpg",
    //     alt2: "rio_mare_tonno_al'Olio_di_oliva_4-02",
    //     url3: "./images/shop/food/canned_food/tuna/rio_mare_tonno_al'Olio_di_oliva_4-03.jpg",
    //     alt3: "rio_mare_tonno_al'Olio_di_oliva_4-03",
    //     marker: "FDTA636",
    //     brand: "Rio Mare",
    //     search: "рио ріо маре тунець тунец в оливковом оливковое масле масло оливкова олія масло рыба риба",
    //     nameUKR: "Тунець в оливковій олії (4 шт.)",
    //     nameEN: "Tonno al'Olio di Oliva",
    //     companyName: "Bolton Food S.P.A.",
    //     countryName: "Італія",
    //     weightName: "Вага",
    //     weight: "260 гр.",
    //     priceGRN: 352,
    //     priceGRNOpt: 300,
    //     description01: "&#171Rio Mare - Tonno al'Olio di Oliva&#187 - це справжня вишуканість для справжніх гурманів. Цей продукт вражає своєю неперевершеною якістю та натуральністю. Кожен шматочок ніжної тунцевої страви знаходиться в оливковій олії, яка підкреслює його неповторний смак.",
    //     description02: "Коли Ви розкриваєте тунця, то отримуєте можливість насолоджуватися найкращими смаковими відчуттями без зайвих зусиль. Тунець ретельно відібраний та приготований так, щоб кожен шматочок був надзвичайно ніжним і соковитим.",
    //     description03: "&#171Rio Mare - Tonno al'Olio di Oliva&#187 стане чудовим доповненням до вашого столу із здоровою їжею. Вона має високий вміст білка та Омега-3 жирних кислот, що корисно для вашого організму.",
    //     description04: "<strong>Тунець у оливковій олії. Без консервантів. 4 шт. в упаковці.</strong>",
    //     description05: "Придбайте &#171Rio Mare - Tonno al'Olio di Oliva&#187 вже сьогодні та дозвольте собі насолодитися неперевершеним смаком та користью для здоров'я!"
    // },
    // {
    //     type: "retail",
    //     mainCategory: "foodstuffs",
    //     subcategory: "conservation",
    //     url: "./images/shop/food/canned_food/tuna/rio_mare_tonno_al'Olio_di_oliva_390.jpg",
    //     alt: "rio_mare_tonno_al'Olio_di_oliva_390",
    //     url1: "./images/shop/food/canned_food/tuna/rio_mare_tonno_al'Olio_di_oliva_390-01.jpg",
    //     alt1: "rio_mare_tonno_al'Olio_di_oliva_390-01",
    //     url2: "./images/shop/food/canned_food/tuna/rio_mare_tonno_al'Olio_di_oliva_390-02.jpg",
    //     alt2: "rio_mare_tonno_al'Olio_di_oliva_390-02",
    //     marker: "FDTA645",
    //     brand: "Rio Mare",
    //     search: "рио ріо маре тунець тунец в оливковом оливковое масле масло оливкова олія масло рыба риба",
    //     nameUKR: "Тунець в оливковій олії",
    //     nameEN: "Tonno al'Olio di Oliva",
    //     companyName: "Bolton Food S.P.A.",
    //     countryName: "Італія",
    //     weightName: "Вага",
    //     weight: "390 гр.",
    //     priceGRN: 420,
    //     quantityOnStorage: 1,
    //     description01: "&#171Rio Mare - Tonno al'Olio di Oliva&#187 - це справжня вишуканість для справжніх гурманів. Цей продукт вражає своєю неперевершеною якістю та натуральністю. Кожен шматочок ніжної тунцевої страви знаходиться в оливковій олії, яка підкреслює його неповторний смак.",
    //     description02: "Коли Ви розкриваєте тунця, то отримуєте можливість насолоджуватися найкращими смаковими відчуттями без зайвих зусиль. Тунець ретельно відібраний та приготований так, щоб кожен шматочок був надзвичайно ніжним і соковитим.",
    //     description03: "&#171Rio Mare - Tonno al'Olio di Oliva&#187 стане чудовим доповненням до вашого столу із здоровою їжею. Вона має високий вміст білка та Омега-3 жирних кислот, що корисно для вашого організму.",
    //     description04: "<strong>Тунець у оливковій олії. Без консервантів. 6 шт. в упаковці.</strong>",
    //     description05: "Придбайте &#171Rio Mare - Tonno al'Olio di Oliva&#187 вже сьогодні та дозвольте собі насолодитися неперевершеним смаком та користью для здоров'я!"
    // },
    {
        type: "retail",
        mainCategory: "foodstuffs",
        subcategory: "conservation",
        url: "./images/shop/food/canned_food/tuna/rio_mare_tonno_al'Olio_di_oliva_12.jpg",
        alt: "rio_mare_tonno_al'Olio_di_oliva_12",
        url1: "./images/shop/food/canned_food/tuna/rio_mare_tonno_al'Olio_di_oliva_12-01.jpg",
        alt1: "rio_mare_tonno_al'Olio_di_oliva_12-01",
        url2: "./images/shop/food/canned_food/tuna/rio_mare_tonno_al'Olio_di_oliva_12-02.jpg",
        alt2: "rio_mare_tonno_al'Olio_di_oliva_12-02",
        marker: "FDTA655",
        brand: "Rio Mare",
        search: "рио ріо маре тунець тунец в оливковом оливковое масле масло оливкова олія масло рыба риба",
        nameUKR: "Тунець в оливковій олії (12 шт.)",
        nameEN: "Tonno al'Olio di Oliva",
        companyName: "Bolton Food S.P.A.",
        countryName: "Італія",
        weightName: "Вага",
        weight: "780 гр.",
        priceGRN: 891,
        quantityOnStorage: 1,
        description01: "&#171Rio Mare - Tonno al'Olio di Oliva&#187 - це справжня вишуканість для справжніх гурманів. Цей продукт вражає своєю неперевершеною якістю та натуральністю. Кожен шматочок ніжної тунцевої страви знаходиться в оливковій олії, яка підкреслює його неповторний смак.",
        description02: "Коли Ви розкриваєте тунця, то отримуєте можливість насолоджуватися найкращими смаковими відчуттями без зайвих зусиль. Тунець ретельно відібраний та приготований так, щоб кожен шматочок був надзвичайно ніжним і соковитим.",
        description03: "&#171Rio Mare - Tonno al'Olio di Oliva&#187 стане чудовим доповненням до вашого столу із здоровою їжею. Вона має високий вміст білка та Омега-3 жирних кислот, що корисно для вашого організму.",
        description04: "<strong>Тунець у оливковій олії. Без консервантів. 12 шт. в упаковці.</strong>",
        description05: "Придбайте &#171Rio Mare - Tonno al'Olio di Oliva&#187 вже сьогодні та дозвольте собі насолодитися неперевершеним смаком та користью для здоров'я!"
    },
]