export const shopLotsBars = [
    {
        type: "retail",
        url: "./images/shop/food/sweets/bars/ferrero_nutella_b_ready_22.jpg",
        alt: "ferrero_nutella_b_ready_22",
        url1: "./images/shop/food/sweets/bars/ferrero_nutella_b_ready_22.jpg",
        alt1: "ferrero_nutella_b_ready_22",
        marker: "FDBS300",
        brand: "Ferrero",
        search: "фереро ферреро нутелла нутела шоколад горіх орех ореховая крем паста батончики",
        nameUKR: "Батончик",
        nameEN: "Nutella B-ready",
        companyName: "Ferrero SpA",
        countryName: "Угорщина",
        weightName: "Вага",
        weight: "22 гр.",
        priceGRN: 24,
        quantityOnStorage: 9,
        description01: "&#171Ferrero - Nutella B-ready&#187 - це справжній шедевр для шоколадних гурманів. Цей шоколадний батончик поєднує у собі найкращі якості &#171Nutella&#187 - ніжний крем з горіховим смаком, обгорнутий хрустким печивом.",
        description02: "Цей батончик справжній момент насолоди, який можна відчути у будь-який час. Ідеально підходить для перекусу вдома або у дорозі. Зручна упаковка робить його ідеальним супутником у вашому щоденному житті.",
        description03: "З &#171Ferrero - Nutella B-ready&#187 Ви завжди будете мати солодкий резерв для бадьорого настрою. Вирушайте у свою солодку подорож і робіть її ще яскравішою разом з цим чудовим батончиком.",
        description04: "<strong>Шоколадно-горіховий батончик. Без консервантів.</strong>",
        description05: "Спробуйте &#171Ferrero - Nutella B-ready&#187 вже сьогодні і занурьтесь у світ найсолодших моментів вашого життя!"
    },    
    {
        type: "retail",
        url: "./images/shop/food/sweets/bars/ferrero_nutella_b_ready_44.jpg",
        alt: "ferrero_nutella_b_ready_44",
        url1: "./images/shop/food/sweets/bars/ferrero_nutella_b_ready_44.jpg",
        alt1: "ferrero_nutella_b_ready_44",
        marker: "FDBS305",
        brand: "Ferrero",
        search: "фереро ферреро нутелла нутела шоколад горіх орех ореховая крем паста батончики",
        nameUKR: "Батончик",
        nameEN: "Nutella B-ready",
        companyName: "Ferrero SpA",
        countryName: "Угорщина",
        weightName: "Вага",
        weight: "44 гр.",
        priceGRN: 45,
        quantityOnStorage: 16,
        description01: "&#171Ferrero - Nutella B-ready&#187 - це справжній шедевр для шоколадних гурманів. Цей шоколадний батончик поєднує у собі найкращі якості &#171Nutella&#187 - ніжний крем з горіховим смаком, обгорнутий хрустким печивом.",
        description02: "Цей батончик справжній момент насолоди, який можна відчути у будь-який час. Ідеально підходить для перекусу вдома або у дорозі. Зручна упаковка робить його ідеальним супутником у вашому щоденному житті.",
        description03: "З &#171Ferrero - Nutella B-ready&#187 Ви завжди будете мати солодкий резерв для бадьорого настрою. Вирушайте у свою солодку подорож і робіть її ще яскравішою разом з цим чудовим батончиком.",
        description04: "<strong>Шоколадно-горіховий батончик. 2 шт. Без консервантів.</strong>",
        description05: "Спробуйте &#171Ferrero - Nutella B-ready&#187 вже сьогодні і занурьтесь у світ найсолодших моментів вашого життя!"
    },
    {
        type: "retail",
        url: "./images/shop/food/sweets/bars/ferrero_nutella_b_ready_132.jpg",
        alt: "ferrero_nutella_b_ready_132",
        url1: "./images/shop/food/sweets/bars/ferrero_nutella_b_ready_132-01.jpg",
        alt1: "ferrero_nutella_b_ready_132-01",
        url2: "./images/shop/food/sweets/bars/ferrero_nutella_b_ready_132-02.jpg",
        alt2: "ferrero_nutella_b_ready_132-02",
        url3: "./images/shop/food/sweets/bars/ferrero_nutella_b_ready_132-03.jpg",
        alt3: "ferrero_nutella_b_ready_132-03",
        marker: "FDBS310",
        brand: "Ferrero",
        search: "фереро ферреро нутелла нутела шоколад горіх орех ореховая крем паста батончики",
        nameUKR: "Батончик",
        nameEN: "Nutella B-ready",
        companyName: "Ferrero SpA",
        countryName: "Угорщина",
        weightName: "Вага",
        weight: "132 гр.",
        priceGRN: 117,
        quantityOnStorage: 7,
        description01: "&#171Ferrero - Nutella B-ready&#187 - це справжній шедевр для шоколадних гурманів. Цей шоколадний батончик поєднує у собі найкращі якості &#171Nutella&#187 - ніжний крем з горіховим смаком, обгорнутий хрустким печивом.",
        description02: "Цей батончик справжній момент насолоди, який можна відчути у будь-який час. Ідеально підходить для перекусу вдома або у дорозі. Зручна упаковка робить його ідеальним супутником у вашому щоденному житті.",
        description03: "З &#171Ferrero - Nutella B-ready&#187 Ви завжди будете мати солодкий резерв для бадьорого настрою. Вирушайте у свою солодку подорож і робіть її ще яскравішою разом з цим чудовим батончиком.",
        description04: "<strong>Шоколадно-горіховий батончик. 6 шт. Без консервантів.</strong>",
        description05: "Спробуйте &#171Ferrero - Nutella B-ready&#187 вже сьогодні і занурьтесь у світ найсолодших моментів вашого життя!"
    },
    // {
    //     type: "retail",
    //     url: "./images/shop/food/sweets/bars/ferrero_nutella_b_ready_10.jpg",
    //     alt: "ferrero_nutella_b_ready_10",
    //     url1: "./images/shop/food/sweets/bars/ferrero_nutella_b_ready_10.jpg",
    //     alt1: "ferrero_nutella_b_ready_10",
    //     marker: "FDBS315",
    //     brand: "Ferrero",
    //     search: "фереро ферреро нутелла нутела шоколад горіх орех ореховая крем паста батончики",
    //     nameUKR: "Батончик",
    //     nameEN: "Nutella B-ready",
    //     companyName: "Ferrero SpA",
    //     countryName: "Угорщина",
    //     weightName: "Вага",
    //     weight: "220 гр.",
    //     priceGRN: 147,
    //     quantityOnStorage: 5,
    //     description01: "&#171Ferrero - Nutella B-ready&#187 - це справжній шедевр для шоколадних гурманів. Цей шоколадний батончик поєднує у собі найкращі якості &#171Nutella&#187 - ніжний крем з горіховим смаком, обгорнутий хрустким печивом.",
    //     description02: "Цей батончик справжній момент насолоди, який можна відчути у будь-який час. Ідеально підходить для перекусу вдома або у дорозі. Зручна упаковка робить його ідеальним супутником у вашому щоденному житті.",
    //     description03: "З &#171Ferrero - Nutella B-ready&#187 Ви завжди будете мати солодкий резерв для бадьорого настрою. Вирушайте у свою солодку подорож і робіть її ще яскравішою разом з цим чудовим батончиком.",
    //     description04: "<strong>Шоколадно-горіховий батончик. 10 шт. Без консервантів.</strong>",
    //     description05: "Спробуйте &#171Ferrero - Nutella B-ready&#187 вже сьогодні і занурьтесь у світ найсолодших моментів вашого життя!"
    // },
    {
        type: "wholesale",
        url: "./images/shop/food/sweets/bars/pottyos_turo_rudi_30.jpg",
        alt: "pottyos_turo_rudi_30",
        url1: "./images/shop/food/sweets/bars/pottyos_turo_rudi_30.jpg",
        alt1: "pottyos_turo_rudi_30",
        marker: "FDBS500",
        brand: "Pöttyös",
        search: "потьош туру туро руди руді шоколад батончики сир сыр сырний батончик",
        nameUKR: "Шоколадно-сирний батончик",
        nameEN: "Túró Rudi",
        companyName: "FrieslandCampima Hungária ZRt.",
        countryName: "Угорщина",
        weightName: "Вага",
        weight: "30 гр.",
        priceGRN: 25,
        priceGRNOpt: 22,
        description01: "&#171Pöttyös - Turo Rudi&#187 - це справжня насолода для шанувальників солодощів. Цей шоколадно-сирний батончик поєднує у собі ніжний крем з натурального творожного сиру та шоколадну оболонку.",
        description02: "Він є ідеальним перекусом для всіх, хто любить поєднання солодкого та кислого. Його ніжна текстура та багатий смак створюють незабутні відчуття.",
        description03: "&#171Pöttyös - Turo Rudi&#187 - це справжнє шедевр солодкого мистецтва. Його унікальний смак і неповторна структура роблять його одним з найулюбленіших десертів серед мільйонів людей.",
        description04: "<strong>Батончик шоколадно-сирний.</strong>",
        description05: "Спробуйте &#171Pöttyös - Turo Rudi&#187 та дозвольте собі підкорити цей неперевершений смак!"
    },
    {
        type: "wholesale",
        url: "./images/shop/food/sweets/bars/pottyos_turo_rudi_180.jpg",
        alt: "pottyos_turo_rudi_180",
        url1: "./images/shop/food/sweets/bars/pottyos_turo_rudi_180.jpg",
        alt1: "pottyos_turo_rudi_180",
        marker: "FDBS505",
        brand: "Pöttyös",
        search: "потьош туру туро руди руді шоколад батончики сир сыр сырний батончик",
        nameUKR: "Шоколадно-сирний батончик",
        nameEN: "Túró Rudi",
        companyName: "FrieslandCampima Hungária ZRt.",
        countryName: "Угорщина",
        weightName: "Вага",
        weight: "180 гр.",
        priceGRN: 145,
        priceGRNOpt: 133,
        description01: "&#171Pöttyös - Turo Rudi&#187 - це справжня насолода для шанувальників солодощів. Цей шоколадно-сирний батончик поєднує у собі ніжний крем з натурального творожного сиру та шоколадну оболонку.",
        description02: "Він є ідеальним перекусом для всіх, хто любить поєднання солодкого та кислого. Його ніжна текстура та багатий смак створюють незабутні відчуття.",
        description03: "&#171Pöttyös - Turo Rudi&#187 - це справжнє шедевр солодкого мистецтва. Його унікальний смак і неповторна структура роблять його одним з найулюбленіших десертів серед мільйонів людей.",
        description04: "<strong>Батончик шоколадно-сирний.</strong>",
        description05: "Спробуйте &#171Pöttyös - Turo Rudi&#187 та дозвольте собі підкорити цей неперевершений смак!"
    },
]