export const shopLotsPates = [
    {
        type: "wholesale",
        url: "./images/shop/food/canned_food/pates/fresh_pecenovka_190.jpg",
        alt: "fresh_pecenovka_190",
        url1: "./images/shop/food/canned_food/pates/fresh_pecenovka_190.jpg",
        alt1: "fresh_pecenovka_190",
        marker: "FDPT280",
        brand: "Fresh",
        search: "печінка печень печеночный печёночный с з печінки печенки печёнки",
        nameUKR: "Печінковий паштет",
        nameEN: "Pečeňovka",
        companyName: "HAMÉ SLOVAKIA, spol.",
        countryName: "Словаччина",
        weightName: "Вага",
        weight: "190 гр.",
        priceGRN: 29,
        priceGRNOpt: 24,
        description01: "&#171Fresh - Pečeňovka&#187 - це смачна і корисна закуска, яка ідеально підходить для будь-якого випадку. Він виготовлений з високоякісних інгредієнтів, включаючи свинячу печінку, шпик, цибулю та спеції.",
        description02: "Паштет має ніжну, кремову текстуру і приємний смак з легкими нотками прянощів. Він не містить штучних барвників, консервантів та ароматизаторів.",
        description03: "Печінковий паштет &#171Fresh - Pečeňovka&#187 - це відмінний вибір для тих, хто хоче насолодитися смачним і корисним продуктом. Він ідеально підходить для бутербродів, канапе, овочевих салатів та інших страв.",
        description04: "<strong>Печінковий паштет, свинина. Жестяна банка.</strong>",
        description05: "Спробуйте печінковий паштет &#171Fresh - Pečeňovka&#187 та переконайтеся у його чудовому смаку!"
    },
    {
        type: "wholesale",
        url: "./images/shop/food/canned_food/pates/freshona_pasta_ardei_120.jpg",
        alt: "freshona_pasta_ardei_120",
        url1: "./images/shop/food/canned_food/pates/freshona_pasta_ardei_120.jpg",
        alt1: "freshona_pasta_ardei_120",
        marker: "FDPT300",
        brand: "Freshona",
        search: "паприка перець веган веганство",
        nameUKR: "Пісний паштет з паприкою",
        nameEN: "Pastă Vegetală Tartinabilă Cu Ardei",
        companyName: "Lidl",
        countryName: "Румунія",
        weightName: "Вага",
        weight: "120 гр.",
        priceGRN: 23,
        priceGRNOpt: 19,
        description01: "&#171Freshona - Pastă Vegetală Tartinabilă Cu Ardei&#187 - це смачна і корисна закуска, яка ідеально підходить для тих, хто дотримується вегетаріанства або веганства. Він виготовлений з високоякісних інгредієнтів, включаючи квасолю, сочевицю, моркву, цибулю та перець.",
        description02: "Він ідеально підходить для вживання на хлібі, як діп для снеків або просто в якості начинки для сендвічів.",
        description03: "Складаючись лише з натуральних інгредієнтів, &#171Freshona - Pastă Vegetală Tartinabilă Cu Ardei&#187 не містить консервантів та шкідливих добавок, що робить його вибором для тих, хто піклується про своє здоров'я. Він багатий вітамінами та антиоксидантами, сприяючи зміцненню імунної системи та покращенню загального самопочуття.",
        description04: "<strong>Пісний паштет з паприкою. Жестяна банка.</strong>",
        description05: "&#171Freshona - Pastă Vegetală Tartinabilă Cu Ardei&#187 - справжня родзинка в світі вегетаріанської кухні готова вразити вас своєю смаковою насолодою та користью для організму!"
    },
    {
        type: "wholesale",
        url: "./images/shop/food/canned_food/pates/freshona_pasta_ciuperci_120.jpg",
        alt: "freshona_pasta_ciuperci_120",
        url1: "./images/shop/food/canned_food/pates/freshona_pasta_ciuperci_120.jpg",
        alt1: "freshona_pasta_ciuperci_120",
        marker: "FDPT305",
        brand: "Freshona",
        search: "веган веганство печериці шампиньоны с шампиньонами",
        nameUKR: "Пісний паштет з печерицями",
        nameEN: "Pastă Vegetală Tartinabilă Cu Ciuperci",
        companyName: "Lidl",
        countryName: "Румунія",
        weightName: "Вага",
        weight: "120 гр.",
        priceGRN: 23,
        priceGRNOpt: 19,
        description01: "&#171Freshona - Pastă Vegetală Tartinabilă Cu Ciuperci&#187 - це справжній шедевр вегетаріанської кухні. Виготовлений з найкращих печериць, цей паштет дарує неперевершений аромат та насичений смак, який стає справжньою насолодою.",
        description02: "Він ідеально підходить на грільований хліб, печиво або в якості начинки для сендвічів.",
        description03: "Зі складом, що не містить штучних барвників та консервантів, &#171Freshona - Pastă Vegetală Tartinabilă Cu Ciuperci&#187 стає вибором для тих, хто цінує натуральність і смак. Він багатий білком та вітамінами, сприяючи вашому здоров'ю та зміцнюючи імунну систему.",
        description04: "<strong>Пісний паштет з печерицями. Жестяна банка.</strong>",
        description05: "Відкрийте для себе безмежні можливості для творчості в кулінарії та додайте смаку своїм стравам з &#171Freshona - Pastă Vegetală Tartinabilă Cu Ciuperci&#187!"
    },
    {
        type: "wholesale",
        url: "./images/shop/food/canned_food/pates/freshona_pasta_măsline_120.jpg",
        alt: "freshona_pasta_măsline_120",
        url1: "./images/shop/food/canned_food/pates/freshona_pasta_măsline_120.jpg",
        alt1: "freshona_pasta_măsline_120",
        marker: "FDPT310",
        brand: "Freshona",
        search: "веган веганство в маслини маслины с маслинами",
        nameUKR: "Пісний паштет з маслинами",
        nameEN: "Pastă Vegetală Tartinabilă Cu Măsline",
        companyName: "Lidl",
        countryName: "Румунія",
        weightName: "Вага",
        weight: "120 гр.",
        priceGRN: 23,
        priceGRNOpt: 19,
        description01: "&#171Freshona - Pastă Vegetală Tartinabilă Cu Măsline&#187 - це справжній кулінарний шедевр, який вкраде ваше серце своєю вишуканістю. Виготовлений зі свіжих маслин, цей паштет вражає яскравим смаком і неповторним ароматом. Він ідеально підходить на хліб чи в якості начинки для канапок.",
        description02: "Складаючись лише з природних інгредієнтів, не містить шкідливих домішок і штучних добавок. Він є чудовим вибором для вегетаріанців та тих, хто прагне зберегти своє здоров'я.",
        description03: "Багатий вітамінами та корисними речовинами, &#171Freshona - Pastă Vegetală Tartinabilă Cu Măsline&#187 сприяє підтриманню вашого імунітету та загального здоров'я.",
        description04: "<strong>Пісний паштет з маслинами. Жестяна банка.</strong>",
        description05: "Не втратьте можливість розкрити нові кулінарні горизонти з &#171Freshona - Pastă Vegetală Tartinabilă Cu Măsline&#187. Замовте його вже сьогодні та насолоджуйтеся неперевершеним смаком та ароматом!"
    },
    {
        type: "wholesale",
        url: "./images/shop/food/canned_food/pates/hame_pioner_pork_190.jpg",
        alt: "hame_pioner_pork_190",
        url1: "./images/shop/food/canned_food/pates/hame_pioner_pork_190.jpg",
        alt1: "hame_pioner_pork_190",
        marker: "FDPT400",
        brand: "Hamé",
        search: "свинина свинячий свинной",
        nameUKR: "Паштет зі свинини",
        nameEN: "Nátierka Z Bravčového Mäsa",
        companyName: "HAME s.r.o.",
        countryName: "Чехія",
        weightName: "Вага",
        weight: "190 гр.",
        priceGRN: 40,
        priceGRNOpt: 35,
        description01: "&#171Hamé - Nátierka Z Bravčového Mäsa&#187 - це справжній деликатес для гурманів, вироблений з найкращої свинини. Цей паштет має неперевершений смак та аромат, які роблять його ідеальним вибором для закусок, сендвічів або супроводу до сиру. Він припаде до смаку навіть найвибагливішим поціновувачам смачної їжі.",
        description02: "Цей продукт відрізняється високою якістю та безпечністю. Він не містить шкідливих добавок та консервантів, а отже, може бути спожитий з повною впевненістю в його користі для здоров'я.",
        description03: " Із паштетом зі свинини &#171Hamé - Nátierka Z Bravčového Mäsa&#187 Ви отримуєте справжню смакову насолоду та поживну цінність.",
        description04: "<strong>Паштет зі свинини. Без барвників та шкідливих речовин.</strong>",
        description05: "Не вагайтесь спробувати &#171Hamé - Nátierka Z Bravčového Mäsa&#187 і насолоджуйтесь неперевершеним смаком і ароматом кожного дня!"
    },
    {
        type: "wholesale",
        url: "./images/shop/food/canned_food/pates/hame_tongalas_pastetom_100.jpg",
        alt: "hame_tongalas_pastetom_100",
        url1: "./images/shop/food/canned_food/pates/hame_tongalas_pastetom_100.jpg",
        alt1: "hame_tongalas_pastetom_100",
        marker: "FDPT410",
        brand: "Hamé",
        search: "тунець с тунца тунец омега",
        nameUKR: "Паштет з тунця",
        nameEN: "Tonhalas Pástétom Omega-3",
        companyName: "Hamé Hungária Kft.",
        countryName: "Угорщина",
        weightName: "Вага",
        weight: "100 гр.",
        priceGRN: 52,
        priceGRNOpt: 46,
        description01: "&#171Hamé - Tonhalas Pástétom Omega-3&#187 - це чудовий взірець поєднання смаку та користі для здоров'я. Він виготовлений з найкращого тунця, що забезпечує яскравий і неперевершений смак, який одразу Вас вразить.",
        description02: "Цей паштет чудово підходить для сендвічів, крекерів та страв як солодкого, так і солоного смаку. Однією з ключових переваг цього продукту є вміст Omega-3 жирних кислот, які відомі своєю користю для серця та судин, а також сприяють загальному зміцненню здоров'я.",
        description03: "Завдяки &#171Hamé - Tonhalas Pástétom Omega-3&#187, Ви можете насолоджуватися не тільки вишуканим смаком, але і піклуватися про себе. Ідеальний вибір для тих, хто прагне поєднати смак та здоров'я в одному продукті.",
        description04: "<strong>Паштет з тунця. Без барвників та шкідливих речовин.</strong>",
        description05: "Замовте &#171Hamé - Tonhalas Pástétom Omega-3&#187 вже сьогодні і насолоджуйтесь найкращим, що пропонує Вам море. Ви заслуговуєте на цей неперевершений смак та користь!"
    },
    {
        type: "wholesale",
        url: "./images/shop/food/canned_food/pates/pamapol_pasztet_mazowiecki_wieprzowy_390.jpg",
        alt: "pamapol_pasztet_mazowiecki_wieprzowy_390",
        url1: "./images/shop/food/canned_food/pates/pamapol_pasztet_mazowiecki_wieprzowy_390.jpg",
        alt1: "pamapol_pasztet_mazowiecki_wieprzowy_390",
        marker: "FDPT500",
        brand: "Pamapol",
        search: "памапол свинина свинной паштет",
        nameUKR: "Паштет зі свинини",
        nameEN: "Pasztet Mazowiecki Wieprzowy",
        companyName: "Pamapol S.A.",
        countryName: "Польща",
        weightName: "Вага",
        weight: "390 гр.",
        priceGRN: 39,
        priceGRNOpt: 36,
        description01: "&#171Pamapol - Pasztet Mazowiecki Wieprzowy&#187 - це справжній шедевр польської кулінарії, який вразить Вас неймовірним смаком та ніжною текстурою. Виготовлений із найкращої свинини за традиційною рецептурою, цей паштет гарантує вам відчуття справжнього задоволення.",
        description02: "За основу береться відібрана свинина, а найкращі спеції та інгредієнти додають неперевершений смаковий букет.",
        description03: "Його текстура м'яка і ніжна, дозволяє Вам отримати задоволення від кожного шматочка. &#171Pamapol - Pasztet Mazowiecki Wieprzowy&#187 стане чудовим доповненням до вашого столу на будь-яке свято чи сімейний обід.",
        description04: "<strong>Паштет зі свинини. Жестяна банка.</strong>",
        description05: "Не витрачайте час на готування, коли у вас є &#171Pamapol - Pasztet Mazowiecki Wieprzowy&#187!"
    },
    {
        type: "wholesale",
        url: "./images/shop/food/canned_food/pates/pamapol_pasztet_z_drobiem_390.jpg",
        alt: "pamapol_pasztet_z_drobiem_390",
        url1: "./images/shop/food/canned_food/pates/pamapol_pasztet_z_drobiem_390.jpg",
        alt1: "pamapol_pasztet_z_drobiem_390",
        marker: "FDPT505",
        brand: "Pamapol",
        search: "памапол куриця курица куриный паштет",
        nameUKR: "Курячий паштет",
        nameEN: "Pasztet Z Drobiem",
        companyName: "Pamapol S.A.",
        countryName: "Польща",
        weightName: "Вага",
        weight: "390 гр.",
        priceGRN: 39,
        priceGRNOpt: 36,
        description01: "&#171Pamapol - Pasztet Z Drobiem&#187 - паштет виготовлений з найсвіжіщої курятинки, що надає йому неперевершений смак і ніжну текстуру. Комбінація інгредієнтів і спецій робить його справжньою насолодою для гурманів.",
        description02: "Ідеальний вибір для закуски, сендвіча або обіду. Він має вишуканий смак і аромат, що зробить його популярним серед всіх членів родини.",
        description03: "&#171Pamapol - Pasztet Z Drobiem&#187 відмінно поєднується з хлібом, сиром та свіжими овочами, створюючи справжню насолоду.",
        description04: "<strong>Курячий паштет. Жестяна банка.</strong>",
        description05: "Не втрачайте час на готування, коли у Вас є &#171Pamapol - Pasztet Z Drobiem&#187 та спробуйте його сьогодні і зануртесь у світ польського смаку!"
    },
]