export const shopLotsChips = [
    {
        type: "wholesale",
        url: "./images/shop/food/snacks/chips/pringles_original_40.jpg",
        alt: "pringles_original_40",
        marker: "FDCH100",
        brand: "Pringles",
        search: "принглс прінглс чипсы со вкусом оригинал оригінал сіль соль с солью з сілью",
        nameUKR: "Чіпси",
        nameEN: "Original",
        companyName: "Kellogg's",
        countryName: "Угорщина",
        weightName: "Вага",
        weight: "40 гр.",
        priceGRN: 39,
        priceGRNOpt: 34,
        description01: "&#171Pringles - Original&#187 - це справжня класика серед чіпсів, яка завжди залишається улюбленою. Їх унікальна трубчаста форма робить їх неповторними, а смак бездоганний. Кожен чіпс має ідеальний баланс солі та картоплі, створюючи неповторний смак, який завжди впізнаєш.",
        description02: "&#171Pringles - Original&#187 - це ідеальний снек для будь-якого випадку. Ці чіпси підходять для вечірки з друзями, перегляду фільму або навіть просто для швидкої закуски під час перерви на обід.",
        description03: "Вони завжди свіжі та смачні, завдяки спеціальній упаковці.",
        description04: "<strong>Смак: солений.</strong>",
        description05: "Спробуйте &#171Pringles - Original&#187 прямо зараз і відчуйте смак класики!"
    },
    {
        type: "wholesale",
        url: "./images/shop/food/snacks/chips/pringles_original_165.jpg",
        alt: "pringles_original_165",
        marker: "FDCH102",
        brand: "Pringles",
        search: "принглс прінглс чипсы со вкусом оригинал оригінал сіль соль с солью з сілью",
        nameUKR: "Чіпси",
        nameEN: "Original",
        companyName: "Kellogg's",
        countryName: "Угорщина",
        weightName: "Вага",
        weight: "165 гр.",
        priceGRN: 88,
        priceGRNOpt: 81,
        description01: "&#171Pringles - Original&#187 - це справжня класика серед чіпсів, яка завжди залишається улюбленою. Їх унікальна трубчаста форма робить їх неповторними, а смак бездоганний. Кожен чіпс має ідеальний баланс солі та картоплі, створюючи неповторний смак, який завжди впізнаєш.",
        description02: "&#171Pringles - Original&#187 - це ідеальний снек для будь-якого випадку. Ці чіпси підходять для вечірки з друзями, перегляду фільму або навіть просто для швидкої закуски під час перерви на обід.",
        description03: "Вони завжди свіжі та смачні, завдяки спеціальній упаковці.",
        description04: "<strong>Смак: солений.</strong>",
        description05: "Спробуйте &#171Pringles - Original&#187 прямо зараз і відчуйте смак класики!"
    },
    {
        type: "wholesale",
        url: "./images/shop/food/snacks/chips/pringles_cheese_onion_165.jpg",
        alt: "pringles_cheese_onion_165",
        marker: "FDCH112",
        brand: "Pringles",
        search: "принглс прінглс чипсы со вкусом сыр с сыром цыбулей цыбуля лук луком цибуля",
        nameUKR: "Чіпси зі смаком сиру та цибулі",
        nameEN: "Cheese & Onion",
        companyName: "Kellogg's",
        countryName: "Угорщина",
        weightName: "Вага",
        weight: "165 гр.",
        priceGRN: 88,
        priceGRNOpt: 81,
        description01: "&#171Pringles - Cheese & Onion&#187 - це справжня симфонія смаку, яка підкорює серця гурманів по всьому світу. Кожен чіпс має неймовірно насичений смак сиру та цибулі.",
        description02: "Смак &#171Pringles - Cheese & Onion&#187 - це ідеальний баланс між солодкістю цибулі та багатим смаком сиру. Ці чіпси чудово підходять як закуска до фільму, на вечірку з друзями або просто для задоволення свого апетиту у будь-який час.",
        description03: "Вони завжди гарантують свіжість та смакове задоволення завдяки своєму унікальному трубчастому пакуванню. Спробуйте ці чіпси і вперше відчуйте справжню якість та смак в одному.",
        description04: "<strong>Смак: сир та цибуля.</strong>",
        description05: "Не вагайтеся, спробуйте &#171Pringles - Cheese & Onion&#187 вже сьогодні та переконайтесь, які чудові можуть бути закуски. Вас чекає справжнє кулінарне задоволення!"
    },
    {
        type: "wholesale",
        url: "./images/shop/food/snacks/chips/pringles_cheesy_cheese_165.jpg",
        alt: "pringles_cheesy_cheese_165",
        marker: "FDCH122",
        brand: "Pringles",
        search: "принглс прінглс чипсы со вкусом сыра сыр с сыром",
        nameUKR: "Чіпси зі смаком сиру",
        nameEN: "Cheesy Cheese",
        companyName: "Kellogg's",
        countryName: "Угорщина",
        weightName: "Вага",
        weight: "165 гр.",
        priceGRN: 88,
        priceGRNOpt: 81,
        description01: "&#171Pringles - Cheesy Cheese&#187 - це справжня кулінарна вишуканість, яка додасть смаку вашому життю. Кожен чіпс пропитаний ароматом справжнього сиру, створюючи букет смакових відчуттів, які не мають собі рівних.",
        description02: "Смак &#171Pringles - Cheesy Cheese&#187 - це ідеальне поєднання нот солодкої плавкої текстури сиру, яка залишає вас бажати більше. Ці чіпси чудово пасують до будь-якого виду вечірки.",
        description03: "Завжди гарантують свіжість та смакову насолоду завдяки своєму унікальному трубчастому пакуванню. Спробуйте ці чіпси і Ви отримаєте найкращий смак у кожному ковзку.",
        description04: "<strong>Смак: сир.</strong>",
        description05: "Вирушайте у смачну подорож з &#171Pringles - Cheesy Cheese&#187 даруючи радість собі та вашим друзям!"
    },
    {
        type: "wholesale",
        url: "./images/shop/food/snacks/chips/pringles_classic_paprika_40.jpg",
        alt: "pringles_classic_paprika_40",
        marker: "FDCH130",
        brand: "Pringles",
        search: "принглс прінглс чипсы со вкусом классік класік класик класик папріка паприка перец перца с з перцем",
        nameUKR: "Чіпси зі смаком перцю",
        nameEN: "Classic Paprika",
        companyName: "Kellogg's",
        countryName: "Угорщина",
        weightName: "Вага",
        weight: "40 гр.",
        priceGRN: 39,
        priceGRNOpt: 34,
        description01: "&#171Pringles - Classic Paprika&#187 - це справжній смаковий вибух, який подарує вам неперевершену насолоду. Ці чіпси відзначаються насиченим смаком паприки, який чудово поєднується з хрусткою текстурою.",
        description02: "Смак &#171Pringles - Classic Paprika&#187 - це чудове поєднання ніжності та гостроти, що робить ці чіпси ідеальними для вечірки з друзями, дегустації фільму або просто для задоволення вашого апетиту.",
        description03: "Чіпси гарантують свіжість і смачну насолоду завдяки своєму унікальному трубчастому пакуванню. Спробуйте та вирушайте у смачну подорож, яка залишить незабутній смак.",
        description04: "<strong>Смак: перець, паприка.</strong>",
        description05: "Не втрачайте шансу підкреслити свою вишуканість. Спробуйте &#171Pringles - Classic Paprika&#187 прямо зараз та переконайтесь в їхній неперевершеній якості."
    },
    {
        type: "wholesale",
        url: "./images/shop/food/snacks/chips/pringles_classic_paprika_165.jpg",
        alt: "pringles_classic_paprika_165",
        marker: "FDCH132",
        brand: "Pringles",
        search: "принглс прінглс чипсы со вкусом классік класік класик класик папріка паприка перец перца с з перцем",
        nameUKR: "Чіпси зі смаком перцю",
        nameEN: "Classic Paprika",
        companyName: "Kellogg's",
        countryName: "Угорщина",
        weightName: "Вага",
        weight: "165 гр.",
        priceGRN: 88,
        priceGRNOpt: 81,
        description01: "&#171Pringles - Classic Paprika&#187 - це справжній смаковий вибух, який подарує вам неперевершену насолоду. Ці чіпси відзначаються насиченим смаком паприки, який чудово поєднується з хрусткою текстурою.",
        description02: "Смак &#171Pringles - Classic Paprika&#187 - це чудове поєднання ніжності та гостроти, що робить ці чіпси ідеальними для вечірки з друзями, дегустації фільму або просто для задоволення вашого апетиту.",
        description03: "Чіпси гарантують свіжість і смачну насолоду завдяки своєму унікальному трубчастому пакуванню. Спробуйте та вирушайте у смачну подорож, яка залишить незабутній смак.",
        description04: "<strong>Смак: перець, паприка.</strong>",
        description05: "Не втрачайте шансу підкреслити свою вишуканість. Спробуйте &#171Pringles - Classic Paprika&#187 прямо зараз та переконайтесь в їхній неперевершеній якості."
    },
    {
        type: "wholesale",
        url: "./images/shop/food/snacks/chips/pringles_hot_spicy_40.jpg",
        alt: "pringles_hot_spicy_40",
        marker: "FDCH140",
        brand: "Pringles",
        search: "принглс прінглс чипсы со вкусом острые гострі пряности пряностей острых ",
        nameUKR: "Чіпси зі смаком гострих прянощів",
        nameEN: "Hot & Spicy",
        companyName: "Kellogg's",
        countryName: "Угорщина",
        weightName: "Вага",
        weight: "40 гр.",
        priceGRN: 39,
        priceGRNOpt: 34,
        description01: "&#171Pringles - Hot & Spicy&#187 - це справжній кулінарний вогонь, який принесе неймовірну гостроту у кожен ковзок. Їх виразний смак поєднує пікантні нотки спецій та гострої паприки, створюючи справжню експлозію смаку.",
        description02: "Смак &#171Pringles - Hot & Spicy&#187 - це захоплюючий мікс паприки та спецій, який піднімає адреналін і додає гостроти у ваше життя. Ці чіпси - ідеальний вибір для сміливих і впертих гурманів, які шукають нові смакові враження.",
        description03: "Вони завжди гарантують свіжість та смакове задоволення завдяки своєму унікальному трубчастому пакуванню. Спробуйте ці чіпси і відчуйте, як вони розпалюють ваші смакові рецептори.",
        description04: "<strong>Смак: гострий.</strong>",
        description05: "Вирушайте у смачну подорож та сміливо смакуйте справжній гострий вогонь. Спробуйте &#171Pringles - Hot & Spicy&#187 прямо зараз і отримайте незабутнє смакове враження!"
    },
    {
        type: "wholesale",
        url: "./images/shop/food/snacks/chips/pringles_pizza_flavour_165.jpg",
        alt: "pringles_pizza_flavour_165",
        marker: "FDCH152",
        brand: "Pringles",
        search: "принглс прінглс чипсы со вкусом пицца с пиццой з піцею",
        nameUKR: "Чіпси зі смаком піци",
        nameEN: "Pizza Flavour",
        companyName: "Kellogg's",
        countryName: "Угорщина",
        weightName: "Вага",
        weight: "165 гр.",
        priceGRN: 88,
        priceGRNOpt: 81,
        description01: "&#171Pringles - Pizza Flavour&#187 - це справжній шедевр, який переносить Вас до італійської піцерії з кожним ковзком. Їх неперевершений смак відтворює смачну суміш сиру, помідорів та ароматних спецій.",
        description02: "Смак &#171Pringles - Pizza Flavour&#187 - це справжнє поєднання тепла та затишку, які приносить з собою італійська піца. Ці чіпси дозволяють Вам насолоджуватися улюбленим смаком навіть на робочому місці або вдома.",
        description03: "Завжди гарантують свіжість та смакове насолодження завдяки своєму унікальному трубчастому пакуванню. Спробуйте ці чіпси і перенесіть себе до мальовничої Італії кожен раз, коли відкриваєте упаковку.",
        description04: "<strong>Смак: піца.</strong>",
        description05: "Замовте &#171Pringles - Pizza Flavour&#187 прямо зараз та насолоджуйтеся справжньою італійською піцею!"
    },
    {
        type: "wholesale",
        url: "./images/shop/food/snacks/chips/pringles_prawn_cocktail_165.jpg",
        alt: "pringles_prawn_cocktail_165",
        marker: "FDCH162",
        brand: "Pringles",
        search: "принглс прінглс чипсы со вкусом креветка креветки",
        nameUKR: "Чіпси зі смаком креветок",
        nameEN: "Prawn Cocktail",
        companyName: "Kellogg's",
        countryName: "Угорщина",
        weightName: "Вага",
        weight: "165 гр.",
        priceGRN: 88,
        priceGRNOpt: 81,
        description01: "&#171Pringles - Prawn Cocktail&#187 - це справжнє відкриття для шанувальників найніжнішого морського смаку. Кожен ковзок цих чіпсів наповнений ароматом тропічних креветок, які створюють неперевершений смак.",
        description02: "Справжнє поєднання ніжності морських страв та тропічних фруктів. Ці чіпси ідеально пасують до будь-якого заходу, будь то пікнік на природі чи вечірка з друзями, завжди викликаючи захоплення гостей.",
        description03: "&#171Pringles - Prawn Cocktail&#187 завжди гарантують свіжість і смакову насолоду завдяки своєму унікальному трубчастому пакуванню. Спробуйте ці чіпси і насолоджуйтесь смаком літа і моря у будь-який час року.",
        description04: "<strong>Смак: креветка.</strong>",
        description05: "Замовте &#171Pringles - Prawn Cocktail&#187 прямо зараз і подаруйте собі справжню тропічну вечірку у кожному ковзку. Насолоджуйтеся смаком моря разом з нами!"
    },
    {
        type: "wholesale",
        url: "./images/shop/food/snacks/chips/pringles_sour_cream_onion_40.jpg",
        alt: "pringles_sour_cream_onion_40",
        marker: "FDCH170",
        brand: "Pringles",
        search: "принглс прінглс чипсы со вкусом сметаны и лука цибулі лук",
        nameUKR: "Чіпси зі смаком сметани та цибулі",
        nameEN: "Sour Cream & Onion",
        companyName: "Kellogg's",
        countryName: "Угорщина",
        weightName: "Вага",
        weight: "40 гр.",
        priceGRN: 39,
        priceGRNOpt: 34,
        description01: "&#171Pringles - Sour Cream & Onion&#187 - це справжній смаковий екстаз, який приносить неймовірну насолоду. Кожен ковзок цих чіпсів насичений смаком ніжної сметани та ароматом свіжої цибулі, створюючи неперевершений баланс солодких та гострих ноток.",
        description02: "Смак &#171Pringles - Sour Cream & Onion&#187 - це ідеальне поєднання смаку сметани та пікантності цибулі, яке завжди приносить задоволення. Ці чіпси - ідеальний вибір для дегустації під час перегляду фільму, пікніка на природі або як швидка смачна закуска під час перерви на обід.",
        description03: "&#171Pringles - Sour Cream & Onion&#187 завжди гарантують свіжість та смакове насолодження завдяки своєму унікальному трубчастому пакуванню. Спробуйте ці чіпси і насолоджуйтесь найкращим смаком в кожному ковзку.",
        description04: "<strong>Смак: сметана та цибуля.</strong>",
        description05: "Не вагайтеся, зануртесь у смачний світ з &#171Pringles - Sour Cream & Onion&#187 і дайте собі справжню насолоду!"
    },
    {
        type: "wholesale",
        url: "./images/shop/food/snacks/chips/pringles_sour_cream_onion_165.jpg",
        alt: "pringles_sour_cream_onion_165",
        marker: "FDCH172",
        brand: "Pringles",
        search: "принглс прінглс чипсы со вкусом сметаны и лука цибулі лук",
        nameUKR: "Чіпси зі смаком сметани та цибулі",
        nameEN: "Sour Cream & Onion",
        companyName: "Kellogg's",
        countryName: "Угорщина",
        weightName: "Вага",
        weight: "165 гр.",
        priceGRN: 88,
        priceGRNOpt: 81,
        description01: "&#171Pringles - Sour Cream & Onion&#187 - це справжній смаковий екстаз, який приносить неймовірну насолоду. Кожен ковзок цих чіпсів насичений смаком ніжної сметани та ароматом свіжої цибулі, створюючи неперевершений баланс солодких та гострих ноток.",
        description02: "Смак &#171Pringles - Sour Cream & Onion&#187 - це ідеальне поєднання смаку сметани та пікантності цибулі, яке завжди приносить задоволення. Ці чіпси - ідеальний вибір для дегустації під час перегляду фільму, пікніка на природі або як швидка смачна закуска під час перерви на обід.",
        description03: "&#171Pringles - Sour Cream & Onion&#187 завжди гарантують свіжість та смакове насолодження завдяки своєму унікальному трубчастому пакуванню. Спробуйте ці чіпси і насолоджуйтесь найкращим смаком в кожному ковзку.",
        description04: "<strong>Смак: сметана та цибуля.</strong>",
        description05: "Не вагайтеся, зануртесь у смачний світ з &#171Pringles - Sour Cream & Onion&#187 і дайте собі справжню насолоду!"
    },
    {
        type: "wholesale",
        url: "./images/shop/food/snacks/chips/pringles_texas_bbq_sauce_40.jpg",
        alt: "pringles_texas_bbq_sauce_40",
        marker: "FDCH180",
        brand: "Pringles",
        search: "принглс прінглс чипсы со вкусом соуса",
        nameUKR: "Чіпси зі смаком соусу барбекю",
        nameEN: "Texas BBQ Sauce",
        companyName: "Kellogg's",
        countryName: "Угорщина",
        weightName: "Вага",
        weight: "40 гр.",
        priceGRN: 39,
        priceGRNOpt: 34,
        description01: "&#171Pringles - Texas BBQ Sauce&#187 - це справжня смакова подорож на дикий захід, яка переносить Вас до атмосфери Техасу. Кожен ковзок цих чіпсів вирушає в експедицію у пошуках смаженого м'яса та вогняного соусу барбекю.",
        description02: "Смак &#171Pringles - Texas BBQ Sauce&#187 - це справжня вибухова суміш солодкості та гостроти. Ці чіпси - ідеальний спосіб насолоджуватися смаком справжнього барбекю без гриля та коптильні.",
        description03: "Завжди гарантують свіжість та смакову насолоду завдяки своєму унікальному трубчастому пакуванню. Спробуйте ці чіпси і перенесіть себе на велику прерію Техасу.",
        description04: "<strong>Смак: соус барбекю.</strong>",
        description05: "Вирушайте у неймовірну смакову подорож і сміливо спробуйте &#171Pringles - Texas BBQ Sauce&#187 прямо зараз!"
    },
    {
        type: "wholesale",
        url: "./images/shop/food/snacks/chips/pringles_texas_bbq_sauce_165.jpg",
        alt: "pringles_texas_bbq_sauce_165",
        marker: "FDCH182",
        brand: "Pringles",
        search: "принглс прінглс чипсы со вкусом соуса",
        nameUKR: "Чіпси зі смаком соусу барбекю",
        nameEN: "Texas BBQ Sauce",
        companyName: "Kellogg's",
        countryName: "Угорщина",
        weightName: "Вага",
        weight: "165 гр.",
        priceGRN: 88,
        priceGRNOpt: 81,
        description01: "&#171Pringles - Texas BBQ Sauce&#187 - це справжня смакова подорож на дикий захід, яка переносить Вас до атмосфери Техасу. Кожен ковзок цих чіпсів вирушає в експедицію у пошуках смаженого м'яса та вогняного соусу барбекю.",
        description02: "Смак &#171Pringles - Texas BBQ Sauce&#187 - це справжня вибухова суміш солодкості та гостроти. Ці чіпси - ідеальний спосіб насолоджуватися смаком справжнього барбекю без гриля та коптильні.",
        description03: "Завжди гарантують свіжість та смакову насолоду завдяки своєму унікальному трубчастому пакуванню. Спробуйте ці чіпси і перенесіть себе на велику прерію Техасу.",
        description04: "<strong>Смак: соус барбекю.</strong>",
        description05: "Вирушайте у неймовірну смакову подорож і сміливо спробуйте &#171Pringles - Texas BBQ Sauce&#187 прямо зараз!"
    },
]