export const shopLotsSprats = [
    {
        type: "retail",
        mainCategory: "foodstuffs",
        subcategory: "conservation",
        url: "./images/shop/food/canned_food/sprats/evrafish_winter_sprats_170.jpg",
        alt: "evrafish_winter_sprats_170",
        url1: "./images/shop/food/canned_food/sprats/evrafish_winter_sprats_170-01.jpg",
        alt1: "evrafish_winter_sprats_170-01",
        url2: "./images/shop/food/canned_food/sprats/evrafish_winter_sprats_170-02.jpg",
        alt2: "evrafish_winter_sprats_170-02",
        url3: "./images/shop/food/canned_food/sprats/evrafish_winter_sprats_170-03.jpg",
        alt3: "evrafish_winter_sprats_170-03",
        marker: "FDST200",
        brand: "EvraFish",
        search: "эврафіш еврафиш шпроты в масле масло олія масло рыба риба",
        nameUKR: "Шпроти в олії",
        nameEN: "Winter Sprats",
        companyName: "EvraFish Sp.",
        countryName: "Польща",
        weightName: "Вага",
        weight: "170 гр.",
        priceGRN: 49,
        quantityOnStorage: 3,
        description01: "&#171EvraFish - Winter Sprats&#187 - це справжній дарунок природи, який переносить нас у світ арктичних вод. Кожен шпрот незвичайно ніжний та смачний завдяки холодним водам, в яких вони зростають.",
        description02: "Смак &#171EvraFish - Winter Sprats&#187 - це поєднання ніжності та м'якості м'яса з багатим ароматом моря. Ці шпроти - ідеальний вибір для тих, хто цінує якість та натуральний смак риби.",
        description03: "Бренд &#171EvraFish&#187 завжди гарантує свіжість та смакову насолоду у кожному ковзку завдяки своєму досвіду та відповідальному відношенню до виробництва.",
        description04: "<strong>Шпроти в олії. Без консервантів.</strong>",
        description05: "Не вагайтеся та замовляйте &#171EvraFish - Winter Sprats&#187 прямо зараз, щоб зануритися у світ арктичних вод!"
    },
    // {
    //     type: "wholesale оптом",
    // mainCategory: "foodstuffs",
        // subcategory: "conservation",    
    // url: "./images/shop/food/canned_food/sprats/king_oscar_szproty_tomato_160.jpg",
    //     alt: "king_oscar_szproty_tomato_160",
    //     url1: "./images/shop/food/canned_food/sprats/king_oscar_szproty_tomato_160-01.jpg",
    //     alt1: "king_oscar_szproty_tomato_160-01",
    //     marker: "FDST250",
    //     brand: "King Oscar",
    //     search: "король оскар шпроты томатный соус рыба риба",
    //     nameUKR: "Шпроти у томатному соусі",
    //     nameEN: "Szproty W Sosie Pomidorowym",
    //     companyName: "Thai Union Poland Sp.",
    //     countryName: "Польща",
    //     weightName: "Вага",
    //     weight: "160 гр.",
    //     priceGRN: 42,
    //     priceGRNOpt: 37,
    //     description01: "&#171King Oscar - Szproty W Sosie Pomidorowym&#187 - це вишуканий дар норвезьких морів, заповнений багатством смаку та користі. Ці шпроти у томатному соусі - справжній діамант серед морських дарунків. Кожен шматочок риби відзначається неймовірною ніжністю та поживністю.",
    //     description02: "Соус, у &#171King Oscar - Szproty W Sosie Pomidorowym&#187 виготовлений з найсвіжіших томатів та ретельно підібраних спецій. Він додає страві неповторний аромат та глибокий смак, який гармонійно поєднується з ніжністю риби. Це ідеальний вибір для гурманів та тих, хто цінує справжню якість.",
    //     description03: "Пригощайте себе та своїх гостей цією розкішшю природного походження. &#171King Oscar - Szproty W Sosie Pomidorowym&#187 - це не просто страва, це смакова подорож у світ норвезької традиції.",
    //     description04: "<strong>Шпроти у томатному соусі. Без консервантів.</strong>",
    //     description05: "Замовляйте &#171King Oscar - Szproty W Sosie Pomidorowym&#187 та відчуйте всю силу морського дару у кожному шматочку."
    // },
    // {
    //     type: "wholesale оптом",
    // mainCategory: "foodstuffs",
        // subcategory: "conservation",    
    // url: "./images/shop/food/canned_food/sprats/king_oscar_szproty_tomato_omega_160.jpg",
    //     alt: "king_oscar_szproty_tomato_omega_160",
    //     url1: "./images/shop/food/canned_food/sprats/king_oscar_szproty_tomato_omega_160-01.jpg",
    //     alt1: "king_oscar_szproty_tomato_omega_160-01",
    //     url2: "./images/shop/food/canned_food/sprats/king_oscar_szproty_tomato_omega_160-02.jpg",
    //     alt2: "king_oscar_szproty_tomato_omega_160-02",
    //     url3: "./images/shop/food/canned_food/sprats/king_oscar_szproty_tomato_omega_160-03.jpg",
    //     alt3: "king_oscar_szproty_tomato_omega_160-03",
    //     marker: "FDST255",
    //     brand: "King Oscar",
    //     search: "король оскар шпроты томатный соус рыба риба омега 3",
    //     nameUKR: "Шпроти у томатному соусі з ОМЕГА-3",
    //     nameEN: "Szproty W Sosie Pomidorowym Omega-3",
    //     companyName: "Thai Union Poland Sp.",
    //     countryName: "Польща",
    //     weightName: "Вага",
    //     weight: "170 гр.",
    //     priceGRN: 35,
    //     priceGRNOpt: 31,
    //     description01: "Відкрийте для себе смаковитий світ здоров'я зі шпротами у томатному соусі з ОМЕГА-3 &#171King Oscar - Szproty W Sosie Pomidorowym Omega-3&#187.",
    //     description02: "Ці шпроти - справжнє джерело корисних ОМЕГА-3 жирних кислот, які покращують здоров'я серця та підтримують нормальний обмін речовин.",
    //     description03: "Мрієте про поєднання смаку та користі? Шпроти &#171King Oscar - Szproty W Sosie Pomidorowym Omega-3&#187 не лише задовольнять Ваш смак, але й додадуть корисних речовин вашому харчуванню.",
    //     description04: "<strong>Шпроти у томатному соусі, ОМЕГА-3. Без консервантів.</strong>",
    //     description05: "Спробуйте шпроти у томатному соусі &#171King Oscar - Szproty W Sosie Pomidorowym Omega-3&#187 вже сьогодні та насолоджуйтеся вишуканим смаком, підтримуючи своє здоров'я!"
    // },
    // {
    //     type: "wholesale оптом",
    // mainCategory: "foodstuffs",
        // subcategory: "conservation",    
    // url: "./images/shop/food/canned_food/sprats/m&k_szprot_podwedzany_w_oleju_160.jpg",
    //     alt: "m&k_szprot_podwedzany_w_oleju_160",
    //     marker: "FDST340",
    //     brand: "M & K",
    //     search: "шпроты в масле масло олія масло рыба риба",
    //     nameUKR: "Шпроти в олії",
    //     nameEN: "Szprot Podwedzany W Oleju",
    //     companyName: "Kasprzyk SP. K.",
    //     countryName: "Польща",
    //     weightName: "Вага",
    //     weight: "160 гр.",
    //     priceGRN: 43,
    //     priceGRNOpt: 38,
    //     description01: "&#171M & K - Szprot Podwedzany W Oleju&#187 - це справжній шедевр у світі морських делікатесів. Кожен шматочок цих ніжних шпротів, замаринованих у відбірній олії, - це витвір мистецтва. Вони виробляються з використанням найкращих рибних уловів та традиційних рецептів.",
    //     description02: "Олія, в якій зберігаються ці шпроти, надає їм неповторний смак та аромат. Ви отримуєте надзвичайно соковиті та ніжні шпроти, які легко тануть у роті. Це ідеальна закуска для гурманів та тих, хто цінує вишуканість в кожній деталі.",
    //     description03: "Спробуйте &#171M & K - Szprot Podwedzany W Oleju&#187 та переконайтеся в якості цього продукту самі. Завдяки найвищому стандарту виробництва і натуральним інгредієнтам, вони стануть вашим улюбленим вибором серед морських смаколиків.",
    //     description04: "<strong>Шпроти в олії. Без консервантів.</strong>",
    //     description05: "А тепер, дозвольте і собі розкрити секрет цього неймовірного смаку та замовте &#171M & K - Szprot Podwedzany W Oleju&#187 вже сьогодні!"
    // },
    // {
    //     type: "wholesale оптом",
    // mainCategory: "foodstuffs",
        // subcategory: "conservation",    
    // url: "./images/shop/food/canned_food/sprats/m&k_szprot_podwedzany_w_sosie_pomidorowym_160.jpg",
    //     alt: "m&k_szprot_podwedzany_w_sosie_pomidorowym_160",
    //     url1: "./images/shop/food/canned_food/sprats/m&k_szprot_podwedzany_w_sosie_pomidorowym_160-01.jpg",
    //     alt1: "m&k_szprot_podwedzany_w_sosie_pomidorowym_160-01",
    //     url2: "./images/shop/food/canned_food/sprats/m&k_szprot_podwedzany_w_sosie_pomidorowym_160-02.jpg",
    //     alt2: "m&k_szprot_podwedzany_w_sosie_pomidorowym_160-02",
    //     marker: "FDST342",
    //     brand: "M & K",
    //     search: "шпроты томатный соус рыба риба",
    //     nameUKR: "Шпроти у томатному соусі",
    //     nameEN: "Szprot Podwedzany W Sosie Pomidorowym",
    //     companyName: "Kasprzyk SP. K.",
    //     countryName: "Польща",
    //     weightName: "Вага",
    //     weight: "160 гр.",
    //     priceGRN: 43,
    //     priceGRNOpt: 38,
    //     description01: "&#171M & K - Szprot Podwedzany W Sosie Pomidorowym&#187 - це найвищий стандарт якості у морських делікатесах. Ця страва переповнена смаком та корисністю. Кожен шматочок ніжної риби насичений таємничим ароматом вогню та помідорів.",
    //     description02: "Томатний соус, що супроводжує ці шпроти, виробляється із відібраних помідорів та суміші спецій, створюючи неперевершений букет смаків. Ця комбінація робить страву ідеальною для закуски або головною страваю. Кожен шматочок - це кулінарна поїзія на вашій тарільці.",
    //     description03: "Спробуйте &#171M & K - Szprot Podwedzany W Sosie Pomidorowym&#187 та відчуйте всю глибину смаку моря, обігріту ніжністю помідорів.",
    //     description04: "<strong>Шпроти у томатному соусі. Без консервантів.</strong>",
    //     description05: "Не відкладайте задоволення на завтра! Замовте &#171M & K - Szprot Podwedzany W Sosie Pomidorowym&#187 вже сьогодні і подаруйте собі смакове св'ято, яке назавжди запам'ятається."
    // },
    {
        type: "only-wholesale оптом",
        mainCategory: "foodstuffs",
        subcategory: "conservation",
        url: "./images/shop/food/canned_food/sprats/m&k_szproty_wedzone_w_oleju_250.jpg",
        alt: "m&k_szproty_wedzone_w_oleju_250",
        url1: "./images/shop/food/canned_food/sprats/m&k_szproty_wedzone_w_oleju_250-01.jpg",
        alt1: "m&k_szproty_wedzone_w_oleju_250-01",
        url2: "./images/shop/food/canned_food/sprats/m&k_szproty_wedzone_w_oleju_250-02.jpg",
        alt2: "m&k_szproty_wedzone_w_oleju_250-02",
        url3: "./images/shop/food/canned_food/sprats/m&k_szproty_wedzone_w_oleju_250-03.jpg",
        alt3: "m&k_szproty_wedzone_w_oleju_250-03",
        url4: "./images/shop/food/canned_food/sprats/m&k_szproty_wedzone_w_oleju_250-04.jpg",
        alt4: "m&k_szproty_wedzone_w_oleju_250-04",
        marker: "FDST346",
        brand: "M & K",
        search: "шпроты в масле масло олія масло рыба риба",
        nameUKR: "Копчені шпроти в олії",
        nameEN: "Szproty Wedzone W Oleju",
        companyName: "Kasprzyk SP. K.",
        countryName: "Польща",
        weightName: "Вага",
        weight: "250 гр.",
        priceGRN: "--",
        priceGRNOpt: 134,
        description01: "&#171M & K - Szproty Wedzone W Oleju&#187 - це справжній шедевр серед морських смаколиків. Кожен шпрот у цій неймовірно смачній олії - це витвір мистецтва та смакова розкіш. Вони виготовлені з найсвіжіших рибних уловів і володіють неперевершеним смаком та ароматом.",
        description02: "Олія, в якій знаходяться ці шпроти, надає їм неймовірну м'якість та ніжність. Кожен шматочок риби пропитаний багатогранним смаком диму та олії, що робить їх неперевершеними. Це ідеальний вибір для вишуканих гурманів і тих, хто цінує справжню якість.",
        description03: "Спробуйте &#171M & K - Szproty Wedzone W Oleju&#187 та відчуйте смакову розкіш, яка вас приголомшить. Дозвольте собі насолоджуватися найкращими смаками моря у кожному шматочку.",
        description04: "<strong>Шпроти в олії, копчені. Без консервантів.</strong>",
        description05: "Замовте &#171M & K - Szproty Wedzone W Oleju&#187 та переконайтеся в їх неперевершеній смаковій якості!"
    },
    {
        type: "retail",
        mainCategory: "foodstuffs",
        subcategory: "conservation",
        url: "./images/shop/food/canned_food/sprats/m&k_szproty_wedzone_tomato_250.jpg",
        alt: "m&k_szproty_wedzone_tomato_250",
        url1: "./images/shop/food/canned_food/sprats/m&k_szproty_wedzone_tomato_250-01.jpg",
        alt1: "m&k_szproty_wedzone_tomato_250-01",
        url2: "./images/shop/food/canned_food/sprats/m&k_szproty_wedzone_tomato_250-02.jpg",
        alt2: "m&k_szproty_wedzone_tomato_250-02",
        url3: "./images/shop/food/canned_food/sprats/m&k_szproty_wedzone_tomato_250-03.jpg",
        alt3: "m&k_szproty_wedzone_tomato_250-03",
        url4: "./images/shop/food/canned_food/sprats/m&k_szproty_wedzone_tomato_250-04.jpg",
        alt4: "m&k_szproty_wedzone_tomato_250-04",
        marker: "FDST350",
        brand: "M & K",
        search: "шпроты в томатном соусе соусы томатний томатный соус рыба риба",
        nameUKR: "Копчені шпроти у томатному соусі",
        nameEN: "Szproty Wedzone W Sosie Pomidorowym",
        companyName: "Kasprzyk SP. K.",
        countryName: "Польща",
        weightName: "Вага",
        weight: "250 гр.",
        priceGRN: 124,
        quantityOnStorage: 1,
        description01: "&#171M & K - Szproty Wedzone W Sosie Pomidorowym&#187 - це справжній кулінарний шедевр, який викликає захоплення з першого дотику.",
        description02: "Ці шпроти вирізняються неперевершеним поєднанням копченого смаку і аромату томатного соусу. Вони - ідеальний вибір для тих, хто цінує вишуканість та гастрономічні насолоди.",
        description03: "Відчуйте ексклюзивність копчених шпротів &#171M & K - Szproty Wedzone W Sosie Pomidorowym&#187, які роблять будь-який стіл вишуканим. Їхній насичений смак залишає незабутнє враження, викликаючи бажання повертатися до цього неперевершеного смаку знову й знову.",
        description04: "<strong>Шпроти у томатному соусі, копчені. Без консервантів.</strong>",
        description05: "Замовте копчені шпроти у томатному соусі &#171M & K - Szproty Wedzone W Sosie Pomidorowym&#187 зараз і відкрийте для себе світ аутентичних смакових вражень!"
    },
    {
        type: "wholesale оптом",
        mainCategory: "foodstuffs",
        subcategory: "conservation",       
        url: "./images/shop/food/canned_food/sprats/marinero_szprot_w_sosie_pomidorowym_170.jpg",
        alt: "marinero_szprot_w_sosie_pomidorowym_170",
        url1: "./images/shop/food/canned_food/sprats/marinero_szprot_w_sosie_pomidorowym_170-01.jpg",
        alt1: "marinero_szprot_w_sosie_pomidorowym_170-01",
        url2: "./images/shop/food/canned_food/sprats/marinero_szprot_w_sosie_pomidorowym_170-02.jpg",
        alt2: "marinero_szprot_w_sosie_pomidorowym_170-02",
        marker: "FDST450",
        brand: "Marinero",
        search: "маринеро марінеро шпроты в томатном соусе томатный соус томатний соус",
        nameUKR: "Шпроти у томатному соусі",
        nameEN: "Szprot W Sosie Pomidorowym",
        companyName: "Jeronimo Martins S.A.",
        countryName: "Польща",
        weightName: "Вага",
        weight: "170 гр.",
        priceGRN: 56,
        priceGRNOpt: 51,
        description01: "&#171Marinero - Szprot W Sosie Pomidorowym&#187 — це класичний смак моря з додаванням соковитого соусу для яскравого поєднання.",
        description02: "Натуральне філе шпротів поєднується з густим томатним соусом, створюючи ніжну текстуру та насичений смаковий баланс.",
        description03: "&#171Marinero - Szprot W Sosie Pomidorowym&#187 ідеально підходять для швидких перекусів, бутербродів або легких страв без зайвих клопотів",
        description04: "<strong>Шпроти у томатному соусі. Зберігати у прохолодному сухомі місці.</strong>",
        description05: "Додайте &#171Marinero - Szprot W Sosie Pomidorowym&#187 до своєї комори, щоб завжди мати під рукою смачний і поживний варіант!"
    },
    {
        type: "only-wholesale оптом",
        mainCategory: "foodstuffs",
        subcategory: "conservation",
        url: "./images/shop/food/canned_food/sprats/pirat_winter_sprats_160.jpg",
        alt: "pirat_winter_sprats_160",
        url1: "./images/shop/food/canned_food/sprats/pirat_winter_sprats_160-01.jpg",
        alt1: "pirat_winter_sprats_160-01",
        url2: "./images/shop/food/canned_food/sprats/pirat_winter_sprats_160-02.jpg",
        alt2: "pirat_winter_sprats_160-02",
        url3: "./images/shop/food/canned_food/sprats/pirat_winter_sprats_160-03.jpg",
        alt3: "pirat_winter_sprats_160-03",
        marker: "FDST554",
        brand: "Pirat",
        search: "шпроты в масле масло олія масло рыба риба",
        nameUKR: "Шпроти в олії",
        nameEN: "Winter Sprats",
        companyName: "Łosos Sp. z o.o.",
        countryName: "Польща",
        weightName: "Вага",
        weight: "160 гр.",
        priceGRN: "--",
        priceGRNOpt: 76,
        description01: "Кожен шматочок &#17Pirat - Winter Sprats&#187 - це джерело білка та вітамінів, які роблять цей продукт не тільки смачним, але і корисним для вашого здоров'я.",
        description02: "Ці шпроти - це справжній дегустаційний діамант. Їх димчастий смак і неповторний аромат подарують Вам враження від подорожі на захоплюючий світ морських смаків.",
        description03: "&#17Pirat - Winter Sprats&#187 виробляються з найкращих інгредієнтів, щоб подарувати Вам смак природи і морської свободи.",
        description04: "<strong>Шпроти в олії. Без консервантів.</strong>",
        description05: "Створіть унікальні кулінарні шедеври разом з &#17Pirat - Winter Sprats&#187 та відчуйте ексклюзивність морського смаку у кожному шматочку!"
    },
    {
        type: "only-wholesale оптом",
        mainCategory: "foodstuffs",
        subcategory: "conservation",
        url: "./images/shop/food/canned_food/sprats/posejdon_szprot_300.jpg",
        alt: "posejdon_szprot_300",
        url1: "./images/shop/food/canned_food/sprats/posejdon_szprot_300-01.jpg",
        alt1: "posejdon_szprot_300-01",
        url2: "./images/shop/food/canned_food/sprats/posejdon_szprot_300-02.jpg",
        alt2: "posejdon_szprot_300-02",
        url3: "./images/shop/food/canned_food/sprats/posejdon_szprot_300-03.jpg",
        alt3: "posejdon_szprot_300-03",
        marker: "FDST600",
        brand: "Posejdon",
        search: "посейдон шпроты томатный соус рыба риба",
        nameUKR: "Шпроти у томатному соусі",
        nameEN: "Szprot XXL",
        companyName: "Przetwórstwo Rybne Sp.",
        countryName: "Польща",
        weightName: "Вага",
        weight: "300 гр.",
        priceGRN: "--",
        priceGRNOpt: 94,
        description01: "&#171Posejdon - Szprot&#187 - це справжній океанський смак у кожному шматочку риби. Ця страва поєднує у собі свіжість морського бризу та ніжність шпротів. Відірвавши кришечку, Ви відразу відчуєте запах рибок, занурених у томатний соус.",
        description02: "Спеціально підібрана рецептура соусу надає шпротам неперевершений смак. Томати, спеції та інші натуральні інгредієнти додають найкращі якості цих риб, роблячи кожен ковзаючий шматочок неперевершеним у своєму роді. Цей продукт стане ідеальним додатком до салатів, канапок або гарячих страв.",
        description03: "Спробуйте шпроти &#171Posejdon - Szprot&#187 і Ви отримаєте чисту морську насолоду, яку можна смакувати у будь-який час.",
        description04: "<strong>Шпроти у томатному соусі. Без консервантів.</strong>",
        description05: "Не відкладайте задоволення на завтра - насолоджуйтесь неперевершеним смаком &#171Posejdon - Szprot&#187 вже сьогодні!"
    },
]